.travis.yml, README.md, setup.py
Add travis configuration for continuous integration 
No
Yes.
=> Add travis ci configuration for CI

bentoml/utils/module_helper.py, tox.ini
Fixed a few issue when running BentoML in python 2.7.
=> Fix tests in python 2.7

bentoml/__init__.py, bentoml/artifacts/__init__.py, bentoml/artifacts/artifact.py, bentoml/artifacts/pickle_artifact.py, bentoml/artifacts/pytorch_model_artifact.py, bentoml/artifacts/text_file_artifact.py, bentoml/artifacts/tf_keras_model_artifact.py, bentoml/cli/__init__.py, bentoml/handlers/__init__.py, bentoml/handlers/base_handlers.py, bentoml/handlers/dataframe_handler.py, bentoml/handlers/image_handler.py, bentoml/handlers/json_handler.py, bentoml/handlers/pytorch_tensor_handler.py, bentoml/handlers/tensorflow_tensor_handler.py, bentoml/loader.py, bentoml/model.py, bentoml/server/__init__.py, bentoml/server/metrics.py, bentoml/server/model_api_server.py, bentoml/server/prediction_logger.py, bentoml/service.py, bentoml/service_env.py, bentoml/utils/__init__.py, bentoml/utils/config.py, bentoml/utils/exceptions.py, bentoml/utils/module_helper.py
Add "from __future__ import" statement to ensure consistent behavior with absolute imports, new / division, and the print function.
=> Add from __future__ import statement

bentoml/model.py, bentoml/utils/module_helper.py, examples/local-dependencies/main.sh, examples/local-dependencies/mymodule/__init__.py, examples/local-dependencies/mymodule/scripts/main.py, examples/local-dependencies/mymodule/submodule/__init__.py, examples/local-dependencies/mymodule/submodule/submodule2.py, examples/local-dependencies/mymodule/submodule1.py, examples/local-dependencies/mymodule/submodule3.py, examples/local-dependencies/mymodule/submodule4/__init__.py, examples/local-dependencies/mymodule2.py, tests/test_model.py, tests/test_model_api_server.py
improve the copy_module_and_local_dependencies helper, make it work with more complex project structure and local python dependencies.
n/a
Pass tox tests locally
=> Improve saving/loading local python module

bentoml/model.py, bentoml/service.py, bentoml/utils/module_helper.py, bentoml/utils/s3.py, examples/quick-start/main.py, examples/sklearn-sentiment-clf/sentiment_lr_model.py, examples/sklearn-sentiment-clf/sklearn-sentiment-clf.ipynb
Specifically fixed the module_file field in saved bentoml.yml, when saving from a jupyter notebook
n/a
n/a
=> Fix saving bentoml archive from jupyter notebook

bentoml/cli/commands.py, bentoml/handlers/base_handlers.py, bentoml/handlers/dataframe_handler.py, bentoml/handlers/image_handler.py, bentoml/handlers/json_handler.py, bentoml/handlers/pytorch_tensor_handler.py, bentoml/handlers/tensorflow_tensor_handler.py, bentoml/handlers/utils.py, bentoml/server/model_api_server.py, bentoml/service.py, tests/cli/test_cli.py, tests/server/test_model_api_server.py, tests/test_model.py
Add configuration options to handlers. Solving issue such as https://github.com/bentoml/BentoML/issues/8. 
https://github.com/bentoml/BentoML/issues/8
=> Add additional options for handlers

MANIFEST.in, bentoml/version.py, setup.py
- Exclude 'tests*' package in sdist
=> Exclude 'tests*' package in sdist

bentoml/utils/module_helper.py, examples/local-dependencies/mymodule/unused_module.py
use sys.prefix and sys.path ends with site-packages to determine if target module should be included in bento service distribution
n/a
n/a
=> Improve copy_module_and_local_dependencies

bentoml/server/feedback_logger.py, bentoml/server/model_api_server.py, bentoml/server/prediction_logger.py
Add feedback route.  Store the info in a temp file
no
n/a
=> Add feedback route and its functionality for rest server

bentoml/__init__.py, bentoml/artifact/artifact.py, bentoml/artifact/pytorch_model_artifact.py, bentoml/artifact/text_file_artifact.py, bentoml/artifact/tf_keras_model_artifact.py, bentoml/loader.py, bentoml/server/model_api_server.py, bentoml/service.py, bentoml/service_env.py
*  add BentoServiceBase abstraction for loaded bento service wrapper
* fixed most linter errors/warnings introduced in the refactoring PR #26 
=> Add BentoServiceBase abstraction

bentoml/handlers/dataframe_handler.py, bentoml/handlers/image_handler.py, bentoml/handlers/json_handler.py
Update handlers code base on linter result.  
=> update handlers base on linter result

bentoml/handlers/image_handler.py, tests/cli/test_cli.py
=> nit, fix typo

bentoml/utils/py_module_utils.py, examples/local-dependencies/mymodule/scripts/main.py, examples/sklearn-sentiment-clf/sklearn-sentiment-clf.ipynb, examples/tf-keras-text-classification/text_classification_service.py, examples/tf-keras-text-classification/tf-keras-text-classification.ipynb
- Update example local-dependencies to new API format
- Finish tf-keras-text-classification example
n/a
n/a
=> Update more examples to new API format

README.md
=> README.md init

bentoml/version.py
- bump version to 0.0.8
n/a
n/a
=> Bump PyPI package version

.travis.yml, setup.py, tox.ini
- Update tox, setup.py dependencies configuration
- Make sure tox run passes from clean state
n/a
n/a
=> Fix tox deps for local test runs

examples/tf-keras-fashion-mnist/basic_classification.ipynb
Update Kera fashion mnist example
=> Update tensorflow.kera fashion mnist example notebook

bentoml/archive.py, bentoml/cli/commands.py, bentoml/server/__init__.py, bentoml/server/bento_api_server.py, bentoml/server/model_api_server.py, bentoml/server/prediction_logger.py, bentoml/service.py, examples/sklearn-sentiment-clf/sklearn-sentiment-clf.ipynb, examples/tf-keras-text-classification/tf-keras-text-classification.ipynb, tests/cli/test_cli.py, tests/server/test_model_api_server.py
=> More naming cleanups for changes introduced in PR #26

.pep8speaks.yml
=> add pep8speak config

bentoml/server/metrics.py
- support all params that works with prometheus client
n/a
n/a
=> Update metrics.time decorator

scripts/lint.sh, tests/cli/test_cli.py, tests/handlers/test_image_handler.py, tests/server/test_model_api_server.py, tests/test_model.py, tests/utils.py
=> update linter script, and fix linter for test files

bentoml/version.py, setup.py
- updated project url in pypi.org
- update to 0.0.8.post1
n/a
n/a
=> Bump version to 0.0.8.post1

bentoml/archive/archiver.py, bentoml/archive/loader.py, bentoml/handlers/__init__.py, bentoml/service.py
- Clean up archive loading code path
n/a
n/a
=> Refactor BentoArchive loading

README.md, bentoml/archive/archiver.py, examples/sklearn-sentiment-clf/sklearn-sentiment-clf.ipynb, examples/tf-keras-text-classification/tf-keras-text-classification.ipynb
- update dockerfile and related docs, reflecting the CLI changes in #44 and #46 
n/a
n/a
=> Fix generated REST API server starting command

README.md, bentoml/archive/archiver.py, examples/pytorch-fashion-mnist/pytorch-fashion-mnist.ipynb, examples/sklearn-sentiment-clf/sklearn-sentiment-clf.ipynb, examples/tf-keras-fashion-mnist/tf-keras-fashion-mnist-classification.ipynb, examples/tf-keras-text-classification/tf-keras-text-classification.ipynb
- Add load method for BentoArchive PyPI package to make APIs for loading archive more consistent
n/a
n/a
=> Add load method for BentoArchive PyPI package

setup.py
- fixing a regression introduced in #46 
n/a
n/a
=> Fix bentoml package cli entry point module

bentoml/archive/archiver.py, bentoml/utils/tempdir.py
- cleanup & refactor archiver.save method
n/a
n/a
=> Cleanup archive save codepath

bentoml/archive/__init__.py, bentoml/archive/archiver.py, bentoml/archive/py_module_utils.py, tests/test_pip_install_bento_archive.py
- adding a simple functional test for `pip install ./BentoArchivePath`
n/a
n/a
=> Add functional test for pip install a BentoArchive

tests/test_pip_install_bento_archive.py
- test calling cli installed with BentoArchive PyPI package
n/a
n/a
=> Add functional test for BentoArchive PyPI package cli command

bentoml/version.py
- bump version to 0.0.9
n/a
n/a
=> 0.0.9-beta release

bentoml/cli/__init__.py, bentoml/cli/serverless.py, examples/deploy-with-serverless/README.md, examples/deploy-with-serverless/tf-keras-text-classification.ipynb
=> Update serverless example and add support for google-python platform

README.md, examples/deploy-with-kubernetes/README.md, examples/deploy-with-kubernetes/deployment.yaml, examples/deploy-with-kubernetes/service-with-ingress.yaml, examples/deploy-with-kubernetes/service-without-ingress.yaml, examples/deploy-with-kubernetes/tf-keras-text-classification.ipynb
Add deploy to kubernetes example
=> Add k8s example

bentoml/cli/__init__.py, bentoml/cli/serverless.py
=> nit formatting

README.md
Include code of conduct in readme
=> Update readme, include code of conduct

examples/sklearn-sentiment-clf/sklearn-sentiment-clf.ipynb, examples/tf-keras-text-classification/tf-keras-text-classification.ipynb
Add curl commands to Rest API service example
https://github.com/bentoml/BentoML/issues/76
=> Add curl examples to notebooks

examples/sklearn-sentiment-clf/sklearn-sentiment-clf.ipynb, examples/tf-keras-text-classification/tf-keras-text-classification.ipynb
Reverts bentoml/BentoML#101
the sklearn model input in the example doesn't seem to work, let's fix it. cc @yubozhao
=> Revert "Add curl examples to notebooks (#101)"

examples/sklearn-sentiment-clf/sklearn-sentiment-clf.ipynb, examples/tf-keras-text-classification/tf-keras-text-classification.ipynb
=> nit, update curl examples

bentoml/artifact/__init__.py, bentoml/artifact/xgboost_artifact.py
=> Add xgboost artifact

bentoml/cli/serverless.py
Issue:
serverless cli will add prefix to any given path, absolute or not. This
will create project at incorrect location.
Solution:
When user use absolute path for the ouput location, we will generate the
project in a temporary folder in the current directory and mvoe to the
desired path when we finish.
We should submit a PR to the upstream serverless project to fix this
issue, instead of using this workaround
=> Fix generate serverless project issue with absolute path.

bentoml/handlers/dataframe_handler.py, setup.py, tests/cli/test_cli.py, tests/handlers/test_dataframe_handler.py
=> add testing for dataframehandler

scripts/lint.sh
* run all lint checks even if some of them fails
n/a
n/a
=> Update script/lint.sh script

examples/sklearn-sentiment-clf/sentiment_lr_model.py, examples/sklearn-sentiment-clf/sklearn-sentiment-clf.ipynb
- update the example to include curl query request
- use typ='series' for the example
n/a
n/a
=> Update sklearn-sentiment-clf example

bentoml/version.py
- Bump version to 0.1.0
- Releasing new version to Pypi
=> Bump version to 0.1.0

bentoml/version.py, scripts/release.sh
- Bump version to 0.1.1
- fixed pypi upload issue with 0.1.0
=> Bump version to 0.1.1

bentoml/archive/archiver.py, bentoml/service_env.py
- speed up docker image build with cached layers 
- run user-defined setup script in the docker build
- include pip in conda env yml
n/a
manually tested locally
=> Improve BentoArchive docker build

bentoml/server/bento_api_server.py, bentoml/service.py
* use `api_func.__doc__` as API doc string by default
* allow override api_doc when defining an api:
```
@api(DataframeHandler, api_doc="...", api_name="...")
def func(df):
pass
```
* improved index page (baby steps towards a full swagger json definition):
n/a
manually tested locally
=> Add BentoServiceAPI doc and improve rest server index page

bentoml/archive/archiver.py, bentoml/archive/config.py, bentoml/archive/loader.py, bentoml/archive/templates.py, bentoml/service.py, bentoml/service_env.py
*  include env config in bentoml.yml
* added utility for loading/saving bentoml.yml
* added validation on bentoml version and archive type when loading an archive
n/a
n/a
=> Update bentoml.yml config file format

bentoml/handlers/image_handler.py
Add aws lambda support for image handler.
* support direct file POST to lambda endpoints.
* support image format jpeg/jpg/png
Localhost
=> Add aws lambda event support for image handler

examples/deploy-with-serverless/Deploying with serverless.ipynb, examples/deploy-with-serverless/README.md
Update deploy with serverless example
=> update deploy with serverless example and documentation

bentoml/version.py
Releasing BentoML version 0.2.0
=> Bump version to 0.2.0

bentoml/deployment/serverless/aws_lambda_template.py
=> Update lambda configuration

CONTRIBUTING.md, DEVELOPMENT.md
Add docs on how to build and run tests in a local development environment.
=> Add local development documentation

bentoml/deployment/serverless/aws_lambda_template.py, bentoml/deployment/serverless/gcp_function_template.py
Make sure we change the service name for serverless configuration
=> make sure change the serverless config's service value

.travis.yml, bentoml/cli/__init__.py, setup.py
Add test coverage in travis ci tests and report coverage results with codecov.
=> Add codecov

examples/deploy-with-kubernetes/deploy-with-kubernetes.ipynb, examples/deploy-with-sagemaker/deploy-with-sagemaker.ipynb, examples/deploy-with-serverless/deploy-with-serverless.ipynb, examples/h2o-classification/h2o-example.ipynb, examples/pytorch-fashion-mnist/pytorch-fashion-mnist.ipynb, examples/sklearn-sentiment-clf/sklearn-sentiment-clf.ipynb, examples/tf-keras-fashion-mnist/tf-keras-fashion-mnist-classification.ipynb, examples/tf-keras-text-classification/tf-keras-text-classification.ipynb, examples/xgboost-predict-titanic-survival/XGBoost-titanic-survival-prediction.ipynb
Follow up to  #162,  #161 :
* added "&cid=" to GA tags
* added "intro" paragraph to all existing example notebooks
* cleaned up the BentoML specific terminologies across a few different examples
=> Support run examples in Google Colab III

README.md, examples/deploy-with-kubernetes/README.md, examples/deploy-with-kubernetes/deploy-with-kubernetes.ipynb, examples/deploy-with-sagemaker/deploy-with-sagemaker.ipynb, examples/deploy-with-serverless/deploy-with-serverless.ipynb, examples/h2o-classification/h2o-example.ipynb, examples/pytorch-fashion-mnist/pytorch-fashion-mnist.ipynb, examples/quick-start/.gitignore, examples/quick-start/bentoml-quick-start-guide.ipynb, examples/quick-start/iris_classifier.py, examples/sklearn-sentiment-clf/sklearn-sentiment-clf.ipynb, examples/tf-keras-fashion-mnist/tf-keras-fashion-mnist-classification.ipynb, examples/tf-keras-text-classification/tf-keras-text-classification.ipynb, examples/xgboost-predict-titanic-survival/XGBoost-titanic-survival-prediction.ipynb
* moving quick start guide to a separate notebook and make it run-able on google colab
* update readme page
* fixed client_id issue with the tracking pixel in notebooks
=> Update quick start guide & readme page

scripts/format.sh
The format script.
Nope.
By running the new script locally.
```
$./scripts/format.sh 
All done! ✨ 🍰 ✨
63 files left unchanged.
```
=> Optimise linter to skip string normalization.

.gitignore
.gitignore file
Nope
Run `git status` to check
=> Update gitignore file.

bentoml/cli/__init__.py, docs/cli.rst, docs/conf.py, docs/index.rst, docs/quickstart.rst, docs/requirements.txt, setup.py
Add documentation for cli and update theme to readthedocs
=> Add documentation for cli

bentoml/server/bento_api_server.py, tests/server/test_model_api_server.py
Add /docs.json endpoint
Nope
tested locally.
=> Add docs endpoint.

bentoml/server/bento_api_server.py
Add the POST method for feedback.
Nope
=> Update docs endpoint.

bentoml/server/bento_api_server.py
=> Update the values for API docs title, version and tags on generation.

bentoml/archive/archiver.py, bentoml/archive/py_module_utils.py, bentoml/config/default_bentoml.cfg, bentoml/server/bento_api_server.py, bentoml/utils/logging.py
* fix the bug described in #175 
* also #61
=> BentoService#save should copy local python modules #175

bentoml/server/bento_api_server.py, tests/server/test_model_api_server.py
=> Add description for generating client SDK.

bentoml/handlers/dataframe_handler.py, bentoml/server/bento_api_server.py, bentoml/service.py, tests/conftest.py, tests/handlers/test_dataframe_handler.py
=> Enhance the input_parameter in DataframeHandler for docs generation.

bentoml/handlers/dataframe_handler.py, tests/conftest.py
Update dataframe handler.
#130 
=> Support input_dtypes parameter as an array.

docs/quickstart.rst
=> Fix typo in docs.

docs/quickstart.rst, examples/quick-start/bentoml-quick-start-guide.ipynb
=> Add docs for generating docs on quick start guide.

.gitignore, DEVELOPMENT.md, bentoml/archive/archiver.py, bentoml/archive/loader.py, bentoml/artifact/pickle_artifact.py, bentoml/artifact/text_file_artifact.py, bentoml/handlers/__init__.py, bentoml/handlers/dataframe_handler.py, bentoml/service.py, scripts/build-docs.sh
* Fixed a few small things in the API docs
* added build script in dev doc
=> API document improvements

bentoml/handlers/base_handlers.py
Proposed by @yubozhao 
Nope
Not tested.
=> Add a default request_schema for all bentoml handlers.

examples/quick-start/bentoml-quick-start-guide.ipynb
Add notes for resting restapi server on google colab
=> Add notes on running rest api server for Google colab for quickstart notebook

bentoml/server/bento_api_server.py, tests/conftest.py
Fix an error about request_schema not found for ImageHandler
Nope
Added unit tests.
=> Fix error: 'ImageHandler' object has no attribute 'request_schema'

bentoml/service.py
=> Simply request_schema in BentoServiceAPI.

bentoml/handlers/image_handler.py
=> Add request_schema for ImageHandler.

tests/conftest.py
=> Add more tests.

README.md, bentoml/artifact/__init__.py, bentoml/artifact/fastai_model_artifact.py, bentoml/handlers/__init__.py, bentoml/handlers/fastai_image_handler.py, bentoml/handlers/image_handler.py, docs/api.rst, setup.py, tests/handlers/test_fastai_image_handler.py, tests/handlers/test_image_handler.py
* Add fast ai model support for artifact
* Add fast ai vision support for image handler.
- fast ai model consume fastai.vision.Image instead of nparray or tensor.
WIP
=> Fastai artifact

bentoml/version.py
- update version.py for 0.2.2 release
=> Bump up version for release

examples/pytorch-fashion-mnist/pytorch-fashion-mnist.ipynb
Use the official FashionMNIST from pytorch.
=> Update example for pytorch-fashion-mnist.

bentoml/handlers/fastai_image_handler.py
remove unnecessary return statement that blocks other code 
=> fix bug in fastai image handler

bentoml/artifact/pytorch_model_artifact.py, bentoml/utils/cloudpickle.py, setup.py
* copy the cloudpickle fork in spark
* use cloudpickle for serializing pytorch models
=> Use cloudpickle for PyTorch artifacts

examples/pytorch-fashion-mnist/pytorch-fashion-mnist.ipynb
=> Try to update pytorch example with a DataframeHandler as a workaround.

bentoml/handlers/dataframe_handler.py, bentoml/utils/__init__.py, tests/handlers/test_dataframe_handler.py
Fix parse csv to dataframe issue on dataframehandler's handle request
Pass in string buffer instead of the string
=> Fix parsing csv request issue

tox.ini
=> Add fastai to py36,py36 deps in tox deps

bentoml/artifact/pytorch_model_artifact.py
=> Improve error message when loading pytorch model artifact.

bentoml/version.py
* update version.py for 0.2.2 release
=> Release 0.3.0

examples/deploy-with-clipper/fastai-pet-classifier-on-clipper.ipynb
Add fastai pet classifier example for clipper deployment
=> Add image classifer example for clipper

bentoml/handlers/image_handler.py
=> Fix a typo in Image handler.

bentoml/archive/loader.py, bentoml/cli/__init__.py, bentoml/cli/click_utils.py, bentoml/cli/deployment.py, bentoml/config/default_bentoml.cfg, bentoml/service.py, bentoml/utils/usage_stats.py, tests/__init__.py, tests/conftest.py
=> Usage tracking

bentoml/version.py
* Bump up pypi version for release 0.3.1
=> Release 0.3.1

bentoml/service.py, bentoml/service_env.py, tests/test_service_env.py
Accept list of string for the requirements_txt parameter.
=> Accept list for env's requirements_txt parameter

examples/deploy-with-clipper/deploy-iris-classifier-to-clipper.ipynb, examples/deploy-with-clipper/fastai-pet-classifier-on-clipper.ipynb, examples/deploy-with-sagemaker/deploy-with-sagemaker.ipynb, examples/h2o-classification/h2o-classification.ipynb, examples/keras-fashion-mnist/keras-fashion-mnist-classification.ipynb, examples/keras-fashion-mnist/keras_fashion_mnist.py, examples/quick-start/bentoml-quick-start-guide.ipynb, examples/quick-start/iris_classifier.py, examples/sklearn-sentiment-clf/sentiment_lr_model.py, examples/sklearn-sentiment-clf/sklearn-sentiment-clf.ipynb, examples/xgboost-predict-titanic-survival/XGBoost-titanic-survival-prediction.ipynb, examples/xgboost-predict-titanic-survival/xgboost_titanic_model.py
=> use pip_dependencies instead of conda_pip for examples

bentoml/cli/deployment.py, bentoml/config/default_bentoml.cfg, bentoml/deployment/sagemaker/__init__.py, bentoml/deployment/serverless/__init__.py, bentoml/deployment/serverless/aws_lambda_template.py, bentoml/deployment/serverless/gcp_function_template.py
refactor deployment for serverless, and little bit of sagemaker
=> refactor deployments

README.md
* change main readme from keras Image example to scikit-learn dataframe example
=> Update quick start example in README.md

bentoml/handlers/fastai_image_handler.py, bentoml/handlers/image_handler.py
=> Fix an OpenAPI error for image uploading.

bentoml/cli/__init__.py, bentoml/cli/config.py
Use subcommand pattern for `bentoml config` operations
=> Cli config subcommand

bentoml/cli/__init__.py, bentoml/cli/click_utils.py, bentoml/cli/deployment.py, bentoml/config/default_bentoml.cfg, bentoml/utils/__init__.py, bentoml/yatai/__init__.py, setup.py
=> BentoML Deployment CLI POC

bentoml/handlers/image_handler.py, tests/conftest.py
Changes on image handler:
- remove parameter `accept_multiple_files`
- rename parameter `input_name` to `input_names`
- simplify handling logic for single file case and multi-files case.
No.
By CI.
=> Refactor Image Handler by simplying multiple file handling.

bentoml/deployment/operator.py, bentoml/deployment/sagemaker/__init__.py, bentoml/deployment/serverless/aws_lambda.py, bentoml/deployment/serverless/gcp_function.py, bentoml/yatai/__init__.py
Operator apply function will also handle update along with create.
Tested locally
=> Update for operator apply

bentoml/yatai/__init__.py, tests/conftest.py, tests/server/test_model_api_server.py
Add unit test to cover the following case:
- upload one image by Fastai image handler.
Currently, Fastai image handler doesn't support multiple-image uploading
Will add more tests after adding the support.
No
by CI.
=> Add unit test for Fastai Image Handler.

bentoml/handlers/fastai_image_handler.py, tests/conftest.py, tests/server/test_model_api_server.py
Improve Fastai Image Handler by:
- Support multiple file uploading
- Add unit tests
No
by CI.
=> Support multiple file uploading for Fastai Image Handler

bentoml/cli/deployment_utils.py, bentoml/utils/validator/__init__.py, bentoml/yatai/__init__.py, setup.py, tests/utils/test_utils.py
Add validation for protobuf schema
=> Validation pb

MANIFEST.in
Update the cfg file path inside manifest.in
=> update cfg file directory in MANIFEST.in

DEVELOPMENT.md, setup.py
* removing py35 in setup.py since we are not currently testing it - please ping us on Slack if you need this
=> Remove py3.5 support in setup.py

bentoml/cli/deployment.py, bentoml/configuration/__init__.py, bentoml/deployment/sagemaker/__init__.py, bentoml/deployment/utils.py, bentoml/utils/validator/__init__.py
Update sagemaker deployment and fix bugs
=> Fix sagemaker deployment

README.md, guides/quick-start/bentoml-quick-start-guide.ipynb
* update documents, matching other notebooks in gallery repo
* removed one of the examples that got deleted
=> Quick start guide notebook updates

bentoml/deployment/sagemaker/__init__.py, tests/deployment/sagemaker/test_sagemaker.py
Better handling of Sagemaker errors
=> Improve error handling in SageMaker deployment operator

bentoml/configuration/default_bentoml.cfg, bentoml/handlers/fastai_image_handler.py, bentoml/handlers/image_handler.py, bentoml/server/bento_api_server.py
=> Preserve request image files in logs directory

guides/deployment/deploy-with-sagemaker/README.md, guides/deployment/deploy-with-serverless/README.md
=> update deployment guide readme witht he new cli commands

bentoml/cli/deployment.py, bentoml/deployment/serverless/aws_lambda.py, bentoml/proto/deployment_pb2.py, bentoml/yatai/yatai_service_impl.py, protos/deployment.proto
* Add '--force' flag for CLI delete command.
* Will remove deployment record, if the cloud resources are not found.
=> Enhance delete deployment command

bentoml/deployment/sagemaker/__init__.py, bentoml/deployment/serverless/aws_lambda.py, bentoml/deployment/serverless/serverless_utils.py, bentoml/deployment/utils.py
* omit 'docker info', 'npm install serverless' output.
* add docker check for sagemaker
=> Omit subprocess stdout print in deployment operator

bentoml/artifact/fastai_model_artifact.py, bentoml/repository/__init__.py
Implement new feature: initialise S3 Bento repository.
Nope
Not yet.
=> Implement new feature: initialise S3 Bento repository.

bentoml/configuration/default_bentoml.cfg, bentoml/repository/__init__.py, tests/conftest.py, tests/handlers/test_fastai_image_handler.py, tests/test_service.py
=> Remove unnecessary check for S3 client initialisation and implement feature: get pre-signed S3 URL.

bentoml/repository/__init__.py
=> Yatai feature: Implement retrieving and removing functionalities for s3 repo.

bentoml/cli/deployment.py, setup.py
Add pretty table option for list deployment command
=> add table option for list deployment output

bentoml/cli/__init__.py
* Fixed the issue @chetanzope helped found as described in #333 
* Tested with windows server AMI on AWS
=> Fix #333 REST API server issue on windows 

setup.py
Add click>=7.0 minimum version require check 
TypeError: __init__() got an unexpected keyword argument 'case_sensitive' #335
https://github.com/bentoml/BentoML/issues/335
manually tested locally
=> [Issue-335] Add click>=7.0 minimum version require check 

scripts/release.sh, scripts/watch-docs.sh
* Add scripts/watch-docs.sh to make writing docs locally more efficient
* It only works on Mac OS and google chrome browser
=> Add scripts/watch-docs.sh for writing/previewing docs locally

bentoml/deployment/serverless/aws_lambda.py, bentoml/yatai/yatai_service_impl.py
* make sure return pb response for delete operation
* use official support of binary media type for lambda deployment
=> Use official support of binary media type for Lambda deployment

bentoml/deployment/sagemaker/__init__.py, bentoml/deployment/serverless/serverless_utils.py, bentoml/deployment/utils.py, bentoml/exceptions.py
* use ecr tag for docker build
* fix typo
=> Use ecr tag for docker build

bentoml/yatai/python_api.py
=> Add comments and add initial upload status before uploading to S3.

bentoml/archive/loader.py, bentoml/repository/__init__.py, bentoml/yatai/python_api.py, bentoml/yatai/yatai_service_impl.py
=> Return S3 downloadable URL on upload and implement loading archive from S3.

bentoml/cli/deployment.py, bentoml/configuration/default_bentoml.cfg, bentoml/utils/validator/__init__.py, bentoml/yatai/deployment_utils.py, bentoml/yatai/python_api.py, bentoml/yatai/yatai_service_impl.py, tests/yatai/test_deployment_utils.py, tests/yatai/test_python_api.py
Clean up CLI and move deployment related to python api
=> Move deployment logic to python_api

bentoml/archive/loader.py, bentoml/yatai/python_api.py
=> Refactor parsing S3 scheme URLs.

bentoml/archive/loader.py, bentoml/service.py, bentoml/yatai/python_api.py, bentoml/yatai/status.py, bentoml/yatai/yatai_service_impl.py, tests/conftest.py, tests/test_save_and_load.py
* Improve error message when calling BentoService#save multiple times
* Refactor yatai python api upload_bento_service 
* Refactor BentoService _bento_service_version and _bento_service_bundle_version
=> Improve error message when calling BentoService#save multiple times

bentoml/cli/deployment.py, bentoml/deployment/serverless/aws_lambda.py, tests/deployment/serverless/test_aws_lambda.py
=> Add feature: support S3 repo for Lambda deployment.

bentoml/deployment/sagemaker/__init__.py, tests/deployment/sagemaker/test_sagemaker.py
=> Add feature: support repo type S3 for Sagemaker deployment.

bentoml/cli/deployment.py, bentoml/utils/usage_stats.py
=> Add platform deployment usage stats

bentoml/clipper/__init__.py, bentoml/utils/usage_stats.py, tests/utils/test_usage_stats.py
* add usage tracking for clipper deployment create
=> Clipper.ai deployment usage tracking

bentoml/artifact/__init__.py, bentoml/artifact/lightgbm_model_artifact.py
add lightgbm artifact
No
tested locally
=> Add support for LightGBM framework

bentoml/cli/deployment.py, bentoml/deployment/aws_lambda/__init__.py, bentoml/deployment/aws_lambda/utils.py, bentoml/deployment/utils.py, bentoml/yatai/python_api.py, bentoml/yatai/yatai_service_impl.py, scripts/e2e_lambda_deployment.py, setup.py, tests/deployment/aws_lambda/test_aws_lambda_deployment_operator.py, tox.ini
* Delete deployment record when it failed to create related cloud resources
* Improved error message
=> AWS Lambda Deployment misc improvements

bentoml/artifact/tf_savedmodel_artifact.py
* modify the docstring in tf_savedmodel_artifact.py, describe the usage of two kinds of TensorFlow Module
no
---------------------------
--
=> doc: tf_savedmodel_artifact docstring

bentoml/deployment/aws_lambda/__init__.py, bentoml/deployment/aws_lambda/utils.py, scripts/e2e_lambda_deployment.py, scripts/e2e_tests/aws_lambda/e2e_lambda_deployment.py, scripts/e2e_tests/aws_lambda/requirements.txt, scripts/e2e_tests/readme.MD, tests/deployment/aws_lambda/test_aws_lambda_deployment_operator.py
=> Deploy AWS Lambda improvements - handle sam command error

bentoml/configuration/default_bentoml.cfg, bentoml/server/bento_api_server.py, guides/metrics.md, tests/deployment/aws_lambda/test_aws_lambda_deployment_operator.py
=> Optimize default metrics

bentoml/cli/__init__.py
remove duplicate bentoml before {API_NAME} command usage.
no.
yes.
=> fix: remove duplicate bentoml before {API_NAME} command usage;

bentoml/server/bento_api_server.py
* Add request in progress gauge
* Add status code label to request duration
* Metrics renamings to follow prometheus convention
=> BentoAPIServer prometheus metrics improvements

bentoml/server/bento_api_server.py
=> Optimise request handler by considering 4xx error before 5xx error.

bentoml/handlers/base_handlers.py, bentoml/handlers/dataframe_handler.py, bentoml/handlers/fastai_image_handler.py, bentoml/handlers/image_handler.py, bentoml/handlers/json_handler.py, bentoml/server/bento_api_server.py, tests/handlers/test_dataframe_handler.py, tests/handlers/test_image_handler.py, tests/handlers/test_json_handler.py
* refactor request.method check
* cherry-pick #425 by @leonsim
* fix borken unit tests in #425
=> BentoAPIServer error handling refactoring

bentoml/artifact/artifact.py, bentoml/artifact/fastai_model_artifact.py, bentoml/artifact/h2o_model_artifact.py, bentoml/artifact/keras_model_artifact.py, bentoml/artifact/lightgbm_model_artifact.py, bentoml/artifact/pytorch_model_artifact.py, bentoml/artifact/sklearn_model_artifact.py, bentoml/artifact/tf_savedmodel_artifact.py, bentoml/bundler/config.py, bentoml/bundler/utils.py, bentoml/exceptions.py, bentoml/service.py, bentoml/utils/__init__.py, setup.py, tests/test_service.py
=> More exception handling improvements and cleanup

bentoml/deployment/aws_lambda/__init__.py, bentoml/deployment/aws_lambda/utils.py, bentoml/deployment/serverless/aws_lambda.py, bentoml/service.py, tests/test_service.py
* Validate artifact type
* Validate name duplication
=> Add validation to BentoService @artifact decorator

bentoml/deployment/aws_lambda/utils.py, bentoml/server/bento_api_server.py
=> Improve error handling in Bento Server.

bentoml/server/bento_api_server.py
=> Improve error message for 500 response.

bentoml/server/bento_api_server.py, bentoml/server/middlewares.py
=> Refactor instrumentation with Flask WSGI middleware.

bentoml/artifact/tf_savedmodel_artifact.py, bentoml/cli/deployment.py, bentoml/deployment/aws_lambda/utils.py, bentoml/handlers/tensorflow_tensor_handler.py, bentoml/handlers/utils.py, tests/handlers/test_tf_tensor_handler.py
=> Improve Lambda deployment - set region as envvar for sam cli subprocess call

bentoml/utils/validator/__init__.py
=> Bug fix - Update namespace validation min length

bentoml/artifact/tf_savedmodel_artifact.py
* Since input auto-reshape is magical, using concrete_function is better than reshaping input(dtype converting is still needed). 
* Sometimes the signatures of a tf.function is None(neither declared in `tf.funtion()` nor called by model.fit ).
no
In fashion_mnist example. https://github.com/bentoml/gallery/pull/10
=> use concrete_function instead of input auto-reshape

bentoml/deployment/aws_lambda/__init__.py, bentoml/deployment/sagemaker/__init__.py, scripts/e2e_tests/aws_sagemaker/e2e_sagemaker_deployment.py, scripts/e2e_tests/aws_sagemaker/requirements.txt
* add e2e testing for sagemaker
* fix bug for sagemaker envvar about gunicorn worker counts
=> Improve testing - add e2e testing for sagemaker

MANIFEST.in
Include `sagemaker_nginx.conf` for release
=> Include sagemaker nginx conf to pypi package

bentoml/cli/aws_lambda.py, bentoml/cli/bento.py, bentoml/cli/utils.py, bentoml/utils/__init__.py
* Fix CLI output option JSON/YAML
* Fix `bentoml lambda get` command
=> Fix CLI output option JSON/YAML

guides/deployment/deploy-with-Azure/deploy-with-Azure.ipynb
Add Azure deployment guide
local
=> Add Azure deployment guide

bentoml/cli/aws_lambda.py, bentoml/deployment/aws_lambda/__init__.py, bentoml/yatai/client/deployment_api.py, scripts/e2e_tests/aws_lambda/e2e_lambda_update_deployment.py
=> Lambda Deployment Improvement - update lambda deployment

bentoml/cli/__init__.py, bentoml/cli/bento.py
* Added the URI path column
* Improved datetime display
* Changed column order
=> Improve bentoml list commnad output

scripts/e2e_tests/aws_lambda/e2e_lambda_update_deployment.py
=> Update lambda e2e script to work with new cli 

README.md, docs/source/quickstart.rst, guides/quick-start/bentoml-quick-start-guide.ipynb
Update README and quick start guide to reflect recent changes that are coming in 0.6.0 release
=> Update README and quick start guide

bentoml/bundler/templates.py, bentoml/cli/__init__.py, tests/cli/test_cli.py
This PR fixes the issue starting gunicorn server, as reported here: 
https://github.com/bentoml/BentoML/issues/499
=> [ISSUE-499] bentoml serve_gunicorn wrong parameter 

README.md, docs/source/quickstart.rst
* update the legacy `deployment` command example
* other minor updates
=> [DOCS] Update quickstart guide

bentoml/handlers/dataframe_handler.py, bentoml/yatai/yatai_service_impl.py, tests/handlers/test_dataframe_handler.py
This is an improvement based on issue https://github.com/bentoml/BentoML/issues/505
=> [ISSUE-505] Make "application/json"  the default Content-Type in DataframeHandler

docs/source/deployment/clipper.rst
Add example of using ClipperHandlers for BentoService
=> Improve clipper deployment documentation guide

bentoml/artifact/tf_savedmodel_artifact.py, bentoml/bundler/loader.py, bentoml/cli/__init__.py, bentoml/configuration/default_bentoml.cfg, bentoml/handlers/__init__.py, bentoml/handlers/base_handlers.py, bentoml/handlers/dataframe_handler.py, bentoml/marshal/__init__.py, bentoml/marshal/marshal.py, bentoml/marshal/utils.py, bentoml/server/bento_api_server.py, bentoml/server/marshal_server.py, bentoml/service.py, bentoml/utils/__init__.py, setup.py, tests/handlers/test_dataframe_handler.py, tests/marshal/test_marshal.py
=> adaptive micro batching

bentoml/server/gunicorn_config.py, bentoml/utils/usage_stats.py
=> Fix server stop event tracking for gunicorn worker process

bentoml/artifact/tf_savedmodel_artifact.py, bentoml/cli/__init__.py, bentoml/handlers/__init__.py, bentoml/handlers/dataframe_handler.py, bentoml/marshal/marshal.py, bentoml/marshal/utils.py, bentoml/server/marshal_server.py, tests/handlers/test_dataframe_handler.py
* Forgot to run the `./script/format.sh` script in #454 , this PR includes only the changes made by the auto code formatter
=> Auto code-formatting for PR #454

bentoml/configuration/default_bentoml.cfg, bentoml/server/bento_api_server.py, bentoml/utils/trace.py, setup.py
=> Add API Server Tracing with Zipkin

bentoml/handlers/fastai_image_handler.py, bentoml/handlers/image_handler.py, bentoml/handlers/json_handler.py, bentoml/handlers/tensorflow_tensor_handler.py, bentoml/handlers/utils.py, bentoml/marshal/marshal.py, bentoml/marshal/utils.py, tests/handlers/test_utils.py
implement micro batching support for tf tensor handler
no
=> implement micro batching support for tf tensor handler

bentoml/cli/__init__.py
support bash completion for bentoml cli.
https://github.com/bentoml/BentoML/issues/506
=> feat: support bash completion

bentoml/bundler/templates.py
add serve flags to dockerfile
no
=> add serve flags to dockerfile

bentoml/cli/__init__.py, bentoml/marshal/marshal.py, bentoml/service.py
=> add tracing for marshal service and user handler

README.md
=> Fix broken link for clipper deployment in the README

bentoml/bundler/bundler.py, bentoml/bundler/py_module_utils.py, bentoml/cli/__init__.py, bentoml/service.py, bentoml/service_env.py, bentoml/utils/pip_pkg.py
Support auto pip dependencies and check user dependency version.
https://github.com/bentoml/BentoML/issues/450
https://github.com/bentoml/BentoML/issues/531
=> Support auto pip dependencies and check user dependency version

bentoml/service_env.py, bentoml/utils/pip_pkg.py
Fix remaining problems for auto pip pull request: 
https://github.com/bentoml/BentoML/pull/536
=> Auto pip dependencies follow up fixes

README.md
=> Add tensorflow 2 fashion mnist notebook example to README

bentoml/service.py, bentoml/service_env.py
* fix bentoml deploy version when auto_pip_dependencies is enabled
* it should update metadata config file when auto_pip_dependencies enabled
=> Fix: auto_pip_dependencies should update metadata config file

bentoml/configuration/default_bentoml.cfg, bentoml/handlers/dataframe_handler.py, bentoml/handlers/tensorflow_tensor_handler.py, bentoml/marshal/__init__.py, bentoml/marshal/marshal.py, bentoml/marshal/utils.py, bentoml/server/marshal_server.py, bentoml/service.py, bentoml/utils/trace.py
=> opt adaptive microbatch service

bentoml/marshal/marshal.py
=> make marshal server relay GET requests

bentoml/cli/__init__.py, bentoml/server/marshal_server.py, tests/marshal/test_marshal.py
=> serve micro batch server with gunicorn

setup.py
+ sqlalchemy-utils should be a required dependency
+ remove "postgres" extra dependencies from test deps
=> Add sqlalchemy-utils to install_requires

DEVELOPMENT.md, bentoml/cli/yatai_service.py, docs/source/concepts/yatai_service.rst
=> CLI yatai-service-start command  improvements

bentoml/handlers/dataframe_handler.py, tests/handlers/test_dataframe_handler.py
=> fix dataframe batch handler

bentoml/cli/__init__.py, bentoml/handlers/base_handlers.py, bentoml/handlers/dataframe_handler.py, bentoml/handlers/tensorflow_tensor_handler.py, bentoml/marshal/dispatcher.py, bentoml/marshal/marshal.py, bentoml/marshal/utils.py, bentoml/server/gunicorn_config.py, bentoml/server/marshal_server.py, bentoml/service.py, setup.py
=> add metrics stat for microbatch service

benchmark/tensorflow_2_fashion_mnist/tensorflow_2_fashion_mnist-serving.ipynb, bentoml/cli/__init__.py, bentoml/marshal/dispatcher.py, bentoml/server/gunicorn_server.py, bentoml/server/marshal_server.py, bentoml/server/utils.py
=> marshal server minor fixes

bentoml/handlers/json_handler.py, bentoml/handlers/utils.py, tests/handlers/test_utils.py
TODOs:
* add warning about the breaking change of json handler
* add `Bento-Multi-Input-Flag`
* update examples
=> json handler: add adaptive batching support

bentoml/configuration/default_bentoml.cfg, bentoml/handlers/base_handlers.py, bentoml/handlers/dataframe_handler.py, bentoml/handlers/json_handler.py, bentoml/handlers/tensorflow_tensor_handler.py, bentoml/marshal/utils.py
=> Add batch request flags for handlers

bentoml/marshal/marshal.py
=> Fix: make batching server relay root path

benchmark/dummy_model/linear_sleep.ipynb, benchmark/dummy_model/linear_sleep_clipper.ipynb, benchmark/dummy_model/linear_sleep_mlflow.ipynb
=> Add dummy model benchmark

setup.py
To fix the UnicodeDecodeError when system locale is not UTF8.
=> Fix: UnicodeDecodeError during installation

bentoml/cli/__init__.py, bentoml/marshal/dispatcher.py, bentoml/marshal/marshal.py
=> Implement adaptive waiting time for batching server

bentoml/yatai/web/client/src/components/BentoServiceDetail/ApisTable.tsx, bentoml/yatai/web/client/src/components/BentoServiceDetail/ArtifactsTable.tsx, bentoml/yatai/web/client/src/components/BentoServiceTable.tsx, bentoml/yatai/web/client/src/ui/Table.tsx
=> [enhancement]Clean up yatai web client

docs/source/deployment/index.rst, docs/source/deployment/knative.rst
=> [Documentation] Add knative deployment guide

.travis.yml, tests/conftest.py, tests/handlers/test_image_handler.py, tests/server/test_model_api_server.py
cc https://github.com/python-pillow/Pillow/issues/4509
=> Fix ImageHandler unit tests issue with Pillow 7.1.0

bentoml/yatai/web/webpack.config.js
* use production more
* cleanup config file
=> Update yatai web server webpack config

benchmark/__init__.py
To fix the stat error introduced by previous commit.
=> Fix(benchmark): stat error

bentoml/yatai/web/client/src/pages/HomePage.tsx
=> YataiService web UI index page emoji encoding fix

README.md, docs/source/deployment/knative.rst, docs/source/quickstart.rst
* Point out "save bentoservice class definition to a separate file" in quick start guide
* fixed docs build issue with knative docs
* Added knative guide to readme.md
=> [DOCS] update README.md and quickstart guide

README.md, docs/source/quickstart.rst
* update headline
* use bash variable for saved_path to make it possible to copy code and run
*
=> [DOCS] Quickstart guide updates

bentoml/cli/aws_sagemaker.py, bentoml/deployment/sagemaker/__init__.py, bentoml/deployment/sagemaker/sagemaker_serve.py, bentoml/proto/deployment_pb2.py, bentoml/utils/validator/__init__.py, bentoml/yatai/client/deployment_api.py, bentoml/yatai/web/src/generated/bentoml_grpc.d.ts, bentoml/yatai/web/src/generated/bentoml_grpc.js, protos/deployment.proto
=> Add `timeout` option for Sagemaker deployment

.gitignore, .vscode/settings.json, docs/source/api/handlers.rst, docs/source/concepts.rst, docs/source/examples.md, docs/source/index.rst, docs/source/quickstart.rst
* Add docs micro-batching and yatai-service
* Add gallery examples and community projects to docs site
* Quickstart cleanups
=> [DOCS] Add docs for using micro-batching and yatai-service

.pep8speaks.yml, guides/quick-start/.gitignore, guides/quick-start/iris_classifier.py
* add iris_classifier.py to repo instead of ignoring in git
* Make sure user can run:
```
git clone git@github.com:bentoml/BentoML.git
python BentoML/guides/quick-start/main.py
```
=> Check in iris_classifier.py file used in quickstart guide

docs/source/deployment/aws_ecs.rst, docs/source/deployment/aws_lambda.rst, docs/source/deployment/aws_sagemaker.rst, docs/source/deployment/knative.rst
* The entire code block is actually missing in the HTML output without the empty line in between code-block and its content
=> [DOCS] fix code-block formatting

bentoml/artifact/__init__.py, bentoml/artifact/fasttext_model_artifact.py
Added an Artifact class for Fasttext models.
#604 
Passed bentoml test suite & was able to build/deploy fasttext models to an endpoint.
=> Support for Fasttext

tests/bento_service_examples/bento_service_with_modified_sys_path.py, tests/test_bundle_local_dependencies.py
Trying to reproduce the issue in #608
=> Add test covering when sys.path is modified for local python dependency

bentoml/bundler/templates.py, tests/test_pip_install_saved_bundle.py
=> [FIX] setup.py template properly handles pip version >=20.1

README.md, docs/source/deployment/heroku.rst, docs/source/deployment/index.rst, docs/source/deployment/kfserving.rst, docs/source/deployment/kubeflow.rst
=> [Docs] Add deployment guide for kubernetes/kubeflow/kfserving

docs/source/concepts.rst
=> [Docs]Nit fix typo in core concept doc

docs/source/deployment/aws_ecs.rst, docs/source/deployment/aws_lambda.rst, docs/source/deployment/aws_sagemaker.rst, docs/source/deployment/azure_container_instance.rst, docs/source/deployment/clipper.rst, docs/source/deployment/google_cloud_run.rst, docs/source/deployment/heroku.rst, docs/source/deployment/kfserving.rst, docs/source/deployment/knative.rst, docs/source/deployment/kubeflow.rst
=> [Docs] nit: fix links and format

bentoml/service_env.py
See details about the issue here: https://github.com/bentoml/BentoML/pull/596#issuecomment-624354686
=> Fix issue with fastcore and ruamel-yaml

bentoml/yatai/web/src/server.ts, docker/yatai-service/Dockerfile, e2e_tests/conftest.py, e2e_tests/yatai_server/test_yatai_docker_container.py, setup.py
Fix postgres modules dependencies issue
Fix use relative path instead, for yatai service web ui
=> fix yatai service postgress dependency issue

README.md, docs/source/frameworks.rst
=> Add fasttext example notebook to readme and doc

bentoml/yatai/web/src/server.ts
Revert the change for how yatai service web ui serve files.
=> Revert changes for yatai service UI

bentoml/artifact/fastai2_model_artifact.py, bentoml/artifact/fasttext_model_artifact.py, bentoml/utils/s3.py, e2e_tests/conftest.py
* add test for yatai service docker image
* linter
=> Add test for Yatai service docker image

bentoml/exceptions.py, bentoml/handlers/dataframe_handler.py, bentoml/marshal/dispatcher.py, bentoml/marshal/marshal.py, bentoml/marshal/utils.py, tests/marshal/dispatcher_benchmark.py, tests/marshal/test_dispatcher.py
Refactor exception handling of batching service. Also fixed a bug that counts failed requests as outbound statistic.
=> Chore(batching): exception handling

bentoml/repository/__init__.py, e2e_tests/yatai_server/test_postgres_s3.py, e2e_tests/yatai_server/test_sqlite_s3.py
* fix double dash issue, if s3 path only provide the bucket name
=> Add e2e test for s3 repo storage

README.md, bentoml/cli/yatai_service.py, bentoml/configuration/default_bentoml.cfg, bentoml/repository/__init__.py, bentoml/yatai/__init__.py, bentoml/yatai/yatai_service_impl.py, e2e_tests/conftest.py
- Add s3_endpoint_url option to support S3-like service
https://github.com/bentoml/BentoML/issues/640
Manually tested locally, e2e test will be added in a separate PR
=> Add s3_endpoint_url option to support S3-like service

bentoml/deployment/aws_lambda/utils.py
Fixing an issue surfaced after https://github.com/bentoml/BentoML/pull/657
e2e test covered this
=> [Lambda] fix requirements list in lambda sam project

.travis.yml, bentoml/bundler/config.py, bentoml/cli/__init__.py, bentoml/utils/pip_pkg.py, tests/cli/test_cli.py, tests/test_bundle_local_dependencies.py, tests/test_pip_install_saved_bundle.py, tests/test_service_env.py
=> [CI] add CI for Windows platform

docs/source/concepts.rst
=> [DOCS] Fix a typo in the 'concepts' document

bentoml/repository/__init__.py, bentoml/yatai/client/bento_repository_api.py
This patch will resolve [the S3 issue](https://github.com/bentoml/BentoML/pull/679#issuecomment-629907043).
=> Fix the internal uri for S3

e2e_tests/aws_sagemaker/test_sagemaker_deployment.py, e2e_tests/iris_classifier_example.py
=> [TEST] fix sagemaker e2e test issue with scikit-learn new release

docs/source/guides/yatai_service.rst
=> [DOCS] add docs for yatai dashboard deployment

.github/PULL_REQUEST_TEMPLATE.md, .github/stale.yml, bentoml/bundler/bundler.py, bentoml/deployment/sagemaker/__init__.py, e2e_tests/aws_sagemaker/utils.py, setup.py
* Updated PR template to include a checklist and component selection
* The checklist includes running code style check script, we will need this manual check before https://github.com/bentoml/BentoML/issues/711 is done
=> Update Github pull-request template with checklist

.travis.yml, dev/lint.sh, setup.py
Modified linting script such that Travis builds will fail on linting errors
To enforce no future linting errors arise
solves issue #711 
I created a Travis build environment for my forked repo and tested on that by deliberately adding linting errors
=> [CI] Perform linting test during build

bentoml/bundler/py_module_utils.py
Attempt to fix https://github.com/bentoml/BentoML/pull/718
=> [Bug] ModuleNotFoundError: No module named 'mock'

bentoml/artifact/__init__.py, bentoml/artifact/onnx_model_artifact.py, tests/artifact/test_onnx_model_artifact.py, tests/bento_service_examples/onnx_onnxruntime_iris_classifier.py
https://github.com/bentoml/BentoML/issues/621
=> Add ONNX model artifact

docs/source/concepts.rst, docs/source/faq.rst
Minor typo fix
Improve document quality.
Locally.
=> Fix typo: dockerisation

README.md, docs/source/api/artifacts.rst, docs/source/examples.md
=> [Doc] Add onnx Artifact to api page

.travis.yml, tests/artifact/test_onnx_model_artifact.py, travis/run_model_artifacts_tests.sh, travis/run_onnx_model_artifact_tests.sh, travis/run_python_tests.sh
Include onnx artifact tests with python 3.6 on travis ci
Add travis directory
=> [Tests]Include onnx artifact test on travis

bentoml/handlers/image_handler.py, tests/conftest.py, tests/handlers/test_image_handler.py
=> Add list input support in ImageHandler CLI

bentoml/handlers/image_handler.py, bentoml/handlers/legacy_image_handler.py
=> [DOC] update docstring of new ImageHandler

bentoml/handlers/image_handler.py
=> Add batch-size to ImageHandler CLI

bentoml/configuration/default_bentoml.cfg
Remove unused "aws" and "google-cloud" fields from `bentoml.cfg`
=> Remove unused "aws.region" config

bentoml/service.py, tests/bento_service_examples/example_bento_service.py, tests/cli/test_cli.py, tests/handlers/test_fastai_image_handler.py, tests/server/test_model_api_server.py, tests/test_pip_install_saved_bundle.py, tests/test_service.py
=> Use new api_decorator signature for coming output adapter

README.md, docs/source/examples.md
Add onnx resnet50 example notebook to BentoML gallery
=> Add resnet50 (onnx model zoo) example notebook to doc and readme

bentoml/artifact/json_artifact.py, bentoml/handlers/dataframe_handler.py, bentoml/handlers/json_handler.py, tests/artifact/test_json_artifact.py
The DataFrame handler (as well as the JsonHandler) do not return the necessary headers for CORS support in AWS Lambda. I've added to both these handlers a cors keyword (defualts to `"*"`) which, if is not set to None, causes the `handle_aws_lambda_event` to return, along with `"statusCode"` and `"body"` also `headers: {'Access-Control-Allow-Origin': self.cors}`.
This solves a problem I had back in BentoML `0.6.0` up to `0.6.3` where otherwise I was unable to integrate the results from the AWS Lambda deployment with a web-service. I also opened an issue, https://github.com/bentoml/BentoML/issues/509, which was closed due to inactivity (not because the problem was solved). This PR should solve the problem.
I tested this in my own deployment (based on BentoML 0.6.3). Since this is a very …
=> Add CORS support for AWS Lambda serving

bentoml/bundler/templates.py, bentoml/clipper/__init__.py, bentoml/configuration/__init__.py, bentoml/configuration/default_bentoml.cfg, bentoml/deployment/sagemaker/__init__.py, bentoml/server/bento_sagemaker_server.py, dev/lint.sh, dev/release_docker_images.sh, dev/release_pypi.sh, docker/model-server/Dockerfile, docker/model-server/Dockerfile-alpine, docker/model-server/entrypoint.sh, docker/model-server/release.sh, docker/yatai-service/Dockerfile, docker/yatai-service/release.sh, docs/source/deployment/clipper.rst, e2e_tests/conftest.py, travis/onnx_integration_tests.sh, travis/unit_tests.sh
A number of refactoring around BentoML model server Dockerisation code path:
* Introduced the `bentoml/model-server` base image, which speeds up the docker build process a lot
* Removed the dependency on `apt-get` and `conda` from the `docker_base_image` config, see https://github.com/bentoml/BentoML/issues/693
* when conda is not available, the conda dependencies specified by the user in the `environment.yml` will be ignored
* Alpine based docker image is possible now, it is still working in progress, will need follow-up work to fully support it
Yes manually tested locally, will need integration tests for this https://github.com/bentoml/BentoML/issues/759
([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-f …
=> Refactor model server Dockerisation 

.travis.yml, tests/bento_service_examples/pytorch_classifier.py, tests/integration_tests/test_pytorch_model_artifact.py, travis/run-keras-tests.sh, travis/run-pytorch-tests.sh
I have added the integration tests for PyTorch artifacts based on the commits form #726.
I've added a unit test for the Pytorch artefact were I create a simple model where the model is initialized with all *ones*. Hence the forward run of the model will give always give deterministic results. I also created a `run-keras-tests.py` script that installs tensorflow and performs the tests.
This PR is based on #723 
=> Integration tests for Pytorch artifacts

.travis.yml, bentoml/__init__.py, dev/format.sh, dev/lint.sh, setup.py, travis/linter.sh, travis/pytorch_integration_tests.sh
Make it a required step for contributors to run `./dev/format.sh` for their code changes to get passed on travis
=> Add code auto-formatting script to travis linter check task

bentoml/handlers/dataframe_handler.py, bentoml/handlers/tensorflow_tensor_handler.py, bentoml/handlers/utils.py, tests/handlers/test_tf_tensor_handler.py
Fixing issue reported in https://github.com/bentoml/BentoML/issues/763
=> [FIX] Fix errors when inheriting handler

docs/source/concepts.rst, docs/source/deployment/aws_ecs.rst, docs/source/deployment/aws_lambda.rst, docs/source/deployment/aws_sagemaker.rst, docs/source/deployment/azure_container_instance.rst, docs/source/deployment/clipper.rst, docs/source/deployment/google_cloud_run.rst, docs/source/deployment/heroku.rst, docs/source/deployment/kfserving.rst, docs/source/deployment/kubeflow.rst, docs/source/deployment/kubernetes.rst, docs/source/faq.rst, docs/source/guides/batch_serving.rst, docs/source/guides/custom_artifact.rst, docs/source/guides/custom_handler.rst, docs/source/guides/index.rst, docs/source/guides/logging.rst, docs/source/guides/monitoring.rst, docs/source/index.rst, docs/source/quickstart.rst
Fix an error in the documentation about packing a model into a service.
The code will now run properly, so people getting started with BentoML will not be confused.
Built the documentation with `docs/build.sh` and checked that everything was updated properly
=> Documentation updates

bentoml/yatai/deployment/operator.py, bentoml/yatai/deployment_utils.py, bentoml/yatai/proto/deployment_pb2.py, bentoml/yatai/validator/deployment_pb_validator.py, bentoml/yatai/web/src/generated/bentoml_grpc.d.ts, bentoml/yatai/web/src/generated/bentoml_grpc.js, protos/deployment.proto
Add Azure function deployment configuration to deployment protobuf definition
=> [Deployment] Add azure function config to deployment protobuf

docs/source/concepts.rst
remove "this" to make the sentence grammatically correct.
=> [DOCS] minor update on core concepts doc

setup.py
=> [CI/TEST] Set minimum pytest version to 4.6.0

bentoml/saved_bundle/config.py, bentoml/yatai/repository/metadata_store.py
=> Supports viewing saved bundle created before adapters refactor

README.md, docs/source/api/adapters.rst, docs/source/concepts.rst, docs/source/index.rst, docs/source/quickstart.rst, guides/quick-start/bentoml-quick-start-guide.ipynb
* Minor changes in `readme.md` and `quickstart` guide & notebook
* A few changes related to the input/output adapter terminology change
=> [DOCS] update for the 0.8.0 release

bentoml/adapters/__init__.py, bentoml/adapters/default_output.py, bentoml/adapters/json_output.py
=> [FIX] typo of JsonSerializableOutput

bentoml/yatai/deployment/aws_lambda/utils.py, e2e_tests/conftest.py
=> [Bug] fix bundled pip dependencies installation in Lambda deployment

bentoml/adapters/legacy_image_input.py, bentoml/configuration/__init__.py, bentoml/handlers/__init__.py
Summary:
* Everything is still backward compatible at this point
* In the new Input Adapter API introduced in 0.8.0, the  `LegacyImageInput` is identical to the previous `ImageHandler`
* The new `ImageInput` works only for single image input, unlike the old `ImageHandler`
* For users using the old `ImageHandler`, we recommend migrating to the new `ImageInput` if it is only used to handle single image input
* For users using `ImageHanlder` for multiple images input, wait until the `MultiImageInput` is added, which will be a separate input adapter type
=> FIx ImageHandler backwards compatibility

MANIFEST.in
* Fix an issue with the 0.8.0 release where `.sh` files are not packaged with the PyPI build
=> Fix FileNotFoundError: No such file or directory .../docker-entrypoint.sh

docker/model-server/Dockerfile-alpine, docker/model-server/release.sh
* Fixed the alpine image build and release script
=> Fix alpine based API server docker image build

bentoml/adapters/dataframe_input.py
The follow error was thrown when using dataframe handler with micro batching enabled:
```bash
[2020-06-15 14:45:40,446] ERROR - Exception on /predict [POST]
File "/Users/chaoyu/workspace/BentoML/bentoml/server/bento_api_server.py", line 265, in api_func
response_body = api.handle_batch_request(request)
File "/Users/chaoyu/workspace/BentoML/bentoml/service.py", line 122, in handle_batch_request
responses = self.handler.handle_batch_request(requests, self.func)
File "/Users/chaoyu/workspace/BentoML/bentoml/adapters/dataframe_input.py", line 304, in handle_batch_request
result_conc, slices=slices, requests=requests,
File "/Users/chaoyu/workspace/BentoML/bentoml/adapters/default_output.py", line 85, in to_batch_response
result_conc, slices, fallbacks, …
```
=> Fix DataframeInput when used with --enable-microbatch

bentoml/adapters/__init__.py, bentoml/adapters/multi_image_input.py
=> Add a placeholder for MultiImageInput

bentoml/marshal/marshal.py, bentoml/saved_bundle/config.py, bentoml/service.py, bentoml/yatai/proto/repository_pb2.py, bentoml/yatai/web/src/generated/bentoml_grpc.d.ts, bentoml/yatai/web/src/generated/bentoml_grpc.js, protos/repository.proto, tests/bento_service_examples/example_bento_service.py, tests/handlers/test_image_handler.py, tests/test_save_and_load.py
=> [FIX] service API micro batch parameters

bentoml/adapters/dataframe_input.py, bentoml/adapters/json_output.py, bentoml/adapters/tensorflow_tensor_output.py, bentoml/utils/__init__.py, bentoml/utils/dataframe_util.py, docs/source/concepts.rst, tests/handlers/test_dataframe_handler.py
=> [FIX] support other orients except table

bentoml/utils/dataframe_util.py, tests/handlers/test_dataframe_handler.py
=> [FIX] Operate csv following RFC4180

bentoml/adapters/base_input.py, bentoml/adapters/dataframe_input.py, bentoml/adapters/dataframe_output.py, bentoml/adapters/fastai_image_input.py, bentoml/utils/dataframe_util.py
=> [STYLE] clean code about dataframe utils

bentoml/saved_bundle/config.py
=> [FIX] default micro batch parameters

bentoml/cli/bento.py, bentoml/saved_bundle/__init__.py, bentoml/saved_bundle/loader.py
This PR adds a `retrieve` method to the cli, allowing the bento cli to retrieve a services artifacts from YataiService. This will small change enable new interesting use cases for CI.
closes https://github.com/bentoml/BentoML/issues/775
As noted in https://github.com/bentoml/BentoML/issues/775, this small addition will create some super interesting possibilities for CI pipelines.
Locally and on my developer k8s cluster
=> Add retrieve cli cmd

bentoml/adapters/base_input.py, bentoml/server/bento_api_server.py, bentoml/server/open_api.py, bentoml/service.py
- Add support for specifying example input for user-defined endpoints as discussed in #491 
- Add requestBody in swagger UI for `/feedback` POST
- Change mime-type of `/healthz` to `text/plain` 
- Implements #491 
- Allows testing infra endpoints via swagger UI
- swagger UI gives parse error for `/healthz` if mime-type is `application/json`
Local Deployment 
It doesn't require changes to documentation but an example for example input would be good.
I will add the documentation later in the week.
=> ModelServer API Swagger schema improvements

bentoml/service.py, bentoml/yatai/client/__init__.py
Replace the instances of `@property` where an underlying `_[property]` was used to cache the first value with `@cached_property` from `werkzeug.utils`
Cuts down on noise in the codebase and makes the code easier to read.
=> [Refactor] use cached_property 

bentoml/cli/aws_lambda.py, bentoml/cli/aws_sagemaker.py
Make BentoService a required option for Lambda's deploy command
=> Require bento tag for lambda cli deploy command

docs/source/deployment/azure_functions.rst, docs/source/deployment/index.rst
Add Azure deployment guide to the documentation
=> [Doc] Add Azure Functions deployment guide

.github/PULL_REQUEST_TEMPLATE.md, .vscode/settings.json, CONTRIBUTING.md, README.md, docs/source/index.rst
* Updated CONTRIBUTING doc to help new contributors
* Updated PR template
* Added link to BentoML discussions mailing list
=> Update contributing doc and add mailing list link

MANIFEST.in
=> [Fix]Update manifest file for the correct nginx conf

MANIFEST.in, bentoml/configuration/__init__.py, bentoml/configuration/default_bentoml.cfg, bentoml/saved_bundle/bundler.py, bentoml/saved_bundle/config.py, bentoml/utils/usage_stats.py, bentoml/yatai/client/bento_repository_api.py, e2e_tests/conftest.py
* Allows running e2e test to run on installed bentoml, this will help us catch errors like this https://github.com/bentoml/BentoML/issues/832
* Fix core/bentoml_deploy_version config
* Fix creating saved bundles with a modified version of bentoml
* Improved warning message about bentoml version mismatching etc
=> Fix configuring bentoml_deploy_version

MANIFEST.in
* Fix a typo that causes Azure Functions deployment to fail, when using pip-installed bentoml
=> Fix Azure Functions settings.json file name in MANIFEST.in

bentoml/cli/click_utils.py, bentoml/configuration/__init__.py, bentoml/server/bento_api_server.py, bentoml/utils/log.py, bentoml/yatai/yatai_service.py
Currently, the BentoML debug mode option is not passed to the model server flask app, this PR fixes that and added a few utility functions for setting and getting current debug mode
=> Set API server debug mode when using --debug/--verbose

protos/generate-docker.sh, protos/generate.sh, setup.py
Follow up https://github.com/bentoml/BentoML/pull/826:
* Fix the docker image build - should rebuild image when dockerfile or dependency have changed
* Use docker local build cache properly
* Pre-install pbjs cli dependencies
* Fixed grpc related dependency installation in this build script
=> [CI/BUILD] generate protobuf code in docker

bentoml/cli/aws_lambda.py, bentoml/cli/azure_functions.py
=> [CLI] Fix azure-functions cli messages

bentoml/service.py
Format issue for API docstring example
=> [Doc]fix api docstring example

bentoml/yatai/web/package.json, bentoml/yatai/web/src/generated/bentoml_grpc.d.ts, bentoml/yatai/web/src/generated/bentoml_grpc.js, bentoml/yatai/web/yarn.lock, protos/generate-docker.sh
Previously the proto generator docker was using a different version of protobufjs than the version used in the node code base managed by yarn(in package.json).  This PR makes them consistent and upgraded to the latest 6.9.0 version.
Building the node server with `yarn build` was failing due to this issue
=> Upgrade protobufjs to version 6.9.0

bentoml/marshal/marshal.py
Fix: #856 
The latest release introduced two issue when micro-batch enabled.
1. Broken marshal server
1. Port conflict when running `serve` command with `--debug` flag
This PR fixed the first one.
I'm currently working on integration tests of micro-batch
=> Fix: 500 Error without message when micro-batch enabled

docs/source/deployment/aws_lambda.rst, docs/source/deployment/aws_sagemaker.rst, docs/source/deployment/azure_functions.rst
=> [Documentation]Add deploy remote YataiService for AWS Lambda and Sagemaker deployment guide

CONTRIBUTING.md, GOVERNANCE.md, README.md
As the BentoML project grows in community members, contributors, and organizations involved with the project, we see the needs of an official governence document that describes the decision-making process and related roles and responsibilities.
The PR adds the initial governance document for the BentoML project.
=> Add BentoML governance document

DEVELOPMENT.md, Makefile
Adding a makefile to make developer's lives easier
Locally
=> add makefile

bentoml/utils/benchmark.py
The benchmark client makes it easier to decide suitable runtime parameters like mb_max_latency.
=> [DOC] benchmark client

tests/conftest.py, tests/integration/api_server/conftest.py, tests/integration/api_server/example_service.py, tests/integration/api_server/test_adapter.py, travis/integration_tests.sh
Employ pytest session to start/stop server container.
=> [CI] Refactor API Server integration tests

tests/integration/api_server/conftest.py
=> [CI] ensure test server ready by checking /healthz

bentoml/service.py
Validate if  api_name is reserved for infra endpoints 
[ref](https://github.com/bentoml/BentoML/pull/839#discussion_r448680611)
Manually
=> Add reserved _api_name validation

bentoml/cli/bento_service.py
We noticed that users rarely use the `--with-conda` option because of it being too slow in the development environment. And it is not recommended for production use. So we decided to just remove the option to avoid confusion there.
=> Remove CLI --with-conda option

bentoml/saved_bundle/config.py, bentoml/saved_bundle/loader.py, bentoml/server/bento_api_server.py, bentoml/server/open_api.py, bentoml/service.py, bentoml/yatai/deployment/aws_lambda/lambda_app.py, bentoml/yatai/deployment/sagemaker/model_server.py, docs/source/api/bentoml.rst, tests/adapters/test_fastai_image_handler.py, tests/deployment/aws_lambda/test_aws_lambda_deployment_operator.py, tests/test_save_and_load.py
* Updated lots of outdated inline comments and API docs
* Refactored BentoService base class structure
* Renamed BentoServiceAPI to InferenceAPI, as we are planning to allow users to define other types of endpoints to BentoService, this name can be confusing. 
=> BentoService refactoring and docs improvements

bentoml/artifact/artifact.py, bentoml/artifact/fastai2_model_artifact.py, bentoml/artifact/fastai_model_artifact.py, bentoml/artifact/fasttext_model_artifact.py, bentoml/artifact/h2o_model_artifact.py, bentoml/artifact/json_artifact.py, bentoml/artifact/keras_model_artifact.py, bentoml/artifact/lightgbm_model_artifact.py, bentoml/artifact/onnx_model_artifact.py, bentoml/artifact/pickle_artifact.py, bentoml/artifact/pytorch_model_artifact.py, bentoml/artifact/sklearn_model_artifact.py, bentoml/artifact/spacy_model_artifact.py, bentoml/artifact/text_file_artifact.py, bentoml/artifact/tf_savedmodel_artifact.py, bentoml/artifact/xgboost_model_artifact.py, bentoml/saved_bundle/config.py, bentoml/service.py
* Removed the unnecessarily complicated artifact wrapper pattern currently used in all artifact classes
* Refactored all artifact classes to follow the new & simpler pattern
* The wrapper pattern is still available when needed, e.g. in the TensorflowSavedModelArtifact
* No user-facing changes
* Custom model artifacts adopting the old pattern should still work
* Will follow up with a PR that adds validation in `get` and `save` to make sure that the model is already packed or it is loaded from disk.
=> Refactor artifact model loading pattern

bentoml/yatai/deployment/aws_lambda/operator.py
Use shorthand Cors setting that includes `AllowMethods` and `AllowHeaders`
=> Use shorthand Cors for SAM configuration

bentoml/yatai/web/package.json, bentoml/yatai/web/src/server.ts
Fix  #903 
Test locally with an ubuntu docker container
=> Direct start yatai web ui script to the correct target file

bentoml/cli/bento_service.py, bentoml/server/__init__.py, bentoml/server/api_server.py, bentoml/utils/flask_ngrok.py, tests/utils/test_usage_stats.py
Support ngrok tunneling service
#894
```
python ./guides/quick-start/main.py
bentoml serve --run-with-ngrok IrisClassifier\20200720224248_727797
```
=> Added Ngrok support

bentoml/marshal/marshal.py
=> [FIX] batching error handling

bentoml/marshal/dispatcher.py, tests/adapters/test_dataframe_handler.py, tests/conftest.py, tests/integration/api_server/conftest.py, tests/integration/api_server/example_service.py, tests/integration/api_server/test_microbatch.py, tests/marshal/test_dispatcher.py
=> [CI] add tests for micro batching

bentoml/artifact/artifact.py, bentoml/artifact/fastai2_model_artifact.py, bentoml/artifact/fastai_model_artifact.py, bentoml/artifact/fasttext_model_artifact.py, bentoml/artifact/h2o_model_artifact.py, bentoml/artifact/keras_model_artifact.py, bentoml/artifact/lightgbm_model_artifact.py, bentoml/artifact/onnx_model_artifact.py, bentoml/artifact/pickle_artifact.py, bentoml/artifact/pytorch_model_artifact.py, bentoml/artifact/sklearn_model_artifact.py, bentoml/artifact/spacy_model_artifact.py, bentoml/artifact/tf_savedmodel_artifact.py, bentoml/artifact/xgboost_model_artifact.py, bentoml/service.py, bentoml/service_env.py
* Improve the artifact API for specifying dependencies
* New API now allows direct access to the BentoServiceEnv instance
* In addition to pip dependencies, artifact implementation can also use this to set service conda dependency and init scripts
=> Artifact refactoring: set_dependencies method 

bentoml/yatai/deployment/sagemaker/operator.py
fix #892 
Locally and on Ec2 machine
=> include assumed-role as part of accept ARN

bentoml/yatai/yatai_service_impl.py
Fix ListDeployment's error return.
test locally
=> [Fix]correct list deployments error response

bentoml/adapters/__init__.py, bentoml/adapters/file_input.py, tests/adapters/test_file_handler.py, tests/adapters/test_image_handler.py, tests/conftest.py, tests/integration/api_server/example_service.py, tests/integration/api_server/test_adapter.py
=> Add file input adapter(BinaryInput)

bentoml/adapters/file_input.py, bentoml/adapters/image_input.py
Add examples and alternatives recommendation to docs
=> Revise docs of FileInput & ImageInput

bentoml/adapters/json_input.py
=> Update doc of JsonInput

bentoml/saved_bundle/pip_pkg.py, bentoml/saved_bundle/py_module_utils.py, tests/integration/test_coreml_model_artifact.py
The issue was first discovered in the CoreML PR: https://github.com/bentoml/BentoML/pull/939, when the CoreML module was added, the ModuleFinder started exceeding the recursion limit. This PR solves this problem by excluding BentoML module from the ModuleFinder instead of filtering BentoML in the run_scripts's results.
=> Fix `RecursionError: maximum recursion depth exceeded` when saving BentoService bundle

e2e_tests/sample_bento_service.py
Make sure the BentoService in testing return list of JSON for the JsonOutputAdapter
=> Fix JsonInput usage in e2e test example BentoService code

bentoml/cli/bento_service.py
Specify the `click.version_option`'s version parameter instead of using the default, which tries to figure out the version by looking at `setup.py`. Making this change due to this behavior of click has some conflicts with how versioneer package works, especially when working with BentoML forks.
=> Fix CLI command `bentoml --version`

docs/source/api/adapters.rst, docs/source/api/artifacts.rst
Add missing APIs  (artifacts and InputAdapter)
=> [Docs]Add missing APIs to the documentation site

.github/workflows/ci.yml, README.md
=> Fix Github Actions build badge in readme

GOVERNANCE.md
Adding Sungjun Kim @withsmilo to BentoML core team members, see the announcement here https://github.com/bentoml/BentoML/discussions/1022
=> Adding Sungjun Kim @withsmilo to BentoML core team members

README.md, docs/source/api/index.rst, docs/source/cli.rst, docs/source/concepts.rst, docs/source/deployment/index.rst, docs/source/examples.md, docs/source/faq.rst, docs/source/frameworks.rst, docs/source/guides/index.rst, docs/source/index.rst, docs/source/quickstart.rst
This change adds a single-pixel image (hosted via Scarf https://scarf.sh) to BentoML's README and documentation.
This change is not required but came about from speaking with @parano directly. This change provides basic insights about the web traffic to BentoML's documentation, so the maintainers can better understand their project's usage. Well informed maintainers -> well-maintained software for everyone. 
I ran the sphinx documentation site locally and verified the images are loading. 
=> Add Scarf Documentation Insights to website

README.md
Display Sourcerer badge in ReadMe to celebrate our awesome contributors. 
=> Add sourcerer badge in ReadMe

README.md, docs/source/concepts.rst, docs/source/deployment/aws_ecs.rst, docs/source/deployment/aws_lambda.rst, docs/source/deployment/aws_sagemaker.rst, docs/source/deployment/azure_container_instance.rst, docs/source/deployment/azure_functions.rst, docs/source/deployment/google_cloud_run.rst, docs/source/deployment/heroku.rst, docs/source/deployment/kfserving.rst, docs/source/deployment/knative.rst, docs/source/deployment/kubeflow.rst, docs/source/deployment/kubernetes.rst, docs/source/deployment/sql_server.rst, docs/source/quickstart.rst, guides/quick-start/bentoml-quick-start-guide.ipynb, guides/quick-start/iris_classifier.py, guides/quick-start/requirements.txt
* Use ` --print-location --quiet` to replace the usage of `jq` in quick start guides
* Added `requirements.txt` specifying quickstart guide dependencies
* Minor updates in quickstart notebook
=> Docs & quickstart guide updates

bentoml/adapters/base_input.py, bentoml/adapters/clipper_input.py, bentoml/adapters/file_input.py, bentoml/adapters/json_input.py, bentoml/adapters/legacy_image_input.py, bentoml/adapters/multi_file_input.py, bentoml/service.py, tests/adapters/test_annotated_image_input.py, tests/adapters/test_file_input.py, tests/adapters/test_image_input.py, tests/adapters/test_json_input.py, tests/adapters/test_multi_file_input.py
=> Redesign from_http_request

bentoml/adapters/base_output.py, bentoml/adapters/default_output.py, bentoml/adapters/json_output.py, bentoml/adapters/tensorflow_tensor_input.py, bentoml/adapters/tensorflow_tensor_output.py, bentoml/marshal/utils.py, bentoml/server/api_server.py, bentoml/service.py, bentoml/types.py, tests/adapters/test_tf_tensor_input.py
=> Refactor TfTensorInput/Output

bentoml/adapters/base_input.py, bentoml/adapters/dataframe_input.py, bentoml/adapters/json_input.py, bentoml/marshal/marshal.py, bentoml/marshal/utils.py, bentoml/server/api_server.py, bentoml/service.py, bentoml/types.py
Signed-off-by: Aanand Kainth <aanand@akainth.me>
=> Refine imports and type annotations

docs/source/concepts.rst
* Link to docker hub images
* Remove specific version from deployment (@parano need to make sure `latest` image always point to the latest release)
Current docs can cause an invalid state (installing bento from pip and running old docker image.
=> Fix Yatai service versions in docs

bentoml/adapters/base_output.py, bentoml/adapters/dataframe_input.py, bentoml/adapters/dataframe_output.py, bentoml/adapters/file_input.py, bentoml/adapters/image_input.py, bentoml/adapters/json_output.py, bentoml/adapters/legacy_image_input.py, bentoml/adapters/multi_file_input.py, bentoml/adapters/utils.py, bentoml/service.py, bentoml/types.py, bentoml/utils/__init__.py, bentoml/utils/csv.py, bentoml/utils/dataframe_util.py, tests/adapters/test_dataframe_input.py, tests/adapters/test_json_input.py
=> Refactor DataframeInput

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
Improve the issues template and add contact links.
=> Update github issues config & template

README.md
* Update messaging
* Simplify the examples & frameworks section
* Simplify the quick start example to focus on the key functionality
=> [DOCS ] Update README

README.md, docs/source/index.rst, guides/quick-start/bentoml-quick-start-guide.ipynb
* update docs index page and quickstart notebook to have consistent messaging
* cleaned up the deployment section in notebooks
=> [DOCS] Update quick start guide notebook and docs index page

bentoml/adapters/dataframe_input.py, bentoml/service.py, docs/source/concepts.rst, docs/source/deployment/azure_functions.rst, tests/adapters/test_dataframe_input.py, tests/bento_service_examples/example_bento_service.py, tests/integration/api_server/example_service.py
Align the parameters of pandas.read_json with the parameters of DataframeInput, as well as the docs.
=> Refine parameters and docs of DataframeInput following pandas.read_json

setup.py
The new `moto` release breaks some of the AWS lambda and sagemaker related tests. @yubozhao we may want to look into this a bit more and make sure BentoML works with the new release.
For now, fixing the version to 1.3.14 to unblock BentoML's CI tests.
=> [CI] Fix AWS moto related unit tests

README.md, docs/source/quickstart.rst
=> [DOCS] Add feature highlights section in readme

bentoml/adapters/base_output.py, bentoml/adapters/dataframe_input.py, bentoml/adapters/dataframe_output.py, bentoml/adapters/default_output.py, bentoml/adapters/file_input.py, bentoml/adapters/json_input.py, bentoml/adapters/json_output.py, bentoml/adapters/legacy_image_input.py, bentoml/adapters/multi_file_input.py, bentoml/adapters/tensorflow_tensor_input.py, bentoml/adapters/tensorflow_tensor_output.py, bentoml/service.py, bentoml/types.py, tests/adapters/test_image_input.py, tests/adapters/test_json_input.py, tests/adapters/test_multi_image_input.py, tests/deployment/aws_lambda/test_aws_lambda_deployment_operator.py
=> Combine InferenceContext into InferenceTask; Renaming

.github/workflows/ci.yml, ci/xgboost_integration_tests.sh, tests/bento_service_examples/xgboost_classifier.py, tests/integration/test_xgboost_model_artifact.py
=> [TEST/CI] Add tests covering XgboostModelArtifact

bentoml/yatai/migrations/versions/719dd2aacc9a_add_labels_table.py, bentoml/yatai/repository/metadata_store.py
=> Fix update labels RPC error in save & upload bento API

bentoml/cli/bento_service.py, bentoml/frameworks/coreml.py, bentoml/frameworks/fastai.py, bentoml/frameworks/fastai2.py, bentoml/frameworks/fasttext.py, bentoml/frameworks/h2o.py, bentoml/frameworks/keras.py, bentoml/frameworks/lightgbm.py, bentoml/frameworks/onnx.py, bentoml/frameworks/pytorch.py, bentoml/frameworks/sklearn.py, bentoml/frameworks/spacy.py, bentoml/frameworks/tensorflow.py, bentoml/frameworks/xgboost.py, bentoml/saved_bundle/bentoml-init.sh, bentoml/saved_bundle/templates.py, bentoml/service/__init__.py, bentoml/service/env.py, docker/model-server/Dockerfile, tests/test_service_env.py
* Avoid installing python in docker build, if base image's python minor version matches the required version. This will speed up docker build, this plus https://github.com/bentoml/BentoML/pull/1081, will basically fix the issue in https://github.com/bentoml/BentoML/issues/998
* Removed the existing docker build arg  PIP_INDEX_URL and ARG PIP_TRUSTED_HOST, due to it [may be conflicting with settings in base image #1036 ](https://github.com/bentoml/BentoML/issues/1036), replaced it by setting from python code, or using the new `EXTRA_PIP_INSTALL_ARGS` build arg
* Fixing issue https://github.com/bentoml/BentoML/issues/1036
* Adding support for setting pip install options in BentoService `@env` specification, as suggested here: https://github.com/bentoml/BentoML/issues/1036#issuecomment-682179 …
=> Environment & dependency management improvements

bentoml/yatai/client/bento_repository_api.py, bentoml/yatai/label_store.py, bentoml/yatai/validator/deployment_pb_validator.py, tests/yatai/client/test_bento_repository_api.py
=> [Fix] Move validate_labels to label_store

README.md
=> Add spaCy example link to README

README.md
=> Fixed Typo.

bentoml/adapters/__init__.py, bentoml/adapters/base_input.py, bentoml/adapters/dataframe_input.py, bentoml/adapters/file_input.py, bentoml/adapters/json_input.py, bentoml/adapters/legacy_image_input.py, bentoml/adapters/multi_file_input.py, bentoml/adapters/string_input.py, bentoml/adapters/tensorflow_tensor_input.py, bentoml/adapters/utils.py, bentoml/configuration/default_bentoml.cfg, bentoml/server/api_server.py, bentoml/service/__init__.py, bentoml/types.py, bentoml/utils/dataclasses.py, tests/adapters/test_file_input.py, tests/adapters/test_json_input.py
log inference task and result per task
=> Adapters Refactor: per inference task prediction log

.github/workflows/ci.yml, bentoml/frameworks/onnx.py, bentoml/frameworks/transformers.py, docs/source/frameworks.rst
Follow up PR for additional notes mentioned in https://github.com/bentoml/BentoML/pull/1090
- Added transformers integration test to GitHub workflow
- Not sure why the documentation build gave an issue. Could'nt replicate it since the local build worked fine. I built the docs again however, just to be sure. Am I missing something? 
Also noticed a small miss in the documentation for the onnx model artifact. Fixed that too. 
Follow up PR for additional notes mentioned in https://github.com/bentoml/BentoML/pull/1090
=> Transformers CI update & docs rebuild

bentoml/yatai/yatai_service_impl.py
=> If bento name is not found,cli crashes as it tries to access its version

bentoml/configuration/default_bentoml.cfg, bentoml/service/env.py
Follow up to #1096 to clean up the default docker base image config related issue and add additional debug/warning logs.
=> Per-python minor version docker base image cleanups

.github/ISSUE_TEMPLATE/bug_report.md, bentoml/configuration/default_bentoml.cfg, bentoml/server/gunicorn_server.py, bentoml/server/marshal_server.py, bentoml/utils/log.py
=> Add notes on turning on debug logging

README.md, docs/source/examples.md
Added the statsmodel example in the examples.md file
=> Add Statsmodels example notebook links

tests/deployment/aws_lambda/test_aws_lambda_deployment_operator.py
In lambda deployment test s3 mock is not required.
Simplifies test
Ran all unit tests.
Removed s3 mock function and corresponding decorator.
=> s3 mock not required to test lambda_app

tests/deployment/aws_lambda/test_aws_lambda_deployment_operator.py
Pytest does not discover test due to wrong return value of decorator.
While testing found 1 test was getting missed.
Ran all tests.
=> pytest discovery failed due wrong return value of mock decorator

tests/deployment/aws_lambda/test_aws_lambda_deployment_operator.py
fixed pytest discovery bug due to wrong return value of decorator
added test to check lambda deployment over allowed max limit
=> added test to check lambda deployment over allowed max limit

bentoml/service/inference_api.py, tests/bento_service_examples/bento_service_with_modified_sys_path.py
=> [FIX] prediction logs and errors during rebasing

bentoml/configuration/default_bentoml.cfg, bentoml/marshal/marshal.py, bentoml/server/gunicorn_server.py, bentoml/server/marshal_server.py
make max_request_size configurable for HTTP server. The default value is 20MB.
=> [FIX 1087] configurable max request size

tests/integration/api_server/conftest.py, tests/integration/api_server/example_service.py
=> [CI] add integration tests for option batch

tests/conftest.py, tests/integration/api_server/example_service.py
=> [FIX] typo in integration test

bentoml/types.py
=> [DOC] add docs for types

dev/release_pypi.sh
Allow publishing preview releases to PyPI
=> Update release script

README.md, docs/source/frameworks.rst
=> Adding to docs

bentoml/service/__init__.py, docs/source/deployment/clipper.rst, e2e_tests/iris_classifier_example.py, tests/test_service_env.py
=> [DOC] fix artifact import path in examples

bentoml/adapters/dataframe_input.py, bentoml/utils/dataframe_util.py, tests/adapters/test_dataframe_input.py
=> [Refactor] refactor DataframeInput with StringInput

bentoml/adapters/dataframe_input.py, bentoml/adapters/json_input.py
Refine docstrings following https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard
=> [DOC] refine docstrings of DataframeInput and JsonInput

bentoml/yatai/deployment/sagemaker/operator.py
WIth the recent release of greenlet 0.4.17, Sagemaker deployment runs into an infinite "Booting worker with pid" issue.
```
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
return f(*args, **kwds)
```
The issue was caused by compatibility issue between old versions of gevent with the most recent version greenlet.  https://github.com/python-greenlet/greenlet/issues/178
Update the gevent requirement in Sagemaker dockerfile solves this.
=> [Fix]Update sagemaker dependency version

bentoml/adapters/annotated_image_input.py, bentoml/adapters/file_input.py, bentoml/adapters/image_input.py, bentoml/adapters/multi_file_input.py, bentoml/adapters/multi_image_input.py
=> [DOC] refine docstrings for file input adapters

README.md
Fix a spelling error in the readme.
Noticed the misspelling, let's fix it.
n/a
n/a
=> fix readme spelling error

bentoml/frameworks/fastai2.py
fastai2 is now in the fastai repository so I think this requirement needs updating
=> Change pip requirement fastai2>2.0.0 to fastai>=2.0.0

docs/source/concepts.rst, docs/source/quickstart.rst
=> [Docs] Add label section for core concept page

docs/source/concepts.rst
=> [Doc] include customize web ui section for core concept

docs/source/api/index.rst, docs/source/api/types.rst, docs/source/concepts.rst
=> [Doc] Add API batch to core concept

README.md, docs/source/index.rst
=> [Doc]Update intro on the home page

bentoml/adapters/annotated_image_input.py, bentoml/adapters/image_input.py, bentoml/adapters/multi_image_input.py, docs/source/api/adapters.rst
=> [Doc]update image related input adapters' doc string

bentoml/adapters/tensorflow_tensor_input.py, docs/source/bentoml_wordlist.txt, docs/source/concepts.rst
=> [Doc]Add notes on Tensor Input type

setup.py
Breadth-First-Search. (For example, if it finds `multidict` at the top level, it just install the latest version of it(5.0), even though `multidict<5.0` is required by the dependency `aiohttp`).
It does nothing about the Breadth-First-Search behavior but doesn't tolerant mismatched sub-dependencies anymore. It now exits with an error code.
=> [FIX] fix dependencies for new resolver of pip

bentoml/adapters/default_output.py, bentoml/service/inference_api.py, tests/integration/api_server/example_service.py, tests/integration/api_server/test_adapter.py
=> [FIX] fix tasks/task API

tests/integration/api_server/example_service.py, tests/integration/api_server/test_adapter.py
=> [CI] more tests about tasks API

docs/source/frameworks.rst
=> [Docs]Remove duplicated Statsmodels section in the framework page

guides/quick-start/bentoml-quick-start-guide.ipynb
I found a tiny typo in bentoml-quick-start-guide.ipynb.
=> [Doc] Fix a typo in bentoml-quick-start-guide.ipynb

bentoml/saved_bundle/bentoml-init.sh, bentoml/saved_bundle/templates.py, bentoml/yatai/deployment/azure_functions/Dockerfile, bentoml/yatai/deployment/sagemaker/operator.py
Slack thread: https://bentoml.slack.com/archives/CKRANBHPH/p1603817386302100
**Issue:**
Both Sagemaker dockerfile and Azure functions dockerfile are not updated when install `bundled_pip_dependencies` step moved out of the `bentoml-init.sh` script.
When a user deploy to either platforms with packages in the `bundled_pip_dependencies` directory, it will fails.
Solution:
Right now, including the install steps in each dockerfiles.  Need to investigate how to better use the base docker image and also fit with each platforms' requirements.
=> [Fix] Make sure install bundled pip dependencies for Azure functions and Sagemaker deployments

bentoml/server/api_server.py
#1183 #1190 
Make swagger static content path to relative. It will load swagger UI and content correctly, if the service is behind an reverse proxy like nginx.
=> [Enhance]Support relative path for swagger static content

ci/spacy_integration_tests.sh, tests/bento_service_examples/spacy_classifier.py, tests/integration/test_spacy_model_artifact.py
Add an integration test for spaCy model artifact code.
Currently, spaCy artifact code is not tested.
This PR possibly solves #1198 
=> Add integration test for spaCy

bentoml/cli/yatai_service.py, bentoml/yatai/web/client/package.json, bentoml/yatai/web/client/src/app.tsx, bentoml/yatai/web/client/src/components/Breadcrumbs.tsx, bentoml/yatai/web/client/src/components/NavigationBar.tsx, bentoml/yatai/web/client/src/utils/HttpRequestContainer.tsx, bentoml/yatai/web/package.json, bentoml/yatai/web/src/index.ts, bentoml/yatai/web/src/server.ts, bentoml/yatai/yatai_service.py
Add support for URL location prefix in yatai-service gRPC/Web server (#1063)
* User can run YataiService behind a reverse proxy server and add a location prefix to the URL being proxied using command line.
* Fixes the Issue #1063 with relevant discussion on #1057
Local deployment
=> Add location prefix to the URL being proxied (Fixes #1063)

bentoml/frameworks/onnx.py
#1205 
Include `onnxruntime-gpu` as part of the supported onnx runtime backend.
=> [Enhancement] Add onnxruntime-gpu as supported onnx runtime backend.

setup.py
https://github.com/bentoml/BentoML/issues/1237
Upcoming SqlAlchemy 1.4 release will introduce compatibility issue `ImportError: cannot import name '_ColumnEntity'`.
This fix limits the sqlalchemy requirement between 1.3 and 1.4, until proper support for 1.4 version
=> [Enhancement]Pin SqlAlchemy to version between 1.3 and 1.4

bentoml/cli/bento_management.py, bentoml/yatai/client/bento_repository_api.py
Update retrieve command to use the new bento management syntax.
=> [CLI]Update retrieve command

bentoml/cli/bento_service.py, bentoml/server/__init__.py, bentoml/server/api_server.py, bentoml/server/gunicorn_server.py, tests/server/test_model_api_server.py, tests/utils/test_usage_stats.py
#1167 Add an option to disable swagger UI.
tested with the following commands and by visiting endpoints `localhost:5000/` and `localhost:5000/docs`
```
bentoml serve-gunicorn IrisClassifier:latest --disable-swagger
bentoml serve-gunicorn IrisClassifier:latest --enable-swagger
bentoml serve IrisClassifier:latest --disable-swagger
bentoml serve IrisClassifier:latest --enable-swagger
```
=> add option to disable swagger ui

bentoml/adapters/tensorflow_tensor_output.py
=> [FIX] TfTensorOutput raise TypeError when mb enabled

bentoml/marshal/marshal.py
=> Avoid potential TypeError in batching server

docs/source/quickstart.rst
Add missing newline in `docs/source/quickstart.rst`.
Fixes #1253
=> [Fix] Incorrect document formatting in quickstart.rst

bentoml/yatai/web/client/src/components/BentoServiceDetail/ArtifactsTable.tsx, bentoml/yatai/web/client/src/components/BentoServiceTable.tsx, bentoml/yatai/web/client/src/components/Label.tsx, bentoml/yatai/web/client/src/components/LabelDetailSection.tsx, bentoml/yatai/web/client/src/pages/BentoServiceDetail.tsx, bentoml/yatai/web/src/server.ts
Artifact metadata in BentoService detail page
Labels in BentoService list page:
Labels in BentoService detail page:
=> [Enhancement]Add label and artifact metadata display to yatai web ui

bentoml/yatai/web/client/package.json, bentoml/yatai/web/client/yarn.lock, bentoml/yatai/web/package.json, bentoml/yatai/web/yarn.lock
Update dependencies to fix vulnerable issues generated by github dep bot
=> [Enhancement]Update Yatai web node server dependencies

README.md, docs/source/frameworks.rst
Follow up on comments from #1264 , this PR updates documentation for the newly added gluon artifacts.
=> [DOC] doc update for gluon artifact support

tests/integration/api_server/conftest.py, tests/integration/test_tensorflow_v2_2_savedmodel_artifact.py
For simpler & faster integration test
Because of
```
https://github.com/pytest-dev/pytest/issues/3393
```
The fixture `tf2_image` has been executed too many times
=> Refactor CI for TensorFlow2

tests/integration/test_tensorflow_v2_2_savedmodel_artifact.py
=> [CI] remove unused params

setup.py, tests/integration/yatai_server/test_postgres_local_fs.py
* Don't override protobuf version in test environment
* Use different ports for yatai service integration tests.
=> [Tests]Don't override protobuf version in testing

bentoml/cli/bento_service.py, bentoml/marshal/marshal.py, bentoml/server/__init__.py, bentoml/server/marshal_server.py, tests/integration/api_server/conftest.py, tests/utils/test_usage_stats.py
In this PR, I add an option to modify micro-batching parameters. ~~I achieve this by introducing a class `SavedBundleLoader` which in addition to loading bentoml service files can modify some of the service metadata while keeping it consistent with its configuration (which is used by other classes in this project). With this abstraction, it should be easy to extend the modification of other service parameters.~~
The logging message should display what are the current micro-batching parameters:
```
➜  bentoml serve-gunicorn --enable-microbatch --mb-max-latency 3333 --mb-max-batch-size 3333 IrisClassifier:20201202154246_C8DC0A                                                                                                                                   
[2020-12-02 16:09:46,684] INFO - …
```
=> [Enhancement] Allow setting micro batching parameters

tests/integration/api_server/test_microbatch.py
=> [CI] loose benchmark test for microbatch dispatcher

tests/bento_service_examples/tensorflow_classifier.py, tests/integration/test_tensorflow_v2_2_savedmodel_artifact.py
=> [CI] add integration tests for ragged_tensor

bentoml/service/__init__.py
Fix #1294 
Before, users have to define `api_doc` on the `@api` decorator to have the message show up in the Swagger UI. Now, the function's docstring will substitute for the `api_doc`, if the docstring is defined and `api_doc` is not.
How Has This Been Tested?
=> [Enhance]Use API function docstring, if api_doc is missing

bentoml/yatai/client/__init__.py, bentoml/yatai/client/bento_repository_api.py, docs/source/api/yatai_client.rst, docs/source/frameworks.rst
Update yatai client repository API documentation
=> [Doc]Update documentation for yatai client repository API

Makefile, bentoml/yatai/web/client/src/components/BentoServiceDetail/EnvTable.tsx
From:
Display dependencies inline without space
To:
Display dependencies in a new line
Update Makefile commands
=> [Enhance]Improve bento service pip dependencies display in yatai web ui

bentoml/saved_bundle/bundler.py, tests/integration/utils.py
To avoid the docker cache issue.
The checksums of `setuptool` generated tarball files changed every time (even with the same version of pip local dependencies), which failed the cache of the `COPY` step in docker build.
=> [Build] normalize checksums of bundled_pip_dependencies

bentoml/saved_bundle/bentoml-init.sh
=> [Fix]Only install bundled_pip_dependencies when files exist during docker build

.github/workflows/codeql-analysis.yml
Add https://github.com/github/codeql as part of the workflow CI check.
View the report at https://lgtm.com/projects/g/bentoml/BentoML/
=> [Enhancement] Add Github CodeQL check to the CI checks

bentoml/marshal/marshal.py
=> [FIX] Disable auto_decompress for batching server

bentoml/frameworks/pytorch.py, tests/integration/test_pytorch_model_artifact.py
- Add support for Pytorch JIT traced/scripted modules.
- Standard `cloudpickle` does not support serialization of TorchScript modules, instead `torch.jit.save()` and `torch.jit.load()` are used
Currently, PytorchModelArtifact does not support scripted/traced models since `cloudpickle` cannot serialize ScriptModules
Fixes issue #873 
Added integration tests for saving/loading scripted and traced models.
=> [Enhancement/Test] Add support for Pytorch JIT traced/scripted models

bentoml/service/__init__.py
Now we can test our bento service right after created, without leaving the development context.
Here is a example: https://github.com/bentoml/gallery/blob/48552c6f569ff1d8a18b1445c641cbaff4d6f8e8/tensorflow/imdb/imdb_text_classification.ipynb 
(from block 15)
=> [Enhancement] add bentom_service.start_dev_server

tests/integration/utils.py
=> [CI] remove test server container on exit

bentoml/service/__init__.py
https://flask.palletsprojects.com/en/master/server/#in-code
> debug=True can be passed to enable the debugger and reloader, but the FLASK_ENV=development environment variable is still required to fully enable development mode.
=> [Enhancement] start dev server in development env

bentoml/service/__init__.py
=> [Chore] skip log when cleaning dev server

docs/source/api/index.rst, docs/source/cli.rst, docs/source/concepts.rst, docs/source/deployment/index.rst, docs/source/examples.md, docs/source/faq.rst, docs/source/frameworks.rst, docs/source/guides/index.rst, docs/source/index.rst, docs/source/quickstart.rst
=> [Doc]Clean up documentation rst

bentoml/yatai/yatai_service.py
This PR will fix https://github.com/bentoml/BentoML/issues/1350.
I tested this PR on my local.
=> Fix YataiService's trailing slash bug

.github/workflows/ci.yml, bentoml/yatai/client/bento_repository_api.py, ci/s3_bucket_integration_tests.sh, tests/integration/test_s3.py
Fix #1336 and add integration test
=> [Fix] Bentoml retrieve from s3 compatible storage

.github/workflows/ci.yml, bentoml/artifact/__init__.py, bentoml/frameworks/pytorch.py, ci/pytorch_lightning_integration_tests.sh, docs/source/frameworks.rst, tests/bento_service_examples/pytorch_lightning_classifier.py, tests/integration/test_pytorch_lightning_model_artifact.py
Add PyTorch lightning model support for BentoML. Pytorch Lightning is the lightweight PyTorch wrapper for developing models.
=> [New feature]Add Pytorch lightning model support

bentoml/marshal/dispatcher.py, bentoml/marshal/marshal.py, bentoml/server/__init__.py
=> [Fix] fix bentoml serve cmd on macOS with py38

ci/keras_with_tf1_integration_tests.sh, ci/tensorflow_v1_14_integration_tests.sh
=> [CI] Fix occasional errors during install tf1.14

bentoml/cli/bento_service.py, docs/source/concepts.rst, docs/source/quickstart.rst, guides/quick-start/bentoml-quick-start-guide.ipynb
=> [Doc] change CLI arguments from "--input" to "--input-file"

.github/workflows/ci.yml, bentoml/saved_bundle/bentoml-init.sh, ci/keras_integration_tests.sh, ci/keras_with_tf1_integration_tests.sh, ci/tensorflow_v2.2_integration_tests.sh
=> [CI] Fix occasional errors during install tf2.2

bentoml/adapters/base_input.py, bentoml/adapters/clipper_input.py, bentoml/adapters/dataframe_input.py, bentoml/adapters/file_input.py, bentoml/adapters/multi_file_input.py, bentoml/adapters/string_input.py, bentoml/types.py
=> Add from_inference_job to input adapters

bentoml/utils/__init__.py, ci/integration_tests.sh, tests/integration/api_server/conftest.py, tests/integration/utils.py, tests/utils/test.py
=> [CI, refactor] support integration test without docker

bentoml/yatai/deployment/store.py
=> Try to fix bentoml lambda list failed with PostgreSQL 11 #1366

README.md
=> [Enhancement]Fix broken Detectron link on ReadMe

bentoml/yatai/deployment/aws_lambda/operator.py, bentoml/yatai/deployment/sagemaker/operator.py, tests/deployment/aws_lambda/test_aws_lambda_deployment_operator.py, tests/test_labels.py
Ensure docker and other requirements are available during Lambda/Sagemaker deployment operator initialization step.
=> [Refactor]check docker availability during deployment operators initialization step

bentoml/yatai/deployment/aws_lambda/operator.py
Lambda update returns this error when the deployment name contains underscore.
`An error occurred (ValidationError) when calling the DescribeStacks operation: 1 validation error detected: Value \'dev-receipt_gross_amount\' at \'stackName\' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*
`
=> fix lambda describe issue

bentoml/adapters/json_output.py, bentoml/saved_bundle/bentoml-init.sh, bentoml/server/api_server.py, bentoml/service/env.py, bentoml/service/inference_api.py, ci/install_python36_osx.sh, tests/test_service_env.py, tests/utils/test_usage_stats.py
TODO:
closes https://github.com/bentoml/BentoML/issues/1377
=> [Fix] request id in HTTP response header

Makefile, docs/source/guides/batch_serving.rst, docs/source/quickstart.rst
* fixed makefile not installing some sphinx deps correctly
* added better docs for offline batch serving
closes #1378 
Locally
=> [docs] Add Documentation for Offline Batch Serving

bentoml/yatai/client/bento_repository_api.py, e2e_tests/yatai_server/test_sqlite_gcs.py, e2e_tests/yatai_server/test_sqlite_s3.py
=> [Enhance]fix bug for uploading to GCS as bento storage and update e2e yatai service tests

bentoml/yatai/db.py
In this configuration, no one is handling connection losses between yatai server and PostgreSQL.
After five minutes of connection(in most cases), the DB will disconnect your session and return a connection dropped error: `ERROR - RPC ERROR ApplyDeployment: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected`
The easiest way to do this is:
https://docs.sqlalchemy.org/en/14/core/pooling.html#disconnect-handling-pessimistic
=> dealing with postgress disconnects

bentoml/saved_bundle/bentoml-init.sh
After all, to prevent conda from installing unwanted version or build of Python(or other packages), we need to include the full spec `<channel>::python=<version>[build=<build>]` in the env.yml.
Just go back to the existing behavior before further modification.
ref: #1375 
=> [Fix] Revert changes about skipping Python installation in 1375

bentoml/yatai/web/src/server.ts
I have added the healthz endpoint to the YataiService Node app. This endpoint is a convention in building microservices, sometimes a deployed service can get into a bad state and become incapable of handling requests.  
This solves a part of the #1060 issue:
https://github.com/bentoml/BentoML/issues/1060
The endpoint is pretty simple, it returns a 200 status if everything is going well. I have tested this locally and it returned 200 as status.
=> Added the healthz issue 1060 feature

bentoml/yatai/web/src/server.ts
Return the healthz status for Yatai web server instead of the Yatai gRPC server
=> [Enhance]Update yatai web healthz endpoint

docs/source/concepts.rst
Fixing bug in the documentation
- [X ] Documentation
=> Update documentation concepts.rst

.github/workflows/ci.yml, ci/fastai_integration_tests.sh, tests/bento_service_examples/fastai2_classifier.py, tests/integration/fastai_utils.py, tests/integration/test_fastai2_model_artifact.py
Adds integration test for fastai2 lib
based on #1194 
I've tested I locally, only issue is that there is a model.pkl file being generated by I'm still confused as to where its coming from.
=> Fastai test 

.github/workflows/ci.yml, ci/back_compatibility_itest.sh
Test bento bundles generated by the release version with the current codebase.
Todos:
=> Add back compatibility integration test

.github/workflows/ci.yml, ci/integration_tests.sh
=> [CI] Enable integration tests for MacOS

bentoml/server/__init__.py, bentoml/utils/__init__.py, bentoml/yatai/client/bento_repository_api.py, bentoml/yatai/deployment/aws_lambda/lambda_app.py, bentoml/yatai/deployment/azure_functions/app_init.py, docs/source/api/yatai_client.rst, tests/deployment/aws_lambda/test_aws_lambda_deployment_operator.py, tests/yatai/client/test_bento_repository_api.py
Add `load` API for yatai client repository
Example:
```
yc = get_yatai_client('remote.yatai.com:50051')
svc = yc.repository.load('Service_Name:version')
```
=> [Feature]Add load api for yatai client repository 

bentoml/yatai/deployment/utils.py, tests/deployment/test_deployment_utils.py
=> [Refactor] use docker sdk to check docker server's availability

.github/workflows/ci.yml, bentoml/frameworks/pytorch.py, ci/pytorch_lightning_integration_tests.sh, tests/integration/test_pytorch_lightning_model_artifact.py
=> [Fix]update PytorchLightning requirement and add docker integration test for it

bentoml/clipper/__init__.py, bentoml/yatai/deployment/aws_ec2/operator.py, bentoml/yatai/deployment/aws_lambda/operator.py, bentoml/yatai/deployment/azure_functions/operator.py, bentoml/yatai/deployment/docker_utils.py, bentoml/yatai/deployment/sagemaker/operator.py, bentoml/yatai/deployment/utils.py, bentoml/yatai/yatai_service_impl.py, e2e_tests/conftest.py, tests/deployment/test_deployment_docker_utils.py, tests/yatai/client/test_bento_repository_api.py, tests/yatai/local_yatai_service.py
=> [refactor] docker related utils 

bentoml/yatai/deployment/aws_ec2/operator.py, bentoml/yatai/deployment/aws_utils.py, bentoml/yatai/deployment/docker_utils.py, bentoml/yatai/deployment/sagemaker/operator.py, tests/deployment/aws_ec2/test_ec2_deployment_operator.py, tests/yatai/deployment/test_aws_utils.py
=> [refactor] ecr utils for AWS deployments

bentoml/yatai/deployment/aws_utils.py, bentoml/yatai/deployment/sagemaker/operator.py, tests/deployment/sagemaker/test_sagemaker.py, tests/yatai/deployment/test_aws_utils.py
=> [refactor]AWS error message to BentoML exception

docs/source/conf.py, docs/source/faq.rst
Update the documentation to show how to use bentonML with loaded MLflow model  
[Open issue](https://github.com/bentoml/BentoML/issues/622)
I built the doc locally and served them locally sucessfully. I also ran the spellcheck and I do not add any spellcheck in the touched files. 
=> Update faq about mlflow by adding an example from the gallery

bentoml/cli/bento_service.py, bentoml/configuration/containers.py, bentoml/configuration/default_bentoml.cfg, bentoml/configuration/default_bentoml.yml, bentoml/marshal/marshal.py, bentoml/saved_bundle/config.py, bentoml/service/__init__.py, tests/configuration/test_containers.py
Marshal server configuration max_batch_size and max_latency should have the following override order. The order got reversed after https://github.com/bentoml/BentoML/pull/1422.
1. CLI parameter or BentoML configuration
2. API metadata defined in the service bundle
3. Default defined in code
A previous PR https://github.com/bentoml/BentoML/pull/1422 changed the order to have the max_batch_size and max_latency defined in the API metadata to take precedence. This PR is intended to restore the original override priority.
./dev/format.sh
./dev/lint.sh
./ci/unit_test.sh
=> Update Marshal Server Configuration Override Priority

e2e_tests/conftest.py, tests/integration/test_xgboost_model_artifact.py, tests/yatai/client/test_bento_repository_api.py, tests/yatai/local_yatai_service.py
Xgboost integration tests are not using fine-tuned util functions in `tests/integration/utils`.
=> [CI] Fix xgboost integration tests

bentoml/yatai/deployment/aws_ec2/operator.py, bentoml/yatai/deployment/aws_ec2/templates.py, bentoml/yatai/deployment/aws_utils.py, tests/yatai/deployment/aws_ec2/test_ec2_deployment_operator.py, tests/yatai/deployment/test_aws_utils.py
=> [refactor] EC2 deployment

bentoml/yatai/web/client/src/components/BentoServiceDetail/ArtifactsTable.tsx
=> Fix YataiService UI bug, when no artifacts are declared for BentoService.

bentoml/configuration/default_bentoml.cfg, bentoml/utils/log.py
As mentioned in https://github.com/bentoml/BentoML/issues/1464, formatting strings for prediction and feedback logs were not working as expected. The temporarily fix attempted in #1478 introduced unwanted complexity. Given the non-urgent nature, we will address this issue at a later time together with other logging related features in the roadmap.
We will remove the format strings for prediction and feedback logs from configuration to avoid confusion.
=> Remove format configuration for prediction and feedback logs

docs/source/guides/logging.rst
Update config documentation to reflect the log format changes introduced in https://github.com/bentoml/BentoML/pull/1482.
=> Update config documentation to reflect the format changes

bentoml/cli/bento_management.py, tests/integration/yatai_server/test_delete.py
=> [Bug fix] fix issue with no delete targets arguments provide for cli delete command

bentoml/adapters/string_input.py, bentoml/cli/bento_service.py, bentoml/service/__init__.py
=> [Docs]fix spelling and the doc-string format for documentation

docs/source/api/yatai_client.rst, docs/source/guides/custom_input_adapter.rst
=> [Docs]Add tutorial for Customize Input Adapter

.github/workflows/ci.yml, bentoml/service/__init__.py, bentoml/service/env.py, docs/source/concepts.rst
Update documentation to recommend using requirements.txt, specified in full and with pinned versions, in production as discussed in #1481. Also, updating Github Actions to trigger CI everyday at 2am UTC.
Specifying both direct and transitive dependencies explicitly with pinned versions is recommended for improving reliability in the production environment. Triggering daily CI to help detect dependency conflict introduced by dependency upgrade.
=> Handling dependency conflict by updating documentation and adding daily CI

.github/workflows/ci.yml
=> Fix github action configuration

bentoml/yatai/web/client/src/components/BentoServiceDetail/ApisTable.tsx
=> [Enhancement]Add route, batch, output type display for Yatai bento service UI

docs/source/guides/custom_artifact.rst, docs/source/guides/custom_input_adapter.rst
=> [documentation]add custom artifact guide

bentoml/yatai/web/client/src/components/BentoServiceDetail/EnvTable.tsx, bentoml/yatai/web/client/src/components/Breadcrumbs.tsx, bentoml/yatai/web/client/src/pages/HomePage.tsx, bentoml/yatai/web/nodemon.json, bentoml/yatai/yatai_service.py
=> [build] improve yatai node and web project dev workflow

bentoml/yatai/web/client/src/app.tsx
=> [Fix] correct Yatai web's nabber link display undefined, if no prefix url provided.

bentoml/yatai/web/client/src/components/BentoServiceTable.tsx
=> Fix Yatai UI error when BentoBundle file upload fail

bentoml/frameworks/tensorflow.py, bentoml/marshal/marshal.py, bentoml/service/__init__.py, bentoml/types.py
=> [FIX] issues when destructor called before initialization

e2e_tests/aws_sagemaker/test_sagemaker_deployment.py, e2e_tests/aws_sagemaker/utils.py
=> [enhancement]use boto client instead of cli

bentoml/tracing/__init__.py
=> Fix trace function when top-level config wiring was missing

README.md, docs/source/concepts.rst, docs/source/index.rst, docs/watch.sh
=> [Docs] document changes on conda & pypi dependencies

.github/workflows/ci.yml, README.md, bentoml/artifact/__init__.py, bentoml/frameworks/paddle.py, docs/source/frameworks.rst, tests/integration/projects/paddle/model/model.py, tests/integration/projects/paddle/service.py, tests/integration/projects/paddle/tests/test_service.py
Added a PaddleModelArtifact to support serving a PaddlePaddle inference model
Implementation for #1443 
Added integration tests and verified with manual testing through python module and colab notebook
=> Paddle model artifact

bentoml/frameworks/gluon.py, bentoml/frameworks/onnx.py, docs/source/bentoml_wordlist.txt, docs/source/guides/logging.rst
=> [DOCS] misc documentation updates

.github/workflows/slash-commands-help.yml, .github/workflows/slash-commands.yml
BentoML developers can use `/help` in the GitHub issue or PR comment section to see the commands available and run scripts base on those commands.
=> [workflow enhancement] Add slash commands for GitHub

.github/workflows/slash-commands-help.yml, .github/workflows/slash-commands.yml
=> [development enhancement]Add help command dispatcher

.github/workflows/slash-commands.yml
=> [development enhancement] fix typo on help command workflow

.github/workflows/codeql-analysis.yml
=> [GitHub Action] move codeQL action to daily

.github/workflows/slash-commands.yml
=> [GitHub Action]remove extra space in help command

.github/workflows/slash-commands.yml
=> [GitHub Action] only run slash actions when comment created.

.github/workflows/e2e.yml, .github/workflows/slash-commands-actions.yml, .github/workflows/slash-commands-dispatch.yml
=> [GitHub Action] Add e2e yatai testing action

docs/source/concepts.rst
Simple Grammatical Error
N/A
N/A
=> fix: grammatical error

.github/workflows/e2e.yml, .github/workflows/slash-commands-actions.yml
=> [GitHub Actions] update the e2e action script

bentoml/saved_bundle/loader.py, bentoml/service/env.py
This PR fixed an issue when the user-specified path to requirement txt is not found in the API server docker image. 
=> Fix bundle load with requirements_txt_file in @env parameter

README.md, bentoml/cli/click_utils.py, bentoml/cli/config.py, bentoml/configuration/default_bentoml.cfg, bentoml/utils/usage_stats.py, tests/utils/test_usage_stats.py
Add --do-not-track CLI option and environment variable. Removed `usage_tracking` config key from `default_bentoml.cfg`.
=> Add --do-not-track CLI option and environment variable

docker/model-server/Dockerfile
=> Upgrade conda to 4.9.2 in default docker base image

docs/source/deployment/kubernetes.rst
=> [documentation] Update prometheus setting for k8s deployment guide

bentoml/adapters/json_output.py
- [JsonOutput] ensure_ascii=False to not escape UTF-8 characters (#1577)
=> fix: ensure_ascii=False (#1577)

bentoml/adapters/json_output.py, tests/integration/projects/general/service.py, tests/integration/projects/general/tests/test_adapter.py
=> Add option ensure_ascii to JsonOutput

docs/source/concepts.rst
=> typo: Lean -> Learn

docs/source/guides/helm.rst
Probably type in article title
- trivial
- n/a
- [x ] Documentation
=> probable typo?

docs/source/cli.rst
=> [fix] update click module path to display CLI reference on the doc

bentoml/configuration/__init__.py
=> [fix]Add yatai service impl to dependency injection

bentoml/yatai/web/src/server.ts
Match behavior to the CLI. Use all namespace tag, if no namespace is provided. 
=> [enhance]Update yatai web list deployment

bentoml/yatai/db/__init__.py, bentoml/yatai/migrations/versions/af18f0b83286_create_lock_table.py, guides/quick-start/main.py
Fix incorrect logic on create tables, after updated to the latest commit
=> [fix] Make sure create tables, if any missing

README.md
=> [readme] Include paddlepaddle example to readme

bentoml/frameworks/onnxmlir.py
Fix the wrong code indentation in class ResNetPredict.
The indentation is wrong.
Tested locally
=> Fix code example indentation

bentoml/marshal/marshal.py, bentoml/saved_bundle/pip_pkg.py, bentoml/server/__init__.py, bentoml/server/gunicorn_server.py, bentoml/server/marshal_server.py, bentoml/service/env.py, bentoml/service/inference_api.py, bentoml/tracing/zipkin.py, bentoml/utils/__init__.py, bentoml/utils/benchmark.py, bentoml/utils/usage_stats.py, bentoml/yatai/client/bento_repository_api.py, bentoml/yatai/client/deployment_api.py, bentoml/yatai/db/__init__.py, bentoml/yatai/db/stores/deployment.py, bentoml/yatai/repository/s3_repository.py, bentoml/yatai/utils.py
Import time measured using Python -X [importtime](https://docs.python.org/3.7/using/cmdline.html#id5) cmdline utility.
```python -X importtime bentoml/import_bentoml.py 2> ~/data/bentoml/import_after0.log```
This PR re-arranged import statements of 3rd party libraries from the top of the python module to inside function definition and removed about 50% of `import bentoml` latency from 0.98s to 0.71s measured by my dev laptop. Savings came from delayed loading from `pkg.resource`, `werkzeug.utils`, `boto3`, `sqlachemy`, and `aiohttp` packages.
Before this PR:
After this PR:
Improve developer experience using bentoml Python API and CLI speed.
([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-c …
=> Optimize BentoML import delay

setup.py
=> [enhancement] pin down sphinx version for documentation

docs/source/guides/custom_artifact.rst
This PR will help in updating the document for the custom artifact, and solves the bug #1607 
This change will improve the documentation
=> Updated the custom artifact document

docs/source/guides/tracing.rst
=> Doc: fix docker run command

bentoml/adapters/json_input.py, docs/source/concepts.rst
change lib name typings to typing
The import in the sample code contains a typo
`from typings import List`
which has been changed to:
`from typing import List`
=> fix typo in the core concept doc

docs/source/quickstart.rst
=> Fix minor typo

bentoml/cli/click_utils.py, bentoml/clipper/__init__.py, bentoml/saved_bundle/loader.py, bentoml/utils/usage_stats.py, bentoml/yatai/client/bento_repository_api.py, bentoml/yatai/grpc_interceptor/prom_server_interceptor.py, bentoml/yatai/web/src/server.ts, bentoml/yatai/yatai_service.py
* Remove "load" event tracking
* Remove repository API client side tracking
* Add yatai grpc server side tracking
=> Usage tracking updates

docs/source/deployment/google_cloud_ai_platform.rst, docs/source/examples.md, docs/source/frameworks.rst
* add new examples project links including example notebook for paddlepaddle
=> [docs] Update example projects page

ci/evalml_integration_tests.sh, tests/bento_service_examples/evalml_classifier.py
=> [integration test]Update EvalML CI and dependency version

tests/integration/projects/general/tests/test_microbatch.py, tests/integration/projects/general_non_batch/tests/test_microbatch.py
=> [CI] make batch size testing more robust

bentoml/cli/bento_service.py, bentoml/configuration/containers.py, bentoml/configuration/default_bentoml.yml, bentoml/marshal/marshal.py, bentoml/server/__init__.py, bentoml/server/marshal_server.py, bentoml/service/__init__.py, docs/source/concepts.rst, tests/cli/test_cli.py, tests/integration/conftest.py, tests/integration/projects/conftest.py, tests/integration/projects/general/tests/test_adapter.py, tests/integration/projects/general/tests/test_microbatch.py, tests/integration/projects/general_non_batch/tests/test_adapter.py, tests/integration/test_keras_artifact.py, tests/integration/test_pytorch_lightning_model_artifact.py, tests/integration/test_tensorflow_v1_14_savedmodel_artifact.py, tests/integration/test_tensorflow_v2_2_savedmodel_artifact.py, tests/integration/test_xgboost_model_artifact.py, tests/integration/utils.py, tests/utils/test_usage_stats.py
Enable micro batch by default.
Implement first part of #1647
Implementing the first part of #1647
=> [Enhancement] Deprecate --enable-microbatch flag for bentoml serve/serve-gunicorn

ci/test_project.sh.cmd
=> [DOC] minor fix for scripts of integration test

docs/source/quickstart.rst, guides/quick-start/bentoml-quick-start-guide.ipynb
Add a minimal project structure for newcomers and others to follow as a convention for BentoML projects.
- allow new users to see other usecases other than jupyter notebook.
- avoid error when new users try to put everything into one file, that by running scripts model loading and saving code are invoked again, when loading the BentoService class
N/A
=> [docs] added project structures

docs/source/guides/custom_artifact.rst
=> [docs] custom_artifacts doc quick fix

docs/source/api/adapters.rst, docs/source/cli.rst, docs/source/concepts.rst, docs/source/deployment/google_cloud_ai_platform.rst, docs/source/guides/configuration.rst, docs/source/guides/gpu_serving.rst, docs/source/guides/logging.rst, docs/source/guides/tracing.rst, docs/source/quickstart.rst
=> [doc]Update yatai server documentation and add words to spelling check ignores

bentoml/marshal/dispatcher.py, bentoml/marshal/marshal.py, ci/test_project.sh.cmd, tests/conftest.py, tests/integration/projects/general/tests/test_adapter.py
Closing #1618 
Fix for the marshal server:
* Maintain outbound connections
* Release coroutine manually to shutdown outbound connections gracefully (or we would get an exception on exit)
=> [Fix] maintain connections; graceful shutdown

bentoml/yatai/deployment/sagemaker/serve, bentoml/yatai/yatai_service_impl.py
Fix upload Bento grpc call return responses.
=> [fix] Update responses in UploadBento grpc call

e2e_tests/yatai_server/test_postgres_gcs.py
Make sure the validation call is the same as sqlite_gcs test
=> [enhancement]update e2e yatai test

.github/workflows/ci.yml, bentoml/marshal/marshal.py, bentoml/server/gunicorn_server.py, tests/integration/projects/slo/bentoml_config.yml, tests/integration/projects/slo/model/model.py, tests/integration/projects/slo/service.py, tests/integration/projects/slo/tests/test_latency.py
=> [feat] SLO - API server max latency

docker/yatai-service/Dockerfile
* `pip install "bentoml[yatai_service]==0.13.0"` will now fail because the new resolver failed to find a version of pyparsing that meets all the requirements from yatai's dependencies
* This PR adds `--use-deprecated=legacy-resolver` option to Yatai's docker base image to make it possible to install
* As part of https://github.com/bentoml/BentoML/issues/1677, we will move out AWS / Azure specific dependencies out of Yatai's default dependencies in its docker base image
=> Fix Yatai docker base image release

DEVELOPMENT.md, docs/source/guides/monitoring.rst
- remove obsolete links
- update prom docs with custom metrics in Prometheus
=> [docs] update prometheus docs

bentoml/service/env.py, tests/test_service_env.py
=> Fix BentoService loading user-provided env.yml file in runtime

docker/model-server/Dockerfile-gpu
#1699. This is due to when miniconda3 docker image has git installed, whereas ``nvidia/cuda`` doesn't.
=> [fix] git deps to GPU image

bentoml/saved_bundle/docker-entrypoint.sh, bentoml/saved_bundle/templates.py, docs/source/deployment/heroku.rst
This fixes the bug mentioned in #1588. Also checks if $PORT is present
and overides $BENTOML_PORT to $PORT if found.
Solves #1588 
I've tested it locally and on Heroku service. 
=> Use $BENTOML_PORT as Dockerfile default port

bentoml/yatai/yatai_service.py
=> [Fix] missing s3_endpoint_url

bentoml/frameworks/detectron.py, tests/integration/test_detectron2_model_artifact.py
Missed packing metadata causing KeyError during load.
=> Fix a detectron2 packing bug missing metadata

docs/source/guides/custom_artifact.rst, docs/source/guides/gpu_serving.rst, docs/source/guides/monitoring.rst
=> [docs] update typo, add clear instructions on using GPU image

bentoml/yatai/deployment/sagemaker/model_server.py
Update the `model_server` used by sagemaker to convert Flask objects to and from dataclasses.
I just submitted a bug report (https://github.com/bentoml/BentoML/issues/1715) where I'm seeing my sagemaker server fail with a 500 internal error. From looking through the code, I think I've found the problem. `StringInput`, which `JsonInput` extends, uses `@decompress_gzip_request`. This annotation assumes the request is not a Flask request but rather a wrapped `bentoml.types.HTTPRequest`. In the `api_server.py` setup, `HTTPRequest.from_flask_request` gets called. In the `model_server`, it does not. This PR attempts to fix that.
Looking for some guidance on how to test this.
([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-che …
=> Wrap request in sagemaker model_server

bentoml/cli/aws_ec2.py, bentoml/cli/aws_lambda.py, bentoml/cli/aws_sagemaker.py, bentoml/cli/azure_functions.py
Add deprecation warnings to CLI deployments' commands 
=> Add deprecation warnings for deployment CLI commands

docs/source/api/bentoml.rst, docs/source/deployment/aws_ec2.rst, docs/source/deployment/aws_sagemaker.rst, docs/source/deployment/azure_functions.rst, docs/source/deployment/heroku.rst, docs/source/frameworks.rst, docs/source/guides/configs/README.rst, docs/source/guides/monitoring.rst
Update deployment guides and fix spelling issues in the doc
=> [docs]Update deployment guides for EC2/Sagemaker/Azure Functions/Heroku

.github/PULL_REQUEST_TEMPLATE.md, DEVELOPMENT.md, dev/githooks/commit-msg, dev/install_git_hooks.sh
=> docs: encourage using Conventional Commits specification to name PR

bentoml/frameworks/evalml.py, bentoml/frameworks/fasttext.py, bentoml/frameworks/keras.py, bentoml/frameworks/onnx.py, bentoml/frameworks/onnxmlir.py, bentoml/frameworks/pytorch.py, bentoml/frameworks/sklearn.py, bentoml/service/artifacts/__init__.py, bentoml/service/artifacts/json_file.py, bentoml/service/artifacts/pickle.py, bentoml/service/artifacts/text_file.py, setup.py
adapt changes introduced by pylint 2.9, by which`arguments-differ` is split into `arguments-differ` and `arguments-renamed`
=> fix: adapt changes introduced by pylint 2.9

bentoml/adapters/utils.py, bentoml/cli/bento_service.py, bentoml/cli/yatai_service.py, bentoml/configuration/__init__.py, bentoml/configuration/containers.py, bentoml/marshal/marshal.py, bentoml/saved_bundle/config.py, bentoml/server/api_server.py, bentoml/server/gunicorn_server.py, bentoml/server/instruments.py, bentoml/server/marshal_server.py, bentoml/service/__init__.py, bentoml/service/env.py, bentoml/tracing/__init__.py, bentoml/utils/log.py, bentoml/utils/open_api.py, bentoml/yatai/deployment/sagemaker/serve, bentoml/yatai/repository/gcs_repository.py, bentoml/yatai/repository/s3_repository.py, bentoml/yatai/yatai_service.py, bentoml/yatai/yatai_service_impl.py, pylintrc, setup.py, tests/configuration/test_containers.py
=> refactor: replace di framework

.github/workflows/ci.yml, DEVELOPMENT.md, bentoml/frameworks/paddle.py, tests/integration/projects/paddle/service.py
=> fix(ci): PaddlePaddle Intergration test

README.md
fix a typo
fix a typo in doc
Locally tested
=> fix: fix a typo in README doc

bentoml/_internal/env/pip_pkg.py
When using BentoML in a Jupyter notebook environment, I found that the `.ipynb_checkpoints` directory was scanned when the `infer_pip_packages` option was turned on. I don't think this makes any sense, it just slows down BentoML. So it would be better to exclude it.
=> fix: Exclude '.ipynb_checkpoints' when seeking pip packages by infer_pip_packages(True)

bentoml/_internal/artifacts/base.py, bentoml/_internal/types.py, bentoml/detectron.py, bentoml/paddle.py, bentoml/tensorflow.py, bentoml/transformers.py
=> fix(type): use PathType representation recommended by PEP 519

yatai/setup.py, yatai/yatai/api/__init__.py, yatai/yatai/api/api_v1/bundles.py, yatai/yatai/bundle_stores/__init__.py, yatai/yatai/bundle_stores/base_bundle_store.py, yatai/yatai/bundle_stores/file_system_bundle_store.py, yatai/yatai/bundle_stores/gcs_bundle_store.py, yatai/yatai/bundle_stores/s3_bundle_store.py, yatai/yatai/schema/bundle.py, yatai/yatai/yatai_service.py, yatai/yatai/yatai_service_impl.py
=> yatai rest api server

docs/source/guides/configuration.rst
=> Fix configuration documentation regarding default configuration

bentoml/_internal/configuration/containers.py
=> fix: yatai variable

.github/workflows/ci.yml
=> fix: update python to 3.7

bentoml/xgboost.py, tests/integration/frameworks/test_xgboost_model_artifact.py
=> refactor: xgboost new model IO

bentoml/_internal/models/base.py
=> fix(model): save when directory does not exist

bentoml/detectron.py
=> fix(framework): detectron loading with device arguments

bentoml/spacy.py, ci/integration/frameworks/run_spacy_tests.sh, docs/source/guides/configuration.rst, tests/integration/frameworks/test_spacy_model_artifact.py, yatai/ui/yarn.lock, yatai/web_server/yarn.lock
=> fix: spacy model options

.github/workflows/ci.yml, bentoml/spacy.py, ci/integration/frameworks/run_pycaret_tests.sh, tests/_internal/frameworks/tensorflow_utils.py, tests/integration/frameworks/onnx/test_onnxmlir_model_artifact.py
=> fix(ci): onnxmlir, spacy test cases

bentoml/paddle.py, tests/integration/frameworks/paddle/test_paddle_model_artifact.py
=> refactor(paddle): support users config for loading

bentoml/_internal/utils/__init__.py, bentoml/onnx.py, tests/integration/frameworks/onnx/test_onnx_model_artifact.py
=> feat: support ONNX providers and session options

bentoml/_internal/environment/local_py_modules.py, bentoml/utils.py, tests/unit/utils/sample.py, tests/unit/utils/test_env_helpers.py
=> feat: env utility functions

bentoml/__init__.py, bentoml/_internal/io_descriptors/image.py, bentoml/_internal/utils/__init__.py, bentoml/catboost.py, bentoml/coreml.py, bentoml/detectron.py, bentoml/easyocr.py, bentoml/evalml.py, bentoml/fastai.py, bentoml/fasttext.py, bentoml/flax.py, bentoml/gluon.py, bentoml/h2o.py, bentoml/keras.py, bentoml/lightgbm.py, bentoml/mlflow.py, bentoml/onnx.py, bentoml/paddle.py, bentoml/pyspark.py, bentoml/pytorch.py, bentoml/sklearn.py, bentoml/spacy.py, bentoml/tensorflow.py, bentoml/transformers.py, bentoml/xgboost.py
=> fix: type hints

bentoml/_internal/io_descriptors/multipart.py
=> fix: imports

bentoml/_internal/models/stores.py, bentoml/models.py
=> fix(modelstore): iterate modelstore

docs/source/deployment/knative.rst
Just updating the branch for https://github.com/bentoml/BentoML/pull/1841
cc @yubozhao
=> docs: Knative doc updates

bentoml/_internal/models/store.py, bentoml/_internal/utils/__init__.py, bentoml/models.py
- import/exports functionality. exported models will be stored under `BENTOML_HOME/models/exported` globally. Per Bento module, change `modelstore` options for base_dir to its correct path
- also added some warning as well
- add `override` tags for both `import` and `export`
=> feat: import/export modelstore

bentoml/_internal/service/__init__.py
=> Fix import for _internal/services. no longer need RUNNER_INIT_DOCS and etc

bentoml/_internal/configuration/containers.py, bentoml/_internal/configuration/default_configuration.yaml, bentoml/_internal/models/store.py, bentoml/_internal/service/utils.py, bentoml/_internal/types.py, bentoml/xgboost.py
=> feat: model tags + optimization

bentoml/adapters/json_output.py
To ensure there is a 'header' in the AWS Lambda returns
```
Hi, I have deployed a Bento to AWS Lambda, and when I try to access it through JS in the browser, it is always blocked by CORS policies.
I tried solutions following this 'CORS headers are not issued for servers'
More specifically, what I did is changing from @api(input=JsonInput(), batch=True) to @api(input=JsonInput(), output=JsonOutput(cors=“*”)) on my spacy_ner.py file.
However, an error was raised from bentoml: 
bentoml.exceptions.APIDeprecated: setting cors from OutputAdapter is no more supported.See cors option in the configuration file.  It's weird since according to what @Chaoyu  mentioned in the link, it should work. 
```
([instructions](https://github.com/bentoml/BentoML/blob/master/DEV …
=> fix: cors headers for AWS Lambda

bentoml/_internal/runner/transport.py, bentoml/_internal/server/runner_app.py, bentoml/_internal/types.py
=> chore: add runner app/client

bentoml/xgboost.py
When running the given example for XGBoost in `bentoml/xgboost.py`, the script wasn't able to find `Runner` class needed to initialize the instance. The import in `xgboost.py` had to be fixed from `from ._internal.service import Runner` to `from ._internal.service.runner import Runner`
This change is required to run the given example and create booster. 
It's been tested by running the example and being able to create a booster instance, train it, and predict with it. 
TAG my_xgboost_model:20211005_C6B141
BST <xgboost.core.Booster object at 0x7f7475787b20>
- [] My code follows the bentoml code style, both `./dev/format.sh` and
=> fix: import Runner for XGBoost

bentoml/_internal/cli/bento_management.py, bentoml/_internal/cli/bento_server.py, bentoml/_internal/io_descriptors/json.py, bentoml/_internal/runner/runner.py, bentoml/_internal/server/__init__.py, bentoml/_internal/service/openapi.py, bentoml/transformers.py, ci/integration/frameworks/run_transformers_tests.sh, tests/integration/frameworks/test_transformers_impl.py, tests/integration/projects/general/service.py
=> feat(transformers): supports non-nlp related pipelines args

bentoml/transformers.py
since redownloading pretrained model is not a good use of storage space 😃 
=> feat(transformers): stop downloading from existing pretrained

bentoml/_internal/runner/utils.py
=> fix: bentoml.__internal.runner.TypeRef minor bug fix

bentoml/_internal/runner/container.py
=> fix: fix DataContainer.create_payload method

bentoml/tensorflow.py, bentoml/transformers.py, ci/integration/frameworks/run_tf2_tests.sh, tests/integration/frameworks/test_tensorflow_impl.py, tests/integration/frameworks/test_transformers_impl.py
=> fix: transformers + tensorlfow CI

bentoml/_internal/service/service.py, bentoml/bentos.py
=> fix: minor import issues

bentoml/_internal/runner/container.py
@bojiang I think we should squeeze ndarray singles along the batch axis when `using batch_to_singles`
=> fix(container): NdarrayContainer batch_to_singles fix
