bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/pandas.py
bentoml/_internal/runner/container.py
bentoml/spacy.py
tests/integration/conftest.py

Literal is not supported before Python3.8

fix: import Literal from typing_extensions

---

bentoml/_internal/cli/bento_server.py
bentoml/_internal/configuration/__init__.py
bentoml/_internal/models/store.py
bentoml/_internal/runner/runner.py
bentoml/_internal/server/__init__.py
bentoml/_internal/server/base_app.py
bentoml/_internal/server/service_app.py
bentoml/_internal/service/loader.py
bentoml/_internal/service/service.py
bentoml/_internal/types.py
bentoml/sklearn.py
tests/conftest.py
tests/integration/projects/conftest.py
tests/integration/projects/general/service.py
tests/integration/projects/general/tests/test_meta.py
tests/integration/utils.py

refactor: major fix; add integration tests for the HTTP server

---

tests/integration/projects/conftest.py
tests/integration/projects/general/tests/test_io.py
tests/integration/projects/general/tests/test_meta.py
tests/integration/projects/general/tests/test_microbatch.py
tests/integration/utils.py

chore: add io integration tests

---

bentoml/_internal/bento/bento.py

fix: create model path if not exists when build tmp bento

---

tests/unit/_internal/bento/test_bentos.py

forgot to make this change when prefixing everything with underscore.

test: fix bento test

---

bentoml/_internal/service/loader.py

fix: import service support relative path and nested py module names

---

bentoml/_internal/runner/container.py
tests/unit/_internal/runner/container.py
tests/unit/_internal/runner/utils.py

feat: draft for Pandas Data Container

---

.github/workflows/ci.yml
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/pandas.py
bentoml/_internal/runner/utils.py
bentoml/testing/__init__.py
bentoml/testing/utils.py
setup.py
tests/integration/projects/general/service.py
tests/integration/projects/general/tests/test_io.py

chore: add itests for pandas

---

bentoml/_internal/io_descriptors/file.py
bentoml/_internal/server/__init__.py
bentoml/_internal/types.py
tests/conftest.py
tests/integration/projects/general/service.py
tests/integration/projects/general/tests/test_io.py
tests/integration/projects/general/tests/test_meta.py
tests/integration/projects/general/tests/test_microbatch.py
tests/integration/utils.py

fix: fix File io & add itest

---

docs/source/guides/monitoring.rst

Help the next reader to directly use custom metrics without research.
Tested on local machine, but it is a straight forward change.

[docs] Fix custom metrics for prometheus (#1663)

---

bentoml/_internal/io_descriptors/file.py
bentoml/_internal/io_descriptors/image.py
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/multipart.py
bentoml/_internal/io_descriptors/pandas.py
bentoml/_internal/runner/container.py
bentoml/_internal/server/service_app.py
bentoml/mlflow.py
bentoml/paddle.py
bentoml/spacy.py
bentoml/transformers.py
tests/integration/frameworks/test_transformers_impl.py

feat: add skeleton of multipart io

---

bentoml/_internal/cli/bento_server.py
bentoml/_internal/server/README.md
bentoml/_internal/server/__init__.py
bentoml/_internal/service/loader.py
bentoml/_internal/service/service.py

feat(BentoServer): implement --reload option

---

bentoml/_internal/utils/http.py

feat: add multipartparser for processing multipart

---

bentoml/_internal/bento/bento.py
bentoml/_internal/cli/click_utils.py
bentoml/_internal/configuration/containers.py
bentoml/_internal/environment/docker_image.py
bentoml/_internal/environment/environment.py
bentoml/_internal/environment/local_py_modules.py
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/pandas.py
bentoml/_internal/marshal/marshal.py
bentoml/_internal/server/service_app.py
bentoml/_internal/service/loader.py
bentoml/_internal/service/service.py
bentoml/_internal/types.py
bentoml/_internal/utils/dataframe.py
bentoml/_internal/utils/docker.py
bentoml/_internal/utils/flask_ngrok.py
bentoml/_internal/utils/http.py
bentoml/_internal/utils/lazy_loader.py
bentoml/_internal/utils/tensorflow.py
bentoml/_internal/utils/validation.py
tests/integration/projects/general/tests/test_io.py

fix: consistent import and lint

---

bentoml/pytorch.py

fix(framwork/pytorch): _run_batch take *args as multiple tensors

---

ci/integration/frameworks/run_pytorch_tests.sh
tests/integration/frameworks/test_pytorch_impl.py

hotfix: `torch.get_num_threads` behaviour

---

bentoml/_internal/io_descriptors/image.py
bentoml/_internal/io_descriptors/multipart.py
bentoml/_internal/utils/formparser.py

fix(internal): Pillow instead of imageio

---

bentoml/_internal/runner/utils.py
bentoml/onnx.py
tests/integration/frameworks/onnx/test_onnx_impl.py

feat(framework): GPU supports for ONNX

---

.github/stale.yml

ci: turn off stale bot auto-closing

---

tests/integration/frameworks/test_pytorch_lightning_impl.py

fix: pytorch lightning thread number test

---

bentoml/testing/README.md

doc: add readme to bentoml/testing

---

bentoml/__init__.py
bentoml/_internal/bento/bento.py
bentoml/_internal/cli/__init__.py
bentoml/_internal/cli/bento_server.py
bentoml/_internal/configuration/__init__.py
bentoml/_internal/log.py
bentoml/_internal/server/README.md
bentoml/_internal/server/__init__.py
bentoml/_internal/service/loader.py
bentoml/_internal/service/service.py
bentoml/_internal/store.py
bentoml/bentos.py
bentoml/build_utils.py
setup.py

fix: allow serve by bento tag

---

.github/workflows/ci.yml

fix: ci default branch to be bentoml-1.0 instead of main

---

.github/workflows/frameworks.yml
codecov.yml

fix: spacy codecov failed to upload reports

---

.github/workflows/ci.yml
codecov.yml

fix: codecov carryforward

---

bentoml/_internal/bento/README.md
bentoml/_internal/bento/bento.py
bentoml/bentos.py
tests/unit/_internal/bento/test_bentos.py

fix: rename build arg 'models' to 'additional_models'

---

bentoml/_internal/configuration/containers.py

fix: bentos folder does not exist error

---

bentoml/_internal/bento/bento.py
bentoml/_internal/server/service_app.py
bentoml/_internal/service/service.py
bentoml/bentos.py
tests/unit/_internal/bento/test_bentos.py

feat: allow user to customize Service readme/docs

---

bentoml/testing/server.py
scripts/ci/config.yml
scripts/ci/run_tests.sh

There is no docker on the macos of Github Action.

fix: test script issue without docker

---

docs/source/guides/custom_input_adapter.rst

I modified the Customizing InputAdapter Document.
I thought that the existing Customizing InputAdapter docs lacked content.
There were not enough examples of how to custom exception handling for actual inputs. And there was also a lack of examples on how to process custom input for batch.
I wanted to update these parts.
If you look at the capture below, you can see that the micro batch is performed well even if a lot of traffic flows to the application of the code modified in the docs.
After building in the local environment, I checked the docs.

docs:Update custom_input_adapter doc

---

.gitignore
MANIFEST.in

build: fix pypi package include files

---

MANIFEST.in
scripts/ci/style/pylint_check.sh

chore: disable pylint running on main branch

---

.github/workflows/ci.yml
.github/workflows/frameworks.yml
bentoml/_internal/configuration/__init__.py
bentoml/_internal/configuration/containers.py

fix: KeyError in expand_env_var

---

bentoml/_internal/bento/bentoml-init.sh
bentoml/_internal/runner/utils.py
docker/README.md
docker/docs/DEV.md
docs/source/concepts.rst
docs/source/deployment/aws_ecs.rst
docs/source/deployment/azure_container_instance.rst
docs/source/deployment/azure_functions.rst
docs/source/deployment/google_cloud_ai_platform.rst
docs/source/deployment/google_cloud_run.rst
docs/source/deployment/heroku.rst
docs/source/deployment/kfserving.rst
docs/source/deployment/knative.rst
docs/source/deployment/kubeflow.rst
docs/source/deployment/kubernetes.rst
docs/source/deployment/sql_server.rst
docs/source/quickstart.rst

chore: drop python 3.6 support

---

bentoml/onnx.py
scripts/ci/config.yml
tests/integration/frameworks/test_onnx_impl.py

refactor(framework): onnx multi args support

---

bentoml/tensorflow.py
tests/integration/frameworks/test_tensorflow_impl.py
tests/utils/frameworks/tensorflow_utils.py

refactor(frameworks): tensorflow bug fix and multi args support

---

bentoml/_internal/bento/bento.py
bentoml/_internal/bento/build_dev_bentoml_whl.py
bentoml/_internal/types.py
bentoml/sklearn.py
bentoml/statsmodels.py

Fix: additional model tags error and attribution error on bento._info

---

.github/workflows/ci.yml
.github/workflows/frameworks.yml
codecov.yml

having separate flags should work better, since sometimes if you change a framework files, it won't carryforward un triggered frameworks tests under the same flags. Seems like a codecov bugs, example is https://github.com/bentoml/BentoML/pull/2055. 

chore: fix codecov not carryforward not related tests

---

README.md
docs/source/concepts/api_io_descriptors.rst
docs/source/concepts/bento_management.rst
docs/source/concepts/building_bentos.rst
docs/source/concepts/containerize_bentos.rst
docs/source/concepts/index.rst
docs/source/concepts/service_definition.rst
docs/source/conf.py
docs/source/frameworks.rst
docs/source/guides/index.rst
docs/source/guides/multi_models.rst
docs/source/guides/runner.rst
docs/source/guides/server.rst
docs/source/index.rst
docs/source/quickstart.rst
requirements/docs-requirements.txt

BentoML 1.0 release user documentation. (in-progress)

docs: 1.0 release user documentation

---

.github/workflows/frameworks.yml

chore: trigger keras tests with tensorflow tests

---

README.md

doc: Update README.md styling

---

bentoml/_internal/models/model.py

At some point we should think about how exactly this should be done, but for now this should be fine.

fix(internal): don't move models

---

bentoml/_internal/bento/build_config.py
bentoml/_internal/cli/bento_server.py
bentoml/_internal/server/__init__.py
bentoml/_internal/service/loader.py

fix: support load from bento dir

---

bentoml/keras.py

refactor(framework): keras add predict kwargs

---

.gitignore
bentoml/_internal/bento/build_config.py
bentoml/_internal/bento/build_dev_bentoml_whl.py
bentoml/_internal/bento/docker/init.sh

Fix: make building bentoml dev wheel optional & bento build fixes

---

bentoml/pytorch.py
tests/integration/frameworks/test_pytorch_impl.py

feat: Pytorch Tensor data container

---

docs/source/concepts/api_io_descriptors.rst
docs/source/concepts/bento_management.rst
docs/source/concepts/building_bentos.rst
docs/source/concepts/containerize_bentos.rst
docs/source/concepts/index.rst
docs/source/concepts/service_definition.rst
docs/source/conf.py
docs/source/guides/yatai_service.rst

BentoML 1.0 release core concepts user documentation.

docs: BentoML 1.0 release core concepts user documentation.

---

bentoml/_internal/marshal/dispatcher.py
bentoml/_internal/runner/container.py
bentoml/_internal/runner/utils.py
bentoml/_internal/server/runner_app.py
bentoml/exceptions.py

chore(runner): enable dynamic batching for runners

---

tests/e2e/bento_server_general_features/service.py
tests/e2e/bento_server_general_features/tests/conftest.py

chore(ci): build bento in e2e tests

---

DEVELOPMENT.md
bentoml/_internal/bento/README.md
bentoml/_internal/bento/bento.py
bentoml/_internal/bento/docker/Dockerfile.template
bentoml/_internal/cli/bento_management.py
bentoml/_internal/cli/containerize.py
bentoml/_internal/cli/model_management.py
bentoml/_internal/frameworks/tensorflow.py
bentoml/_internal/io_descriptors/__init__.py
bentoml/_internal/server/__init__.py
bentoml/_internal/utils/tensorflow.py
bentoml/bentos.py
bentoml/io.py
docs/source/quickstart.rst
requirements/tests-requirements.txt
setup.cfg

feat: add BentoML build & containerize cli

---

bentoml/_internal/io_descriptors/json.py
bentoml/pytorch_lightning.py

style: minor fix

---

bentoml/_internal/bento/README.md
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/log.py
bentoml/_internal/models/model.py
docs/source/quickstart.rst
tests/integration/frameworks/paddle/conftest.py
tests/integration/frameworks/paddle/test_paddle_impl.py

chore: misc fixes

---

bentoml/_internal/server/__init__.py
tests/e2e/bento_server_general_features/tests/test_io.py
tests/integration/conftest.py

fix: error when serve --production using bento path

---

bentoml/_internal/cli/bento_server.py
bentoml/_internal/cli/click_utils.py
bentoml/_internal/cli/containerize.py
bentoml/_internal/configuration/containers.py
bentoml/_internal/configuration/default_configuration.yaml
bentoml/_internal/server/__init__.py
bentoml/bentos.py

feat: adding more serve CLI options, fix Uvicorn logs

---

bentoml/spacy.py
tests/integration/frameworks/spacy/conftest.py
tests/integration/frameworks/spacy/test_spacy_impl.py
tests/integration/frameworks/spacy/test_spacy_runner.py

fix some of spacy internal API to lazy loader, since it slows down import significantly.

chore: type-safe spacy

---

bentoml/_internal/runner/runner.py
bentoml/_internal/server/__init__.py
tests/e2e/bento_server_general_features/pickle_model.py
tests/e2e/bento_server_general_features/service.py
tests/e2e/bento_server_general_features/tests/conftest.py
tests/e2e/bento_server_general_features/train.py
tests/integration/frameworks/spacy/test_spacy_runner.py

fix: regular runner names

---

.gitignore
bentoml/_internal/frameworks/catboost.py

minor type fix, stubs for catboost can be used from bentoml/stubs :)

chore: fix typings, added editted stubs for catboost

---

bentoml/_internal/yatai_client/__init__.py

fix: type error in yatai_client caused by bento refactoring

---

bentoml/_internal/bento/README.md
bentoml/_internal/bento/bento.py
bentoml/_internal/bento/build_config.py
bentoml/_internal/bento/docker.py
docker/README.md
docker/generated/bento-server/README.md
docker/generated/bento-server/debian10/cudnn/Dockerfile
docker/generated/bento-server/debian10/devel/Dockerfile
docker/generated/bento-server/debian10/runtime/Dockerfile
docker/manager.py
docker/manifest.yml
docker/templates/docs/README.md.j2

chore: fix bentoserver base image release

---

bentoml/_internal/frameworks/catboost.py
bentoml/_internal/frameworks/detectron.py
bentoml/_internal/frameworks/easyocr.py
bentoml/_internal/frameworks/gluon.py
bentoml/_internal/frameworks/h2o.py
bentoml/_internal/frameworks/keras.py
bentoml/_internal/frameworks/lightgbm.py
bentoml/_internal/frameworks/mlflow.py
bentoml/_internal/frameworks/onnx.py
bentoml/_internal/frameworks/onnxmlir.py
bentoml/_internal/frameworks/paddle.py
bentoml/_internal/frameworks/pycaret.py
bentoml/_internal/frameworks/pytorch.py
bentoml/_internal/frameworks/pytorch_lightning.py
bentoml/_internal/frameworks/sklearn.py
bentoml/_internal/frameworks/spacy.py
bentoml/_internal/frameworks/statsmodels.py
bentoml/_internal/frameworks/tensorflow.py
bentoml/_internal/frameworks/transformers.py
bentoml/_internal/frameworks/xgboost.py
tests/integration/frameworks/mlflow/test_mlflow_save_load.py

chore: fix model module check on load

---

bentoml/_internal/runner/remote.py
scripts/ci/config.yml
tests/e2e/bento_server_general_features_sync/bentoml_config.yml
tests/e2e/bento_server_general_features_sync/pickle_model.py
tests/e2e/bento_server_general_features_sync/service.py
tests/e2e/bento_server_general_features_sync/tests/conftest.py
tests/e2e/bento_server_general_features_sync/tests/test_io.py
tests/e2e/bento_server_general_features_sync/tests/test_meta.py
tests/e2e/bento_server_general_features_sync/tests/test_microbatch.py
tests/e2e/bento_server_general_features_sync/train.py

fix(runner): sync call of remote runner; add e2e test

---

docker/manager.py
scripts/release_docker_images.sh

chore: support concurrent build in base image release process

---

bentoml/_internal/bento/docker.py
bentoml/_internal/configuration/__init__.py
pyproject.toml

By using `post-release` version schema, it will be a lot easier to find the `latest` official release version, when using BentoML development branch.
This can help the Bento build process to determine if there is a pre-built image for this branch or if it should use the docker images for the last PyPI release.
This is different form the `devel` which is meant for a nightly build of base images. Users need to specifically state using `devel` images in their bento file, e.g.:
```
service: "iris_classifier:svc"
python:
packages:
- scikit-learn
- pandas
docker:
distro: debian
devel: True
```

build: use setuptools_scm.version_scheme = "post-release"

---

bentoml/_internal/bento/bento.py
bentoml/_internal/models/model.py
bentoml/_internal/server/__init__.py
bentoml/_internal/service/loader.py
bentoml/_internal/service/service.py
bentoml/bentos.py

chore: misc log message changes

---

CONTRIBUTING.md
DEVELOPMENT.md
GOVERNANCE.md
README.md
docker/README.md
docs/source/api/yatai_client.rst
docs/source/concepts.rst
docs/source/examples.md
docs/source/faq.rst
docs/source/frameworks.rst
docs/source/guides/configs/README.rst
docs/source/guides/configuration.rst
docs/source/guides/gpu_serving.rst
docs/source/guides/monitoring.rst
docs/source/index.rst

Several documents links are broken since we moved from `master` to `main`. This PR fix the broken URLs. 

chore: update documents url from master to main

---

bentoml/_internal/bento/docker/Dockerfile.template
bentoml/_internal/cli/bento_server.py
bentoml/_internal/cli/click_utils.py
bentoml/_internal/configuration/containers.py
bentoml/_internal/frameworks/sklearn.py
bentoml/bentos.py

fix: set default bento server host to localhost in dev mode

---

bentoml/_internal/bento/bento.py
bentoml/_internal/configuration/containers.py
bentoml/_internal/server/runner_app.py
bentoml/_internal/service/service.py
bentoml/_internal/types.py

style(type): minor fix

---

bentoml/_internal/cli/bento_management.py
bentoml/_internal/cli/model_management.py
bentoml/_internal/cli/yatai.py
bentoml/_internal/io_descriptors/image.py
bentoml/_internal/runner/remote.py
bentoml/_internal/server/runner_app.py
bentoml/_internal/yatai_rest_api_client/config.py

chore: fix absolute to relative imports

---

bentoml/_internal/server/base_app.py

Give endpoint names to routes inside `base_app`. This is especially useful for referring to these internal routes by names in 
the sagemaker app's redirection functions. 

fix: added endpoint names to routes in baseapp

---

bentoml/_internal/configuration/containers.py
bentoml/_internal/ext_typing.py
bentoml/_internal/io_descriptors/image.py
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/numpy.py
bentoml/_internal/io_descriptors/pandas.py
bentoml/_internal/runner/container.py
pyproject.toml
tests/e2e/bento_server_general_features/service.py
typings/pyarrow/__init__.pyi
typings/pyarrow/plasma/__init__.pyi
typings/schema/__init__.pyi

style: fix typing for io descriptors

---

bentoml/utils/cloudpickle.py

fix: add checking if obj has __module__ attribute

---

README.md
docs/source/index.rst

docs: 1.0 preview release update

---

bentoml/adapters/json_output.py

Adding an option to specify the CHARSET in the Output Header.
If the JSON output is a UTF-8 string, it is required.
`
@api(input=JsonInput(), output=JsonOutput(charset="utf-8"), …)
`

feat: add a charset option for the json output header

---

README.md
docs/source/quickstart.rst

docs: fix broken links and 1.0 installation note

---

bentoml/adapters/file_input.py
bentoml/frameworks/keras.py
bentoml/service/inference_api.py
bentoml/types.py
tests/bento_service_examples/keras_classifier.py
tests/integration/projects/general/service.py

For LTS
fix:
* custom route
* various API changes due to the upgrading of dependencies
There are still some e2e tests failures, which require more context to get fixed.
TL;DR:
With bentoml-0.13, users cannot enable micro-batching for endpoints like this:
```python
@api(route="/xxxxxxxx", batch=True)
```
We can reproduce it in e2e test:
https://github.com/bentoml/BentoML/runs/4817059421?check_suite_focus=true#step:5:777

fix[0.13-LTS]: batching not works with some customize route; minor fixes for lib versions

---

tests/integration/projects/general/bentoml_config.yml
tests/integration/projects/general/tests/test_meta.py

chore(ci): add a test case to ensure preflight cors requests are handled

---

bentoml/_internal/cli/bento_management.py
bentoml/_internal/cli/model_management.py

feature(cli): delete command for models and bentos

---

docs/source/_static/css/bentoml.css
docs/source/_static/js/bentoml.js
docs/source/conf.py

fix: logo size

---

bentoml/_internal/bento/docker/Dockerfile.template

Fixes _Change layers order in Dockerfile.template due permission issues on compile_ #2199 
Changes the position of the `USER` command in the bento `Dockerfile.template`
Fixes #2199 - a bug that happens when using Kubeflow
Tested by creating a new venv, installing this branch in editable mode, then generating a new bento of the IrisClassifier toy example.
Then used the reproducibility steps described in the #2199 issue.
Verified that the docker image now successfully builds.

fix:  Change layers order in Dockerfile.template due permission issues on compile #2199 

---

README.md
docs/source/index.rst

docs: update project readme

---

tests/e2e/bento_server_general_features/service.py
tests/e2e/bento_server_general_features/tests/test_io.py

chore(ci): add e2e test cases for PandasDataFrame output

---

bentoml/_internal/runner/remote.py

fix(server): task attaching error for sync routes

---

bentoml/_internal/runner/remote.py

fix(server): surface upstream error

---

bentoml/_internal/frameworks/pytorch.py
tests/integration/frameworks/test_pytorch_impl.py

fix: pytorch load correctly address device_id

---

setup.cfg

`pip install --pre bentoml` would install unstable `opentelemetry-api` and `opentelemetry-sdk`

fix(server): lock dependencies about opentelemetry

---

bentoml/_internal/frameworks/mlflow.py
bentoml/_internal/frameworks/spacy.py
bentoml/_internal/frameworks/tensorflow.py
tests/integration/frameworks/mlflow/test_mlflow_save_load.py
tests/integration/frameworks/spacy/test_spacy_impl.py

fix: spacy exception

---

bentoml/_internal/configuration/containers.py
bentoml/_internal/server/__init__.py
bentoml/_internal/utils/__init__.py
bentoml/_internal/utils/circus.py

Circus is designed to be a singleton daemon in each system. It listens on the same set of ports by default.

fix(server): init standalone circus for each serving

---

bentoml/_internal/server/service_app.py

A quick fix for occational 500 on `/metrics` endpoint.
`simple_di.inject` currently not work with async functions. 

fix(server): metrics endpoint

---

bentoml/_internal/bento/bento.py

:facepalm: 
We should maybe have some tests where we set the configuration and use the defaults.

fix: inject default store into bento save

---

bentoml/_internal/bento/bento.py
bentoml/_internal/configuration/containers.py
bentoml/_internal/ext_typing.py
bentoml/_internal/server/__init__.py
bentoml/_internal/server/instruments.py
bentoml/_internal/server/metrics/prometheus.py
bentoml/_internal/server/service_app.py
tests/e2e/bento_server_general_features/tests/test_meta.py

The solution of the OpenTelemetry Prometheus exporter is still not ready for production (`alpha`, otel said).
Let's focus on `promethrus_client`.
TODO:

feat(server): fix the metrics middleware

---

bentoml/_internal/frameworks/transformers.py
setup.cfg
tests/integration/frameworks/test_transformers_impl.py

feat(transformers): add lm_head warning

---

README.md

correcting possibly broken link to usage_stats.py in README.
was just passing by this repo.. please feel free to close this if this is not relevant.

docs: README: update usage_stats.py link

---

bentoml/_internal/bento/README.md
bentoml/_internal/bento/docker/init.sh

fix: pip install issue when lock_packages=False

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md
GOVERNANCE.md
README.md
SECURITY.md
docker/templates/docs/README.md.j2
docs/source/guides/index.rst
docs/source/index.rst

chore: update join slack community links

---

bentoml/frameworks/fastai.py

Add metadata functionality to FastaiModelArtifact (fastai2)
Add metadata functionality to FastaiModelArtifact (fastai2)
The functionality is available in most of the other frameworks and in Fastai1ModelArtifact but is missing for fastai2.
Fixes /metadata for fastai v2.
Tested manually by packing with _metadata_ kwarg. 

fix: missing metadata for FastaiModelArtifact

---

scripts/ci/config.yml

* scipy just released 1.8.0
* statsmodels is using internal API of scipy

fix(ci): lock dependencies of statsmodels

---

docs/source/quickstart.rst

patching quickstart so that save codeblock appears

---

bentoml/_internal/marshal/dispatcher.py

chore(sdk): adjust dynamic batching log messages

---

bentoml/_internal/frameworks/transformers.py
bentoml/transformers.py
tests/integration/frameworks/test_transformers_impl.py

depends on #2254 to merge first since there are some types changes that is related in this PR.

chore: remove import_from_huggingface_hub from public API

---

bentoml/_internal/bento/bento.py
bentoml/_internal/cli/bento_management.py
bentoml/_internal/cli/model_management.py
bentoml/_internal/models/model.py

feature(cli): add get command

---

bentoml/_internal/log.py
bentoml/_internal/server/access.py
bentoml/_internal/trace.py

Update logging format to re-order trace data and add field names as suggested.
```
[00:25:48] INFO     [iris_clf] _ (scheme=http,method=POST,path=/run,type=multipart/form-data; boundary=02329502b8f644dbb679cdaaf4a7d45f,length=432) (status=200,type=,length=152) 0.002ms
(trace=299854727798388563194151159522763349322,span=10924663519931178761,sampled=False)
[00:25:48] INFO     [api_server] 127.0.0.1:58051 (scheme=http,method=POST,path=/classify,type=application/json,length=9) (status=200,type=application/json,length=1) 0.151ms
(trace=299854727798388563194151159522763349322,span=14694874138107506710,sampled=False)
```
Improve service and access log readability.
([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-form …

feat: Update logging format to re-order trace data and add field names

---

bentoml/_internal/bento/bento.py

refactor(internal): make the bento fs onsetattr a validator

---

bentoml/_internal/bento/docker/Dockerfile.template
bentoml/_internal/configuration/default_configuration.yaml
bentoml/_internal/io_descriptors/file.py
bentoml/_internal/io_descriptors/image.py
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/multipart.py
bentoml/_internal/io_descriptors/numpy.py
bentoml/_internal/io_descriptors/pandas.py
bentoml/_internal/io_descriptors/text.py
bentoml/_internal/utils/benchmark.py
bentoml/testing/server.py
docs/source/concepts/containerize_bentos.rst
docs/source/guides/gpu.rst
docs/source/guides/tracing.rst
docs/source/quickstart.rst

This reverts commit 02c8333d289e1ff1e6f38ef85ee8760daeca69df.
Will merge this change before next release, to make sure all docs changes reflect latest change.

Revert "chore: change default serving port to 3000 (#2273)"

---

bentoml/_internal/server/access.py
bentoml/_internal/server/base_app.py
bentoml/_internal/server/instruments.py
bentoml/_internal/server/service_app.py

fix(server): respect metrics configs to turn on/off metrics

---

bentoml/_internal/server/runner_app.py

Fix the HTTP status code of TOO_MANY_REQUESTS from 427 to 429.

fix: HTTP status code of TOO_MANY_REQUESTs

---

docs/source/quickstart.rst

Update the quickstart guide to be consistent with the gallery.

fix: Update the quickstart guide to be consistent with the gallery

---

bentoml/_internal/store.py
tests/unit/_internal/test_store.py

Fixes #2297 
This was mostly an oversight on my part.

fix(internal): skip all files when listing store

---

bentoml/_internal/utils/__init__.py

chore: use backported cached_property

---

bentoml/_internal/server/runner_app.py

fix(runner): do not enable dispatcher for SimpleRunners

---

bentoml/_internal/server/__init__.py
bentoml/_internal/server/cli/api_server.py
bentoml/_internal/server/cli/dev_api_server.py
docs/source/quickstart.rst

…
Make dev and prod api_server circus process and port management consistent.
This change also addresses https://github.com/bentoml/BentoML/issues/2287 by logging the server address during the circus stage.
Dev:
```
02/24/2022 03:16:49 INFO     [cli] Starting development BentoServer from "iris_classifier:latest" running on http://127.0.0.1:5000 (Press CTRL+C to quit)
02/24/2022 03:16:50 INFO     [dev_api_server] Service loaded from Bento store: bentoml.Service(tag="iris_classifier:dpijemevl6nlhlg6", path="/Users/ssheng/bentoml/bentos/iris_classifier/dpijemevl6nlhlg6")
02/24/2022 03:16:50 INFO     [dev_api_server] Started server process [30772]
02/24/2022 03:16:50 INFO     [dev_api_server] Waiting for application startup.
02/24/2022 03:16:50 INFO     [dev_api_server] Application startup …
```

fix: Make dev and prod circus process and port management consistent

---

bentoml/_internal/server/__init__.py
bentoml/_internal/server/cli/api_server.py
bentoml/_internal/server/cli/dev_api_server.py

style: fix server/__init__.py

---

docs/source/concepts/bento_management.rst

docs: typo correction
In pushing models section, the example of command or function is related to `delete`. I would recommend to change it to `push`

docs: typo correction

---

bentoml/_internal/server/cli/dev_api_server.py

fix(server): serve --reload

---

.github/workflows/frameworks.yml
bentoml/__init__.py
bentoml/_internal/frameworks/common/pytorch.py
bentoml/_internal/frameworks/pytorch.py
bentoml/_internal/frameworks/pytorch_lightning.py
bentoml/_internal/frameworks/torchscript.py
bentoml/pytorch.py
bentoml/torchscript.py
codecov.yml
scripts/ci/config.yml
tests/integration/frameworks/test_pytorch_impl.py
tests/integration/frameworks/test_pytorch_lightning_impl.py
tests/integration/frameworks/test_torchscript_impl.py
tests/utils/frameworks/pytorch_utils.py

refactor(framework): pytorch splitting refactor

---

docker/generated/bento-server/README.md
docker/generated/bento-server/alpine3.14/runtime/Dockerfile
docker/generated/bento-server/amazonlinux2/runtime/Dockerfile
docker/generated/bento-server/centos7/cudnn/Dockerfile
docker/generated/bento-server/centos7/runtime/Dockerfile
docker/generated/bento-server/centos8/cudnn/Dockerfile
docker/generated/bento-server/centos8/runtime/Dockerfile
docker/generated/bento-server/debian10/cudnn/Dockerfile
docker/generated/bento-server/debian10/runtime/Dockerfile
docker/manifest.yml
docker/pyproject.toml

chore: update docker for 1.0.0a5

---

bentoml/_internal/io_descriptors/pandas.py
requirements/tests-requirements.txt
tests/e2e/bento_server_general_features/tests/test_io.py

Currently when the PandasDataFrame IO descriptor is used, it always print a warning about the pyarrow dependency, even if the serialization format is not set to parquet. This PR fixes that and only print this warning when it is specified as the default serialization format or when a request content type indicating the format to be parquet.

chore: remove unnecessary missing dependency warning 

---

bentoml/_internal/bento/build_config.py

chore: fall back to lock_packages=False when pip-tools fails

---

README.md
docker/README.md
docker/templates/docs/README.md.j2
docs/source/index.rst

docs: update slack community link

---

README.md

docs: update yatai and bentoctl project description

---

setup.cfg

BentoML 1.0 is currently under preview release, installing it with `--pre` flag means it will also install preview release for all dependencies is possible. This lead new users to install preview release of aiohttp 4.0, which isn't compatible with BentoML yet, as reported here https://github.com/bentoml/BentoML/issues/2313
This PR limits aiohttp to its current stable release. We should revisit support for aiohttp 4.0 when it is fully released. cc @bojiang 

fix: avoid using aiohttp preview release

---

bentoml/_internal/bento/build_config.py
bentoml/_internal/bento/docker.py
docker/README.md
docker/generated/bento-server/README.md
docker/generated/bento-server/ubi7/Dockerfile
docker/generated/bento-server/ubi7/cudnn/Dockerfile
docker/generated/bento-server/ubi7/cudnn/cuda.repo
docker/generated/bento-server/ubi7/cudnn/nvidia-ml.repo
docker/generated/bento-server/ubi7/devel/Dockerfile
docker/generated/bento-server/ubi7/runtime/Dockerfile
docker/generated/bento-server/ubi8/Dockerfile
docker/generated/bento-server/ubi8/cudnn/Dockerfile
docker/generated/bento-server/ubi8/cudnn/cuda.repo
docker/generated/bento-server/ubi8/cudnn/nvidia-ml.repo
docker/generated/bento-server/ubi8/devel/Dockerfile
docker/generated/bento-server/ubi8/runtime/Dockerfile
docker/manager.py
docker/manifest.yml
docker/poetry.lock
docker/utils.py

feat(docker): add ubi images

---

bentoml/_internal/frameworks/keras.py
tests/integration/frameworks/test_keras_impl.py
tests/utils/frameworks/tensorflow_utils.py

feature(framework): keras add save_format option

---

bentoml/_internal/server/access.py
bentoml/_internal/server/service_app.py

style: not inherit starlette middleware

---

bentoml/_internal/cli/bento_management.py
bentoml/_internal/cli/model_management.py
bentoml/_internal/models/model.py

feat(cli): add export/import cli for bento and model

---

bentoml/_internal/bento/docker/Dockerfile.template
bentoml/_internal/configuration/default_configuration.yaml
bentoml/_internal/io_descriptors/file.py
bentoml/_internal/io_descriptors/image.py
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/multipart.py
bentoml/_internal/io_descriptors/numpy.py
bentoml/_internal/io_descriptors/pandas.py
bentoml/_internal/io_descriptors/text.py
bentoml/_internal/utils/benchmark.py
bentoml/testing/server.py
docs/source/concepts/containerize_bentos.rst
docs/source/guides/gpu.rst
docs/source/guides/tracing.rst
docs/source/quickstart.rst

chore: change BentoServer default port to 3000

---

bentoml/_internal/frameworks/catboost.py
bentoml/_internal/frameworks/common/model_runner.py
bentoml/_internal/frameworks/detectron.py
bentoml/_internal/frameworks/easyocr.py
bentoml/_internal/frameworks/gluon.py
bentoml/_internal/frameworks/h2o.py
bentoml/_internal/frameworks/keras.py
bentoml/_internal/frameworks/lightgbm.py
bentoml/_internal/frameworks/mlflow.py
bentoml/_internal/frameworks/onnx.py
bentoml/_internal/frameworks/onnxmlir.py
bentoml/_internal/frameworks/paddle.py
bentoml/_internal/frameworks/picklable_model.py
bentoml/_internal/frameworks/pycaret.py
bentoml/_internal/frameworks/pytorch.py
bentoml/_internal/frameworks/pytorch_lightning.py
bentoml/_internal/frameworks/sklearn.py
bentoml/_internal/frameworks/spacy.py
bentoml/_internal/frameworks/statsmodels.py
bentoml/_internal/frameworks/tensorflow_v1.py
bentoml/_internal/frameworks/tensorflow_v2.py
bentoml/_internal/frameworks/torchscript.py
bentoml/_internal/frameworks/transformers.py
bentoml/_internal/frameworks/xgboost.py

This PR fixed an issue introduced in the last 1.0.0a5 release, where packaged models can not load properly when running in a docker container. This PR fixes that issue.
Fixes https://github.com/bentoml/BentoML/issues/2335

hotfix: model not found issue in docker run 

---

bentoml/_internal/cli/bento_management.py
bentoml/_internal/cli/model_management.py

docs(cli): clean up cli docstrings

---

bentoml/_internal/cli/yatai.py
bentoml/_internal/yatai_rest_api_client/config.py

fix: https://github.com/bentoml/BentoML/issues/2347

fix: YataiClientContext initialization missing email argument

---

bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/numpy.py
bentoml/_internal/runner/container.py
bentoml/_internal/utils/__init__.py

style: minor typing fixes

---

bentoml/_internal/store.py

fix error message when python version < 3.9
In python < 3.9, we cannot chain @classmethod and @property together. This is a simple fix to add better compatibility for older version of python.

fix: better error message in python < 3.9

---

bentoml/_internal/frameworks/catboost.py
bentoml/_internal/frameworks/detectron.py
bentoml/_internal/frameworks/easyocr.py
bentoml/_internal/frameworks/gluon.py
bentoml/_internal/frameworks/h2o.py
bentoml/_internal/frameworks/keras.py
bentoml/_internal/frameworks/lightgbm.py
bentoml/_internal/frameworks/mlflow.py
bentoml/_internal/frameworks/onnx.py
bentoml/_internal/frameworks/onnxmlir.py
bentoml/_internal/frameworks/paddle.py
bentoml/_internal/frameworks/picklable_model.py
bentoml/_internal/frameworks/pycaret.py
bentoml/_internal/frameworks/pytorch.py
bentoml/_internal/frameworks/pytorch_lightning.py
bentoml/_internal/frameworks/sklearn.py
bentoml/_internal/frameworks/spacy.py
bentoml/_internal/frameworks/statsmodels.py
bentoml/_internal/frameworks/tensorflow_v1.py
bentoml/_internal/frameworks/tensorflow_v2.py
bentoml/_internal/frameworks/torchscript.py
bentoml/_internal/frameworks/transformers.py
bentoml/_internal/frameworks/xgboost.py
bentoml/models.py

As a prelude to some changes which will freeze `Model` info after creation.

fix(frameworks): use bentoml.models.create instead of Model.create

---

bentoml/_internal/bento/bento.py
bentoml/_internal/server/__init__.py
bentoml/_internal/server/cli/api_server.py
bentoml/_internal/server/cli/dev_api_server.py
bentoml/_internal/server/cli/runner.py
bentoml/_internal/service/loader.py

fixes: https://github.com/bentoml/BentoML/issues/2263
changing global working directory is a necessary side effect for BentoML service load, however when interactively debugging service code using `bentoml.load`, this behavior can be confusing. This PR makes it an optional behavior that is only triggered when `change_global_cwd=True`.

fix: add change_global_cwd params to bentoml.load

---

bentoml/saved_bundle/bundler.py

… if uploading to a remote location, we do not upload the zip imports because it happens after the call to _upload_file_to_remote_path
Reported that zipimports are not uploaded when uploading to a remote location, it seems that because we move the zip imports after we call "_upload_file_to_remote_path" in the case where we are uploading to a remote location, the zip imports are not uploaded

fix: zip imports while upload to remotes

---

bentoml/_internal/frameworks/catboost.py
bentoml/_internal/frameworks/common/pytorch.py
bentoml/_internal/frameworks/h2o.py
bentoml/_internal/frameworks/onnx.py
bentoml/_internal/frameworks/paddle.py
bentoml/_internal/frameworks/picklable_model.py
bentoml/_internal/frameworks/sklearn.py
bentoml/_internal/frameworks/statsmodels.py
bentoml/_internal/frameworks/tensorflow_v1.py
bentoml/_internal/frameworks/tensorflow_v2.py
bentoml/_internal/frameworks/xgboost.py
bentoml/_internal/runner/runner.py
bentoml/_internal/runner/utils.py
tests/integration/frameworks/test_catboost_impl.py

- address #2371 
For all value calculated from `cfs_quota_us`, if between 0 and 1 then we will always return 0. We should also check `cpusets.cpus` to get the number of CPUs set for a given container. This should make CPU count on kubernetes consistent with what we have when reading in a docker container.

fix: cgroups for cpu should be 1 when <= 0

---

setup.cfg

Lock Rich version to be >=11.2.0

chore: lock rich to be >=11.2.0

---

setup.cfg

recent updates with the usage tracking PR brings attention to cleanup 3.6 from
our support list.

chore: cleanup 3.6 metadata

---

setup.cfg

fix: not lock typing_extensions to fix rich and pytorch lightning requirements

---

bentoml/_internal/cli/bento_management.py
bentoml/_internal/cli/model_management.py

Fixed an issue where deleting with `latest` tag does not work: `bentoml delete iris_classifier:latest`

bug: fix CLI command delete with latest tag

---

bentoml/_internal/cli/bento_management.py
bentoml/_internal/cli/model_management.py
bentoml/_internal/utils/__init__.py

* move path to the last column in the list output
* shorten full path with leading `~` indicating home directory
* fixed issue `-o yaml` option, introduced in a previous PR

feat: improve list CLI command output

---

bentoml/_internal/yatai_client/__init__.py

fix: update yatai client to work with BentoInfo changes

---

bentoml/_internal/server/metrics/prometheus.py

fix(server): duplicate metrics

---

bentoml/_internal/server/cli/api_server.py

chore(server): pass runner map through envvar

---

bentoml/_internal/server/__init__.py
bentoml/_internal/server/cli/api_server.py

fix(server): init prometheus dir for standalone running

---

bentoml/_internal/cli/click_utils.py

fix(#2316): --quiet should set logger level

---

bentoml/_internal/bento/bento.py
bentoml/_internal/cli/bento_management.py
bentoml/_internal/cli/bento_server.py
bentoml/_internal/service/loader.py

Allow users to run just `bentoml serve` from a project directory containing a `bentofile.yaml` build file. It will import the service using the "service" field in the `bentofile.yaml` by default. All existing load/serve behavior remain the same.

feat: allow serving from project dir using import str from bentofile.yaml

---

requirements/docs-requirements.txt

docs: fix readthedocs build issue

---

README.md

docs: update fossa license scan badge

---

bentoml/__init__.py
bentoml/_internal/context.py
bentoml/_internal/io_descriptors/base.py
bentoml/_internal/io_descriptors/file.py
bentoml/_internal/io_descriptors/image.py
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/multipart.py
bentoml/_internal/io_descriptors/numpy.py
bentoml/_internal/io_descriptors/pandas.py
bentoml/_internal/io_descriptors/text.py
bentoml/_internal/server/service_app.py
bentoml/_internal/service/inference_api.py
bentoml/_internal/types.py
bentoml/_internal/utils/formparser.py
bentoml/_internal/utils/http.py

Very WIP, context still needs to be merged with tracing context. Mostly for @bojiang to take a quick look at inference API implementation.

feat(internal): implement request contexts and check inference API types

---

bentoml/_internal/bento/bento.py
bentoml/_internal/bento/build_config.py
bentoml/_internal/models/model.py
bentoml/_internal/utils/analytics/schemas.py
bentoml/_internal/utils/analytics/usage_stats.py

I now have 20.1.0 in my env, so hopefully this shouldn't happen again.
We probably also want to start fixing the versions of our dependencies in the CI to the lowest ones we claim to support.
/cc @timliubentoml

fix: ensure compatibility with attrs 20.1.0

---

bentoml/_internal/io_descriptors/json.py
bentoml/_internal/runner/local.py
bentoml/_internal/runner/remote.py

fix(sdk): remote exception

---

bentoml/_internal/frameworks/common/pytorch.py
bentoml/_internal/frameworks/detectron.py
bentoml/_internal/frameworks/easyocr.py
bentoml/_internal/frameworks/gluon.py
bentoml/_internal/frameworks/lightgbm.py
bentoml/_internal/frameworks/onnx.py
bentoml/_internal/frameworks/paddle.py
bentoml/_internal/frameworks/spacy.py
bentoml/_internal/frameworks/tensorflow_v1.py
bentoml/_internal/frameworks/tensorflow_v2.py
bentoml/_internal/frameworks/xgboost.py
bentoml/_internal/runner/runner.py
bentoml/_internal/runner/utils.py
setup.cfg

chore(server): resource utils

---

bentoml/_internal/bento/build_config.py
bentoml/_internal/bento/docker.py

fix: consistent naming accross docker and build config

---

bentoml/_internal/runner/remote.py
bentoml/_internal/runner/resource.py
bentoml/_internal/runner/runnable.py
bentoml/_internal/runner/runner.py
bentoml/_internal/runner/strategy.py
bentoml/_internal/server/schedule_strategy.py

refactor: runner/runnable interface

---

bentoml/__init__.py
bentoml/_internal/models/model.py
bentoml/_internal/runner/__init__.py
bentoml/_internal/runner/resource.py
bentoml/_internal/runner/runner.py
bentoml/_internal/runner/utils.py
bentoml/_internal/service/service.py

runner refactor: Model to_runner/to_runnable interface

---

bentoml/_internal/runner/resource.py
bentoml/_internal/runner/runner.py

Runner Resources implementation

---

bentoml/_internal/runner/runner_handle/local.py

fix(runner): async run

---

bentoml/_internal/runner/runner.py
bentoml/_internal/server/runner_app.py

refactor: runner app

---

bentoml/_internal/runner/container.py

refactor: datacontainer api changes with ndarray draft

---

bentoml/_internal/runner/resource.py

To suppress the warning message from the high level pynvml API

chore(runner): use low level nvml API

---

bentoml/_internal/runner/container.py
bentoml/_internal/runner/runner_handle/remote.py
bentoml/_internal/runner/utils.py
bentoml/_internal/server/runner_app.py

Somehow I failed to test `--production` 🤦

fix(server): fix container in runner app IPC

---

bentoml/_internal/runner/container.py
bentoml/_internal/runner/strategy.py
bentoml/_internal/server/__init__.py
bentoml/_internal/server/cli/runner.py
bentoml/_internal/server/runner_app.py

feat(runner): scheduling strategy

---

bentoml/_internal/utils/analytics/cli_events.py
bentoml/_internal/utils/analytics/schemas.py
bentoml/_internal/utils/analytics/usage_stats.py

Fix: attribute error runner_type in bento serve

---

bentoml/_internal/runner/container.py

refactor(runner): update Pandas and Default DataContainer

---

bentoml/_internal/exportable.py
bentoml/_internal/models/model.py
bentoml/_internal/runner/resource.py
bentoml/_internal/store.py
bentoml/models.py

Didn't bother separating out some actual changes:
- new docs for `ModelSignature`
- removed `flushed` from `Model` and added a manual flush call inside of `bentoml.models.create`
We should probably start documenting the methods of `Model` now that at least some of them are user-facing.

chore(internal): fix typing

---

bentoml/_internal/bento/bento.py
bentoml/_internal/bento/build_config.py
bentoml/_internal/cli/model_management.py
bentoml/_internal/models/model.py
bentoml/_internal/runner/resource.py
bentoml/_internal/runner/runnable.py
bentoml/_internal/types.py
bentoml/_internal/utils/cattr.py
bentoml/_internal/yatai_client/__init__.py
bentoml/models.py
setup.cfg
tests/conftest.py
tests/unit/_internal/bento/test_bento.py
tests/unit/_internal/models/test_model.py
tests/unit/test_models.py

tests: fix runner1.0 branch unit tests

---

bentoml/_internal/frameworks/FRAMEWORK_TEMPLATE_PY
bentoml/_internal/frameworks/sklearn.py

Current codes will break a runnable if the model has multiple methods
see: https://stackoverflow.com/questions/8946868/is-there-a-pythonic-way-to-close-over-a-loop-variable

fix(framework): fix Runnable closing over loop variable bug

---

bentoml/_internal/bento/bento.py
bentoml/_internal/cli/bento_management.py
bentoml/_internal/cli/model_management.py
bentoml/_internal/exportable.py
bentoml/_internal/models/model.py
bentoml/_internal/runner/runnable.py
bentoml/_internal/runner/runner.py
bentoml/models.py

chore: fix types

---

bentoml/_internal/bento/bento.py
bentoml/_internal/models/model.py

chore: make ModelInfo yaml backwards compatible

---

bentoml/_internal/runner/runnable.py
bentoml/_internal/runner/runner_handle/local.py
bentoml/_internal/server/runner_app.py

Now properly deals with edge cases, I think... I want to factor this out into its own module so we can reuse it, I think that would make sense. (Also we could write unit tests for the logic...)

fix(runner): fix bugs in runner batching

---

.readthedocs.yml
bentoml/_internal/models/model.py
requirements/docs-requirements.txt

chore: add furo to docs-requirements.txt

---

bentoml/_internal/frameworks/picklable.py
bentoml/_internal/io_descriptors/file.py
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/models/model.py
bentoml/_internal/runner/runner_handle/__init__.py
bentoml/_internal/runner/runner_handle/local.py
bentoml/_internal/runner/runner_handle/remote.py
bentoml/picklable_model.py
bentoml/testing/server.py
tests/e2e/bento_server_general_features/pickle_model.py
tests/e2e/bento_server_general_features/service.py
tests/e2e/bento_server_general_features/tests/test_io.py
tests/e2e/bento_server_general_features/train.py
tests/e2e/bento_server_general_features_sync/tests/test_io.py

feat(ci): re-enable e2e tests

---

.github/workflows/ci.yml
.github/workflows/frameworks.yml

add runners-1.0 to CI for development.

chore: add runners-1.0 to CI

---

bentoml/_internal/frameworks/xgboost.py
bentoml/_internal/utils/cattr.py
docs/source/frameworks/xgboost.rst

docs: update for xgboost doc

---

bentoml/frameworks/onnx.py

Added provider option when creating onnxruntime session.
When you get an instance of onnx framework, you need to add a provider.
- Changed __init__ function
- Changed _get_onnx_inference_session function
- Bento service example code, add providers

fix: onnx framework added provider

---

bentoml/_internal/runner/container.py
tests/unit/_internal/runner/container.py

test(runner): update DataContainer tests

---

bentoml/_internal/cli/containerize.py
bentoml/_internal/frameworks/xgboost.py
bentoml/_internal/io_descriptors/file.py
bentoml/_internal/models/model.py
bentoml/_internal/utils/buildx.py
bentoml/bentos.py
docs/source/conf.py
tests/e2e/bento_server_general_features/train.py

- feat: add buildx interface
- feat: expose docker options to bentoml containerize
To help with the new docker revamp, also expose buildx options through bentoml
containerize

feat: buildx backend for `bentoml containerize`

---

bentoml/_internal/frameworks/picklable.py
bentoml/_internal/frameworks/sklearn.py
bentoml/_internal/models/model.py
bentoml/_internal/runner/container.py
bentoml/_internal/runner/runnable.py
bentoml/_internal/runner/runner.py
bentoml/_internal/runner/utils.py
bentoml/_internal/server/runner_app.py
bentoml/_internal/utils/http.py
bentoml/testing/server.py
requirements/dev-requirements.txt

refactor(runner): simplify batch dim

---

bentoml/_internal/runner/runner.py
bentoml/_internal/runner/runner_handle/remote.py

fix(runner): removing inspect

---

bentoml/_internal/configuration/containers.py
bentoml/_internal/configuration/default_configuration.yaml

fix(server): fix development_mode in the config

---

bentoml/_internal/runner/runner_handle/remote.py
bentoml/_internal/utils/buildx.py
bentoml/_internal/utils/click.py
bentoml/testing/server.py

fix(server): fix containerize subcommand

---

bentoml/_internal/models/model.py
tests/unit/_internal/models/test_model.py

We no longer support non-tuple batch_dim.

fix(tests): update model unit tests for new batch_dim type

---

bentoml/_internal/frameworks/transformers.py
bentoml/_internal/models/model.py
bentoml/transformers.py
docs/source/conf.py
scripts/ci/config.yml
tests/integration/frameworks/test_transformers_impl.py

feat: Transformers framework runner implementation 1.0

---

bentoml/_internal/frameworks/tensorflow_v2.py
bentoml/tensorflow.py
tests/integration/frameworks/test_tensorflow_v2_impl.py

Runners 1.0 tensorflow_v2 impl

---

.github/workflows/frameworks.yml
bentoml/_internal/frameworks/keras.py
bentoml/keras.py
tests/integration/frameworks/test_keras_impl.py

refactor(framework): update keras to runners-1.0 branch

---

bentoml/_internal/frameworks/FRAMEWORK_TEMPLATE_PY
bentoml/_internal/frameworks/keras.py
bentoml/_internal/frameworks/picklable.py
bentoml/_internal/frameworks/sklearn.py
bentoml/_internal/frameworks/tensorflow_v2.py
bentoml/_internal/frameworks/transformers.py
bentoml/_internal/frameworks/xgboost.py
bentoml/_internal/models/model.py
tests/conftest.py
tests/integration/frameworks/test_frameworks.py
tests/unit/_internal/models/test_model.py
tests/unit/test_models.py

feat(internal): add save_format_version for BentoML model

---

bentoml/_internal/frameworks/FRAMEWORK_TEMPLATE_PY
bentoml/_internal/frameworks/keras.py
bentoml/_internal/frameworks/picklable.py
bentoml/_internal/frameworks/sklearn.py
bentoml/_internal/frameworks/tensorflow_v2.py
bentoml/_internal/frameworks/transformers.py
bentoml/_internal/frameworks/xgboost.py
bentoml/_internal/models/model.py
tests/conftest.py
tests/integration/frameworks/test_frameworks.py
tests/unit/_internal/models/test_model.py
tests/unit/test_models.py

Revert "feat(internal): add save_format_version for BentoML model"

---

bentoml/_internal/frameworks/keras.py
bentoml/_internal/frameworks/tensorflow_v2.py
bentoml/_internal/frameworks/transformers.py

fix(framework): adapt changes for Tensorflow DataContainer

---

docs/source/concepts/bento.rst
docs/source/concepts/deploy.rst
docs/source/concepts/model.rst
docs/source/concepts/runner.rst
docs/source/guides/gpu.rst
docs/source/tutorial.rst

docs: misc docs updates

---

bentoml/_internal/frameworks/keras.py
bentoml/_internal/frameworks/tensorflow_v2.py
scripts/ci/config.yml
setup.cfg

moving `_mapping` function so it will be only defined when the runner method is defined.

refactor(framework): move `_mapping` for tf2 and keras

---

scripts/ci/run_tests.sh

fix: revert pining pip version for tests

---

README.md

docs: update readme installation --pre flag

---

.github/workflows/ci.yml

chore(ci): quit immediately for errors e2e tests

---

docs/source/guides/gpu.rst

docs: fix cuda_version string value 

---

bentoml/_internal/frameworks/keras.py
bentoml/_internal/frameworks/tensorflow_v2.py
docs/source/concepts/runner.rst

fix(framework): fix tf2 and keras class variable names

---

bentoml/_internal/utils/__init__.py
bentoml/testing/server.py
tests/e2e/bento_server_general_features/pickle_model.py
tests/e2e/bento_server_general_features/service.py
tests/e2e/bento_server_general_features/tests/conftest.py
tests/e2e/bento_server_general_features/tests/test_io.py
tests/e2e/bento_server_general_features/train.py

reuse images & bentos between test parameters

chore(ci): add more edge cases; boost e2e tests

---

bentoml/_internal/bento/docker/entrypoint.sh

fix(docker): remove backslash in comments

---

bentoml/_internal/runner/runner_handle/remote.py

currently our runner_app and remote runner handler does not agree with how to handle `__call__` method. We need to sync them for runners using `__call__` method
- https://github.com/bentoml/BentoML/blob/main/bentoml/_internal/server/runner_app.py#L101
- https://github.com/bentoml/BentoML/blob/main/bentoml/_internal/runner/runner_handle/remote.py#L151

fix(runner): sync remote runner uri schema with runner_app

---

bentoml/_internal/models/model.py

chore(sdk): allowed single int value as the batch_dim

---

bentoml/_internal/frameworks/FRAMEWORK_TEMPLATE_PY
bentoml/_internal/frameworks/keras.py
bentoml/_internal/frameworks/picklable.py
bentoml/_internal/frameworks/pytorch.py
bentoml/_internal/frameworks/sklearn.py
bentoml/_internal/frameworks/tensorflow_v2.py
bentoml/_internal/frameworks/torchscript.py
bentoml/_internal/frameworks/transformers.py
bentoml/_internal/frameworks/xgboost.py
bentoml/_internal/models/model.py
bentoml/models.py
tests/unit/_internal/models/test_model.py

chore(framework): Add api_version for current implemented frameworks

---

docs/source/guides/server.rst

relates to https://github.com/bentoml/BentoML/issues/2541

doc(server): remove unnecessary `svc.asgi` lines

---

.github/workflows/ci.yml
bentoml/_internal/server/instruments.py
tests/e2e/bento_server_general_features/requirements.txt
tests/e2e/bento_server_general_features/service.py
tests/e2e/bento_server_general_features/tests/test_meta.py

Commits on Jun 3, 2022
[chore(ci): test asgi app mounting](https://github.com/bentoml/BentoML/commit/66c0ed379164b09d4a0ca49208b076fa92e2476a)
@[bojiang](https://github.com/bentoml/BentoML/commits?author=bojiang)
bojiang committed 22 minutes ago
[chore(server): lazy load meters](https://github.com/bentoml/BentoML/commit/ed77c2f9d805b2ef7b0daa9722c2ce96895ed711)
@[bojiang](https://github.com/bentoml/BentoML/commits?author=bojiang)
bojiang committed 1 minute ago

chore(server): lazy load meters; cover asgi app mounting in e2e test

---

.github/workflows/frameworks.yml

chore(ci): skip unsupported frameworks for now

---

README.md
docs/source/index.rst

doc: fix github action CI badge link

---

docs/source/guides/server.rst

doc(server): fix header div

---

bentoml/_internal/server/metrics/prometheus.py
bentoml/_internal/utils/analytics/usage_stats.py

https://github.com/bentoml/BentoML/pull/2518

fix(metrics): filter out non-API endpoints in metrics

---

bentoml/_internal/server/static_content/swagger-initializer.js

Update swaggerUI config to remove the warning that says "Can't read from file http://0.0.0.0:3000/docs.json":

fix: Update SwaggerUI config

---

bentoml/_internal/server/service_app.py
bentoml/exceptions.py

fix(server): wrong status code format in metrics

---

bentoml/_internal/bento/build_config.py
bentoml/_internal/bento/docker.py
bentoml/_internal/bento/docker/entrypoint.sh
bentoml/_internal/bento/docker/templates/base.j2
bentoml/_internal/bento/docker/templates/miniconda_alpine.j2
bentoml/_internal/bento/docker/templates/miniconda_debian.j2
bentoml/_internal/bento/gen.py
setup.cfg

fix: path for custom dockerfile templates

---

bentoml/_internal/bento/bento.py
tests/unit/_internal/bento/test_bento.py

feat: include env build options in bento.yaml

---

bentoml/_internal/bento/build_config.py
bentoml/_internal/cli/bento_server.py
bentoml/_internal/server/__init__.py
docs/source/concepts/bento.rst
setup.cfg

chore: minor fixes and docs change from QA

---

bentoml/_internal/bento/build_config.py

fix(qa): allow cuda_version when distro is None with default

---

bentoml/_internal/runner/runner.py
bentoml/_internal/runner/strategy.py
bentoml/_internal/server/__init__.py
bentoml/_internal/server/runner_app.py

fix(qa): bento runner resource should limit to user provided configs

---

bentoml/_internal/cli/bento_management.py
bentoml/_internal/cli/model_management.py

feat(cli): output times in the local timezone

---

bentoml/_internal/io_descriptors/numpy.py

docs: fix wrong variable name in comment

---

bentoml/_internal/io_descriptors/json.py

fix(service): JsonIO doesn't return a pydantic model

---

bentoml/_internal/runner/runner.py
bentoml/_internal/server/__init__.py
bentoml/_internal/server/runner_app.py
tests/integration/frameworks/test_pytorch_impl.py
tests/integration/frameworks/test_sklearn_impl.py
tests/integration/frameworks/test_torchscript_impl.py

* reuse code
* should be useful for writing streaming udf from a runner

chore(runner): add shcedule shortcuts to runners

---

bentoml/_internal/frameworks/keras.py
bentoml/_internal/frameworks/tensorflow_v2.py
bentoml/_internal/frameworks/transformers.py
bentoml/_internal/models/model.py
bentoml/keras.py
bentoml/tensorflow.py
bentoml/transformers.py
tests/conftest.py
tests/integration/frameworks/test_transformers_impl.py
tests/unit/_internal/models/test_model.py
tests/unit/test_models.py

Make `model.with_options()` additive as opposed to overriding. Changed the `ModelOptions` from UserDict to an `attrs` class. Specific framework implementation can still provide a customized `FrameworkOptions(ModelOptions)` to type check and validate the options attributes.

fix(bug): Make `model.with_options()` additive

---

requirements/docs-requirements.txt

docs: add setuptools to docs dependencies

---

bentoml/_internal/runner/runnable.py
bentoml/_internal/runner/runner.py
bentoml/_internal/runner/runner_handle/local.py
docs/source/concepts/runner.rst

fix(runner): pass init params to runnable

---

bentoml/_internal/log.py

fix: propagate should be false

---

bentoml/_internal/server/runner_app.py

Remove starlette request log

---

docs/source/guides/streaming.rst

docs: Update streaming.rst

---

bentoml/_internal/log.py
bentoml/_internal/models/model.py
bentoml/_internal/yatai_client/__init__.py

bug: Fix Yatai client push bentos with model options

---

README.md
docs/source/concepts/deploy.rst
docs/source/conf.py
docs/source/index.rst
docs/source/tutorial.rst

docs: allow running tutorial from docker 

---

setup.cfg

fix(model): lock attrs to >=21.1.0

---

docs/source/concepts/bento.rst
docs/source/concepts/model.rst
docs/source/concepts/runner.rst
docs/source/guides/streaming.rst

docs: Fix documentation links and formats

---

bentoml/_internal/models/model.py
tests/integration/frameworks/test_frameworks.py

Also add a less opinionated base `ModelOptions`; that's not really necessary and I'm not actually sure I want it to exist. @ssheng thoughts?

fix(model): load ModelOptions lazily

---

bentoml/_internal/bento/build_config.py
bentoml/_internal/bento/gen.py

When `base_image` is used, user may run into the following error. This PR fixes this issue.
> Error: [cli] `build` failed: Invalid build option: docker.python_version="None", python version must follow standard python semver format, e.g. 3.7.10
Thank you @mqk for reporting the issue!
Notes: all fields in DockerOptions must be type `t.Optional`

fix: invalid build option python_version="None" when base_image is used

---

bentoml/_internal/frameworks/FRAMEWORK_TEMPLATE_PY
bentoml/_internal/frameworks/transformers.py
bentoml/_internal/frameworks/xgboost.py

As reported in https://github.com/bentoml/BentoML/issues/2620, Transformers accepts an integer device ID. The current implementation pass the value of NVIDIA_VISIBLE_DEVICES environment variable as device without converting to an integer.

fix: Transformers NVIDIA_VISIBLE_DEVICES value type casting

---

bentoml/_internal/frameworks/FRAMEWORK_TEMPLATE_PY
bentoml/_internal/frameworks/transformers.py
bentoml/_internal/frameworks/xgboost.py
tests/integration/frameworks/test_frameworks.py

fix(framework): some GPU related fixes

---

.github/workflows/ci.yml

chore: updates ci

---

bentoml/_internal/bento/docker/templates/base.j2
bentoml/_internal/bento/docker/templates/base_amazonlinux.j2
bentoml/_internal/bento/docker/templates/cuda_debian.j2
bentoml/_internal/bento/docker/templates/cuda_ubi8.j2
bentoml/_internal/bento/docker/templates/miniconda_alpine.j2
bentoml/_internal/bento/docker/templates/miniconda_debian.j2

fix(docker): templates bash heredoc should pass `-ex`

---

docs/source/concepts/model.rst

docs: missing code annotation

---

bentoml/_internal/frameworks/tensorflow_v2.py
bentoml/_internal/utils/tensorflow.py

fix(tensorflow): casting error on kwargs

---

.github/workflows/frameworks.yml
bentoml/_internal/frameworks/pytorch.py
scripts/ci/config.yml
tests/integration/frameworks/models/pytorch.py
tests/integration/frameworks/test_pytorch_impl.py
tests/integration/frameworks/test_pytorch_unit.py

test(frameworks): change pytorch test using test_frameworks

---

tests/integration/frameworks/test_frameworks.py

fix(tests): nvidia gpu resource specs should be str or int

---

.github/workflows/frameworks.yml
bentoml/_internal/frameworks/common/pytorch.py
bentoml/_internal/frameworks/pytorch_lightning.py
bentoml/_internal/frameworks/torchscript.py
scripts/ci/config.yml
tests/integration/frameworks/models/pytorch_lightning.py
tests/integration/frameworks/models/torchlightning.py
tests/integration/frameworks/models/torchscript.py

tests(framework): torchscript/pytorch_lightning

---

bentoml/models.py

Import model CLI use to show an redundant message about a new model being saved to the model store, it is now cleaner with just "Model(..) imported"
```
> bentoml models import ./iris_clf-tjj7vax2p2x4puqj.bentomodel
Model(tag="iris_clf:tjj7vax2p2x4puqj") imported
```

fix: improve import model output 

---

bentoml/_internal/frameworks/FRAMEWORK_TEMPLATE_PY
bentoml/_internal/frameworks/common/pytorch.py
bentoml/_internal/frameworks/keras.py
bentoml/_internal/frameworks/lightgbm.py
bentoml/_internal/frameworks/onnx.py
bentoml/_internal/frameworks/picklable.py
bentoml/_internal/frameworks/pytorch.py
bentoml/_internal/frameworks/pytorch_lightning.py
bentoml/_internal/frameworks/sklearn.py
bentoml/_internal/frameworks/tensorflow_v2.py
bentoml/_internal/frameworks/torchscript.py
bentoml/_internal/frameworks/transformers.py
bentoml/_internal/frameworks/xgboost.py

fix: improve missing dependency exception error message format

---

docs/source/concepts/bento.rst

docs: improve the bento build page setup_scripts section

---

docs/source/tutorial.rst

Made some minor edits to conform with English grammar.
When there are mistakes it adds time to comprehend what is being said.

style: Update tutorial.rst

---

bentoml/_internal/cli/bento_server.py
bentoml/_internal/configuration/containers.py
bentoml/_internal/frameworks/common/pytorch.py
bentoml/_internal/runner/container.py
bentoml/_internal/runner/runner_handle/remote.py
bentoml/_internal/server/__init__.py
bentoml/_internal/server/cli/api_server.py
bentoml/_internal/server/cli/ngrok.py
bentoml/_internal/server/cli/runner.py
bentoml/_internal/server/instruments.py
bentoml/_internal/server/runner_app.py
bentoml/_internal/server/service_app.py
bentoml/_internal/utils/analytics/usage_stats.py
bentoml/_internal/yatai_rest_api_client/config.py

refactor: di containers

---

README.md

chore: update readme according to latest logs change

---

bentoml/_internal/io_descriptors/image.py
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/multipart.py
bentoml/_internal/io_descriptors/numpy.py
bentoml/_internal/io_descriptors/pandas.py
bentoml/_internal/io_descriptors/text.py
bentoml/_internal/server/runner_app.py
docs/source/concepts/service.rst
docs/source/frameworks/lightgbm.rst
docs/source/frameworks/picklable.rst
docs/source/frameworks/pytorch.rst
docs/source/frameworks/pytorch_lightning.rst
docs/source/frameworks/sklearn.rst
docs/source/frameworks/tensorflow.rst
docs/source/frameworks/transformers.rst
tests/unit/_internal/bento/simplebento/simplebento.py

fix(doc): deprecated APIs & the IO list

---

bentoml/_internal/bento/bento.py
bentoml/_internal/bento/build_config.py
bentoml/_internal/cli/__init__.py
bentoml/_internal/models/model.py
bentoml/_internal/tag.py
bentoml/_internal/types.py
bentoml/_internal/utils/cattr.py
bentoml/_internal/utils/pkg.py
requirements/dev-requirements.txt
setup.cfg

This should be compatible with current GenConverter.
address #2684

refactor: move from Converter to GenConverter

---

bentoml/_internal/service/loader.py

fix(service): patch the model_store rather than set/reset

---

docs/source/frameworks/fastai.rst
docs/source/guides/containerization.rst

Some minor formatting for docs that I thought I already changed at the first PR

fix: some minor docs format

---

bentoml/_internal/frameworks/transformers.py
docs/source/frameworks/transformers.rst
docs/source/index.rst
docs/source/reference/frameworks/index.rst
docs/source/reference/frameworks/transformers.rst

docs: Add Hugging Face Transformers framework guide

---

bentoml/_internal/frameworks/onnx.py
docs/source/frameworks/index.rst
docs/source/frameworks/onnx.rst
docs/source/reference/frameworks/index.rst
docs/source/reference/frameworks/onnx.rst

docs(framework): ONNX guide

---

bentoml/_internal/bento/docker/templates/base.j2

It's common for user's setup script to download files in the "user"'s home directory, here's an example with the NLTK custom runner example: https://github.com/bentoml/gallery/pull/136/files#diff-2ab6e592645153e012e4d282fdf21b410441cb78081cdfbbb1e56730bab71bf3R8
Prior to this change, user need to modify code and figure out where to write or load the data files, which can be very complicated process from user perspective. But everything just works if we run the setup_script with `USER bentoml`, where user service code will be executed with

fix: setup_script should run with `USER bentoml`

---

bentoml/_internal/bento/docker/templates/base.j2

Revert HOME changes by @parano

revert: HOME changes

---

docs/source/concepts/bento.rst

Fixes some current documentation format
cc @ssheng @sauyon

fix: containerization docs format

---

bentoml/_internal/models/model.py
bentoml/_internal/runner/runner.py
docs/source/concepts/runner.rst

adding one API for `bentoml.Model.load_model` to initialize the model object.
This would fix some of the current bug

docs: custom runner usage

---

bentoml/_internal/bento/bento.py
bentoml/_internal/runner/runner.py
bentoml/_internal/server/__init__.py
bentoml/_internal/server/cli/api_server.py
bentoml/_internal/server/cli/dev_api_server.py
bentoml/_internal/server/cli/runner.py
bentoml/_internal/service/loader.py
bentoml/_internal/service/service.py

Attempt to address the same issue as https://github.com/bentoml/BentoML/pull/2726

Add standalone_load option 

---

DEVELOPMENT.md
README.md
bentoml/bentos.py
docs/source/guides/migration.rst
docs/source/index.rst
docs/source/installation.rst
docs/source/tutorial.rst

#2729. Since bentoml docker doesn't include git by default.

chore: remove all `--pre` from documentation

---

docs/source/frameworks/onnx.rst

chore(framework): onnx guide minor improvements

---

bentoml/_internal/io_descriptors/numpy.py

Readded the `from grpc request` and `to_grpc_response` methods for io_descriptor NumpyNdarray. Fixed imports of generated pb2 files. Due to changes in `io_descriptor.proto`, some changes are made to use `Array` message instead of the old `NumpyNdarray` message.
Feel free to suggest changes @aarnphm

chore: rename protobuf message for Array repr

---

setup.cfg

Fixes #2757 
guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a pull request. :orange_circle: `TODO`
those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation). `NA`

chore(deps): `cattrs>=22.1.0` in setup.cfg

---

setup.py

Previous `setup.py` was not generating protobuf stubs properly for windows. This issue is now fixed.
@aarnphm Thanks for the fix!

fix: protobuf generation on windows

---

bentoml/_internal/cli/bento_server.py
bentoml/_internal/server/__init__.py
bentoml/_internal/server/cli/grpc_dev_api_server.py
bentoml/_internal/service/service.py
hooks/pre-commit
requirements/tests-requirements.txt
scripts/tools/formatter.sh
setup.cfg

Spawn a grpc dev server with command `bentoml serve --grpc`. Default port is 3000 which is the same as uvicorn. Users can specify the port using `--port <number goes here>`.  The async grpc server is started based on the following:
https://github.com/grpc/grpc/blob/master/examples/python/helloworld/async_greeter_server_with_graceful_shutdown.py 
@aarnphm @sauyon @ssheng Looking forward to your …

feat(dev-server): `--grpc`

---

SECURITY.md

docs: fix typo in SECURITY.md

---

bentoml/_internal/server/__init__.py
bentoml/_internal/server/cli/api_server.py
bentoml/_internal/server/cli/dev_api_server.py

P2
We could not launch multiple server instances by the same project/bento, because there would be a contest about Prometheus db files. But for now it gets fixed

chore: more robust prometheus directory ensuring

---

bentoml/_internal/yatai_rest_api_client/schemas.py
requirements/dev-requirements.txt
requirements/tests-requirements.txt
setup.cfg

Cleaned up unused and barely-used dependencies.

chore: clean up dependencies

---

setup.py

chore: Patch LTS with security update

---

bentoml/adapters/annotated_image_input.py
bentoml/adapters/image_input.py
bentoml/adapters/multi_image_input.py
setup.py

Fixes #2416
If i run `make format` it will just reformat a lot of files :)
cc @ssheng @parano

chore: lock imageio<=2.9.0 to address #2416

---

bentoml/_internal/io_descriptors/image.py
bentoml/_internal/io_descriptors/multipart.py
bentoml/_internal/io_descriptors/pandas.py

This should fix the multipart issue discovered with #2772.

fix(io descriptors): finish removing init_http_response

---

bentoml/_internal/io_descriptors/base.py
bentoml/_internal/io_descriptors/file.py
bentoml/_internal/io_descriptors/image.py
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/multipart.py
bentoml/_internal/io_descriptors/numpy.py
bentoml/_internal/io_descriptors/pandas.py
bentoml/_internal/io_descriptors/text.py
pyproject.toml
setup.cfg

initialize abstract methods for IO descriptors for gRPC supports.

chore: init correct io_descriptors abstract methods

---

docs/source/concepts/bento.rst

chore: fix typo

---

bentoml/_internal/models/model.py
tests/unit/_internal/models/test_model.py

feat(model): allow custom model versions

---

bentoml/_internal/server/__init__.py
bentoml/_internal/utils/circus/watchfilesplugin.py
setup.cfg

add watchfiles as bentoml dependencies

chore: add watchfiles as bentoml dependency

---

bentoml/_internal/frameworks/keras.py
docs/source/frameworks/keras.rst
docs/source/reference/frameworks/index.rst
docs/source/reference/frameworks/keras.rst

doc(framework): keras guide

---

docs/source/frameworks/catboost.rst
docs/source/frameworks/fastai.rst
docs/source/frameworks/keras.rst
docs/source/frameworks/onnx.rst
docs/source/frameworks/xgboost.rst

doc(frameworks): fix pip package syntax

---

bentoml/_internal/runner/strategy.py

Set RAYON_RS_NUM_CPUS for huggingface tokenizer num of threads, see
* https://github.com/huggingface/tokenizers/blob/28cd3dce2a75d106572392194ff2564574c33235/tokenizers/src/lib.rs#L114-L119
* https://docs.rs/rayon/0.7.1/rayon/struct.Configuration.html

feat: add additional env var configuring num of threads in Runner

---

bentoml/_internal/bento/docker/templates/base_debian.j2

Fixes #2784
Before we are using a shared variables from `base_debian.j2`. However, this variables before only available at the block level, not the template level.
This PR address that
cc @parano

fix(templates): sharing variables at template level

---

.gitattributes
DEVELOPMENT.md
bentoml/_internal/cli/bento_server.py
bentoml/_internal/configuration/containers.py
bentoml/_internal/configuration/default_configuration.yaml
hooks/pre-commit
scripts/ci/style/proto_check.sh
scripts/tools/formatter.sh
scripts/tools/linter.sh

- chore: initialize grpc configuration fields
- chore: cleanup formatter and linter scripts
rebase from #2779
cc @Proto007

chore: initialize grpc configuration

---

bentoml/_internal/io_descriptors/base.py
bentoml/_internal/io_descriptors/file.py
bentoml/_internal/io_descriptors/image.py
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/multipart.py
bentoml/_internal/io_descriptors/numpy.py
bentoml/_internal/io_descriptors/pandas.py
bentoml/_internal/io_descriptors/text.py

chore: add context to grpc abstract methods

---

bentoml/_internal/service/loader.py

For example, if a user's service code imported a module that they forgot to install, or if there's a typo in their code.
Before this PR, the error message is hidden away in lots of irrelevant text:
With this change, the error message is a lot more clear:

chore: improve error message when failed importing user service code

---

bentoml/_internal/frameworks/common/pytorch.py

cc https://bentoml.slack.com/archives/CKRANBHPH/p1658419198487199
``` bash
Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
```
Currently, [`from_payload`](https://github.com/bentoml/BentoML/blob/main/bentoml/_internal/frameworks/common/pytorch.py#L176) doesn't respect or running inside `torch.no_grad()`,
hence, the issue mentioned from slack.
those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting …

fix(datacontainer): pytorch to_payload should disable gradient

---

bentoml/_internal/frameworks/keras.py

When handling multi input, we should treat single input separately with multiple input. We used to put all inputs in a list for multi input support, but for some edge case this not works for a single input.

fix(framework): fix keras single input edge case

---

bentoml/_internal/bento/build_dev_bentoml_whl.py
bentoml/_internal/io_descriptors/text.py
bentoml/_internal/server/grpc/interceptors/__init__.py
bentoml/_internal/server/grpc/interceptors/access.py
bentoml/_internal/server/grpc/interceptors/access_log.py
bentoml/_internal/server/grpc_app.py
bentoml/_internal/utils/grpc/__init__.py
setup.cfg

Added access log interceptor for grpc with trace and span. Sample output:
```
2022-07-27T12:34:21-0400 [INFO] [grpc_dev_api_server] ipv6:[::1]:53866 (api_name=numpy_test,type=array,size=11) (status=0,type=array,size=11) 0.007ms (trace=62596654224895953649071701753620790238,span=8538425674779274945,sampled=0)
```
Implemented `from_grpc_request` and `to_grpc_response` for io_descriptor `text.py`. …

feat: added grpc access log

---

bentoml/_internal/frameworks/keras.py
tests/integration/frameworks/models/keras_tf2.py

fix(framework): keras GPU handling

---

docs/source/guides/server.rst

* Added section about usage of the `route` parameter in `api` decorated
* updated example code for mount_asgi/wsgi_apps with the latest examples here: https://github.com/bentoml/gallery/pull/148

docs: update custom bentoserver guide 

---

bentoml/_internal/runner/runner_handle/local.py

fix(runner): bind limiter to runner_ref instead

---

bentoml/_internal/frameworks/common/pytorch.py

fix(pytorch): inference_mode context is a thead local

---

bentoml/_internal/cli/containerize.py
bentoml/_internal/utils/buildx.py
bentoml/_internal/utils/docker.py
bentoml/bentos.py

fix: address multiple tags for containerize

---

docs/source/guides/security.rst

I was trying to implement a secured endpoint using JWT according to the BentoML official documentation and I was getting an error saying that the `secret` argument doesn't exist in:
`svc.add_asgi_middleware(SessionMiddleware, secret='my secret')`
After searching for the middleware implementation in the official [starlette authlib repository](https://github.com/aogier/starlette-authlib), I saw that the starlette team had used `secret_key` instead of `secret`. I changed it in my code to:
`svc.add_asgi_middleware(SessionMiddleware, secret_key='my secret')`
And then it worked properly.
I've updated this in the official BentoML security guide.
guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-reques …

docs: update security auth middleware

---

bentoml/_internal/io_descriptors/pandas.py

Pandas Dataframe creation raises an exception if the number of rows matches the number of rows expected. This is contrary to expected logic as well as the already written language of the exception.

fix(io_descriptor): DataFrame columns check

---

bentoml/_internal/cli/containerize.py
bentoml/_internal/utils/buildx.py
bentoml/_internal/utils/docker.py
bentoml/bentos.py

This reverts commit 4171eb89f5f4812767ba7ad4fd1b9337392dcd9f.
```
return __callback(*args, **kwargs)
File "/Users/ssheng/opt/anaconda3/envs/bentoml/lib/python3.9/site-packages/bentoml/_internal/cli/click_utils.py", line 167, in wrapper
return func(*args, **kwargs)
File "/Users/ssheng/opt/anaconda3/envs/bentoml/lib/python3.9/site-packages/bentoml/_internal/cli/click_utils.py", line 139, in wrapper
return_value = func(*args, **kwargs)
File "/Users/ssheng/opt/anaconda3/envs/bentoml/lib/python3.9/site-packages/bentoml/_internal/cli/click_utils.py", line 101, in wrapper
return func(*args, **kwargs)
File "/Users/ssheng/opt/anaconda3/envs/bentoml/lib/python3.9/site-packages/bentoml/_internal/utils/__init__.py", line 86, in wrapper
return func(*args, **{k: transformer(v) for k, v in …
```

revert: "fix: address multiple tags for containerize (#2797)"

---

bentoml/_internal/bento/build_dev_bentoml_whl.py
bentoml/_internal/io_descriptors/numpy.py
bentoml/_internal/server/grpc/__init__.py
bentoml/_internal/server/grpc/interceptors/__init__.py
bentoml/_internal/server/grpc/interceptors/opentelemetry.py
bentoml/_internal/server/grpc/interceptors/trace.py
bentoml/_internal/server/grpc/server.py
bentoml/_internal/server/grpc/servicer.py
bentoml/_internal/server/grpc/types.py
bentoml/_internal/server/grpc_app.py
bentoml/_internal/utils/grpc/__init__.py
bentoml/_internal/utils/grpc/codec.py
bentoml/grpc/v1/service.proto

fix: logging should also be included for exception
cc @Proto007

feat: adding OpenTelemetry interceptor

---

docs/source/concepts/bento.rst

For system that install docker without Docker Desktop, BuildKit might not be
available by default.
Added docs for that 🤗.

docs: update notice about buildkit

---

docs/source/frameworks/tensorflow.rst
docs/source/guides/containerization.rst
docs/source/guides/gpu.rst
docs/source/installation.rst
docs/source/reference/frameworks/tensorflow.rst

doc(frameworks): tensorflow

---

bentoml/_internal/io_descriptors/text.py
bentoml/_internal/server/grpc/interceptors/__init__.py
bentoml/_internal/server/grpc/interceptors/prometheus.py
bentoml/_internal/server/grpc_app.py
bentoml/_internal/service/service.py

The current implementation creates an http server in a reserved port where the metrics can be accessed.

feat(grpc): Prometheus interceptors

---

bentoml/__init__.py
bentoml/_internal/context.py
docs/source/concepts/service.rst

When customizing the response context, `status_code` and `cookies` currently must be set together. If only one of the two is set, an `AttributeError` is raised.
```
2022-08-03T02:46:27-0700 [ERROR] [dev_api_server] Exception on /classify [POST] (trace=223757535694722150591774830096001335825,span=17137919863646420089,sampled=0)
File "/Users/ssheng/github/BentoML/bentoml/_internal/server/service_app.py", line 314, in api_func
response = await api.output.to_http_response(output, ctx)
File "/Users/ssheng/github/BentoML/bentoml/_internal/io_descriptors/numpy.py", line 249, in to_http_response
set_cookies(res, ctx.response.cookies)
AttributeError: cookies
```
Added documentation to service page to explain the inference context usage.
Duplicate of …

fix: Setting status code and cookies

---

README.md

chore: README typo

---

bentoml/_internal/frameworks/common/pytorch.py
bentoml/_internal/runner/runner_handle/remote.py
bentoml/_internal/runner/utils.py
bentoml/_internal/server/runner_app.py
tests/integration/frameworks/test_frameworks.py

- use: pickle for runner i/o
- fix: faster
- chore: updates changes
Tries to address #2267 where this has to do with multipart serialization. We were dumbfounded about the actual performance deficit on this topic and found out the the majority of overhead lies within `python-multipart` libraries themselves. 
We will share more bout our findings separately.

fix(runner): use pickle instead for multi payload parameters

---

bentoml/_internal/cli/bento_server.py
bentoml/_internal/configuration/containers.py
bentoml/_internal/configuration/default_configuration.yaml
bentoml/_internal/server/__init__.py
bentoml/_internal/server/cli/grpc_api_server.py
bentoml/_internal/server/cli/grpc_dev_api_server.py
bentoml/_internal/server/grpc/server.py
bentoml/_internal/server/grpc_app.py
bentoml/_internal/service/service.py

this PR also address adding generic handlers from users if they want to add it
```
svc.add_generic_handlers(MyGrpcHandler(...))
```
address prometheus in a following PR.

feat(grpc): --production

---

docs/source/frameworks/pytorch.rst

doc(framework): pytorch guide

---

docs/source/concepts/runner.rst

- docs: runner.rst
I think this is a mistake in the docs as I got the following error: `TypeError: Service.api() missing 1 required positional argument: 'output'`
- @parano
- @yubozhao
- @bojiang

docs: add missing `output` to Runner docs

---

.readthedocs.yml
bentoml/_internal/bento/build_dev_bentoml_whl.py
bentoml/_internal/io_descriptors/text.py
pyproject.toml
requirements/docs-requirements.txt

fix(grpc): readthedocs build

---

bentoml/_internal/bento/build_config.py
bentoml/_internal/bento/docker/templates/base.j2
tests/unit/_internal/bento/test_bento.py

feat: add --grpc for containerized bento

---

bentoml/yatai/web/client/package.json
bentoml/yatai/web/package.json

chore: patching security for yarn modules

---

bentoml/_internal/cli/containerize.py

Fixes `--push` and `--load` interop. Either one should only be specified.
Previously if `bentoml containerize --push` is invoked, `--load` will also be
set. This PR fixes that.
TODO:
- testing

chore: fix push and load interop

---

README.md
bentoml/_internal/utils/analytics/usage_stats.py

Fixes https://github.com/bentoml/Kitchen/issues/17

fix: Usage stats

---

bentoml/_internal/io_descriptors/json.py
tests/unit/_internal/io/test_json.py

Address comments in https://github.com/bentoml/BentoML/pull/2874.

chore: Address comments in the #2874

---

MANIFEST.in
bentoml/_internal/bento/build_config.py
bentoml/_internal/bento/build_dev_bentoml_whl.py
bentoml/_internal/bento/docker/templates/base.j2
bentoml/_internal/configuration/containers.py
bentoml/_internal/configuration/default_configuration.yaml
bentoml/_internal/external_typing/__init__.py
bentoml/_internal/server/grpc/interceptors/__init__.py
bentoml/_internal/server/grpc/interceptors/access.py
bentoml/_internal/server/grpc/interceptors/opentelemetry.py
bentoml/_internal/server/grpc/interceptors/prometheus.py
bentoml/_internal/server/grpc/server.py
bentoml/_internal/server/grpc_app.py
bentoml/_internal/server/http/access.py
bentoml/_internal/server/http/instruments.py
bentoml/_internal/server/http_app.py
bentoml/_internal/server/metrics/prometheus.py
bentoml/_internal/server/runner_app.py
bentoml/_internal/service/service.py
bentoml/serve.py
bentoml_cli/server/grpc_api_server.py
bentoml_cli/server/grpc_dev_api_server.py
bentoml_cli/server/grpc_prometheus_server.py
bentoml_cli/server/http_api_server.py
bentoml_cli/server/http_dev_api_server.py
bentoml_cli/utils.py
scripts/release_pypi.sh
scripts/release_quickstart_image.sh
setup.cfg
setup.py

fix --production to be able to run with grpc.
depends on #2867 

fix: --production

---

scripts/release_quickstart_bento.sh
scripts/release_quickstart_image.sh

The quickstart Bento is used in bentoctl docs for users to quick test out the deployment process without them going through the quickstart code and building a bento themselves. This script will be part of the bentoml release process for creating a new bento and exporting it to BentoML's public s3 bucket.
Fixes #(issue)

chore: script for releasing quickstart bento

---

bentoml/_internal/yatai_client/__init__.py

fix: pushing models from Bento instead of local modelstore

---

bentoml/serve.py

Added logged instructions to use gRPC UI using the official gRPC UI docker image. Link to the docker image:
https://hub.docker.com/r/fullstorydev/grpcui
@aarnphm any feedback is appreciated as always.

feat: `gRPCUI` instruction

---

bentoml/_internal/bento/docker/templates/base_debian.j2

Cleanup debian installation logics

chore(templates): cleanup debian dependency logic

---

bentoml_cli/cli.py

Add figlet to CLI help message

chore(cli): add figlet for CLI

---

bentoml/_internal/bento/build_dev_bentoml_whl.py
bentoml/_internal/io_descriptors/base.py
bentoml/_internal/io_descriptors/file.py
bentoml/_internal/io_descriptors/image.py
bentoml/_internal/io_descriptors/json.py
bentoml/_internal/io_descriptors/multipart.py
bentoml/_internal/io_descriptors/numpy.py
bentoml/_internal/io_descriptors/pandas.py
bentoml/_internal/io_descriptors/text.py
bentoml/_internal/server/grpc/servicer.py
bentoml/grpc/types.py
bentoml/grpc/utils/__init__.py
bentoml/grpc/v1/service.proto
bentoml/grpc/v1/service_test.proto
pyproject.toml

- revert(types): pyright unstrict
- fix: numpy logics with validate_array

fix: cleanup io logics

---

bentoml/_internal/bento/bento.py
bentoml/_internal/bento/build_config.py
bentoml/_internal/bento/build_dev_bentoml_whl.py
bentoml/_internal/bento/docker.py
bentoml/_internal/bento/docker/templates/base.j2
bentoml/_internal/bento/gen.py
bentoml/bentos.py
bentoml/serve.py
bentoml_cli/serve.py
pyproject.toml
requirements/docs-requirements.txt
requirements/tests-requirements.txt
scripts/generate-grpc-stubs
setup.cfg
tests/unit/_internal/bento/test_bento.py

update logs instruction when running inside docker container
specifying build options via `python`:
```yaml
python:
extras_require:
- tracing
- grpc
```

feat(build_config): extras_require

---

bentoml/_internal/io_descriptors/pandas.py
bentoml/grpc/utils/mapping.py

Added implementation for `from_grpc_request` and `to_grpc_response` for dataframe `io_descriptor`.
@aarnphm @sauyon @ssheng  Feel free to suggest any changes.

feat(io): `pd.DataFrame`

---

bentoml/yatai/web/package.json
protos/Dockerfile

patch: 0.13 security

---

bentoml/_internal/server/static_content/index.css

revert: unminify CSS

---

README.md
bentoml/_internal/service/service.py

chore: update README messaging

---

docs/source/concepts/runner.rst

Add documentation for runner configuration for batching, resource allocation, access logs, and timeout.

docs: Runner configuration for batching and resource allocation

---

bentoml_cli/worker/http_api_server.py
bentoml_cli/worker/http_dev_api_server.py
bentoml_cli/worker/runner.py

Fix component name in access log (extra `:`).
Before:
```
2022-08-25T23:18:03-0700 [INFO] [:runner:iris_clf:1] _ (scheme=http,method=POST,path=/predict,type=application/octet-stream,length=511) (status=200,type=application/vnd.bentoml.NdarrayContainer,length=179) 1.512ms (trace=278659486253167754913431204277364461501,span=12276199527631075045,sampled=0)
```
After:
```
2022-08-25T23:18:03-0700 [INFO] [runner:iris_clf:1] _ (scheme=http,method=POST,path=/predict,type=application/octet-stream,length=511) (status=200,type=application/vnd.bentoml.NdarrayContainer,length=179) 1.512ms (trace=278659486253167754913431204277364461501,span=12276199527631075045,sampled=0)
```
guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-reques …

fix(cli): component name regression

---

bentoml/_internal/bento/docker/entrypoint.sh
bentoml_cli/start.py

tested with yatai v0.4.6-e40c427

fix(entrypoint): backward compatibility with yatai<1.0.0

---

bentoml/_internal/frameworks/keras.py
bentoml/_internal/runner/runnable.py
bentoml/_internal/runner/runner_handle/remote.py
bentoml/_internal/server/runner_app.py
tests/e2e/bento_server_general_features/service.py
tests/e2e/bento_server_general_features/tests/test_io.py

feature(runner): add multiple output support

---

tests/integration/frameworks/test_transformers_unit.py

the check_task now returns three values

chore(ci): fix the unit test of transformers

---

bentoml_cli/worker/runner.py

fix(server): service_name label of runner metrics

---

.github/PULL_REQUEST_TEMPLATE.md

This PR prevents noise ping to team members. CODEOWNERS has already done this for us.
cc @sauyon

chore(misc): remove mentioned for team member from PR request

---

bentoml/_internal/frameworks/xgboost.py
bentoml/xgboost.py
tests/integration/frameworks/models/__init__.py
tests/integration/frameworks/models/xgboost.py

n.b.: I don't believe this supports 0.7post3; will do some digging later to identify which version we support now.
Should resolve #2983.

feat(xgboost): support xgboost sklearn models

---

bentoml_cli/worker/grpc_api_server.py
bentoml_cli/worker/grpc_dev_api_server.py
bentoml_cli/worker/http_api_server.py
bentoml_cli/worker/http_dev_api_server.py
bentoml_cli/worker/runner.py

fix: broken legacy metrics

---

bentoml/_internal/io_descriptors/image.py

@aarnphm you'll probably have to update your exceptions PR if that's in progress.

feat(io/image): allow writeable mimes as output

---

docs/source/concepts/service.rst

docs: fix descriptor typo

---

bentoml/serve.py

We should log `localhost` as the host to access if the listen address is `0.0.0.0`.

fix(server): log localhost instead of 0.0.0.0

---

bentoml/_internal/bento/docker/__init__.py
docs/source/concepts/bento.rst

Support cuda version 11.2.2 and 11.4.3 docker images so the built image can run on machine with older nvidia-driver version (like 470 in debian 11)
Fixes #(issue)

chore(docker): support more cuda versions

---

bentoml/bentos.py

qa(bentos): update latest options

---

MANIFEST.in

qa: ignore tools from distribution

---

docs/source/frameworks/catboost.rst
docs/source/frameworks/fastai.rst
docs/source/frameworks/keras.rst
docs/source/frameworks/onnx.rst
docs/source/frameworks/transformers.rst
docs/source/frameworks/xgboost.rst
examples/custom_model_runner/service.py
examples/custom_python_model/lda_classifier/service.py
examples/custom_python_model/simple_pickable_model/service.py
examples/custom_runner/nltk_pretrained_model/service.py
examples/custom_runner/torch_hub_yolov5/service.py
examples/custom_web_serving/fastapi_example/service.py
examples/custom_web_serving/flask_example/service.py
examples/kfserving/service.py
examples/mlflow/lightgbm/service.py
examples/mlflow/pytorch/service.py
examples/pydantic_validation/service.py
examples/quickstart/README.md
examples/quickstart/service.py
examples/sklearn/linear_regression/service.py
examples/sklearn/pipeline/service.py
examples/xgboost/agaricus.py

We should use async endpoints in our docs and examples
Fixes #(issue)

docs: using async implementation

---

docs/source/frameworks/tensorflow.rst

docs(framework): fix typos in TensorFlow framework docs

---

bentoml/_internal/bento/docker/templates/base.j2

Move the syntax version to 1.2 to be compatible with kaniko support.

fix(containerize): kaniko support

---

docs/source/concepts/bento.rst
docs/source/concepts/runner.rst
docs/source/frameworks/catboost.rst
docs/source/frameworks/pytorch_lightning.rst
docs/source/frameworks/tensorflow.rst
docs/source/guides/grpc.rst
requirements/tests-requirements.txt

Fix sphinx warning and broken built links

docs: cleanup and fix broken links

---

bentoml/_internal/frameworks/mlflow.py
tests/integration/frameworks/mlflow/test_mlflow_save_load.py

In https://github.com/bentoml/BentoML/pull/2930 I submitted a fix for importing MLFlow models using a models:/ URI.  These imports are different, because the mlflow client does not add an extra new directory for the download.  This means that the directory which gets renamed to `mlflow_model` is incorrect and causes the import to explode.  To fix that I added an extra sacrificial temporary directory into which the model is downloaded (`download_dir` in the code).  For most cases, this directory is left behind and needs to be cleaned up.  For `models:/` imports, this directory gets renamed.  Therefore, the rmtree of that directory needs to be conditional or it will explode for `models:/` downloads.  Sometime beteween verions 1.0.5 and 1.0.6 this if condition was removed, re-breaking …

fix(mlflow): cleanup if temporary models:/ exists

---

bentoml_cli/bentos.py
bentoml_cli/cli.py
bentoml_cli/env.py
bentoml_cli/models.py
bentoml_cli/utils.py
bentoml_cli/yatai.py

lazy imports all bentoml inside bentoml_cli to avoid side effects from import bentoml

chore(cli): lazy import bentoml to avoid side effects

---

bentoml/testing/pytest/plugin.py

This is to fix windows tests being skipped

fix(ci): running windows test

---

bentoml/_internal/resource.py

chore(log): move GPU warning to debug

---

bentoml/_internal/bento/docker/templates/_macros.j2
bentoml/_internal/bento/docker/templates/base_amazonlinux.j2
bentoml/_internal/bento/docker/templates/cuda_debian.j2
bentoml/_internal/bento/docker/templates/cuda_ubi8.j2

Ensure that only 1.2 features from docker/dockerfile are used.

fix(containerize): ensure only 1.2 features are used

---

scripts/tools/formatter.sh
src/bentoml/grpc/buf.yaml

Make sure to format stubs inside src

fix(style): correct format stubs

---

examples/quickstart/BENCHMARK.md
examples/quickstart/locustfile.py

Add gRPC support to quickstart locustfile.

feat: Add gRPC support to quickstart locustfile

---

examples/pytorch_mnist/train.py

docs(examples): fix pytorch_mnist example GPU training

---

.github/workflows/ci.yml

ci: fix proto lint

---

.github/workflows/ci.yml
pyproject.toml
src/bentoml/_internal/configuration/containers.py
src/bentoml/_internal/configuration/default_configuration.yaml
src/bentoml/_internal/server/grpc/server.py
src/bentoml/bentos.py
src/bentoml/serve.py
src/bentoml/start.py
src/bentoml/testing/server.py
src/bentoml_cli/serve.py
src/bentoml_cli/start.py
src/bentoml_cli/worker/grpc_api_server.py
src/bentoml_cli/worker/grpc_dev_api_server.py

Add channelz support to allow easy live server tracing
This is useful to debug the server if user wish to debug the rpc.

feat(grpc): channelz

---

src/bentoml/_internal/server/grpc_app.py

chore: fixing logs for runner readiness

---

src/bentoml/_internal/marshal/dispatcher.py
src/bentoml/_internal/runner/runner_handle/remote.py
src/bentoml/_internal/server/runner_app.py
src/bentoml/exceptions.py

chore(server): propagate runner exceptions

---

src/bentoml_cli/env.py

This PR address issue for `bentoml env` when user are using mamba, micromamba as an
alternative to conda.
Note that we will now print both `pip_package` and `conda_package` when user are inside a conda environment.
Example output:
`bentoml`: 1.0.7.post26+g38ead763.d20221017
`python`: 3.10.6
`platform`: macOS-13.0-arm64-arm-64bit
`uid:gid`: 501:20
`micromamba`: 0.27.0
`in_conda_env`: True
<details><summary><code>conda_packages</code></summary>
<br>
```yaml
name: base
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- libxgboost=1.6.2=cpu_h13cf1d8_1
- tk=8.6.12=he1e0b03_0
- libcblas=3.9.0=16_osxarm64_openblas
- setuptools=65.5.0=pyhd8ed1ab_0
- libsqlite=3.39.4=h76d750c_0
- wheel=0.37.1=pyhd8ed1ab_0
- bzip2=1.0.8=h3422bc3_4
- pip=22.3=pyhd8ed1ab_0
- …
```

feat(env): make sure to check for mamba

---

README.md

docs: update links about BentoML Cloud

---

docs/source/guides/containerization.rst

I add ENV instructions to Dockerfile.template when using environment variables to give AWS credentials to a Bento. 
Not only ARG instructions but also ENV instructions must be written to run the docker image properly.
Fixes #(issue)

docs: add ENV instructions to provide AWS credentials

---

pyproject.toml
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/utils/__init__.py
tests/e2e/bento_server_http/bentofile.yaml
tests/e2e/bento_server_http/requirements/service.txt
tests/e2e/bento_server_http/requirements/train/requirements.txt

This is arguably a bug fix? Not sure... somewhere between a bug fix and a feature... I'd expected this to 'just work'.
Fixes #3102

feat: allow nested `requirements.txt` files

---

src/bentoml/_internal/marshal/dispatcher.py

Trains the optimizer by attempting to create requests with small batch sizes at the beginning of the runner server's lifecycle.

 fix: dispatcher for early requests

---

examples/quickstart/bentofile.yaml
pyproject.toml
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/utils/dotenv.py

This PR address a licensing issue with python-dotenv.
We will port a implementation from djiango-dotenv

fix: licensing issue with dotenv

---

.github/workflows/frameworks.yml

fix: framework ci

---

examples/quickstart/bentofile.yaml

revert: remove invalid options in quickstart

---

src/bentoml/_internal/runner/runner_handle/remote.py

qa: retry env to be NoneType

---

requirements/dev-requirements.txt

Remove this for release schedule
we should include this afterwards tho

qa: remove framework-requirements from dev-requirements.txt for now

---

src/bentoml/_internal/frameworks/keras.py
src/bentoml/_internal/frameworks/onnx.py
src/bentoml/_internal/frameworks/tensorflow_v2.py
src/bentoml/_internal/frameworks/utils/onnx.py
src/bentoml/_internal/frameworks/utils/tensorflow.py

chore: add framework utils functions directory

---

docs/source/concepts/service.rst

Update asynchronous API documentation to advise against using async API if blocking logic is involved.
Fixes #(issue)

docs: Update asynchronous API documentation

---

src/bentoml/_internal/configuration/containers.py
src/bentoml/_internal/frameworks/FRAMEWORK_TEMPLATE_PY
src/bentoml/_internal/frameworks/lightgbm.py
src/bentoml/_internal/frameworks/sklearn.py
src/bentoml/_internal/frameworks/xgboost.py
src/bentoml/_internal/runner/runner_handle/local.py
src/bentoml/_internal/server/base_app.py
src/bentoml/_internal/server/runner_app.py

style: use relative import inside _internal/

---

src/bentoml/_internal/monitoring/api.py

style: fix `monitoring` type error

---

examples/quickstart/iris_classifier.ipynb

Correct minor spelling errors in Quickstart tutorial.

docs: grammar corrections

---

pyproject.toml
requirements/tests-requirements.txt

deps: bumping gRPC and OTLP dependencies

---

docs/source/concepts/runner.rst
docs/source/guides/metrics.rst

Add advanced guide for default metrics.

docs(metrics): Update docs for the default metrics

---

docs/source/frameworks/onnx.rst
docs/source/reference/frameworks/keras.rst
docs/source/reference/frameworks/onnx.rst
src/bentoml/_internal/frameworks/onnx.py

docs: ONNX signature docs

---

src/bentoml/_internal/io_descriptors/pandas.py

Only attempt to set dataframe.columns if `apply_column_names` is set, `columns` have been provided, and the length of `columns` matches the dataframe.
Fixes #3263 

fix(pandas): only set columns when `apply_column_names` is set

---

src/bentoml/_internal/bento/build_config.py

fix(container): support comma in docker env

---

src/bentoml_cli/containerize.py

docs: update instructions for containerize message

---

src/bentoml/_internal/io_descriptors/multipart.py

Fixes some major issues with the multipart logic:
- values not awaited
- fallback being called only when the first attempt succeeded.

fix: multipart logic

---

src/bentoml/_internal/runner/runner_handle/remote.py

Fixes the problem that `anyio.from_thread.run` does not support kwargs

fix(runner): remote run_method with kwargs

---

src/bentoml/_internal/container/podman.py

fix(container): podman health result string parsing

---

src/bentoml/_internal/container/__init__.py

fix https://bentoml.slack.com/archives/CKRANBHPH/p1671623024894159

fix(containerize): fs path format on windows

---

src/bentoml/container.py
src/bentoml_cli/containerize.py

fix(sdk): handling container platform from CLI separately

---

src/bentoml/_internal/server/grpc/servicer/v1/__init__.py

revert a wrong annotations I added while refactoring servicer for different stubs version

fix: wrong self annotations

---

src/bentoml_cli/models.py

fix: regression f-string

---

src/bentoml/_internal/runner/runner.py

Fixes https://github.com/bentoml/BentoML/issues/3420
This is a small change but helps debugging (at least for the project I was working on).

fix(runner): log correct error types during model validation

---

src/bentoml/client.py

@ssheng 
https://github.com/bentoml/BentoML/issues/2900
~~~Python
if __name__ == '__main__':
client = Client.from_url("http://localhost:3000")  # raise  below Error
res = client.classify(np.array([[4.9, 3.0, 1.4, 0.2]]))
print(res)
~~~
~~~Python
File "${MY_HOME}/workspace/bentoml/examples/quickstart/client_example.py", line 5, in <module>
client = Client.from_url("http://localhost:3000")
File "${MY_HOME}/workspace/bentoml/src/bentoml/client.py", line 100, in from_url
if "Service APIs" in meth_spec["tags"]:
KeyError: 'tags'
~~~
those accordingly? Here are [documentation …

fix(client): make sure tags is available in specs

---

src/bentoml/client.py

Adds a list of endpoints to the client for convenience.

feat: add endpoints list to client

---

src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/container/__init__.py

fix: #3399 during `containerize`

---

requirements/dev-requirements.txt

chore: add setuptools-scm as dev deps

---

examples/quickstart/service.py
src/bentoml/__init__.py
src/bentoml/_internal/batch/spark.py
src/bentoml/_internal/io_descriptors/base.py
src/bentoml/_internal/io_descriptors/numpy.py
src/bentoml/_internal/io_descriptors/pandas.py
src/bentoml/batch.py

Builds on the work done by @qu8n in #3099.

feat: support batch inference with Spark

---

requirements/dev-requirements.txt

- chore: add pandas-stubs as dev dependencies

chore: add pandas-stubs as dev-dependencies

---

src/bentoml/_internal/io_descriptors/base.py

Raise `InvalidArgument` instead of `BentoMLException`.

fix: raise more specific error in `from_spec`

---

src/bentoml/_internal/models/model.py

fix(exception): wrong variable reference

---

src/bentoml/_internal/configuration/containers.py

fix: make sure to run migration for envvar

---

tests/integration/frameworks/mlflow/test_apis.py

fix(tests): raises OSError instead (regression from mlflow)

---

docs/source/integrations/index.rst
docs/source/integrations/spark.rst
docs/source/reference/batch.rst

docs: Update Spark integration and reference documentation

---

.github/workflows/ci.yml

fix(ci): run lint on PR only

---

docs/source/integrations/spark.rst
docs/source/reference/batch.rst
src/bentoml/_internal/batch/spark.py

Fixes formatting and the API reference not working.

docs: fix spark docs

---

src/bentoml/_internal/frameworks/mlflow.py

types: update annotations for mlflow signatures

---

src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/models/model.py
src/bentoml/models.py

@aarnphm factored this out of triton.

fix: remove internal save from model

---

docs/source/integrations/spark.rst

Minor refactoring, and providing easy ways to get input and quickstart Bento.

docs: spark docs improvement

---

src/bentoml/triton.py

fix(triton): disable metrics after parsing args

---

src/bentoml/serve.py

For some reason this commit got loss during rebase

fix(triton): throw exception if allow-metrics is passed

---

src/bentoml/serve.py
src/bentoml/triton.py

fix(triton): make sure to set grpc_port

---

src/bentoml/_internal/frameworks/tensorflow_v2.py

Handle cases when model also returns a list, then we process it as tuple

fix(tensorflow): handle if results returns a list

---

src/bentoml/_internal/frameworks/onnx.py

This PR aims to address the flattened providers list when passed to `load_model`
if users have something like
```bash
import bentoml
runner = bentoml.onnx.get("onnx-mnist").with_options(providers=[
("CUDAExecutionProvider", {"device_id": 1, "arena_extend_strategy": "kSameAsRequested" }), "CPUExecutionProvider"]
).to_runner()
```
This will be parsed as `["CUDAExecutionProvider", {"device_id": 1, "arena_extend_strategy": "kSameAsRequested" }, "CPUExecutionProvider"]`, which will fail our exception check.

fix(onnx): flatten providers include incorrect info

---

scripts/release_quickstart_image.sh

Make sure to include grpc-reflection in quickstart image

chore: make sure to enable reflection in quickstart image

---

pyproject.toml

chore(deps): relax packaging

---

docs/source/guides/configuration.rst

docs: fix missing configuration path

---

docs/source/concepts/runner.rst
docs/source/frameworks/index.rst
docs/source/reference/frameworks/index.rst

fix(docs): links and broken framework name

---

docs/source/integrations/spark.rst

fix: spark docs link to main tutorial

---

docs/source/guides/index.rst

docs: update index grid items

---

src/bentoml/__init__.py

chore: lazy export exceptions

---

src/bentoml/_internal/bento/build_config.py

Fixes #3528 
One question I have is, do I also need to make this change in `grpc-client/bentoml/_internal/bento/build_config.py`?

fix: wheel directory check for notebook workflow

---

src/bentoml/_internal/utils/formparser.py

@ssheng writing unit tests is a little involved so thought I'd put this up now; wrote a Bento using multipart and it seems to work.
Discovered another issue where we set the filename to `<request body>` always when using multipart, opened #3541.

fix: update formparser to new Starlette version

---

src/bentoml/_internal/service/inference_api.py
src/bentoml/client.py

chore: add missing logger and fix types

---

.readthedocs.yaml

chore(rtd): disable epub and pdf as format

---

src/bentoml/_internal/frameworks/torchscript.py

Passing \_extra_files to torch.jit.save

feat(torchscript): support `_extra_files`

---

.github/workflows/ci.yml

refactor(ci): make sure to run types on py,pyi files

---

src/bentoml/_internal/container/frontend/dockerfile/__init__.py

feat(containerization): support 11.7

---

src/bentoml/_internal/bento/build_config.py

Removes the warning:
```
WARNING: the legacy dependency resolver is deprecated and will be removed in future versions of pip-tools. The default resolver will be changed to 'backtracking' in pip-tools 7.0.0. Specify --resolver=backtracking to silence this warning.
```
Fixes #3457 

chore: remove deprecation warning when building bentos

---

src/bentoml/_internal/container/podman.py

Bug fix for #3575
Describe your changes in detail.
Only check for running podman machine on Windows and MACOS.
Fixes #3575
- [x ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
- [x ] Does the code follow BentoML's code style, both `make format` and `make lint` script have passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [x ] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBU …

fix(container): podman virtual machine healthcheck (#3575)

---

src/bentoml/testing/server.py

chore(test): using container API for testing

---

src/bentoml_cli/serve.py
src/bentoml_cli/start.py

address #3570
Make sure that value from CLI uses BentoMLContainer as default.

fix(serve-cli): Make sure to use BENTOML_CONFIG value

---

docs/source/index.rst

docs: Update documentation with an examples link

---

src/bentoml/_internal/frameworks/diffusers.py

feature(diffusers): support `enable_attention_slicing`

---

docs/source/concepts/service.rst

There is a small typo resulting in this red text you can see in the screenshot.

docs: Fix typo in concepts/service

---

docs/source/conf.py
docs/source/index.rst
src/bentoml/_internal/frameworks/keras.py
src/bentoml/_internal/frameworks/picklable.py
src/bentoml/_internal/frameworks/sklearn.py
src/bentoml/_internal/frameworks/tensorflow_v2.py
src/bentoml/_internal/io_descriptors/pandas.py
src/bentoml/_internal/service/loader.py
src/bentoml/bentos.py
src/bentoml/keras.py
src/bentoml/metrics.py
src/bentoml/models.py

fix(docs): broken inline docstring

---

docs/source/guides/configuration.rst

docs: typo in configuration.rst

---

docs/source/guides/configuration.rst

Fix link to configuration folder in configuration.rst
Fixes #(issue)

docs: correct links to configuration source code

---

src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/models/model.py
src/bentoml/_internal/utils/__init__.py

- fix: make sure to convert labels to dict[str, str]
- chore: add warning message

chore: ensure all labels are dict[str,str]

---

docs/source/integrations/index.rst
docs/source/integrations/snippets/triton/bentofile.yaml
docs/source/integrations/snippets/triton/build_bento.py
docs/source/integrations/snippets/triton/service_model_version_1.py
docs/source/integrations/triton.rst
pyproject.toml
src/bentoml/_internal/container/__init__.py

Added documentation about our Triton integration.
depends on #3471 #3518 #3502 #3503

docs: Triton Inference Server

---

docs/source/deployment/aws_lambda.rst

docs(0.13): typo

---

src/bentoml/serve.py
src/bentoml/start.py

fix: update scheme logic using ssl.enabled

---

docs/source/reference/api_io_descriptors.rst
src/bentoml/_internal/client/grpc.py
src/bentoml/_internal/io_descriptors/base.py
src/bentoml/_internal/io_descriptors/file.py
src/bentoml/_internal/io_descriptors/image.py
src/bentoml/_internal/io_descriptors/json.py
src/bentoml/_internal/io_descriptors/multipart.py
src/bentoml/_internal/io_descriptors/numpy.py
src/bentoml/_internal/io_descriptors/pandas.py
src/bentoml/_internal/io_descriptors/text.py
src/bentoml/_internal/server/grpc/servicer/v1/__init__.py
src/bentoml/_internal/server/grpc/servicer/v1alpha1/__init__.py
src/bentoml/grpc/utils/__init__.py
tests/unit/_internal/io/test_base.py

Add from_sample docstring for all IODescriptor

feat: `from_sample` docstring

---

tests/e2e/bento_server_http/requirements.txt

This locks the starlette on CI that makes container tests failing atm.

fix(ci): locking starlette for container tests

---

docs/source/integrations/triton.rst
examples/triton/onnx/README.md
examples/triton/onnx/train.py
examples/triton/pytorch/README.md
examples/triton/pytorch/train.py
examples/triton/tensorflow/README.md
examples/triton/tensorflow/train.py

Added a caveat for using adaptive batching with Triton. Updated Triton examples with the latest mechanism for passing CLI arguments.

docs: Update Triton documentation and examples

---

docs/source/integrations/index.rst

docs: Update integration docs

---

src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/miniconda_alpine.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/miniconda_debian.j2

When creating an image from bento using `bentoml containerize` the docker image layers with Python environment (pip or conda installed) were invalidated by any source file change. This could result in ~ 10 minutes image build times (e.g. conda installation of pytorch and related packages).
This pull request defers copying of sources after `SETUP_BENTO_COMPONENTS` block where Python environment is created. Only the Python environment specification files (requirements.txt, environment.yml, ...) are copied before the conda or pip installation.
With this patch I reduced image build times from 10 minutes to 10 seconds when the Python environment is not changed.
Note: I placed the `COPY --chown={{ bento__user }}:{{ bento__user }} . ./` line outside of defined blocks, but it should be probably …

feat(containerize): caching pip/conda installation layers

---

src/bentoml/_internal/external_typing/__init__.py

fix(type): annotate PdSeries with pandas-stubs

---

examples/triton/onnx/containerize_bento.py
examples/triton/pytorch/containerize_bento.py
examples/triton/tensorflow/containerize_bento.py

fix: makes containerize for triton examples to all amd64

---

src/bentoml/_internal/marshal/dispatcher.py

Revert as there is a bug in the training code.

revert: "chore(dispatcher): refactor out training code (#3663)"

---

pyproject.toml
src/bentoml/_internal/runner/container.py
src/bentoml/_internal/runner/runner_handle/remote.py
src/bentoml/_internal/server/runner_app.py
tests/integration/frameworks/models/pytorch_lightning.py
tests/integration/frameworks/models/tensorflow.py
tests/integration/frameworks/models/torchscript.py

perf: serialization optimization

---

.github/dependabot.yml

Remove duplicate dependabot create PRs.

fix: remove duplicate dependabot check for pip

---

docs/source/integrations/flink.rst
docs/source/integrations/index.rst
docs/source/integrations/kubeflow.rst
examples/kubeflow/README.md

docs: Kubeflow integration documentation

---

examples/README.md

fix(readme): format markdown table

---

.github/workflows/ci.yml
.github/workflows/frameworks.yml

Temporary disable coverage for now, as it is not working properly.

ci: temporary disable coverage

---

src/bentoml/container.py

Correct type hint for `image_tag` so that the tuple can contain more than a single str element.
Currently, IDE (and mypy) is not accepting code like this:
```python
bentoml.container.build(
bento_tag=model_bento.tag,
image_tag=(
"job-sectioning-model-opt:latest",
f"job-sectioning-model-opt:{sys.argv[1]}"
),
platform="linux/amd64"
)
```
This is due to the fact that the type hint for `image_tag` is `tuple[str]` and not `tuple[str, ...]` for a tuple with an arbitrary length.
Fixes #(issue)
those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on …

fix(type): `bentoml.container.build` should accept multiple `image_tag`

---

src/bentoml/_internal/context.py
tests/e2e/bento_server_http/service.py
tests/e2e/bento_server_http/tests/test_meta.py

feat: add query params to request context

---

src/bentoml/_internal/marshal/dispatcher.py

Makes jobs slightly easier to read.

chore(dispatcher): use attr class instead of a tuple

---

docs/source/frameworks/transformers.rst

Transformers documentation on pre-trained instances support
Fixes #(issue)

docs: Transformers documentation on pre-trained instances support

---

src/bentoml/_internal/yatai_client/__init__.py

WIP investigation into io.BytesIO BufferError

fix: BufferError when pushing model to BentoCloud

---

requirements/tests-requirements.txt

Remove codecov dependencies for now
See https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259/2

chore: remove codecov dependencies

---

src/bentoml_cli/env.py
tests/e2e/bento_server_grpc/tests/conftest.py
tests/e2e/bento_server_http/tests/conftest.py

This pull request modifies the method of invoking pip commands to 'python -m pip'. This ensures that the version of pip installed with the venv Python is called, even if the venv is not activated.

fix(env): using `python -m` to run pip commands

---

src/bentoml/_internal/client/http.py

This PR address a current bug with HTTPClient, where if an API endpoint defines route:
```python
@svc.api(input=...,output=....,route="/v1/predict")
def predict(...): ...
```
The client created for this endpoint will fail, since the current main implementation prepend the route with a slash, resulting in a double slash in the URL.

fix(client): service route prefix

---

tests/e2e/bento_server_http/tests/test_meta.py

This should properly exercise the training code.

chore: add test with many requests

---

src/bentoml/_internal/marshal/dispatcher.py

Fixes the refactor from earlier, which broke a name change, and also introduces a try-catch to the training code in order to surface issues in the dispatcher.

chore(dispatcher): (re-)factor out training code

---

src/bentoml/_internal/container/frontend/dockerfile/__init__.py

Supports building targets for 3.11

feat(build): support 3.11

---

docs/source/frameworks/tensorflow.rst

docs: Fix TensorFlow `save_model` parameter order

---

src/bentoml/_internal/service/loader.py
tests/unit/_internal/service_loader/bento_service_in_module/multi_service.py
tests/unit/_internal/service_loader/bento_service_in_module/single_service.py
tests/unit/_internal/service_loader/multi_service_in_package/__init__.py
tests/unit/_internal/service_loader/single_service_in_package/__init__.py
tests/unit/_internal/service_loader/test_import_service.py

Currently when the service import string is pointing to a top-level Python package (a directory under working_dir containing a `__init__.py` file), e.g. the demo project here: https://github.com/bentoml/CLIP-API-service, BentoML fails to recognize it as a module name and try to treat it as a python file path.
This PR fixes this corner case and adds related tests for the service loading code.
Fixes #(issue)
those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documenta …

fix: allow import service defined under a Python package

---

src/bentoml/_internal/frameworks/diffusers.py

In previous implementation we use "auto" as the default value of `device_map` when loading the pipeline, and then move the pipeline to gpu if available. In newer version of diffusers (after 0.14), loading a pipeline with `device_map=auto | balanced | etc.` will put the necessary parts of the pipeline to gpu if available, and enable sequential model loading. This means: 1. we don't need to put the pipeline to gpu again 2. we cannot put the pipeline to gpu again because enable sequential model loading disallowing putting the pipeline to gpu manually. (see https://github.com/huggingface/diffusers/issues/2782)
Another fix in this pr is if user pass `device_map=None`, we won't overwrite it with "auto" because `device_map=None` will let user to manually put pipeline to gpu for whatever reason …

fix(framework): adjust diffusers device_map default behavior

---

docs/README.md
docs/source/_templates/base.html
docs/source/guides/grpc.rst
docs/source/index.rst
docs/source/installation.rst
examples/README.md
examples/inference_graph/README.md
examples/monitoring/task_classification/README.md
examples/quickstart/README.md
examples/quickstart/iris_classifier.ipynb

docs: update community slack links

---

requirements/tests-requirements.txt

ci: add Pillow to tests dependencies

---

src/bentoml/_internal/configuration/v1/__init__.py
src/bentoml/_internal/configuration/v1/default_configuration.yaml
src/bentoml/_internal/server/http_app.py

Optionally return trace_id as a header via `X-BentoML-Trace-Id` (only enabled with api_server.http.response.trace_id=True)
Fixes #(issue)

feat: optional returning trace_id in response

---

src/bentoml/_internal/io_descriptors/file.py

This PR fixes a hidden bug that has been here since some time, where the
response headers `content-type` was not set.
This will failed if the user is using the client, as the fake_req actually will
try to get the `content-type` from the headers.
cc @sauyon
[Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
naming? Here are
[GitHub's guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
on how to create a pull request.
([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
[contribution …

fix: make sure to set content-type for file type

---

docs/source/concepts/bento.rst

docs: update default docs to use env as key:value instead of list type

---

src/bentoml/_internal/client/__init__.py
src/bentoml/serve.py
src/bentoml/server.py

customize stdin, stdout, stderr pipe
add encoding, safe guard logging for _check_process
clean up process to make sure remove all zombied PID

feat(server): improve server APIs

---

src/bentoml/_internal/io_descriptors/json.py

chore(client): make JSON warning debug to debloat logs users

---

src/bentoml/_internal/io_descriptors/pandas.py

feat(pandas): fixes handling known types and return tolist()

---

.github/workflows/ci.yml

Ignore 3.11 CI for gRPC for now as it needs more investigation

chore: ignore 3.11 for gRPC

---

scripts/release_pypi.sh

chore: Update release_pypi.sh to check if there are uncommitted changes

---

src/bentoml/_internal/server/http/timeout.py
src/bentoml/_internal/server/http_app.py
tests/e2e/bento_server_http/configs/timeout.yml
tests/e2e/bento_server_http/service.py
tests/e2e/bento_server_http/tests/test_serve.py

This PR implements the timeout config for API server, it takes effect on the server side via a new middleware.
Fixes #2147

feat: Support API server timeout config

---

docs/source/concepts/deploy.rst
docs/source/concepts/service.rst
docs/source/guides/configuration.rst
docs/source/guides/containerization.rst
docs/source/guides/grpc.rst
docs/source/guides/metrics.rst
docs/source/guides/migration.rst
docs/source/guides/monitoring.rst
docs/source/guides/performance.rst
docs/source/guides/snippets/tracing/docker-compose.yml
docs/source/guides/tracing.rst
docs/source/integrations/triton.rst
docs/source/tutorial.rst
examples/custom_model_runner/README.md
examples/flax/MNIST/README.md
examples/fraud_detection/benchmark/README.md
examples/kubeflow/README.md
examples/monitoring/task_classification/locustfile.py
examples/pytorch_mnist/README.md
examples/quickstart/BENCHMARK.md
examples/quickstart/locustfile.py
examples/tensorflow2_keras/README.md
examples/tensorflow2_native/README.md
examples/triton/onnx/README.md
examples/triton/pytorch/README.md
examples/triton/tensorflow/README.md
examples/xgboost/README.md

make docs/examples update for embedded runner. Let's merge this after a new version with embedded runner is released

docs: documentation and examples updated for embedded runner

---

src/bentoml/_internal/server/grpc_app.py
src/bentoml/grpc/utils/__init__.py

I thought I have already remove this 😃

chore(grpc): remove duplicated codepath

---

docs/source/_static/css/custom.css

Centering the "BentoML" text in the sidebar.
In the older version of sphinx this is automatically centered, as seen in the Yatai's docs, which is using sphinx v4.5, while bentoml is using v6.2.
Fixes #(issue)

docs: Centering CSS (:

---

pyproject.toml
src/bentoml/_internal/server/base_app.py

This should allow the BentoML API to remain the same whilst staying compatible with newer Starlette versions.
Follows up on #3600

chore(deps): update Starlette

---

docs/source/index.rst

Adding an Ecosystem Section to the sidebar in docs
Related to https://github.com/bentoml/Yatai/pull/468

doc: Adding Ecosystem to Sidebar

---

.github/workflows/ci.yml

fix: a typo in CI workflow

---

examples/triton/onnx/serve_bento.py
examples/triton/pytorch/serve_bento.py
examples/triton/tensorflow/serve_bento.py
src/bentoml/_internal/batch/spark.py

bug: Fix Spark client `wait_until_server_ready`

---

.gitignore
docs/source/concepts/deploy.rst

docs: update deployment guide

---

src/bentoml/_internal/frameworks/transformers.py

fix(transformers): make sure to set correct GPU device on set framework

---

docs/source/guides/batching.rst

doc: add example of adaptive batching for collection parameter types

---

DEVELOPMENT.md

adds documentation for the issue fixed here #2950 
**Following old development document:**
> (base) vrushali@Vrushalis-MacBook-Air BentoML % bentoml --version              
File "/Users/vrushali/anaconda3/bin/bentoml", line 5, in <module>
from bentoml_cli.cli import cli
File "/Users/vrushali/omkar/BentoML/src/bentoml_cli/cli.py", line 55, in <module>
cli = create_bentoml_cli()
File "/Users/vrushali/omkar/BentoML/src/bentoml_cli/cli.py", line 18, in create_bentoml_cli
from bentoml import __version__ as BENTOML_VERSION
File "/Users/vrushali/omkar/BentoML/src/bentoml/__init__.py", line 20, in <module>
from ._internal.configuration import load_config
File "/Users/vrushali/omkar/BentoML/src/bentoml/_internal/configuration/__init__.py", line 62, in <module> …

docs: adding missing step 'git fetch upstream --tags' in documentation #3903

---

README.md

Fixes typo in readme file with reference to issue #3869
URL "http://127.0.0.1:3000/predict_image" is not present so changing the documentation to "http://127.0.0.1:3000/predict"
Attaching screen-console for the same.
> (base) vrushali@Vrushalis-MacBook-Air BentoML % curl -X POST -H "content-type: application/json" --data "[[5, 3]]" http://127.0.0.1:3000/predict
> [3.9999999999999996]%                                                                                                                                                                                       > (base) vrushali@Vrushalis-MacBook-Air BentoML % curl -X POST -H "content-type: application/json" --data "[[5, 3]]" http://127.0.0.1:3000/predict_image
> Not Found% …

fix: FIX Readme typo in first example #3869

---

src/bentoml/_internal/frameworks/diffusers.py

improv(framework): catch up with diffusers' new features

---

src/bentoml/_internal/container/frontend/dockerfile/__init__.py

Fixes #(issue)
[Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
naming? Here are
[GitHub's guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
on how to create a pull request.
([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
[contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute)
and follow
[development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#start-developing)?
those accordingly? Here are …

feat(cuda): support cuda-12 for generation

---

src/bentoml/_internal/cloud/basecloud.py
src/bentoml/_internal/cloud/bentocloud.py
src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/config.py
src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas.py
src/bentoml/_internal/cloud/yatai.py
src/bentoml/_internal/service/service.py
src/bentoml/bentos.py

Implement deployment client that supports operations related to deployments on Bento Cloud
Fixes #(issue)

feat: implement deployment client

---

src/bentoml/_internal/configuration/v1/__init__.py

fix: Fix the error key change during iteration

---

src/bentoml_cli/bentos.py
src/bentoml_cli/models.py

This PR adds support for parsing space in delete command for both `benotml delete` and `bentoml models delete`
Instead of returning value argument as a STRING , It is removed to take default one. Also added nrgs=-1 to have functionality of multiple targets.
Rest of the code is just parsing.
**TEST SNAPSHOTS:**
Issue reproduce (bentoml models delete):
```
(base) vrushali@Vrushalis-MacBook-Air simple_pickable_model % bentoml models list
Tag                               Module                   Size      Creation Time       
my_python_model:wurpysaau6io4js4  bentoml.picklable_model  1.01 KiB  2023-06-01 23:41:19 
iris_clf:i7wa4yqau6dnajs4         bentoml.sklearn          5.71 KiB  2023-06-01 23:38:16 
linear_reg:l7l4uqh6a6mvejs4       bentoml.sklearn          940.00 B  2023-05-29 15:28:34 …
```

feat: support parsing space for deletion #3418

---

src/bentoml/__init__.py
src/bentoml/_internal/models/model.py
src/bentoml/_internal/types.py
src/bentoml/types.py

Move ModelSignatureDict to _internal.types to fix import
Fixes #(issue)

fix: lazy load types

---

src/bentoml/_internal/yatai_client/__init__.py

Upload is tested and working, but image building isn't, pending money / default build issues.
/cc @ssheng @aarnphm

feat: disable compression

---

src/bentoml/server.py

Fixes a server bug where we set working_dir to Non.
This doesn't effect HTTPServer since in HTTP server implementation we actually set the working_dir again.
This will fail if starting gRPC server.
Currently, this won't block the initial release of OpenLLM, but start-grpc won't work atm
Fixes #(issue)

fix(server): remove setting working_dir to None

---

src/bentoml_cli/bentos.py

feat(cli): fix -o tag to quiet all logs

---

examples/sklearn/pipeline/service.py
examples/sklearn/pipeline/train.py

bugs: Fix SKLearn pipeline example

---

docs/source/concepts/service.rst
src/bentoml/__init__.py
src/bentoml/_internal/context.py
src/bentoml/_internal/io_descriptors/base.py
src/bentoml/_internal/io_descriptors/file.py
src/bentoml/_internal/io_descriptors/image.py
src/bentoml/_internal/io_descriptors/json.py
src/bentoml/_internal/io_descriptors/multipart.py
src/bentoml/_internal/io_descriptors/numpy.py
src/bentoml/_internal/io_descriptors/pandas.py
src/bentoml/_internal/io_descriptors/text.py
src/bentoml/_internal/server/base_app.py
src/bentoml/_internal/server/grpc/servicer/v1/__init__.py
src/bentoml/_internal/server/grpc/servicer/v1alpha1/__init__.py
src/bentoml/_internal/server/grpc_app.py
src/bentoml/_internal/server/http_app.py
src/bentoml/_internal/server/runner_app.py
src/bentoml/_internal/service/inference_api.py
src/bentoml/_internal/service/service.py
src/bentoml/_internal/types.py
src/bentoml/_internal/utils/__init__.py
src/bentoml/_internal/utils/formparser.py
src/bentoml/serve.py
tests/e2e/bento_server_http/service.py
tests/e2e/bento_server_http/tests/test_serve.py
tests/unit/_internal/io/test_base.py
tests/unit/_internal/io/test_custom.py

- Added lifecycle hooks `on_deployment`, `on_startup`, `on_shutdown` to service object.
- Create context on app startup and set the request/response corotine locals when handling requests.
- Change the on_startup and on_shutdown to supporting async and sync.
- Add a more robust `is_async_callable()` helper function to replace the `asyncio.iscoroutinefunction()`
those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentat …

feat: Service lifecycle hooks

---

docs/source/concepts/bento.rst

docs: fixes typo

---

docs/source/index.rst

Renaming BentoML Cloud to BentoCloud

doc: Standardize BentoCloud Naming

---

pyproject.toml

- Change to `starlette>=0.13.5,<0.28`
- Removes security vulnerability for lower than 0.27
- Vulnerability mentioned here - https://github.com/encode/starlette/security/advisories/GHSA-v5gw-mw7f-84px

chore: bump up starlette version

---

docs/source/conf.py

doc: Fix the broken link to og image

---

src/bentoml_cli/utils.py

chore(cli): add spaces between aliases

---

docs/source/tutorial.rst

The existing doc misuses the word "besides". I think it tends to say you cannot run related commands in the Docker deployment section in Google Colab, which is the case as I tried. "Besides" means it is included and the proper word should be "except". But I suggest using a new sentence with both the fact and the reason in it.
Fixes #(issue)

docs: Fix wording in intro tutorial

---

src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/config.py
src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas.py

feat(bentocloud): implement update, terminate and delete deployment

---

.github/workflows/frameworks.yml
src/bentoml/_internal/frameworks/diffusers.py
tests/integration/frameworks/test_diffusers_unit.py

Give diffusers an option to import a pre_trained model from huggingface hub and tag the model with huggingface's commit hash. This will help us to avoid importing duplicated models into BentoML model store, which is helpful for our future projects.

improv(framework): diffusers sync BentoModel version with huggingface version

---

src/bentoml/_internal/frameworks/diffusers.py

chore: remove debug lines

---

src/bentoml/_internal/yatai_rest_api_client/yatai.py

fix: correctly handle 404 in Yatai REST API client

---

.github/workflows/ci.yml
src/bentoml/server.py
tests/e2e/bento_server_http/service.py
tests/e2e/bento_server_http/tests/test_serve.py

fix(ci): the timeout issue on Windows e2e and re-enable

---

src/bentoml/_internal/server/http/instruments.py
src/bentoml/_internal/server/runner_app.py

fix: remove legacy metrics

---

docs/source/guides/snippets/tracing/bentoml_configuration.yaml
docs/source/guides/tracing.rst

docs: update wrong instruction for tracing

---

src/bentoml/_internal/frameworks/diffusers.py
tests/integration/frameworks/models/diffusers.py

feature(framework): diffusers runner support changing scheduler

---

docs/source/concepts/bento.rst
docs/source/tutorial.rst

Add docs for the `models` field. For the code pr, see https://github.com/bentoml/BentoML/pull/3961.
Fixes #(issue)
Preview docs:

docs: Add model field under BentoBuildConfig

---

src/bentoml/_internal/server/http_app.py

doc: Change Dangling "Flask" word in docstrings

---

src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/config.py
src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas.py
src/bentoml/_internal/configuration/containers.py
src/bentoml_cli/cli.py
src/bentoml_cli/deployment.py

It implements the CLI interface for bentocloud deployment.
Fixes #(issue)

feat(bentocloud): implement deployment CLI

---

src/bentoml/_internal/cloud/schemas.py

Fix corresponding schema
Fixes #(issue)

fix(bentocloud): sync schema of ClusterFullSchema

---

docs/source/concepts/bento.rst
src/bentoml/_internal/configuration/v1/default_configuration.yaml
src/bentoml/_internal/marshal/dispatcher.py
src/bentoml/_internal/server/runner_app.py

Also incidentally fixes the max batch size bug.
/cc @frostming @aarnphm

fix: use dispatcher for all workloads

---

src/bentoml/_internal/io_descriptors/json.py

To silence the annoying client warning. Only show it when user has custom json encoder.
Fixes #(issue)

fix(json): only show warning if custom json encoder is used

---

docs/source/concepts/bento.rst
src/bentoml/_internal/configuration/v1/default_configuration.yaml
src/bentoml/_internal/marshal/dispatcher.py
src/bentoml/_internal/server/runner_app.py

This reverts commit 95dc56e7d313b6fa39aa95576ac6765403541412.
Fixes #(issue)

revert: "fix: use dispatcher for all workloads (#3973)"

---

src/bentoml/_internal/configuration/v1/default_configuration.yaml
src/bentoml/_internal/marshal/dispatcher.py
src/bentoml/_internal/server/runner_app.py

@aarnphm can you quickly test this one?

fixed single-batch dispatcher

---

src/bentoml/__init__.py

chore: expose monitoring to __all__

---

src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas.py
src/bentoml_cli/deployment.py
tests/unit/_internal/cloud/test_deployment.py

Add tests and fix the deployment accordingly
Fixes #(issue)

tests: base unit tests for create deployment

---

src/bentoml_cli/deployment.py

Update deployment CLI documentation
Fixes #(issue)

doc(bentocloud): Deployment CLI documentation

---

docs/source/bentocloud/getting-started/ship.rst
docs/source/bentocloud/how-tos/monitor-events.rst

docs: Fix docs linking issue

---

src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/config.py
src/bentoml/_internal/cloud/deployment.py
src/bentoml/exceptions.py
src/bentoml_cli/cli.py
src/bentoml_cli/cloud.py
src/bentoml_cli/deployment.py
src/bentoml_cli/utils.py

- Support `bentoml cloud login` and put `bentoml yatai login` as an alias. 
- Rename yatai to cloud for REST client. 
Fixes #(issue)

refactor(bentocloud): Add cloud login, and rename yatai rest client

---

Makefile

fix: update the format hook id in Makefile

---

src/bentoml/_internal/runner/runner_handle/remote.py

As titled, checked that the code that is being removed has no side effect. I think.

refactor: Extra Instantiation of Params class in remote runner handler

---

docs/source/integrations/ray.rst

docs: Update Ray integration documentation

---

README.md
examples/tutorial/bentofile.yaml
examples/tutorial/init_model.py
examples/tutorial/requirements.txt
examples/tutorial/service.py
src/bentoml_cli/containerize.py

+ minor updates to readme.md
Fixes #(issue)

docs: add tutorial code folder

---

.github/workflows/frameworks.yml
requirements/tests-requirements.txt
src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/utils/__init__.py
src/bentoml/_internal/utils/uri.py

It seems we only need to handle `!` and `@` as shown by https://github.com/PyFilesystem/pyfilesystem2/blob/8ed9dc495d8ba2f83fbb2a1145d34d92e13644be/fs/opener/parse.py#L41-L57
But it may be too deep into the implementation detail of fs. So we just quote all non-URL characters here.
- Fixes #3489
- Fixes #4011

fix: handle special characters in path

---

CITATION.cff
README.md

chore: add BentoML citation

---

src/bentoml/_internal/runner/runner_handle/remote.py

fix: add timeout exception catch while getting readyz
Fixes #4023
/cc @bojiang 

fix: add timeout exception catch while getting readyz

---

docs/source/frameworks/diffusers.rst
docs/source/frameworks/index.rst
docs/source/reference/frameworks/diffusers.rst
docs/source/reference/frameworks/index.rst

docs(framework): diffusers documentation first draft

---

src/bentoml/_internal/external_typing/__init__.py
src/bentoml/_internal/runner/container.py
src/bentoml/_internal/types.py

This adds a data container for PIL image types. Instead of pickling the whold image object, we only extract the bytes data from it.
After change, the performance is 3-4x better.
**Before:** 125 RPS
**After:** 430 RPS
**Development mode(no serialization):** 440 RPS
Fixes #3431

feat: PIL image encoder to improve the performance

---

pyproject.toml

To use @t.override and t.Unpack[TypedDict]
Fixes #(issue)

chore(type): bump pyright to 3.12 features

---

src/bentoml/serve.py
src/bentoml/testing/grpc/__init__.py
src/bentoml_cli/serve.py

chore: remove experimental docstring for gRPC
