- bentoml/handlers/dataframe_handler.py
- bentoml/handlers/image_handler.py
- setup.py
* instead of reading file then read into dataframe, use pandas's built
in func instead.
* remove image handler's cv2 dependency, only import the package when we
need it.
no
n/a
> Remove cv2 dependency for bentoml and update dataframe handle_cli func

- bentoml/__init__.py
- bentoml/service.py
- Move 'api' decorator out of BentoService class definition, but keep the same external facing api
n/a
n/a
;
> Custom BentoService should not have 'api' attribute

- bentoml/archive/archiver.py
- bentoml/archive/loader.py
- bentoml/service.py
- Fix artifact path not found issue when loading pip installed BentoService
n/a
n/a
> Fix loading pip installed BentoService

- bentoml/archive/loader.py
- bentoml/service.py
- tests/test_model.py
- Fix `version` property of loaded BentoService
- command `bentoml info ./archive_path` should show service version correctly now
n/a
unit test
> Fix `version` property of loaded BentoService

- scripts/format.sh
- scripts/lint.sh
- tests/cli/test_cli.py
- tests/handlers/test_image_handler.py
- tests/server/test_model_api_server.py
- tests/test_archive.py
- tests/test_model.py
- tests/utils.py
./script/format.sh ./script/lint.sh now also applies to python files under /tests directory
n/a
n/a
> Include tests directory in format and linter script

- .pep8speaks.yml
- MANIFEST.in
- bentoml/__init__.py
- bentoml/archive/archiver.py
- bentoml/server/bento_api_server.py
- bentoml/service.py
- examples/quick-start/main.py
- tests/test_model.py
- added `@ver` decorator for specifying model service's MAJOR, MINOR version
#75
> Use semantic versioning for BentoService and its generated PyPI package

- bentoml/archive/archiver.py
- bentoml/artifact/__init__.py
- bentoml/server/bento_api_server.py
- bentoml/service.py
- ignore major/minor version when they are not specified by user - so we don't have the "0.0." prefix by default
> Fix BentoArchive version format when not specified with @ver decorator

- bentoml/archive/archiver.py
- bentoml/cli/__init__.py
- bentoml/server/gunicorn_server.py
- setup.py
* Use gunicon instead of flask for DockerFile
- take 2 optional arguments
1. -w, --workers, default number of core / 2 + 1
2. -p, --port, default 5000
```bash
cd archive_path
python __init__.py --port 4000 --workers 3
```
> Add gunicorn support for bentoml

- bentoml/deployment/aws_lambda_template.py
This fix issue for deployoing to aws lambda.  It will use the correct name for layers that generated by python-requirements plugin
> fix python requirement layer issue

- bentoml/server/gunicorn_server.py
Quick solution to https://github.com/bentoml/BentoML/issues/136
> instead of listening localhost, gunicorn will bind to 0.0.0.0

- bentoml/archive/archiver.py
- bentoml/archive/templates.py
- bentoml/cli/__init__.py
- bentoml/deployment/base_deployment.py
- bentoml/deployment/sagemaker.py
- bentoml/deployment/sagemaker/__init__.py
- bentoml/deployment/sagemaker/templates.py
- bentoml/deployment/serverless/__init__.py
- bentoml/deployment/utils.py
- bentoml/server/__init__.py
- bentoml/server/bento_sagemaker_server.py
- setup.py
Add Sagemaker as a new platform target for BentoML deployment.
```bash
bentoml deploy /ARCHIVE_PATH --platform=aws-sagemaker
```
https://github.com/bentoml/BentoML/issues/52
> Deploy to AWS Sagemaker

- bentoml/deployment/serverless/aws_lambda_template.py
- bentoml/deployment/serverless/gcp_function_template.py
* remove extra `:` at end of importing unzip_requirements for aws handler
* correctly import BentoML service
> fix templates for serverless platform

- bentoml/service_env.py
- setup.py
- tox.ini
Use  ```pip install bentoml[api_server]``` when building API server image, which will install extra deps including gunicorn
> Specify api_server deps separately

- MANIFEST.in
- bentoml/__init__.py
- bentoml/archive/loader.py
- bentoml/archive/py_module_utils.py
- bentoml/cli/__init__.py
- bentoml/config/__init__.py
- bentoml/config/configparser.py
- bentoml/config/default_bentoml.cfg
- bentoml/deployment/sagemaker/__init__.py
- bentoml/deployment/serverless/__init__.py
- bentoml/deployment/utils.py
- bentoml/exceptions.py
- bentoml/handlers/image_handler.py
- bentoml/server/bento_api_server.py
- bentoml/server/gunicorn_server.py
- bentoml/service.py
- examples/deploy-with-sagemaker/README.md
- setup.py
* implementation of python configparser and env var based configuration
* added apiserver config as an example
Breaking change:
* changed home folder from `~/.bentoml` to `~/bentoml`
> BentoML configuration base

- bentoml/version.py
- scripts/release.sh
Release notes:
* Improved inline python docs and new documentation site launched https://bentoml.readthedocs.io
* Support running examples on google colab
* OpenAPI docs endpoint beta
* Configurable prediction and feedback logging in API server
* Serverless deployment improved
* Bug fixes
> 0.2.1 Beta Release

- bentoml/cli/__init__.py
- bentoml/server/__init__.py
- bentoml/server/bento_api_server.py
- tests/test_pip_install_bento_archive.py
Add CLI
Nope
```
$IrisClassifier docs
{
"openapi": "3.0.0",
"info": {
"version": "2019_06_29_cb4814c7",
"title": "IrisClassifier",
"description": "To get a client SDK, copy all content from <a href=\"/docs.json\">docs</a> and paste into <a href=\"https://editor.swagger.io\">editor.swagger.io</a> then click the tab <strong>Generate Client</strong> and choose the language."
},
"tags": [
{
"name": "infra"
},
{
"name": …
```
> Add CLI docs command to display docs.

- bentoml/handlers/fastai_image_handler.py
- bentoml/handlers/image_handler.py
* allow post image directly with '--data-binary', for example:
```
curl -X POST "http://127.0.0.1:5000/predict" -H "Content-Type: image/png" --data-binary @Sample_Image.png
```
* 👆 also fixed posting image with the OpenAPI debugging web UI, user can upload image from the web UI for testing API endpoint now:
* fix ImageHandler request_schema for OpenAPI docs
* add request_schema for FastaiImageHandler
> ImageHandler update

- bentoml/handlers/base_handlers.py
- bentoml/handlers/fastai_image_handler.py
- bentoml/handlers/image_handler.py
- bentoml/service.py
- bentoml/service_env.py
- tests/test_service.py
Include handler's dependencies as well, when we are archiving bento service
> Include handler's dependencies to the archived env yml

- bentoml/cli/__init__.py
- bentoml/config/default_bentoml.cfg
- bentoml/deployment/sagemaker/templates.py
- bentoml/server/gunicorn_server.py
* Fixed an issue with serving Keras model in API server docker image
* Gunicorn custom application should load bento service separately for each worker instance
> Fix keras model loading in gunicorn server

- bentoml/archive/config.py
Avoid the following exception when loading from a dev version of local bentoml:
```
ValueError: invalid literal for int() with base 10: '0+untagged'
```
> Fix Bento loading error in dev environment caused by versioneer version str

- bentoml/handlers/image_handler.py
Handling multiple images in ImageHandler
#264
Since `handle_request` isn't covered in tests, I've tested simple service using curl:
```
@ver(major=1, minor=0)
class ImageSimilarityScorer(BentoService):
@api(ImageHandler, input_name='image', accept_multiple_files=True)
def predict(self, images):
original = images[0]
compared = images[1]
return int(original[0, 0, 0] == compared[0,0, 0])
```
It returns expected value for two different random images I've got from the web
> ImageHandler - handling multiple images

- bentoml/archive/archiver.py
- bentoml/archive/templates.py
- bentoml/deployment/sagemaker/__init__.py
- bentoml/deployment/serverless/serverless_utils.py
- bentoml/deployment/utils.py
- bentoml/service_env.py
- bentoml/utils/__init__.py
- bentoml/utils/usage_stats.py
- bentoml/yatai/yatai_service_impl.py
If `bentoml_deploy_version` is set in bentoml.cfg. When archiving service, it will use that version instead of the installed bentoml version.
When deploying to the cloud, if Bentoml is in editor mode(BentoML module is installed with `pip install -e`), we will generate tar.gz file of the BentoML module and placed it in the archive directory for deploying.  Deployed service will have the targz file's BentoML installed
> use in-development bentoml package for deployment

- bentoml/deployment/clipper/templates.py
Hi, I'm the maintainer of Clipper. `Clipper` was updated from 0.3 to 0.4.1 recently. See [this](https://github.com/ucbrise/clipper/releases/tag/v0.4.1).
No.
No. You don't have any unit-tests about Clipper.
> Update clipper/python36-closure-container's version from 0.3 to 0.4.1

- .gitignore
- bentoml/deployment/serverless/aws_lambda.py
- bentoml/deployment/serverless/gcp_function.py
- bentoml/deployment/serverless/serverless_utils.py
- bentoml/deployment/utils.py
- bentoml/exceptions.py
> Enhance serverless deployment

- bentoml/deployment/serverless/serverless_utils.py
Move '\n' to the front, so the first entry won't be on the same line as the last required module in requirements.txt
> fix include bundle requirement for serverless deployment

- bentoml/cli/deployment.py
- bentoml/cli/utils.py
- bentoml/deployment/sagemaker/__init__.py
- bentoml/deployment/serverless/aws_lambda.py
- bentoml/deployment/serverless/gcp_function.py
- bentoml/deployment/serverless/serverless_utils.py
- bentoml/deployment/utils.py
- bentoml/repository/__init__.py
- bentoml/yatai/yatai_service_impl.py
- guides/deployment/deploy-with-sagemaker/deploy-with-sagemaker.ipynb
> Refactoring sagemaker deployment experience

- bentoml/service.py
* updated the version format to look like: "20191009135240_D246ED" for example
* renamed to `versioneer` function, as an interface for users to customize the version format
> Update default BentoService version format

- bentoml/artifact/keras_model_artifact.py
- tests/conftest.py
- tests/handlers/test_fastai_image_handler.py
- tests/test_service.py
This PR introduces the option for users of `KerasModelArtifact` to store only what is absolutely necessary for inference. This is particularly helpful for rapid, space-conscious deployments of Keras models that may have training configuration or history bloat.
Note: For `Keras` models that have already reduced to minimal information for inference, this option is still viable but will not reduce model storage size. Other options (i.e. translation to [`Tensorlow Lite`](https://www.tensorflow.org/lite/convert)) are necessary in this case.
No.
`tox` passes on …
> KerasModelArtifact Feature: Save As Weights & JSON

- bentoml/artifact/keras_model_artifact.py
- bentoml/cli/__init__.py
- bentoml/exceptions.py
* Added support for pure Keras model (instead of model created with tf.keras module), thanks @ghunkins for reporting this issue
KerasModelArtifact#pack expects type: keras.engine.training.Model #336
Tested locally, will follow up with more unit tests
> [ISSUE-336] Support both keras and tf.keras in KerasModelArtifact

- bentoml/configuration/__init__.py
* Fixed an issue when dev branch is clean but different from PyPI release, current behavior will skip bundling the local BentoML repository and instead use the untagged version string.
> Fix BentoML local dev branch bundling

- bentoml/archive/archiver.py
* Currently REST API docker image build will fail to install local dev BentoML bundle due to the permission of 'bentoml_init.sh' file
> Fix docker build error: add executable permission to bentoml_init.sh file

- bentoml/__init__.py
- bentoml/artifact/fastai_model_artifact.py
- bentoml/artifact/sklearn_model_artifact.py
- bentoml/configuration/configparser.py
- bentoml/handlers/fastai_image_handler.py
- bentoml/handlers/image_handler.py
- tests/conftest.py
- tests/handlers/test_dataframe_handler.py
- tests/test_pip_install_bento_archive.py
- tests/test_save_and_load.py
- tests/test_service.py
- tests/test_service_env.py
* Make `bentoml.handlers` behave the same to `bentoml.artifact` submodule, to reduce initial loading time and avoid unnecessarily imports
* This may break users that are accessing handler class directly e.g.:
```
import bentoml
bentoml.handlers.DataframeHandler # this will no longer work
from bentoml.handlers import DataframeHandler
DataframeHandler # this will work
import bentoml.hanlders
bentoml.handlers.DataframeHandler # this will work
```
* Tested locally, improves `import bentoml` loading time by about 3-4x
> Imporve BentoML module loading time

- bentoml/artifact/keras_model_artifact.py
This PR is for a two-line bug-fix. A recent feature unfortunately broke the `KerasModelArtifact` when passing in a `dict` to pack the model.
No, but it may prevent an imminent one. :)
Personal deployment on this branch was successful.
> Bugfix: KerasModelArtifact (data -> model)

- bentoml/artifact/fastai_model_artifact.py
* This ensures that fastai.basic_train submodule is loaded when trying to load a FastaiModelArtifact
* Fixed bug reported at https://github.com/bentoml/BentoML/issues/358
> Fix Fastai module import when loading artifact

- .gitignore
- bentoml/deployment/serverless/aws_lambda.py
- bentoml/proto/repository_pb2.py
- bentoml/repository/__init__.py
- bentoml/yatai/python_api.py
- bentoml/yatai/yatai_service_impl.py
- protos/repository.proto
- setup.py
> Implement feature uploading bento repo to S3.

- bentoml/archive/archiver.py
- bentoml/service.py
- bentoml/utils/__init__.py
- bentoml/utils/hybirdmethod.py
- tests/conftest.py
- tests/test_save_and_load.py
Added support for the follow syntax, which makes creating services with multiple models easier
```
bento_service = MyBentoService()
bento_service.pack('model1', ...)
bento_service.pack('model2', ...)
bento_service.save()
```
> Add pack method for BentoService instance

- bentoml/artifact/__init__.py
- bentoml/artifact/tf_savedmodel_artifact.py
- bentoml/handlers/base_handlers.py
- bentoml/utils/__init__.py
Issue #319
This is first part of adding Tensorflow SavedModel format support in BentoML, with this PR, user can create BentoService with tf.SavedModel format models and all BentoML features including create REST API service or CLI runs will work.
The second part will be loading SavedModel in Tensorflow Serving when serving via REST API server, that will be added in follow up PRs.
> [#319] Tensorflow SavedModel format support 

- bentoml/artifact/fastai_model_artifact.py
- bentoml/artifact/keras_model_artifact.py
- bentoml/artifact/pickle_artifact.py
- bentoml/artifact/pytorch_model_artifact.py
- bentoml/artifact/sklearn_model_artifact.py
- bentoml/artifact/tf_savedmodel_artifact.py
- bentoml/artifact/xgboost_model_artifact.py
- docs/api/artifacts.rst
- scripts/watch-docs.sh
* add/improve TensorflowSavedModelArtifact doc
* update artifact doc string
> [DOC] add TensorflowSavedModelArtifact doc

- bentoml/archive/templates.py
- bentoml/server/gunicorn_server.py
Fixing issue #372
* Pinned base image version
* Remove "import gunicorn.six" whish got removed in gunicorn's latest release 20.0.0
> [ISSUE-372] fix API server docker image build: No module named 'gunicorn.six'

- bentoml/archive/archiver.py
- bentoml/archive/templates.py
- bentoml/deployment/sagemaker/__init__.py
* Currently sagemaker-dockerfile was generated in every BentoService bundle directory, this PR will remove that behavior.
> Generate sagemaker-dockerfile only at deployment time

- bentoml/yatai/__init__.py
* Unblock an issue with AWS Lambda deployment, where grpcio module is incompatible
> Make grpcio dependency optional in serving environment

- bentoml/handlers/image_handler.py
- bentoml/service_env.py
- tests/handlers/test_image_handler.py
* fix accept format check - previously it will fail for filename with captialized extension e.g. '.PNG'
* when prediction request is malformated, API server should return 400 error response instead of raise exception with 500 internal error
* add unit tests for ImageHandler
> ImageHandler accept file type check fix and unit tests

- bentoml/bundler/templates.py
- pytest.ini
- tests/test_pip_install_saved_bundle.py
- tox.ini
This PR fixed the issue posted at #395 - when using BentoService bundle as a PyPI package, it failed to set the list of pip dependencies as the `install_requires` field in setup.py
#395
unit test, manually tested locally
> Fix BentoService bundle pip package dependencies 

- .travis.yml
- tox.ini
* As part of our plans to deprecate support of python 2.7, this PR stops the default Travis test runs for python 2.7 environment
> Removing Python2.7 form test environments list

- bentoml/artifact/pickle_artifact.py
- setup.py
* Use cloudpickle instead of dill as the default
* remove dill from the required dependencies list
N/A
Current unit tests have covered PickleArtifact
> Use cloudpickle as default pickle module for PickleArtifact

- bentoml/deployment/aws_lambda/utils.py
Use the correct appy.py path to copy for lambda deployment
> fix copy app.py for aws lambda deployment

- bentoml/service.py
- tests/test_service.py
* make sure the first parameter to @api is a BentoHandler subclass
* make sure `bentoml.artifacts` submodule is lazily loaded
> Add validation to BentoService @api decorator parameters

- bentoml/configuration/default_bentoml.cfg
- bentoml/deployment/aws_lambda/lambda_app.py
- bentoml/handlers/base_handlers.py
- bentoml/handlers/dataframe_handler.py
- bentoml/handlers/fastai_image_handler.py
- bentoml/handlers/image_handler.py
- bentoml/handlers/json_handler.py
- bentoml/handlers/tensorflow_tensor_handler.py
- bentoml/handlers/utils.py
- bentoml/server/bento_api_server.py
- bentoml/utils/tempdir.py
- tests/cli/test_cli.py
- tests/deployment/aws_lambda/test_aws_lambda_deployment_operator.py
- tests/handlers/test_dataframe_handler.py
- tests/handlers/test_tf_tensor_handler.py
- tests/server/test_model_api_server.py
* Removed the behavior of configuring API handler output type by setting HTTP request header
* Fixed issues with Numpy outputs from user API function
* Additional parameter validation for `orient` and `output_orient` in DataframeHandler
* Removed the leading "predictions" key in TensorHandler outputs
* Fixed all linter errors
> BentoHandler API output format refactor

- bentoml/bundler/templates.py
- bentoml/service.py
- bentoml/service_env.py
- tests/test_service_env.py
It appears that the setup_sh feature of the `env` decorator was broken.
We (@seantur and myself) implemented the functionality as described in the documentation
and added the tests seen below.
Additionally, we moved the setup.sh execution higher in the generated Dockerfile.
The reason for this was to allow the setup.sh script to add our private PyPI repository
to the image, which is required for the `pip install -r /bento/requirements.txt` line to
succeed for private packages. We would certainly welcome feedback on this solution
and discuss alternatives.
No. …
> Fixed setup_sh feature in service_env

- bentoml/cli/__init__.py
- bentoml/cli/aws_lambda.py
- bentoml/cli/aws_sagemaker.py
- bentoml/cli/bento.py
- bentoml/cli/click_utils.py
- bentoml/cli/config.py
- bentoml/cli/deployment.py
- scripts/e2e_tests/aws_lambda/e2e_lambda_deployment.py
- scripts/e2e_tests/aws_sagemaker/e2e_sagemaker_deployment.py
- scripts/e2e_tests/aws_sagemaker/e2e_sagemaker_update_deployment.py
- tests/cli/test_cli.py
- tests/test_pip_install_saved_bundle.py
* BREAKING CHANGE - changed the signature of 'bentoml run' 
previous users can directly use the API name as the command to load and run a model API from cli, it looks like this: `bentoml predict {saved_path} --input=my_test_data.csv`. The problem is that the API names are dynamically loaded and this makes it hard for bentoml command to provide useful `--help` docs. And the `default command` workaround with Click, makes it very confusing when the user types a wrong command. So we decided to make this change.
* Also a breaking change but less intrusive. The `--quiet` and  `--verbose` options are now an option for subcommands instead of only at top-level command.
Basically instead of `bentoml --verbose lambda deploy ...`, you will now do  `bentoml lambda deploy ... --verbose`
* Support for …
> BentoML cli refactors

- bentoml/repository/metadata_store.py
- bentoml/service.py
- bentoml/utils/validator/__init__.py
- tests/utils/test_validators.py
* users can do `bentoml serve IrisClassifier:latest` or `bentoml get IrisClassifier:latest` now
* creating deployment with version 'latest' is not allowed by design
> Support "latest" bento service version in model management CLI

- bentoml/cli/bento.py
* hide the URI column in the 'bentoml list' output, when '-o wide' is not presented
> Add '-o wide' option  for 'bentoml list' command

- bentoml/cli/bento.py
* use '-y' to bypass the 'bentoml delete' command's "Y/N" prompt
> Add '-y' option to 'bentoml delete' command

- bentoml/cli/__init__.py
- tests/cli/test_cli.py
Changing from 
```bentoml run predict IrisClassifier:latest --input='[....]'```
to
```bentoml run IrisClassifier:latest predict --input='[....]'```
> Move 'bentoml run' command option 'api_name' to behind "bento" option

- bentoml/deployment/aws_lambda/download_extra_resources.py
- bentoml/deployment/aws_lambda/lambda_app.py
Ensure `/tmp/requirements` directory is in `PYTHONPATH`.
> Lambda deployment improvement - ensure requirement dir in PYTHONPATH

- bentoml/cli/utils.py
- bentoml/deployment/sagemaker/__init__.py
> CLI improvement - Add bento service as column for deployment list command

- bentoml/deployment/sagemaker/__init__.py
- tests/deployment/sagemaker/sagemaker_moto/model.py
> sagemaker deployment - handle endpoint not found for sagemaker delete

- bentoml/bundler/templates.py
- bentoml/cli/__init__.py
- bentoml/clipper/__init__.py
add options to set PIP_INDEX_URL when build image.
With this change, users can set local pypi mirrors/cache during building docker images.
Pypi cache with Nginx: https://gist.github.com/dctrwatson/5785638
> add options to set PIP_INDEX_URL when build image

- bentoml/utils/pip_pkg.py
Identify the local package paths for 'pip install -e'.
> fix: ignore pip local '-e/--editable' installed package

- bentoml/cli/__init__.py
- bentoml/utils/log.py
This made it possible to custom these options more easily when running API server docker image
> Set serve-gunicorn command options from envvar

- bentoml/cli/yatai_service.py
- bentoml/yatai/__init__.py
- dev/release_yatai_service_docker_image.sh
- docker/yatai-service/Dockerfile
- docker/yatai-service/entrypoint.sh
- docs/source/concepts.rst
- tests/conftest.py
This PR made it more convinent to deploy YataiService(bentoml's model management and deployment automation component) via docker:
```
$ docker run bentoml/yatai-service:0.7.0  --db-url postgresql://chaoyu:passwd@localhost:5432/bentomldb --repo-base-url s3://my-bentoml-repo/
```
> Add YataiService dockerfile and release script

- MANIFEST.in
- setup.py
* The previous attempt https://github.com/bentoml/BentoML/pull/590, to exclude benchmark module from PyPI distribution, only works for sdist but not bdist_wheel build. This PR is fixing that
> [BUILD] Exclude benchmark module in bdist_wheel build

- setup.py
Lock grpcio to 1.27.2 or below. New grpcio version 1.28.2(Apr 3, 2020) is breaking AWS lambda deployment
> Lock grpcio version

- bentoml/marshal/marshal.py
- setup.py
Many a times people create the model in windows and serve in in Linux. Even though gunicorn is not supported windows we can remove issues with creating and packaging model in windows. These changes allow the same.
Fixed Issues in windows
1. ModuleNotFoundError: No module named 'resource'
2. AttributeError: module 'aiohttp' has no attribute 'web'
I have not seen any related issues. But I am sure people will experience these issues in the future when using windows
How was this patch …
> Fix Windows compatibility while packaging models

- bentoml/bundler/bundler.py
- bentoml/bundler/templates.py
- bentoml/cli/__init__.py
* Updated miniconda version to 4.8.2
* Added `docker-entrypoint.sh`, now users can pass extra parameters to bentoml docker container directly, e.g.:
```
$ docker run -p 3000:3000 parano/test:latest --port=3000 --enable-microbatch
```
* Support direct heroku deployment with the $PART env var:
```
$ docker run -e PORT=3333 -p 3333:3333 parano/test:latest
```
* Fixed an issue with custom pip index with BentoML docker build
* Removed the previously added $FLAGS env var, cc @hrmthw 
* TODO: move dockerfile and entry-point code to separate file instead of string template in a python file
> MISC API server docker image improvements

- bentoml/marshal/marshal.py
- bentoml/utils/s3.py
- e2e_tests/aws_lambda/test_lambda_deployment.py
For creating s3 bucket for `us-east-1` region, you can not specify the region in the request https://github.com/boto/boto3/issues/125.
> Fix create s3 bucket issue for us-east-1 region

- bentoml/artifact/spacy_model_artifact.py
Adding a Spacy model artifact able to load Spacy models saved using the ['to_disk'](https://spacy.io/usage/saving-loading) method.
Adds functionalities requested in issue #639 
Since there seems to be no unit testing of artifacts. I tested it on a project of mine using pretty much the snippet included in the docstring.
> Adding spacy_model_artifact.py

- bentoml/server/utils.py
This PR fixed an issue(introduced in 0.7.0) where the prometheus multiprocess directory is not setup properly in-between runs, and user may see the following error message when starting up BentoML API server:
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/chaoyu/bentoml/prometheus_multiproc_dir/gauge_all_83520.db'
```
Thanks @fernandocamargoti for reporting the issue
> Fix prometheus multiprocess mode directory missing

- bentoml/configuration/default_bentoml.cfg
- bentoml/yatai/__init__.py
- bentoml/yatai/utils.py
- setup.py
* How to use:
https://www.notion.so/How-to-deploy-yatai-server-behind-Nginx-and-TLS-1327e8a3cd484a1d998ec1c7c9edde57
* grpcs:// ?
Nginx use this scheme in its config: https://www.nginx.com/blog/nginx-1-13-10-grpc/
* How to specify ca cert?
`bentoml config set yatai_service.client_certificate_file=<path_to_your_ca_cert.pem>`
It is using Mozilla ca cert as default.
> Chore: allow yatai client to connect secure gRPC

- docs/source/deployment/aws_ecs.rst
- docs/source/deployment/azure_container_instance.rst
- docs/source/deployment/google_cloud_run.rst
- docs/source/deployment/heroku.rst
- docs/source/deployment/kfserving.rst
- docs/source/deployment/knative.rst
- docs/source/deployment/kubeflow.rst
- docs/source/deployment/kubernetes.rst
Add install instruction for `jq` and avoid use `we`
> [Docs] clean up deployment guides

- bentoml/marshal/dispatcher.py
- bentoml/service.py
- bentoml/service_env.py
- bentoml/utils/pip_pkg.py
- tests/test_service_env.py
* fix an issue where handler or artifact optional dependencies are overwriting the dependency version that user has specified through `@env`
https://github.com/bentoml/BentoML/issues/642
* Manual test on my local machine
* Unit Test
> [Bug] Fix overwriting pip_dependencies specified through @env

- bentoml/cli/aws_lambda.py
- bentoml/cli/aws_sagemaker.py
- bentoml/utils/validator/__init__.py
- bentoml/yatai/client/deployment_api.py
Currently, deployment namespace configured on the client-side will be used for creating deployments. This PR fixes this issue.
No, reported via community slack
e2e test covered
> [Bug] use default deployment namespace config on server side

- bentoml/configuration/default_bentoml.cfg
- bentoml/repository/__init__.py
- bentoml/yatai/client/bento_repository_api.py
1. I set the signature version of the S3 client `s3v4` as default. If user needs to change it, the user can change it via a new environment variable named `BENTOML_S3_SIGNATURE_VERSION`.
2. I changed from `generate_presigned_post` to `generate_presigned_url` because the former might have a bug for MinIO or other S3-compatible services.
maybe #676 
Our company has an internal S3-compatible service. I succeeded in testing there.
> Generate a presigned-url instead of presigned-post for S3

- bentoml/bundler/loader.py
- bentoml/cli/__init__.py
- bentoml/proto/repository_pb2.py
- bentoml/repository/__init__.py
- bentoml/utils/pip_pkg.py
- bentoml/yatai/client/bento_repository_api.py
- bentoml/yatai/web/src/generated/bentoml_grpc.d.ts
- bentoml/yatai/web/src/generated/bentoml_grpc.js
- bentoml/yatai/yatai_service_impl.py
- protos/repository.proto
* BentoML's model registry is designed to support s3, and only the server-side need to be configured with s3 credentials
* Currently the client-side use boto3 for s3 file download, which requires the client to also have the s3 credentials in order to load or run a BentoML bundle saved in s3
* This PR fixes this issue by using a pre-signed s3 URL to download 
* Updated BentoUri Protobuf definition. Replaced `additional_fields` with just `presigned_url`
* All e2e tests are passing on my local machine now
* Manually tested with AWS s3 and MinIO deployment,  both`save` and `load` works as expected
cc @withsmilo @yubozhao
> Use pre-signed S3 url for downloading saved bundle from s3 service

- setup.py
We need to lock the version of `grpcio-tools` and `grpcio-reflection` as well as `grpcio`.
See old https://github.com/bentoml/BentoML/pull/600.
N/A
N/A
> [Setup] Lock grpcio-tools and grpcio-reflection's version

- bentoml/yatai/yatai_service_impl.py
An issue introduced here: https://github.com/bentoml/BentoML/commit/f59493942754fd1bd9b60cbb5be913492f720ae7
When an unknown exception was caught, it failed to return to the gRPC due to it using the wrong message type.
> Fix YataiService gRPC server error handling

- bentoml/repository/__init__.py
Fix https://github.com/bentoml/BentoML/issues/697
This PR adds additional handles to the s3 delete object response that is not documented.  The undocumented response was causing `bentoml delete` display internal error, even when the metadata and file obj are deleted.
https://github.com/bentoml/BentoML/issues/697
> [FIX] properly handle s3 delete_object response

- e2e_tests/aws_sagemaker/test_sagemaker_update_deployment.py
> [Test] Fix assert result in sagemaker e2e test

- bentoml/cli/aws_sagemaker.py
The comma between two value `-n` and `--namespace` was missing. It was causeing the option name changed  from `namespace` to `n__namespace`
https://github.com/bentoml/BentoML/issues/732
> [BUG] fix deleting Sagemaker deployment with namespace from CLI

- tests/test_save_and_load.py
Skip collecting the `TestBentoWithOutArtifact` class when running tests by adding `__test__ = False`
When running tests with `./travis/unit_tests.sh` right now, a warning is logged to the console.
```
home/aanand/PycharmProjects/BentoML/tests/test_save_and_load.py:87: PytestCollectionWarning: cannot collect test class 'TestBentoWithOutArtifact' because it has a __init__ constructor (from: tests/test_save_and_load.py)
class TestBentoWithOutArtifact(bentoml.BentoService):
```
I reran the unit tests after making this change, and it does not cause any tests to be skipped.
> Skip collecting test artifacts

- bentoml/saved_bundle/config.py
Fix `BentoService` being called `BentoServie` in a log when the serving and packing versions are different.
Makes logs clearer and more professional
Tested by reproducing and serving a service
> Fix typo in mismatched versions log

- bentoml/artifact/__init__.py
> fix to actually use SpacyModelArtifact as a model

- DEVELOPMENT.md
- docs/watch.sh
Run the watch script on Linux
Better support for more development environments
Used it to do the previous pull request #780 
> [DOCS/BUILD] Update watch script for Linux

- bentoml/yatai/deployment/sagemaker/operator.py
This change specifies `gevent==1.4` in `operator.py`. This ensures the generated Dockerfile for sagemaker workers will have the required version of `gevent`.
Without this change, the [Sagemaker deployment tutorial](https://docs.bentoml.org/en/latest/deployment/aws_sagemaker.html) doesn't work. Workers on AWS will throw a `ModuleNotFoundError` because `gunicorn` can't find the right version of `gevent`.
I completed the AWS Sagemaker deployment tutorial. I verified that my endpoint was in service and could generate predictions.
> Specifies gevent version in Dockerfile to enable Sagemaker deployment.

- CODE_OF_CONDUCT.md
* Update to the latest version of Contributor Covenant https://www.contributor-covenant.org/version/2/0/code_of_conduct/
* Updated the bentoml developers' email address (I will be inviting active contributors to the list soon)
> [Community] Update CODE_OF_CONDUCT.md

- bentoml/service.py
- bentoml/service_env.py
When migrating from the old handler API to new Input/Output adapters API, one easy mistake was to pass in the class of InputAdapter instead of an instance.
E.g. from `@api(DataframeHandler)` to `@api(input=DataframeInput)`, which will produce an error when saving the BentoService: `AttributeError: 'property' object has no attribute 'insert'`
The right syntax with the new API is `@api(input=DataframeInput()`, this allow the user to customize the input adapter more easily, for example `@api(input=DataframeInput(input_dtypes={'col1': 'int64'})))`
This PR helps the user to avoid this mistake when migrating to new API
> Add input parameter type check to `@api`

- bentoml/adapters/dataframe_input.py
- tests/handlers/test_dataframe_handler.py
> [FIX] DataFrameInput supports json input with orient="records"

- bentoml/artifact/artifact.py
- tests/artifact/test_bento_service_artifact.py
Add simple validation for artifact's 'name' attribute. As this name is used as a property to access the artifact, the string should respect Python's variable naming conventions. Those are the following:
- A variable name must start with a letter or the underscore character.
- A variable name cannot start with a number.
- A variable name can only contain alpha-numeric characters and underscores.
- Variable names are case-sensitive.
The check is done in `BentoServiceArtifact` __init__ method.
Some tests were added for the validation.
Issue [#747](https://github.com/bentoml/BentoML/issues/747)
Following the `DEVELOPMENT.md` file:
```bash
$ ./travis/unit_tests.sh
```
([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and …
> Artifact string name validation

- bentoml/adapters/dataframe_input.py
- bentoml/adapters/json_input.py
- bentoml/artifact/json_artifact.py
- bentoml/artifact/keras_model_artifact.py
- bentoml/artifact/text_file_artifact.py
- bentoml/cli/config.py
- bentoml/configuration/__init__.py
- tests/handlers/test_dataframe_handler.py
Attempt to fix issue https://github.com/bentoml/BentoML/issues/742
When a request has specified encoding in its header, flask's `request.get_data(as_text=True)` will use this encoding. But in BentoML, it has been using `utf-8` for all requests.
cc @bojiang, do we need to worry about this issue when handling batched request?
https://github.com/bentoml/BentoML/issues/742
> Use encoding specified in request header if presented

- bentoml/cli/bento.py
- tests/cli/test_cli.py
Adds `--print-location` flag to `bentoml get <bento>:<version>`
* Closes #819.
* Implemented `--print-location`
Locally.
> BentoML `get` improvement

- .coveragerc
- bentoml/server/bento_api_server.py
- travis/onnx_integration_tests.sh
- travis/pytorch_integration_tests.sh
- travis/unit_tests.sh
Fix: #848 
When starting flask app with debug flag, it will launch a child process and restart to watch file changes, which spawns another batching server.
ref: https://flask.palletsprojects.com/en/1.1.x/server/#in-code
```
The reason for this is that due to how the reload mechanism works there are some bizarre side-effects (like executing certain code twice, sometimes crashing without message or dying when a syntax or import error happens).
```
Run locally.
> Fix: port conflict with --debug flag

- docs/source/concepts.rst
Add documentation for the new`bentoml retrieve` command.
In https://github.com/bentoml/BentoML/pull/810 I added the retrieve command, but there should be some docs to describe its usage.
> Add documentation around use of retrieve cli cmd

- bentoml/adapters/__init__.py
- bentoml/adapters/json_input.py
- bentoml/adapters/legacy_json_input.py
- bentoml/marshal/utils.py
- setup.py
- tests/bento_service_examples/example_bento_service.py
- tests/conftest.py
- tests/handlers/test_dataframe_handler.py
- tests/handlers/test_fastai_image_handler.py
- tests/handlers/test_json_handler.py
- tests/handlers/test_legacy_image_handler.py
- tests/handlers/test_legacy_json_handler.py
- tests/handlers/test_tf_tensor_handler.py
- tests/marshal/test_dispatcher.py
- tests/utils/test_usage_stats.py
- travis/unit_tests.sh
* Fix the inconsistency of current JsonInput API for handling single prediction request and handling batch request
* Added legacy JSON input class for an easy tranistion
> Fix JsonInput micro-batching support

- bentoml/adapters/base_input.py
- bentoml/adapters/dataframe_input.py
- bentoml/marshal/utils.py
- setup.py
ref: https://github.com/benoitc/gunicorn/issues/1778
> [FIX] decode headers with latin1

- bentoml/adapters/dataframe_input.py
This PR removes the `dtype=False` option in DataframeInput pandas.read_json call - this allow BentoML to follow the `pandas`'s convention on converting JSON to dataframe
See issue #862 
> Fix DataFrameInput passing NaN values over HTTP JSON request

- bentoml/configuration/default_bentoml.cfg
- bentoml/service.py
- docs/source/deployment/azure_functions.rst
- docs/source/guides/micro_batching.rst
It assumed that more users prefer less 429 error than faster response.
> Change the default value of mb_max_latency

- bentoml/yatai/repository/metadata_store.py
The default value for `list` is currently set to 200, which makes the `bentoml list` very slow for users that have lots of BentoML bundles created. This PR changes this default to 40.
> Set a smaller page limit for `bentoml list`

- bentoml/cli/bento_service.py
- bentoml/cli/utils.py
- tests/cli/test_cli.py
* rename _echo -> echo
* refactor to use load_bento_service_metadata to support file paths
* callback tag validation to cleanup containerize
* parameterized testing
> address comments for containerize command

- bentoml/service.py
- tests/test_save_and_load.py
In early BentoML releases(before Nov 2019), the artifact `pack` is invoked from BentoService class' class method:
```python
@artifact([PytorchModelArtifact('model')])
class ImageClassifier(BentoService):
@api(inpud=ImageInput)
def classify(image_list):
...
import torchvision.models as models
resnet18 = models.resnet18()
svc = ImageClassifier.pack(model=resnet18)
```
This syntax was then changed to:
```python
svc = ImageClassifier()
svc.pack('model', resnet18)
```
We've been providing backward compatibility for the old syntax for over 6 months now and have updated all the documentation and examples over to the new syntax ever since.  As we continue to improve the artifacts API, it is time for us to get rid of this older syntax now. …
> Deprecate old style 'pack'

- bentoml/saved_bundle/bentoml-init.sh
Add `--no-cache-dir` option to `pip install`.
Lightens Docker images.
This removes 750Mb of pip cache for Torch for example.
> Do not cache pip requirements in Dockerfile

- bentoml/artifact/artifact.py
- tests/artifact/test_bento_service_artifact.py
Before #911, we used a slightly restricted pattern to ensure an artifact can only be accessed or saved after it has been packed or loaded from disk. #911 refactored the interface to make it cleaner to implement although it now missed the enforcement of packed or loaded state check before accessing the model. This PR adds that back by wrapping those methods and setting the internal state when `pack` or `load` is invoked.
This is part of an effort to provide a more flexible artifacts API that will allow custom model training workflows to integrate better with BentoML's model serving workflow https://github.com/bentoml/BentoML/issues/758 …
> Add artifact loaded, packed, is_ready state check

- bentoml/saved_bundle/config.py
- tests/test_save_and_load.py
* Adds a warning in `SavedBundleConfig.load()` for Python version mismatches.
* Adds a test to ensure warning is raised at appropriate cases.
Fixes #820.
BentoML installed in --editable mode. Ran test in this PR (`test_pyversion_warning_on_load`).
> Add warning for SavedBundle Python version mismatch (#820)

- bentoml/cli/bento_service.py
- tests/cli/test_cli.py
Fix `validate_tag` function raise exception when the optional`--tag` flag is not specified for command `bentoml containerize`
**Current behavior:**
`bentoml containerize MyBentoService:v1` without adding optional `--tag` flag will raise exception:
```
value = invoke_param_callback(self.callback, ctx, self, value)
File "/usr/local/anaconda3/envs/dev/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
return callback(ctx, param, value)
File "/Users/bozhaoyu/src/BentoML/bentoml/cli/bento_service.py", line 69, in validate_tag
if ":" in tag:
TypeError: argument of type 'NoneType' is not iterable
```
**Expected behavior:**
`bentoml containerize MyBentoService:v1` will build docker image with the tag generated from BentoService name and version, when `--tag` option is …
> Fix containerize CLI tag parameter validation

- bentoml/adapters/json_input.py
- tests/adapters/test_json_handler.py
This addresses an issue with AWS Lambda where sometimes a `Content-Type` header is not being sent to the Lambda function even though it is set by the client. This resolves https://github.com/bentoml/BentoML/issues/893.
With this change the JsonInput adapter will, by default, try to parse the input as JSON without testing for the `Content-Type` header, for AWS Lambda functions. If a JSONDecodeError is raised, it will raise a BadInput error.
I had problems with AWS Lambda not transferring the correct headers and as a result, a server error was raised because the Content-Type was missing. We also discussed this on Slack.
In a function I use in production, I made this change manually to the lambda function and deployed it. …
> JsonInput shouldn't check Content-Type for AWS Lambda functions

- bentoml/artifact/artifact.py
- bentoml/saved_bundle/bundler.py
- bentoml/service.py
- tests/test_service.py
As a follow up to #911, #921, #915, this PR refactored the BentoService base class to adopt the new BentoServiceArtifact API. This enables a couple of ways for users to change BentoService's artifacts, in a more flexible way. This unlocks two key use cases:
The first use case is a faster development workflow with BentoML: save model with artifact class in training pipeline and load it later for creating BentoService class for serving. This makes debugging BentoML code a lot easier:
Step 1, model training:
```python
from sklearn import svm
from sklearn import datasets
from bentoml.artifact import SklearnModelArtifact
if __name__ == "__main__":
iris = datasets.load_iris()
X, y = iris.data, iris.target
clf = svm.SVC(gamma='scale')
clf.fit(X, y)
btml_model_artifact = …
```
> Artifacts refactoring: moving BentoService base class to new API

- .travis.yml
We are seeing some tests falling on Travis, due to the fact that we had over 50 commits on master since last PyPI release.(a new release is coming out soon!)
Here is why we made the change:
```
git:
```
We may want to eventually set this config to `false` to avoid the git clone depth flag completely. This works fine for now as we have a pretty fast release cycle. (sorry we have been a bit slow on making releases the past a few weeks!)
> Fix git clone depth travis config

- bentoml/cli/bento_service.py
Just a typo:
```diff
$ bentoml serve --help
...
-  --port INTEGER       The port to listen on for the REST api server, default is $5000
+  --port INTEGER       The port to listen on for the REST api server, default is 5000
...
```
So the diff is basically removing the `$` sign off `serve` and `serve-gunicorn`:
```diff
@@ -215,0 +215,0 @@ def open_api_spec(bento=None):
-        f"default is ${BentoAPIServer._DEFAULT_PORT}",
+       f"default is {BentoAPIServer._DEFAULT_PORT}",
@@ -249,0 +249,0 @@ def serve(port, bento=None, enable_microbatch=False, run_with_ngrok=False):
-        f"default is ${BentoAPIServer._DEFAULT_PORT}",
+        f"default is {BentoAPIServer._DEFAULT_PORT}",
```
> Remove $ from port default argument message

- .gitignore
- bentoml/saved_bundle/bundler.py
- bentoml/saved_bundle/pip_pkg.py
- bentoml/saved_bundle/py_module_utils.py
Fix the unit test `pytest  tests/test_bundle_local_dependencies.py` where BentoML failed to package local dependencies under the `tests` module.
This means that users defining their BentoService within a python package may run into the same problem, due to BentoML ignoring modules found in current directory, which is recognized as a distribution in `pkg_resources.working_set`.
> Fix local py module tests and pip_pkg/py_module_util refactoring

- .travis.yml
- setup.py
- tests/adapters/test_dataframe_handler.py
- tests/integration/api_server/conftest.py
- tests/integration/test_h2o_model_artifact.py
- tests/integration/test_tensorflow_v2_2_savedmodel_artifact.py
- travis/h2o_integration_tests.sh
- travis/install_python36_osx.sh
- travis/integration_tests.sh
- travis/pytorch_integration_tests.sh
- travis/tensorflow_v2.2_integration_tests.sh
Multiple integration tests are falling now due to the latest python client pypi package is "too new" for the docker daemon version on Travis base environment.  Here is an example test run https://travis-ci.org/github/bentoml/BentoML/builds/716700170 with the error message:
```
E       docker.errors.APIError: 400 Client Error: Bad Request ("client version 1.39 is too new. Maximum supported API version is 1.38")
```
> Fix flaky integration tests on travis-ci

- MANIFEST.in
After #839, in release 0.8.4 swagger static files are returning 404 since they are not included in pypi dist 
Issue reported by Bo Han on slack
> Fix static files not found error in 0.8.4

- bentoml/saved_bundle/pip_pkg.py
> Fix #978: Failed to package local pip installed dependency in 0.8.4

- bentoml/yatai/deployment/sagemaker/operator.py
- tests/deployment/sagemaker/test_sagemaker.py
There are cases where an IAM role can have more than one IAM principal in addition to the SageMaker principal. Handle cases where this is true. Experienced this first hand while attempting to deploy to SageMaker in an account where none of the roles had a singular principal in its `AssumeRolePolicyDocument`.
If this condition is unchecked, the following error is produced:
```
Error: sagemaker deploy failed: INTERNAL:Can't find proper Arn role for Sagemaker, please create one and try again
```
Example of an IAM role where this is true:
```
{
"Path": "/",
"RoleName": "dummy",
"RoleId": "ABCDEFGHIJK1234",
"Arn": "arn:aws:iam::0000111112222:role/dummy",
"CreateDate": datetime.datetime(2020, 10, 10, 10, 10, 10, tzinfo=tzutc()),
"AssumeRolePolicyDocument": {
"Version": "2012-10-17", …
```
> Handle multiple IAM principals

- bentoml/adapters/__init__.py
- bentoml/adapters/annotated_image_input.py
- bentoml/adapters/dataframe_input.py
- bentoml/adapters/image_input.py
- docs/source/api/adapters.rst
- tests/adapters/test_annotated_image_handler.py
- tests/conftest.py
Further to [Issue #934](https://github.com/bentoml/BentoML/issues/934)
Added an AnnotatedImageInput adapter that uses multipart/form-data to read in an image file and JSON file at the same time.  This is to handle the common use-case for models that require additional information about an image (such as object detection bounding boxes, segmentation masks, class labels, face keypoints, etc.) 
Unit tests and documentation are included!
See the conversation in [the issue here](https://github.com/bentoml/BentoML/issues/934)
A common use-case for models that take image input is to also include additional information about the image (such as object detection bounding boxes, segmentation masks, class labels, face keypoints, etc.) ImageInput does not allow you to include this kind of information. …
> AnnotatedImageAdapter for Image file plus additional JSON data

- bentoml/cli/bento_service.py
- bentoml/server/marshal_server.py
For MacOS, before Python3.8, the multiprocessing module starts new processes in fork mode by default, and starts new processes in spawn mode by default since 3.8.
The latter will use pickle to pass objects between processes.
And because of the use of `__getattr__` in https://github.com/benoitc/gunicorn/blob/20.0.4/gunicorn/config.py#L54, the magic methods `__getstate__` and `__setstate__` required by pickle to reconstruct the Config object was covered, Which in turn caused the RecursionError.
This PR closes https://github.com/bentoml/BentoML/issues/989
> [FIX] force start batching server with fork method

- bentoml/yatai/deployment/sagemaker/operator.py
- tests/deployment/sagemaker/test_sagemaker.py
Bugfix for issue stemming from https://github.com/bentoml/BentoML/pull/987
Ran into this error
```
[2020-08-13 22:31:47,711] ERROR - URPC ERROR ApplyDeployment: argument of type 'NoneType' is not iterable
Error: sagemaker deploy failed: INTERNAL:argument of type 'NoneType' is not iterable
```
The issue was that when `statement["Principal"].get("Service", None)` is executed for a policy statement which does not have the `"Service"` key and returns a `None`, the string comparison fails with the `'NoneType' is not iterable` exception. 
*Bonus*: Add unit test for the `Can't find proper Arn role for Sagemaker, please create one and try again` `YataiDeploymentException` exception.
Bug from [previous PR](https://github.com/bentoml/BentoML/pull/987), fixing it here.
Tested this out in an AWS …
> [Fix] Condition for IAM principal check

- .github/workflows/ci.yml
- bentoml/saved_bundle/loader.py
Discussed offline with @yubozhao on refactoring the fix for #1030 
cc @yubozhao could you take over the PR and add the remaining CI part?
> [ISSUE-1030] Handle module file path when loading from different OS

- docker/model-server/release.sh
- docker/yatai-service/release.sh
* Add the `latest` tag when releasing a new docker image that is user-facing.
* We will not do this for BentoML internal docker images, e.g. the azure-function image will not have `latest` tag
* `latest` tag can cause issues when used in a production environment, although it is very convenient when a user is just starting out. We should add a warning about it in our YataiService deployment guide.
For context, see PR https://github.com/bentoml/BentoML/pull/1045 from @danield137 and slack discussions with @jackyzha0 here: https://bentoml.slack.com/archives/CK8PQU2JY/p1597872697082800
Tested locally, published `latest` tag for release 0.8.6
([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code …
> Add "latest" tag to BentoML user-facing docker image

- .github/workflows/ci.yml
- bentoml/yatai/deployment/sagemaker/operator.py
- tests/deployment/sagemaker/test_sagemaker.py
While doing a SageMaker endpoint deployment update, the following error was encountered:
```
Invalid endpoint: https://api.sagemaker..amazonaws.com
```
As can be noted in the error, the AWS region name is not visible in the endpoint URL, even when the `AWS_DEFAULT_REGION` and `AWS_REGION` environment variables are setup. This PR fixes the issue by obtaining the default AWS region from the current session.
Fixes the issue described above.
Built package+CLI locally and tested in existing environment.
> Handle missing region during updates

- bentoml/yatai/web/client/yarn.lock
- bentoml/yatai/web/yarn.lock
Update the Yatai service's web server/client package lock.
`parcel-bundler` error is causing Yatai web ui client build fails, see image.
This issue also happens to other parcel users: https://github.com/parcel-bundler/parcel/issues/4817
I think we should move the web client bundling to Webpack as well.
Test locally
> Update Yatai service web packages lock

- bentoml/yatai/db.py
- setup.py
* Lock `sqlalchemy-utils` version to `0.36.7` until the `database_exists` bug is fixed. See additional discussion at https://github.com/bentoml/BentoML/discussions/1053
* Attempt to create the database if it doesn't exist, instead of raising an exception.
> Lock SQLAlchemy-utils version

- bentoml/saved_bundle/bentoml-init.sh
- bentoml/saved_bundle/templates.py
- bentoml/service.py
- bentoml/service_env.py
I split the copying of the service files in the Dockerfile into two parts:
1. Files required for bento-init.sh
2. The rest of the service files
This allows docker to cache the service dependencies effectively (Copying the whole directory at the beginning invalidates cache each time), thus the same or other services would now be able to reuse this cached layer if they have the same dependencies.
NOTE: I had to keep the conda environment name fixed to avoid cache invalidation when copying it over. (I don't think this is the best way, maybe just offer it as the default?? and allow changing it)
I have a use case where I run celery tasks to build custom bentoml service images very frequently, and push them to a private docker repository. I found that each build was taking too much time, nearly …
> Optimize image build time

- bentoml/service/env.py
- docker/model-server/Dockerfile
- docker/model-server/release.sh
- tests/test_service_env.py
The major changes are:
- release docker images for each supported python version, similar to slim images
- use the docker image corresponding to the environment python version, if it is supported
Minor change:
- fix of error in test code (incorrect arg name)
#998 
All tests passed. 
Ran docker release script and confirmed all images built
Tested build with different python versions to confirm the base image changed
This is a breaking change since it will change the base image used to be different than previous, depending on the environment. This, along with #1084, will no longer install python via conda.
- [ x] My code follows the bentoml code style, both `./dev/format.sh` and
([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#s …
> [ISSUE-998] per Python minor version docker base image

- bentoml/adapters/__init__.py
- bentoml/adapters/dataframe_output.py
- bentoml/adapters/default_output.py
- bentoml/adapters/json_output.py
- bentoml/adapters/tensorflow_tensor_output.py
- docs/source/api/adapters.rst
Rename JsonSerializableOutput to JsonOutput to fit the JsonInput
> [Refactor] rename JsonSerializableOutput to JsonOutput

- bentoml/adapters/string_input.py
- setup.py
- Add multipart/form-data support for StringInput
- Update string_input.py
Add multipart/form-data support for StringInput
> Add multipart/form-data support for StringInput

- bentoml/cli/bento_management.py
- e2e_tests/yatai_server/test_sqlite_gcs.py
- e2e_tests/yatai_server/test_sqlite_s3.py
- e2e_tests/yatai_server/utils.py
fix #1174 
The bug was introduced when adding Google cloud storage support for the `bentoml retrieve` command
> [Fix] `bentoml retrieve` s3 error

- bentoml/saved_bundle/bentoml-init.sh
- bentoml/saved_bundle/templates.py
Slack thread:
> Hi there! I assume bentoml is intended to create docker images that contain all of the dependencies. Are there any plans on injecting model weights dynamically after the docker is already created? Maybe it's already possible? This would dramatically reduce the size of the docker image when the model files are big.
There are two ways to achieve this:
1. Inject model weights directly into the container and hot reload the service without a restart.
1. Inject model weights into the image and restart a new container.
For [1], the hot-updating of weights highly relies on frameworks' API. Since `bentoml` supports more than just one framework, it's not consistent to just support some of them.
And [2] is hardly the same as:
* Build a new image with the new model weights without …
> Faster image rebuilding when only model artifacts are updated

- bentoml/adapters/annotated_image_input.py
- bentoml/adapters/file_input.py
- bentoml/adapters/image_input.py
- bentoml/adapters/multi_file_input.py
- bentoml/adapters/multi_image_input.py
As title.
https://github.com/bentoml/BentoML/issues/1201
> [DOC] add examples of query with requests for adapters

- bentoml/yatai/repository/metadata_store.py
- tests/yatai/client/test_bento_repository_api.py
Fix #1209 
Issue:
BentoML was getting and deleting records already marked deleted, when users are setting the version to be the same, for example: `svc.save(version="1")`, bentoml will throw error.
Solution:
make sure fetching/deleting records that is not marked deleted.
> [Fix] Allow delete bento that was previously deleted that share the same name:version. 

- bentoml/frameworks/fastai.py
Going through the code comments made it pretty confusing since the import paths across projects vary.
This just updates those comments with what works.
> Update import paths to reflect fastai2->fastai rename

- bentoml/cli/bento_service.py
- replace `docker.APIClient()` with `docker.from_env().api`
closes #1232 
* manually with local bento services
> patch: construct docker api from env

- bentoml/frameworks/tensorflow.py
- tests/integration/test_tensorflow_v2_2_savedmodel_artifact.py
```python
class Tensorflow2Model(tf.keras.Model):
def __init__(self):
super(Tensorflow2Model, self).__init__()
self.dense = tf.keras.layers.Dense(
units=1,
input_shape=(5,),
use_bias=False,
kernel_initializer=tf.keras.initializers.Ones(),
)
def call(self, inputs):
return self.dense(inputs)
model = Tensorflow2Model()
svc = Tensorflow2Classifier()
svc.pack('model', model)
```
The behavior of `svc.artifacts.model` before save/load and after are inconsistent.
This PR should fix this.
Breaking change:
* it may break some tests that rely on the original model behavior before save/load.
> [FIX] TfSavedModelArtifact packed model behavior

- ci/fasttext_integration_tests.sh
- tests/bento_service_examples/fasttext_classifier.py
- tests/integration/test_fasttext_model_artifact.py
This PR adds an integration test for the Fasttext artifact code.
Changes:
- Added a simple Fasttext Classifier class in tests/bento_service_examples
- Added Fasttext save/load/inference test in tests/integration
This change is required as Fasttext artifact code is currently not tested.
This PR solves #1195 
> Added Integration test for Fasttext

- ci/lightgbm_integration_tests.sh
- tests/bento_service_examples/lightgbm_service.py
- tests/integration/test_lightgbm_model_artifact.py
This PR adds an integration test for the LightGBM Model artifact code
LightGBM artifact code is currently not tested.
This PR solves #1197 
> [Test] Add integration test for LightGBM

- docs/source/concepts.rst
> [Doc]Add model artifact metadata information to the core concept page

- bentoml/frameworks/tensorflow.py
- bentoml/utils/tensorflow.py
When packing a model built with the `tf.keras` API:
```
[2020-11-13 19:06:52,091] WARNING - Due to TensorFlow's save and load mechanism, only methods marked by `tf.function` (and some keras defaults) could be restored after packing & loading.
You can test the restored model object by referring:
<bento_svc>.artifacts.model
[2020-11-13 19:06:52,093] INFO - Found restored functions:
model(inputs, training, mask)
------------
Arguments Option 1:
Positional arguments (3 total):
* TensorSpec(shape=(None, None), dtype=tf.float32, name='inputs')
* False
* None
Keyword arguments:
{}
Arguments Option 2:
Positional arguments (3 total):
* TensorSpec(shape=(None, None), dtype=tf.float32, name='embedding_input')
* True
* None
Keyword arguments:
{}
Arguments Option 3:
Positional arguments (3 total):
* …
```
> [Refactor] opt auto casting of TfSavedModelArtifact & clearer feedback

- bentoml/cli/aws_ec2.py
- bentoml/yatai/deployment/aws_ec2/operator.py
- bentoml/yatai/deployment/aws_utils.py
- e2e_tests/aws_ec2/test_ec2_deployment.py
- e2e_tests/aws_ec2/utils.py
- e2e_tests/cli_operations.py
- tests/integration/yatai_server/test_postgres_local_fs.py
- tests/yatai/local_yatai_service.py
> [Test]Add more logging information for ec2 end-to-end test

- bentoml/__main__.py
```bash
python -m bentoml <subcommand>
```
> Make bentoml module executable

- ci/tensorflow_v1_14_integration_tests.sh
- docs/source/frameworks.rst
- tests/bento_service_examples/tensorflow1_classifier.py
- tests/bento_service_examples/tensorflow_classifier.py
- tests/integration/test_tensorflow_v1_14_savedmodel_artifact.py
> [CI]add integration test for tf1

- bentoml/saved_bundle/loader.py
This change refactors `bentoml.saved_bundle.loader` module to decorate functions to handle remote bundle path.
> Refactor Saved Bundle Loader

- tests/integration/yatai_server/test_local_fs.py
Skip the Postgres + local storage yatai service integration for now, because it is very flaky with Github Action CI
> [Test]Make yatai service integration test less flaky

- .github/workflows/ci.yml
- bentoml/frameworks/keras.py
- ci/keras_integration_tests.sh
- ci/keras_with_tf1_integration_tests.sh
- tests/bento_service_examples/keras_classifier.py
- tests/bento_service_examples/keras_with_tf1_classifier.py
- tests/integration/test_keras_artifact.py
See linked issues.
Added Integration tests for:
both with `store_as_json_and_weights=True` and false.
Also tested on gallery/legacy-keras examples.
> Refine KerasModelArtifact & its integration test

- tests/integration/api_server/conftest.py
- tests/integration/api_server/example_service.py
- tests/integration/conftest.py
- tests/integration/test_h2o_model_artifact.py
- tests/integration/test_keras_artifact.py
- tests/integration/test_tensorflow_v1_14_savedmodel_artifact.py
- tests/integration/test_tensorflow_v2_2_savedmodel_artifact.py
- tests/integration/test_transformers_model_artifact.py
- tests/integration/utils.py
> [Style] opt integration tests

- bentoml/adapters/dataframe_input.py
- bentoml/adapters/file_input.py
- bentoml/adapters/image_input.py
https://github.com/bentoml/BentoML/discussions/1224
> [DOC] fix the commands to post files with curl

- bentoml/saved_bundle/bundler.py
- bentoml/saved_bundle/loader.py
- bentoml/yatai/client/bento_repository_api.py
Add S3 and Google Cloud Storage support for `save_to_dir` function
```python
save_to_dir(my_bento_service, path='s3://bucket_name/path/to/save')
save_to_dir(my_bento_service, path='gs://bucket_name/path/to/save')
```
> [Enhancement]Add remote path support for save_to_dir function

- bentoml/configuration/default_bentoml.cfg
- bentoml/yatai/client/interceptor/generic_client_interceptor.py
- bentoml/yatai/client/interceptor/header_client_interceptor.py
- bentoml/yatai/yatai_service.py
Added authentication token at all grpc requests, this token can be use with a grpc middleware to authenticate and authorized the requests.
BentoML itself doesn’t provide authentication and authorization, it’s commonly done in a proxy in front of it but it's necessary put token in all bentoml request
To do this change, I have added a client interceptor in order to manipulate header request and add token information get by configuration.
I get the example from [here](https://github.com/grpc/grpc/tree/master/examples/python/interceptors/headers)
Set the token in client with following command
`bentoml config set yatai_service.access_token=valid_token`
I've verified that work sniffing the request in a gRPC Proxy
A new package client.interceptor is now available in code, and in …
> [New Feature] Add authentication token at grpc requests

- bentoml/service/__init__.py
- bentoml/service/env.py
- tests/test_service_env.py
Adds an option to the env decorator so that conda_channels will overwrite the default
**This is an alternate approach to https://github.com/bentoml/BentoML/pull/1354 and only one is needed to solve the problem**
There is no easy way to use _only_ a specified set of conda channels which is problematic in environments where the defaults are unavailable. This fixes that. 
I have added a test case specifically for this option. 
There should not be any integration issues.
The default option is False, which is the same behaviour currently so is backwards compatible.
> Allow option to overwrite list of conda channels

- bentoml/saved_bundle/bentoml-init.sh
- bentoml/service/env.py
- ci/install_python36_osx.sh
- tests/test_service_env.py
- tests/utils/test_usage_stats.py
- always call `conda install python="{version}"`
- locked the channel of `python` and `pip`
In the past two weeks, our integration tests on TensorFlow, Keras with docker failed at some point.
Here is an example: https://github.com/bentoml/BentoML/pull/1375/checks?check_run_id=1644036917
Two issues related to it in the `bento-init.sh`:
- If the Python version in the base image was the same as required, `conda install python={version}` would be skipped. The `python` package wasn't added to the specs of conda. Thus conda will also try to install the newest version of python, 3.9, in the next call.
- The channels of conda are set as ['conda-forge', 'defaults']. Plus we call `conda install python=3.7` to update Python. Sometimes this version code matches "python_pypy=3.7" in the conda-forge …
> [Fix] ensure Python version; exclude conda-forge from default conda channels

- bentoml/cli/bento_service.py
- bentoml/yatai/yatai_service_impl.py
- tests/integration/yatai_server/test_containerize.py
* fix #1403
* Add additional test for using CLI command
> [Fix]Failure to containerize model with build-arg value contains multiple `=` characters

- bentoml/configuration/default_bentoml.cfg
- bentoml/yatai/yatai_service.py
Will allow the user to set a custom `access_token_header` within their config which will then ensure the set `access_token` is used under that Header defined when making requests with `BentoML` to `Yatai`
I am happy to contribute some docs around this if this works as expected so others are able to use authentication in-front of yatai in the future 👍 
relates to: https://github.com/bentoml/BentoML/issues/1415
Essentially want to pass a JWT via a custom header to whatever sits in front of `Yatai`. Currently the hard-coded `access_token` header limits my options on the service that can sit in front of `yatai` to valid these tokens
Wasn't able to get the pip packages installed on my MacBook, will reattempt then but hoping for tests to run upon this PR being opened
`./dev/lint.sh` script have …
> Lets user set a custom access_token header

- ci/coreml_integration_tests.sh
https://github.com/apple/coremltools/issues/1077
> [CI] lock version of numpy for coreml itest

- bentoml/__init__.py
- bentoml/server/marshal_server.py
Refactor multiprocessing set_start_method('fork') to the very beginning, before forking or spawning any process. The logic was added in response to the default start method change in multiprocess for MacOS. Ideally, the start method should be set before forking or spawning any processes. The original location in `bentoml/server/marshal_server.py` was not ideal because we have logic starting a new process before reaching that point in `bentoml/server/__init__.py`.
Thanks for the troubleshooting help from @yubozhao.
Similar to gunicorn, dependency-injector requires the start method of new processes to be forking, to carry forward the containers and providers. Therefore, we should ensure start method is "fork" before starting any new processes.
./dev/format.sh
./dev/lint.sh
./ci/unit_test.sh …
> Refactor multiprocessing set_start_method('fork') to initialization

- bentoml/marshal/marshal.py
- bentoml/saved_bundle/config.py
- bentoml/server/api_server.py
- bentoml/server/open_api.py
- bentoml/service/__init__.py
- bentoml/service/inference_api.py
- bentoml/yatai/proto/repository_pb2.py
- bentoml/yatai/web/src/generated/bentoml_grpc.d.ts
- bentoml/yatai/web/src/generated/bentoml_grpc.js
- ci/back_compatibility_itest.sh
- ci/install_test_deps.sh
- protos/repository.proto
- tests/bento_service_examples/example_bento_service.py
- tests/conftest.py
- tests/integration/projects/general/service.py
- tests/integration/projects/general/tests/test_adapter.py
- tests/integration/projects/general/tests/test_meta.py
- tests/integration/utils.py
- tests/server/test_model_api_server.py
Provided integration tests. 
It also passed the backward compatibility tests. See https://github.com/bentoml/BentoML/pull/1370
> Customize route of API endpoint

- bentoml/__init__.py
- bentoml/server/gunicorn_server.py
- bentoml/server/marshal_server.py
- tests/utils/test_usage_stats.py
Restricted Gunicorn application classes to POSIX environments.
This change allows dependency injector to wire packages separately for CLI `bentoml serve` and `bentoml serve-unicorn` allowing `bentoml serve` continue to work for non-POSIX operating systems.
./dev/format.sh
./dev/lint.sh
./ci/unit_test.sh
> Restricted Gunicorn application classes to POSIX environments

- bentoml/saved_bundle/bentoml-init.sh
- bentoml/saved_bundle/docker-entrypoint.sh
- bentoml/saved_bundle/templates.py
Run the API server as root has potential security risks.
> [Fix] run entry point as a non-root user in docker

- bentoml/adapters/base_input.py
- bentoml/service/inference_api.py
- tests/integration/projects/general/service.py
- tests/integration/projects/general/tests/test_meta.py
- tests/integration/projects/general/tests/test_microbatch.py
- tests/integration/projects/general_non_batch/tests/test_meta.py
- tests/integration/utils.py
> [Feature] Customizable request schema

- e2e_tests/yatai_server/test_postgres_gcs.py
- e2e_tests/yatai_server/test_postgres_local_fs.py
- e2e_tests/yatai_server/test_postgres_s3.py
- e2e_tests/yatai_server/test_sqlite_gcs.py
- e2e_tests/yatai_server/test_sqlite_s3.py
- e2e_tests/yatai_server/utils.py
> [Refactor]Update yatai e2e tests to the latest python APIs

- .github/workflows/ci.yml
- bentoml/service/__init__.py
- bentoml/service/env.py
- tests/test_service_env.py
- tests/utils/test_usage_stats.py
The current option `conda_channels` and `conda_overwrite_channels` imply developers have full control of the conda channels. But a bentoml service with `conda_overwrite_channels=True` will still install packages from channels other than specified in `conda_channels ` (from the official channels #1429). conda itself has a similar option `--override-channels` and already has a different solution for that.
In this PR, the behavior of `conda_overwrite_channels ` is changed following the official pattern: [conda/docs/sharing-an-environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment)
An option `conda_override_channels ` was added and act like the `--override-channels` option for conda.
`conda_overwrite_channels` now is a …
> Applying conda's `--override_channels` in bento-init.sh

- bentoml/cli/bento_service.py
- bentoml/configuration/default_bentoml.yml
- bentoml/marshal/marshal.py
- bentoml/server/__init__.py
- bentoml/server/api_server.py
- docs/source/concepts.rst
- tests/cli/test_cli.py
- tests/utils/test_usage_stats.py
Marshal server is always started at serving time. If micro-batching is enabled, marshal server will perform batching; otherwise, requests to the marshal server are pass through. Refactored `start_dev_server` to follow the same pattern as `start_prod_server`.
Marshal server will start functioning like a sidecar or reverse proxy. The change enables further functionality to be added to the marshal server.
`./ci/unit_tests.py` but I'm still investigating the right fix to an existing test. 
> Always start marshal server even if micro-batch is disabled

- bentoml/marshal/marshal.py
Todo: enable integration tests for the development server on Windows(#1546) to avoid breaks in the future. 
> Fix aiohttp importing for Windows

- .github/workflows/ci.yml
- ci/install_test_deps.sh
- ci/install_test_deps.sh.cmd
- ci/test_project.sh.cmd
- tests/integration/projects/conftest.py
- tests/integration/projects/general/tests/test_microbatch.py
- tests/integration/utils.py
Until now integration tests in CI only cover the production server on POSIX platforms.
This change covers the development server (`bentoml serve`) on Windows #1544 
> [CI] test dev server on Windows

- bentoml/cli/bento_management.py
- bentoml/yatai/client/bento_repository_api.py
- tests/yatai/client/test_bento_repository_api.py
fix #1589 
**Breaking Change:**
Python API
```python
yatai_client.repository.push(bento_tag, labels) -> yatai_client.repository.push(bento_tag, with_labels)
```
Remove old parameters `labels`, add new parameter `with_labels`
with labels, Boolean, default `True`:  If `True`, local bento service's labels will be preserved in the remote yatai server.
CLI:
```bash
$ bentoml push bento_bundle_name:version --yatai-url $yatai_service_endpoint  --with-labels/--without-labels
```
`--with-labels/--without-labels`: new CLI option flag. If user does not want to preserve the bento service labels in the remote yatai server use `--without-labels` flag. Default is `--with-labels`
**Follow up Changes**
Introduce new `set labels` function to the Yatai.  
*API and CLI syntax is not finalized.*
```python …
```
> [enhancement] default to retain bento service's label when push to remote yatai

- bentoml/saved_bundle/bundler.py
The indentation for this call is wrong: the temporary directory will have already been deleted before uploading the file.
Without this change, you will get an error like `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/bentoml-temp-g_e81bcl/IrisExampleForestService.tar'`
With the change, the .tar file is successfully uploaded to S3.
> Fix indentation for uploading to remote path

- README.md
- bentoml/frameworks/onnxmlir.py
This is a follow-up to https://github.com/bentoml/BentoML/issues/1565 
The readme and doc needs to be fixed to reflect the ONNX-MLIR support and to better format the doc example.
Motivation is to have the doc more in-line with other frameworks supported. 
Regenerated the doc as shown in the developer markdown file. Displayed to ensure formatting looks as desired.
- [] My change reduces project test coverage and requires unit tests to be added
> fix docs and readme for onnx-mlir

- bentoml/server/api_server.py
This PR will solve the issue of docs.json in the Swagger Page
This PR will solve the bug #1486 
This PR has been tested in local by running the Swagger API docs page
- [x ] Bug fix (non-breaking change which fixes an issue)
> Fixing the Bug 1486 to point to proper docs.json file in Swagger Page

- bentoml/adapters/string_input.py
- bentoml/types.py
- tests/adapters/test_string_input.py
The StringInput is added as the parent of other practical InputAdapters. Its behavior was not fully covered by tests.
requires: #1576 
> [Fix] StringInput doesn't work with batch=True

- bentoml/yatai/db/stores/lock.py
- bentoml/yatai/migrations/versions/370a2bf2e594_update_lock_table_column.py
fix #1680 
Lock table's `resource_id` column was Integer type.  SQLite uses what it calls a dynamic typing system, which ultimately means that you can store text in integer fields. It wasn't reporting error. If use Postgres, BentoML will throw error when attempting to acquire lock.
This fix update the column type in the table declaration, also create a migration for existing users.
> [bug fix] Update lock table's resource_id column type

- yatai/ui/src/components/BentoBundleDeleteConfirm.tsx
- yatai/ui/src/pages/BentoServiceDetail.tsx
- yatai/ui/src/utils/Toaster.ts
- yatai/web_server/package.json
This adds a delete button to the web UI. The button triggers a modal dialog that informs the user of their decision, then attempts to delete a Bento bundle. Upon deletion it triggers a global toast informing the user of the deletion or if an error occurred.
Here is a [link to a gif](https://imgur.com/GnDs16C) of it in action.
This helps build out functionality for the Yatai web UI and is in response to issue #1445 
> feat(yatai): Add delete button

- bentoml/_internal/utils/__init__.py
- bentoml/_internal/utils/csv.py
- bentoml/_internal/utils/dataframe_util.py
- bentoml/_internal/yatai_client/__init__.py
- bentoml/_internal/yatai_client/utils.py
- bentoml/keras.py
- mypy.ini
Some internal decorator utility functions are not type-safe now, for example: 
before:
after:
I fixed the error above in this PR, but some decorators like `cached_contextmanager` and `catch_exceptions` are still not type-safe, this problem that relies on this issue: https://github.com/python/mypy/issues/8645
> fix(type): make some decorator utility functions type-safe and add some type annotations

- bentoml/_internal/adapters/dataframe_output.py
#1780 DataframeOutput adapter http header respect
Changed `Content-Types` to `application/json`.
`DataframeOutput` is extending `JsonOutput`, but `Content-Types` of http-header is `text/html`.
It causes confusion for users.
**Test Code**
```python
@bentoml.api(input=DataframeInput(orient="records", columns=[], dtype={}),
output=DataframeOutput(),
batch=True)
```
**\<As-is\>**
**\<To-be\>**
> fix: dataframe output adapter http header respect

- Makefile
- bentoml/transformers.py
- ci/integration/frameworks/run_transformers_tests.sh
- tests/integration/frameworks/test_transformers_model_artifact.py
Add supports for transformers 4.x, which includes Flax supports. This also comes with a minor change to API. User can now specified the type of model head corresponding to its tasks. Default framework and language modeling head would be PyTorch and Causal head correspondingly.
```python
tf_model = TransformersModel.load('distilbert', framework='tf', lm_head='masked')
flax_model = TransformersModel.load('gpt2', framework='flax') 
```
Added new test cases
> feat: supports for transformers 4.x

- setup.py
With urllib3's version < 1.26.5, the impact could be:
When provided with a URL containing many @ characters in the authority component the authority regular expression exhibits catastrophic backtracking causing a denial of service if a URL were passed as a parameter or redirected to via an HTTP redirect.
Reference: 
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33503
https://jvn.jp/en/vu/JVNVU92413403/
The patched version of this issue is 1.26.5.
Passed `./ci/unit_tests.sh `
> upgrade: urllib3

- bentoml/_internal/bento/bento.py
- bentoml/bentos.py
I added `export` and `push` as methods of the `Bento` class, and added `push` and `pull` placeholders so @yetone can start work on that if necessary.
> chore(internal): minor bento store fixes

- bentoml/_internal/bento/bento.py
- bentoml/_internal/models/store.py
- bentoml/_internal/types.py
- bentoml/_internal/utils/__init__.py
- bentoml/_internal/utils/validation.py
- bentoml/bentos.py
This is somewhat a proposal, but I've changed the version format to `YYYYMMDD.<stamp>`, where `<stamp>` is a custom base64 encode of the unix timestamp in seconds.
This way, versions are lexically sortable if we ever decide that they should be. This is currently only important because the store implementations are sorting by tag when listing, which may not be the "correct" order for the user.
There's definitely an argument to be made that the store implementation should also sort by item timestamp too.
> feat(internal): change the format of generated versions

- .github/workflows/ci.yml
- ci/format_and_lint.sh
- ci/install_dependencies.sh.cmd
Using pyright because `mypy` is unbearably slow and doesn't seem to limit itself to the files passed on the CLI.
> tests: add pyright ci check

- pyproject.toml
We only need attrs 21.1 for type checking.
> chore: revert attrs dependency changes

- pyproject.toml
maybe we should enable pyright for other directory as well, since if we don't do it now we might never :)
> chore: enable pyright for testing

- bentoml/_internal/bento/bento.py
Seems like `pyyaml` already handled this.
> fix(internal): BentoInfo: don't try to parse creation time again

- setup.cfg
pytest was constantly complaining to me about this
> chore(internal): use license_files instead of license_file

- bentoml/_internal/bento/bento.py
This works around a bug in pathspec < 0.9.0 where absolute paths are not
matched properly.
/cc @yubozhao
> fix(internal): strip leading slashes off paths when building bentos

- bentoml/_internal/frameworks/catboost.py
- bentoml/_internal/frameworks/detectron.py
- bentoml/_internal/frameworks/easyocr.py
- bentoml/_internal/frameworks/gluon.py
- bentoml/_internal/frameworks/h2o.py
- bentoml/_internal/frameworks/keras.py
- bentoml/_internal/frameworks/lightgbm.py
- bentoml/_internal/frameworks/mlflow.py
- bentoml/_internal/frameworks/onnx.py
- bentoml/_internal/frameworks/onnxmlir.py
- bentoml/_internal/frameworks/paddle.py
- bentoml/_internal/frameworks/pycaret.py
- bentoml/_internal/frameworks/pytorch.py
- bentoml/_internal/frameworks/pytorch_lightning.py
- bentoml/_internal/frameworks/sklearn.py
- bentoml/_internal/frameworks/spacy.py
- bentoml/_internal/frameworks/statsmodels.py
- bentoml/_internal/frameworks/tensorflow.py
- bentoml/_internal/frameworks/transformers.py
- bentoml/_internal/frameworks/xgboost.py
- bentoml/_internal/runner/runner.py
- bentoml/_internal/service/service.py
- bentoml/pyspark.py
- tests/e2e/bento_server_general_features/service.py
- tests/e2e/bento_server_general_features_sync/service.py
> refactor: asign runner name

- bentoml/_internal/frameworks/pytorch.py
- bentoml/_internal/io_descriptors/image.py
- bentoml/_internal/runner/container.py
- bentoml/_internal/runner/utils.py
- bentoml/_internal/types.py
- pyproject.toml
- tests/unit/_internal/runner/utils.py
TypeRef provides solutions for several conflicts when applying lazy dependencies,
type annotations and runtime class checking.
It works both for runtime and type checking phases.
* conflicts 1
isinstance(obj, class) requires importing the class first, which breaks
lazy dependencies
solution:
>>> TypeRef("numpy.ndarray").isinstance(obj)
* conflicts 2
`isinstance(obj, str)` will narrow obj types down to str. But it only works for the
case that the class is the type at the same time. For numpy.ndarray which the type
is actually numpy.typing.NDArray, we had to hack the type checking.
solution:
>>> if TYPE_CHECKING:
>>>     from numpy.typing import NDArray
>>> TypeRef["NDArray"]("numpy.ndarray").isinstance(obj)`
>>> #  this will narrow the obj to NDArray with PEP-647
* conflicts 3 …
> feat(codebase): add LazyType.isinstance with TypeGuard(PEP647) support

- bentoml/utils/cloudpickle.py
Add checking if obj has `__module__` attribute in order to avoid getting an exception when saving service with  PyTorch DynamicQuantizedLinear artifact
Fix #2169
Do the same as in #2169
> fix: add checking if obj has __module__ attribute

- setup.cfg
https://github.com/encode/uvicorn/pull/1261
> fix: pin uvicorn for python 3.6

- bentoml/_internal/io_descriptors/pandas.py
- setup.cfg
https://github.com/pandas-dev/pandas/releases/tag/v1.4.0
> pandas 1.4.0 supports Python 3.8 and higher.
pip will install old versions under lower Python versions. Thus only tests with >py38 failed
> fix(io): support pandas 1.4.0

- bentoml/_internal/io_descriptors/pandas.py
This PR fixes https://github.com/bentoml/BentoML/issues/2219 by adding a missing "not" to the type check in pandas.PandasDataFrame.to_http_response.
fixes https://github.com/bentoml/BentoML/issues/2219
> fix: incorrect PandasDataFrame.to_http_response exception (Issue #2219)

- bentoml/_internal/service/loader.py
Previously the global model store was being set to the provider instead of the contents of the provider, which was causing issues.
fixes #2264
> fix(internal): fix issue with global model store after load

- bentoml/_internal/configuration/containers.py
- bentoml/_internal/configuration/default_configuration.yaml
- bentoml/_internal/log.py
- bentoml/_internal/server/access.py
- bentoml/_internal/server/runner_app.py
- bentoml/_internal/server/service_app.py
- bentoml/_internal/trace.py
Improve service and access logging format and configurability.
- Standardize log timestamp to using ISO_8601 standards, e.g. 02/21/2022T23:39:34.
- Repeat timestamp in log entries even though they were generated from the same second.
- Fix a bug in producing excessive access logs in streaming mode.
- Restructure configuration and separate logging configuration for `api_server` and `runners`.
- Updated the `sampled` key value pair to logging `0` or `1` instead of `False` or `True`.
> feat: Improve logging format and configurability

- README.md
404 Error Found!
[404 error](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md%3E)
It solves the broken link to the user to redirect to the correct Contribute page
> fix: Fix broken link to Contribute.md

- bentoml/bentos.py
Instead of showing a stacktrace error message, print an easy-to-read error message when `bentoml containerize` failed. E.g. when the docker daemon is not running, it will do:
```
> bentoml containerize iris_classifier:23qseuez5c4yhuqj 
03/01/2022 21:30:44 INFO     [cli] Building docker image for
Bento(tag="iris_classifier:23qseuez5c4yhuqj")...
03/01/2022 21:30:44 ERROR    [cli] Failed building docker image: Cannot connect to the Docker daemon at
unix:///var/run/docker.sock. Is the docker daemon running?
```
Previously it will show a stacktrace like the following:
```
> bentoml containerize iris_classifier:23qseuez5c4yhuqj     
03/01/2022 21:33:41 INFO     [cli] Building docker image for
Bento(tag="iris_classifier:23qseuez5c4yhuqj")...
Cannot connect to the Docker daemon at …
```
> chore: better error message when containerize failed

- bentoml/_internal/bento/bento.py
- bentoml/_internal/exportable.py
- bentoml/_internal/models/model.py
- bentoml/_internal/store.py
- bentoml/bentos.py
- bentoml/models.py
- tests/unit/_internal/bento/bentoa/bentoa.py
- tests/unit/_internal/bento/bentoa/testfile
- tests/unit/_internal/bento/bentoa1/bentoa.py
- tests/unit/_internal/bento/bentob/bentob.py
- tests/unit/_internal/bento/test_bento.py
- tests/unit/_internal/models/test_model.py
- tests/unit/_internal/test_store.py
- tests/unit/test_models.py
This is just the export implementation; will add tests and import etc. later but putting this up for review so we can talk about how this should work.
Currently, the API supports:
- `bento.export("")` - export the bento to `name-version.bento` in the current directory. this isn't a default because it feels weird for the API to have a default; arguably this should be handled by the CLI.
- `bento.export("dir")` - if `dir` is a directory, will output to `dir/name-version.bento`.
- `bento.export("dir/")` - even if `dir` is not a directory, try to output to `dir/name-version.bento`. note this doesn't actually try to create the folder, so save for weird filesystems where directories don't need to be created this will error if `dir` doesn't exist.
- `bento.export("/path/to/filename")` - if …
> Implement more sophisticated import / export APIs

- bentoml/_internal/exportable.py
There was an error when importing a model from S3 using the command:
```
bentoml models import s3://my-bucket/models/my_model.bentomodel
```
The first error appeared in `copy.py` file from `fs` package:
```
TypeError: copy() got an unexpected keyword argument 'preserve_time'.
```
After removing this param on `fs` package for testing, the error changed:
```
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the CopyObject operation: This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.
```
When looking into file `exportable.py`, I noticed an error on `copy_file` method, that was trying to copy a file over itself.
After a change, …
> fix: import model from S3

- bentoml/_internal/bento/docker/init.sh
This PR proposes a fix for the way that the desired Python version of the Docker image is extracted by the `init.sh`.
Currently, the `init.sh` script used by BentoML infers the desired Python version by slicing the value of the saved Python version, retrieving the first three chars. But if the saved Python version is >3.9 (such as 3.10), the script returns 3.1 as the desired Python version, which is incorrect.
The proposed change uses parameter expansion to remove the patch version from the saved Python version, fixing the issue.
I was unable to test the entire script, but I tested the area affected, and can confirm that it works. Since parameter expansion is native to bash, this modification should not break the code.
> fix: extract correct desired Python version

- bentoml/_internal/service/loader.py
When `import_service` failed, we tried to `load_bento` but supply `change_global_cwd` to arugment `bento_store`. This behavior shadows the true error message and always failed the retry
> fix(service): fix `load_bento` arguments position when retrying after `import_service` failed

- bentoml/_internal/frameworks/sklearn.py
- bentoml/_internal/models/model.py
- bentoml/_internal/runner/container.py
- bentoml/_internal/runner/runnable.py
- bentoml/_internal/runner/runner.py
- bentoml/_internal/runner/runner_handle/remote.py
- bentoml/_internal/runner/strategy.py
- bentoml/_internal/runner/utils.py
- bentoml/_internal/server/__init__.py
- bentoml/_internal/server/cli/api_server.py
- bentoml/_internal/server/cli/dev_api_server.py
- bentoml/_internal/server/cli/runner.py
- bentoml/_internal/server/instruments.py
- bentoml/_internal/server/runner_app.py
- bentoml/_internal/server/service_app.py
- bentoml/_internal/utils/analytics/usage_stats.py
- bentoml/_internal/utils/formparser.py
- bentoml/models.py
`*args` and `**kwargs` are now handled like so:
```python
@Runnable.method(batchable=True, batch_dim=([1], 0))
def my_runner_method(*args):
...
```
Will have all arguments to `my_runner_method` batched with index 1.
Probably worth looking at this later, but for now this is probably good enough.
> feat(server): implement runner app

- bentoml/_internal/store.py
This deals with the fact that we only store times with second precision; this should not be an issue in practice because users should not be using "latest" in production code as it's meant as a convenience for local development.
> fix(store): use >= for time checking

- bentoml/_internal/bento/build_config.py
This fixes the issue where importing pip-tools was causing the root logger to be configured.
> fix(build): use subprocess to call pip-compile

- bentoml/_internal/cli/__init__.py
We are using `subprocess.check_output().encode()` to evoke other commands. But for Windows cmd.exe, the default encoding is not utf-8. So all features calling other commands like that will fail by default on Windows now.
> fix(cli): cli encoding error on Windows

- tests/integration/frameworks/models/xgboost.py
- tests/integration/frameworks/test_frameworks.py
Minor update to the XGBoost tests to cleanup and skip GPU tests depending on the `SUPPORT_NVIDIA_GPU` flag.
Note that batching tests are enabled when there are multiple inputs, because we're setting `batchable` to false in most frameworks so I'm not going to skip that test when it's false.
> test(frameworks): minor test improvements

- bentoml/_internal/bento/docker/templates/base.j2
Safe cat of pip_args.txt in case there are mulitple options
Escape references to EXTRA_PIP_INSTALL_ARGS so they are evaluated correctly
cat of pip_args.txt was not safe if there are multiple options, i.e. there's a space between two options
references to variables created in a heredoc scripts need to be escaped with a single preceeding slash
I was unable to build a container that referenced my internal package index.
Tested rebuild of containers with this change
There is no python code change, just a tweak to the docker file template.
No documentation change.
I hope that is all enough? Thanks!
> fix: Bug fix for 2596

- docs/source/frameworks/pytorch.rst
In the pytorch section of framework-specific guides, model was not specified in the save_model() call.
> docs: Add model in bentoml.pytorch.save_model() pytorch integration example

- .github/workflows/ci.yml
Noticed there's no CI on #2645; let's just have actions run on every PR?
> chore(ci): always enable actions on PR

- docs/source/index.rst
fix GitHub naming from toctree from `Github` to `GitHub`
> style: github naming

- bentoml/_internal/bento/docker/templates/_macros.j2
- bentoml/_internal/bento/docker/templates/base.j2
- bentoml/_internal/bento/docker/templates/miniconda_alpine.j2
- bentoml/_internal/bento/docker/templates/miniconda_debian.j2
- bentoml/_internal/bento/gen.py
- cached pip installation process with conda
- take advantage of jinja2 macros for conda snippets.
> perf(templates): cache python installation via conda

- bentoml/_internal/bento/docker/templates/miniconda_alpine.j2
- bentoml/_internal/bento/docker/templates/miniconda_debian.j2
it should install python first when using conda
> fix(conda): python installation order

- docs/source/concepts/model.rst
- docs/source/tutorial.rst
update tutorials with latest log changes
ideally we should use some sort of repl.it for all of this code block that can
be ran on the docs. Logging can then be updated correctly.
I updated this for now so that it fits with rc3 logs.
> docs: updates with latest logs change

- .github/workflows/frameworks.yml
- bentoml/_internal/frameworks/tensorflow_v2.py
- tests/integration/conftest.py
- tests/integration/frameworks/test_tensorflow_v2_unit.py
tensorflow data container should not be of type `_EagerTensorBase`
By default if eager_execution is enabled, then `Tensor` is of type `EagerTensor`
context: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L1045
> fix(tensorflow): register data container when eager execution is enabled

- bentoml/frameworks/onnxmlir.py
BentoML is used as one of the serving environments for onnx-mlir compiled model artifacts and a recent change in the number of entry points to the compiled model left our serving environment clients in a broken state. This PR fixes that and allows us to clients to resume normal use of BentoML for serving onnx-mlir compiled models.
Due to confusion on most people's parts on driving this manually inside of the onnx-mlir docker container, these tests will be driven through PR status logic and documentation will be introduced down the road so we don't face trouble like this again.
([instructions](https://github.com/bentoml/BentoML/blob/master/DEVELOPMENT.md#style-check-and-auto-formatting-your-code)). (A two line change is introduced following community …
> fix: Fix onnx mlir artifact

- setup.cfg
we will look into migrating to GenConverter after 1.0
> chore: lock cattrs <= 21.1.0

- bentoml/_internal/bento/build_config.py
- bentoml/_internal/bento/docker/templates/_macros.j2
- bentoml/_internal/bento/docker/templates/base.j2
Address #2666
also address one bug where if only wheels arguments is specified, it should
still respect content of wheels folder and install with given args
Also address a bug where if conda is specified without python field, install.sh should still be available.
Will update #2539 after this got merged. We should have unittest for 1.0
> fix: install.sh should be optional if python is not specified

- bentoml/_internal/server/__init__.py
--reload should work on Windows 
The issue lies at enabling `debug` for Circus plugin.
By default this enable plugins stdout and stderr to be pipe through the
supervisor, however,this only works on UNIX system.
This PR should enable windows user to use --reload. Current caveats is that the
output from the reloader plugin won't be pipe out to stdout
This should fix #2675
> fix: reload on windows

- bentoml/__main__.py
- bentoml/_internal/cli/__init__.py
- bentoml/_internal/cli/bento_server.py
When initializing we can see some empty dict when init. This is due to when
initializing circus supervisor doesn't have a components name.
```bash
2022-07-06T23:48:18-0700 [DEBUG] [] Default runner method set to `predict`, it can be accessed both via `runner.run` and `runner.predict.async_run`
2022-07-06T23:48:19-0700 [DEBUG] [] Default runner method set to `predict`, it can be accessed both via `runner.run` and `runner.predict.async_run`
2022-07-06T23:48:19-0700 [DEBUG] [] 'iris_classifier' loaded from '/Users/aarnphm/workspace/playground': bentoml.Service(name="iris_classifier", import_str="service:svc", working_dir="/Users/aarnphm/workspace/playground")
2022-07-06T23:48:19-0700 [INFO] [] Starting development BentoServer from "." running on http://127.0.0.1:3000 (Press CTRL+C to quit) …
```
> chore: generic components name for supervisor

- bentoml/_internal/server/__init__.py
- bentoml/_internal/utils/circus/watchfilesplugin.py
- tests/unit/_internal/utils/circus/test_watchfilesplugin.py
A somewhat hacky workaround to circus configuring logging when `debug` is set to true.
> fix(dev-server): fix logging for reload

- bentoml/_internal/frameworks/transformers.py
- docs/source/frameworks/transformers.rst
- docs/source/reference/frameworks/transformers.rst
Transformers docs should be called `Transformers` not `HuggingFace` (since
HuggingFace is the company )
> fix: transformers API docs

- bentoml/_internal/frameworks/onnx.py
On M1 machine, onnxruntime hasn't provided a wheel yet. There is a package
called `onnxruntime-silicon` that enables M1 devices to use `onnxruntime`
This PR adds `onnxruntime-silicon` to version checking for saving onnx model.
> chore(onnx): adding onnxruntime-silicon for m1 devices

- bentoml/_internal/runner/runner.py
- bentoml/_internal/server/cli/runner.py
- tests/unit/_internal/runner/test_runner.py
More clear log message when using runnable class name as runner name, and use colon for separating runner component names.
> chore: minor log fixes

- bentoml/_internal/frameworks/common/pytorch.py
> fix(framework): fix how pytorch DataContainer convert GPU tensor

- bentoml/_internal/io_descriptors/numpy.py
Due to changes made in field names in proto files, some of the functions stopped working properly. Changes are made to handle the conversion of arrays without the existence of old `dtype` field. While testing, encountered a problem with conversion for Timestamp and Duration. `Timestamp().FromDatetime(item)` syntax doesn't work for handling `datetime` objects. Similarly, `Duration().FromTimedelta(item)` doesn't work for `timedelta`. Changes are made to fix that issue.
those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting …
> chore: update protobuf conversion functions

- bentoml/_internal/runner/runner.py
runner.run() and runner.async_run() before
runner.run() after
This changes only affects TYPE_CHECKING runtime.
cc @sauyon
> chore: add type hint for run and async_run

- bentoml/_internal/runner/runner_handle/local.py
Background
-------------
Accoring to the doc of anyio https://anyio.readthedocs.io/en/stable/api.html#anyio.to_thread.run_sync , setting up the limiter should limit the thread count that used for this task. The default limiter is 40 threads, will take effect with `async_run(limiter=None)` during test.
But the limiter wont take effect once specified, like `async_run(limiter=anyio.CapacityLimiter(1))`. The limit gone. Threads count can reach a large number.
To reproduce
--------------
test on the general feature project under e2e tests.
Start 1000 requests at the same time:
```python
import aiohttp
client = aiohttp.ClientSession()
await asyncio.gather(*(client.post("http://127.0.0.1:3000/echo_json", json=[1]) for i in range(1000)))
```
For the 1.0 version: 
```
(tf2@py3.7)  bojiang ➜ …
```
> fix(runner): thread limiter doesn't take effect

- bentoml/_internal/io_descriptors/json.py
- docs/source/concepts/service.rst
Currently, when using a JSON io descriptor with a pydantic class, the input data type also depends on the validate_json option with is very confusing. Essentially when a user provides a pydantic class, it is expected to receive an instance of that pydantic class as the inference API callback function's input parameter. However, currently, this is only the case when validate_json=True. If the user sets a pydantic model while setting validate_json=False, it will still pass in a regular dict to user-defined API function and completely ignore the pydantic option.
This PR proposes to remove the `validate_json` option and make sure the input value type to user-defined API function is consistent:
* if pydantic is None, the input value will be type object
* if pydantic is not None, the input …
> bug: fix JSON io_descriptor validate_json option

- bentoml/_internal/utils/buildx.py
When invoking 
```
python -m bentoml containerize --cache-from "adsf/asdf:asdf" --cache-from "asdf/asdf:asdf" bento_t5:wyn742ar5g3v2ri3
```
I run into
```
args = [f"{k}={v}" for k, v in cache_from.items()]
AttributeError: 'tuple' object has no attribute 'items'
```
This PR extends the cli --cache-from consumption code to include the tuple case.
> fix: extend --cache-from consumption to python tuple

- bentoml/_internal/configuration/__init__.py
- bentoml/_internal/configuration/containers.py
- bentoml/_internal/configuration/default_configuration.yaml
- bentoml/_internal/server/runner_app.py
- bentoml/_internal/server/service_app.py
Fixes #2829 
No: requires external dependency (Jaeger)
Tested manually by
1. Take an existing working Bento (e.g. from using the basic iris-clf example)
2. Package the new bentoml wheel file into the Bento
3. Use docker-compose to set up the Bento and a Jaeger
```
version: '3.9'
services:
iris_clf:
build:
context: <Bento folder> …
```
> feat: add support for excluding urls from tracing

- bentoml/_internal/configuration/containers.py
- docs/source/guides/tracing.rst
In https://github.com/bentoml/BentoML/pull/2843, we can specify urls to exclude from tracing as a comma-separated string. It was suggested that this parameter should also support a list of strings. In addition, this PR also adds documentation for excluding routes from tracing.
This change was also manually tested using docker compose, by setting up the Bento and Jaeger. Test cases are a bit hard to …
> feat: add support for specifying urls to exclude from tracing as a list

- bentoml/_internal/configuration/containers.py
- tests/unit/_internal/test_configuration.py
> fix(configuration): merging global runner config to runner specific config

- bentoml/_internal/configuration/containers.py
- bentoml/_internal/configuration/default_configuration.yaml
- bentoml/_internal/server/grpc_app.py
- bentoml/_internal/server/instruments.py
Users can configure a port for prometheus metrics using `config.yml`. Works for both grpc and uvicorn server. For uvicorn server, if the specified port is busy, users can still access the metrics using `/metrics` endpoint.
@aarnphm @ssheng @sauyon  Any feedback is appreciated as always!
> feat: added port config for prometheus metrics

- bentoml/_internal/io_descriptors/json.py
- tests/unit/_internal/io/test_json.py
The default behavior of `json.dumps` is to transform the return `None` to a string `null`.
But let's say we want to set a status_code 204 (NO_CONTENT), in this case it is expected an empty body.
Then, even if the function returns `None`, an error like  `h11._util.LocalProtocolError: Too much data for declared Content-Length` is thrown because the response has a body (a string `null`).
I described this scenario in this [slack thread](https://bentoml.slack.com/archives/CKRANBHPH/p1659623872508249?thread_ts=1659476156.379999&cid=CKRANBHPH) too.
:bulb: Extra:
-  I've noticed that the tests `test_json_encoder` had an `or` in the assert expression. To make it more assertive, I refactored it to pass the expected result as a parameter. I'm use to doing this in this kind of test, to keep the …
> fix: `JSON(IODescriptor[JSONType]).to_http_response` returns empty body when the response is `None`.

- bentoml/_internal/server/__init__.py
- bentoml/_internal/service/loader.py
Before this PR, if users use debugger inside `service.py` lazily or eagerly:
lazy case:
```python
@svc.api(input=NumpyNdarray(), output=NumpyNdarray())
async def predict(input_series: NDArray[np.float16]) -> NDArray[np.int16]:
import pdb
pdb.set_trace()
return await iris_clf_runner.async_run(input_series)
```
eager case:
```python
import pdb
pdb.set_trace()
@svc.api(input=NumpyNdarray(), output=NumpyNdarray())
async def predict(input_series: NDArray[np.float16]) -> NDArray[np.int16]:
return await iris_clf_runner.async_run(input_series)
```
This would break when users use `serve`. This has to do with how circus manages
child process and how debugger like `pdb` requires process' stdin. By default
circus omit child stdin, via [`close_child_stdin`](https://circus.readthedocs.io/en/latest/for-o …
> fix: debugger breaks on circus process

- bentoml/_internal/runner/runnable.py
- bentoml/_internal/runner/runner.py
- bentoml/_internal/types.py
- setup.cfg
Remove dependency on `typing-extensions`.
Currently uses code from @bojiang's `typing_utils` for `get_args` and `get_origin` specifically for Python 3.7.
> chore: remove typing-extensions dependency

- bentoml/_internal/bento/build_config.py
- bentoml/_internal/bento/docker/templates/_macros.j2
- bentoml/_internal/bento/docker/templates/base.j2
`install.sh` and all related scripts generated by BentoML should use bash to run
instead of `chmod +x`.
Usually `chmod +x` are not recommended for container application.
cc @sauyon
> fix: remove chmod install scripts

- bentoml/_internal/utils/analytics/schemas.py
- bentoml/_internal/utils/analytics/usage_stats.py
- tests/conftest.py
- tests/unit/_internal/utils/test_analytics.py
Add some more unit test for metrics.
> qa: analytics unit tests

- bentoml/__init__.py
- bentoml/_internal/utils/buildx.py
- bentoml/_internal/utils/docker.py
- bentoml/bentos.py
- bentoml_cli/containerize.py
`-t` should create multiple docker image tag. This PR address the current
behaviour where the only last tag will be omitted.
> fix(containerize): supports passing multiple tags

- bentoml/_internal/configuration/containers.py
- bentoml/serve.py
- bentoml_cli/serve.py
- bentoml_cli/server/http_api_server.py
- bentoml_cli/server/http_dev_api_server.py
> feat: Add SSL support for http api servers via bentoml serve

- bentoml/_internal/frameworks/mlflow.py
When importing a MLFlow model with a models:/ URI, the downloader puts the files at the registered model path directly into the `dst_path`.  When `dst_path` is specified as `bento_model.path` in this case, the downloader simply returns that same value.  If `bentoml_model.path` had the value `/tmp/test_tmp_path`, then the subsequent rename of the downloaded dir to `mlflow_model` to turn into the equivalent of:
`shutil.move(/tmp/test_tmp_path, /tmp/test_tmp_path/mlflow_model)`, which is going to always fail.  The other URI types I've tried don't seem to do this, they all seem to create a subdirectory under `bento_model.path` as a side effect of the download.
This fix creates an extra directory to download into, so if a `models:/` URI is used, it will instead download into this directory and …
> fix: importing mlflow:/ urls with no extra path info

- bentoml/_internal/configuration/containers.py
- bentoml/_internal/configuration/default_configuration.yaml
- bentoml/_internal/runner/runner_handle/remote.py
- tests/unit/_internal/test_configuration.py
Fixes #2888 
eg
```yaml
runners:
timeout: 400 #seconds (global)
pytorch_runner:
timeout: 500 # individual timeouts for specific runners
```
by default all runner have a timeout of 300 seconds 
> feat: add timeout option for bentoml runner config

- bentoml/__init__.py
- tests/test_cli_regression.py
This PR speeds up CLI performance by 100ms
Tested with `hyperfine` with 3 rounds of warmup and 1000 runs.
This PR also refactor some of the utilities functions that is only used by `bentoml_cli`
to `bentoml_cli` folder, which also helps with import speeds
This PR also add a regression tests to make sure that in the future, if we accidentally
introduce a heavy imports, we will be able to catch it.
> perf(cli): speed up

- .github/workflows/ci.yml
- bentoml/_internal/io_descriptors/json.py
This PR removes an eager check for a pydantic object.
Our JSONEncoder should already handle pydantic object lazily
https://bentoml.slack.com/archives/CKRANBHPH/p1660930201114169
> fix(json): revert eager check

- bentoml_cli/utils.py
- docs/source/guides/configuration.rst
- docs/source/guides/tracing.rst
We used a `--config` flag in our bentoml cli to load the bentoml config. However, the recommended way to load the config is by setting the env var `BENTOML_CONFIG` to the config file's path. This PR will remove the `--config` flag from `bentoml_cli`
> chore: remove `--config` flag to load the bentoml runtime config

- bentoml/_internal/utils/formparser.py
This should alleviate some of the performance issues observed due to the current implementation of formparser: using a Python list for large data (greater than megabytes) appears to have a severely detrimental (effects measured in minutes) effect on performance.
> fix: use a temporary file for file uploads

- bentoml/_internal/utils/buildx.py
- bentoml/bentos.py
- bentoml_cli/containerize.py
This PR address to check for buildx earlier
This PR also remove cache stored for buildx to ensure we run that check everytime before
`bentoml containerize`
> chore(docs): earlier check for buildx

- bentoml_cli/serve.py
- bentoml_cli/start.py
Default value in help text is outputting incorrect value from config.
Before:
```
Options:
--production                 Run the BentoServer in production mode
--port INTEGER               The port to listen on for the REST api server  [default: <bound method
_ConfigurationItem.get of _ConfigurationItem(_config={'api_server': {'port': 3000,
'host': '0.0.0.0', 'backlog': 2048, 'workers': 1, 'timeout': 60, 'max_request_size':
20971520, 'metrics': {'enabled': True, 'namespace': 'BENTOML'}, 'logging': {'access':
{'enabled': True, 'request_content_length': True, 'request_content_type': True,
'response_content_length': True, 'response_content_type': True}}, 'cors': {'enabled':
False, 'access_control_allow_origin': None, 'access_control_allow_credentials': None,
'access_control_allow_methods': …
```
> fix(cli): helper message default values

- bentoml/_internal/frameworks/FRAMEWORK_TEMPLATE_PY
- bentoml/_internal/frameworks/catboost.py
- bentoml/_internal/frameworks/fastai.py
- bentoml/_internal/frameworks/keras.py
- bentoml/_internal/frameworks/lightgbm.py
- bentoml/_internal/frameworks/mlflow.py
- bentoml/_internal/frameworks/onnx.py
- bentoml/_internal/frameworks/picklable.py
- bentoml/_internal/frameworks/pytorch.py
- bentoml/_internal/frameworks/pytorch_lightning.py
- bentoml/_internal/frameworks/sklearn.py
- bentoml/_internal/frameworks/tensorflow_v2.py
- bentoml/_internal/frameworks/torchscript.py
- bentoml/_internal/frameworks/transformers.py
- bentoml/_internal/frameworks/xgboost.py
- bentoml/_internal/models/model.py
- bentoml/models.py
- tests/e2e/bento_server_general_features/bentofile.yaml
- tests/e2e/bento_server_general_features/train.py
- tests/integration/frameworks/test_picklable_model_impl.py
- tests/integration/frameworks/test_sklearn_impl.py
TODO:
for https://github.com/bentoml/BentoML/issues/2785
> feat(sdk): add external_modules option to save_model

- bentoml/_internal/server/runner_app.py
Catch and log errors raised inside runners explicitly. If not logged explicitly, Uvicorn will log the error but we will lose the trace context causing the exception log to contain no trace and span IDs.
```
2022-08-30T02:32:24-0700 [ERROR] [runner:iris_clf:1] Exception in ASGI application
File "/opt/miniconda3/envs/bentoml/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
result = await app(  # type: ignore[func-returns-value]
File "/opt/miniconda3/envs/bentoml/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
return await self.app(scope, receive, send)
File "/opt/miniconda3/envs/bentoml/lib/python3.9/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
raise …
```
> fix: log runner errors explicitly

- tests/unit/test_models.py
Another temporary fix for the weird store issue that seems to occur only on actions.
> ci: temp fix for models test

- bentoml/_internal/service/inference_api.py
I should probably write a test for the multipart descriptor...
> fix: fix context parameter for multi-input IO descriptors

- bentoml/_internal/frameworks/common/pytorch.py
When running pytorch runner with `async_run` method in production mode(not in dev mode), tensors with other type than `Float32` type is converted into `Float32` type.(Ex. `LongTensor` is converted to `FloatTensor`) And I think this bug is originated by [this](https://github.com/bentoml/BentoML/blob/3de0c9a33d595eb70f4618b8a043d66a3d48befa/bentoml/_internal/frameworks/common/pytorch.py#L170) line.
I made small test to check this issue. (numpy == 1.22.3 / torch == 1.12.1)
```python
import torch
import numpy as np
arr = np.array([1, 2, 3, 4], dtype=np.int64)
t1 = torch.from_numpy(arr)
t2 = torch.Tensor(arr)
assert t1.dtype == torch.int64
assert t2.dtype == torch.float32
```
Thus I think changing `torch.Tensor(ret)` to `torch.from_numpy(ret)` should resolve this bug. Please tell me if it was …
> fix: use `torch.from_numpy()` instead of `torch.Tensor()` to keep data type

- docs/source/frameworks/pytorch.rst
> docs: fix wrong name for example neural net

- bentoml_cli/bentos.py
- bentoml_cli/models.py
Remove unused `--no-trunc` from `bentoml models list` and `bentoml list`.
@aarnphm
> chore(cli): remove unused `--no-trunc`

- bentoml/_internal/bento/build_config.py
This change allows for environment variables with dashes in them.
@aarnphm
> fix: relax regex for setting environment variables

- bentoml/_internal/utils/analytics/schemas.py
- bentoml/_internal/utils/analytics/usage_stats.py
- bentoml/start.py
> feat: track serve update for start subcommands

- bentoml_cli/utils.py
I forgot we set debug mode globally and I didn't need to grab the value of the flag from the click arguments, so this was actually pretty simple :sweat_smile:
Should resolve #2966 @smidm, if you want to confirm.
> feat(cli): show full tracebacks in debug mode

- bentoml/_internal/utils/formparser.py
Fixes an oversight where if a user passed a multipart input with a `filename` to a descriptor that did not attempt to use request files, the descriptor would fail with a cryptic `RuntimeError: Receive channel has not been made available`.
> fix(multipart): support multipart file inputs to non-file descriptors

- bentoml/_internal/marshal/dispatcher.py
- bentoml/_internal/server/runner_app.py
> fix(runner): receive requests before cork

- bentoml/_internal/io_descriptors/image.py
This PR enables support for passing a list of mime types to the `Image` IO descriptor, which, alongside passing `accept_all_images=False`, will allow users to whitelist allowed image formats.
> feat(io/image): allow restricting mime types

- bentoml_cli/containerize.py
This PR fixes message output after successfully built Docker image where tags are None
> fix(grpc): docker message

- bentoml/_internal/io_descriptors/image.py
- tests/e2e/bento_server_general_features/tests/test_io.py
pdf reading is not supported by PIL
> revert(3017): filter write-only mime type for Image IO

- bentoml/grpc/v1alpha1/service.proto
I forgot to add this on the main gRPC PR. `pb.Part` should have a `serialized_bytes`
synonymous to `pb.Request` and `pb.Response`
> feat(proto): add `serialized_bytes` to `pb.Part`

- bentoml/_internal/io_descriptors/pandas.py
Bug Fix: PandasDataFrame orient does not change open api schema generation to expected format. 
Bug Fix: PandasSeries orient does not change open api schema generation to expected format. 
Separated openapi schema generation for each.
PandasSeries from_http_request() seem to be missing io.BytesIO.  Added it.
When specifying the pandas PandasDataFrame and PandasSeries input spec the generated open api schemas do not match the expected schema with the provided orient parameter.  This shows in the bento serve index webpage in the request body and successful response output sections.  This PR seeks to address this by adding orient to the schema generation in addition to the existing the dtype dict parameter (Dataframe) or dtype str parameter (Series) to return the correct Schema.
Fixes …
> fix(io): Pandas OpenAPI schema

- docs/source/concepts/bento.rst
- docs/source/concepts/service.rst
- docs/source/frameworks/tensorflow.rst
- docs/source/reference/frameworks/index.rst
There are some docs block that are not render
also start migrating :code: to double backtick for inline
> docs: updates on blocks that failed to render

- docs/source/guides/grpc.rst
> chore: update links

- bentoml/_internal/configuration/containers.py
revert some of changes before #3018
> fix(configuration): should validate config early

- pyproject.toml
Currently protobuf 3.19.5 is pretty much broken, and the latest version that is usuable
and not break stub is 3.19.4
this means that we can't also have to restrict grpcio not to use 1.48.2
> dependencies: ignore broken pypi combination

- bentoml/_internal/server/metrics/prometheus.py
- bentoml/_internal/utils/__init__.py
- bentoml/_internal/utils/analytics/schemas.py
- bentoml/_internal/utils/analytics/usage_stats.py
- bentoml/serve.py
- bentoml/start.py
- pyproject.toml
- tests/unit/_internal/utils/test_analytics.py
Fixes #2991 
Depends on #2984 
> feat: gRPC tracking

- bentoml/_internal/configuration/containers.py
- bentoml/_internal/configuration/default_configuration.yaml
- bentoml/_internal/log.py
- docs/source/guides/logging.rst
Move access logging format configuration from a top level config to under `api_server.logging.access` for semantic correctness.
> configuration: migrate schema to `api_server`

- bentoml/_internal/frameworks/mlflow.py
Cleanup some logic, qa with local postgres, mysql setup of mlflow registry.
cleanup some types as well.
> qa: cleanup MLflow

- bentoml/_internal/configuration/containers.py
- bentoml/_internal/configuration/default_configuration.yaml
- bentoml/serve.py
- bentoml_cli/serve.py
- bentoml_cli/start.py
`bentoml serve . --production` was ignoring `api_server.workers` in `bento_configuration.yaml`. This is now fixed. I believe I've maintained the previous behaviour when the value was not manually set by the user.
Fixes #(issue)
> fix(config): respect `api_server.workers`

- bentoml/serve.py
Remove unused imports from lazy imports
> chore(lint): remove unused import

- bentoml/__init__.py
Fix namespace collision with default builtin modules in sys.modules
> fix(import): namespace collision

- pyproject.toml
Dependencies resolution for pip-tools apparently will try to lock to the latest version
instead of depending on previous dependent packages.
The expected behaviour would be:
- grpcio == 1.42 -> (grpcio-health-checking should lock to 1.42)
However, this will lock grpcio-health-checking to latest.
This could be a bug, but imminent fix for this is to specify the boundary.
> chore(deps): ensure grpc resolve dependencies correctly

- .github/workflows/ci.yml
- .github/workflows/frameworks.yml
- DEVELOPMENT.md
- pyproject.toml
Instead of exporting pytest plugins via setuptools, we should do it via PYTEST_PLUGINS
to avoid interfere with users who already using pytest
Using environment variables also unblocks https://bentoml.slack.com/archives/CKRANBHPH/p1665006750560559
> fix(pytest): export plugin lazily via environment variables

- bentoml/serve.py
- bentoml/start.py
- bentoml_cli/worker/grpc_api_server.py
- bentoml_cli/worker/grpc_dev_api_server.py
This PR ensures that prometheus dir is created when users use `bentoml.metrics`
This is to update gRPC changes introduced from #3053
> fix(grpc): ensure prometheus dir is created

- bentoml/_internal/configuration/containers.py
- bentoml/_internal/server/grpc/server.py
- bentoml/serve.py
- bentoml/start.py
- bentoml_cli/serve.py
- bentoml_cli/start.py
- bentoml_cli/worker/grpc_api_server.py
- bentoml_cli/worker/grpc_dev_api_server.py
Initial SSL support for gRPC.
```bash
b serve-grpc --ssl-certfile credentials/cert.pem --ssl-keyfile credentials/key.pem --production --enable-reflection
```
To run on Docker:
```bash
docker run -it --rm -p 3000:3000 -p 3001:3001 --mount=type=bind,target=/credentials,source=$(pwd)/credentials iris_classifier:soc6p2ce62jvxgxi serve-grpc --ssl-certfile /credentials/cert.pem --ssl-keyfile /credentials/key.pem --production --enable-reflection
```
> feat(grpc): SSL/TLS support

- grpc-client/go/client
- grpc-client/go/go.mod
- grpc-client/go/go.sum
Ah `./go/client` shell scripts requires tidy before it can run
> chore(grpc-client): tidy mod when running shell script

- src/bentoml/_internal/configuration/containers.py
- src/bentoml/_internal/configuration/default_configuration.yaml
- src/bentoml/_internal/runner/runner.py
- src/bentoml/_internal/runner/runner_handle/__init__.py
- src/bentoml/_internal/runner/runner_handle/local.py
- src/bentoml/_internal/runner/runner_handle/remote.py
- src/bentoml/_internal/server/grpc_app.py
- src/bentoml/_internal/server/http_app.py
- src/bentoml_cli/worker/grpc_api_server.py
- src/bentoml_cli/worker/http_api_server.py
- tests/e2e/bento_server_http/tests/test_meta.py
- Added `is_ready` method to `RunnerHandle`'s `init` file, then implemented it in the local and remote runners
- Added new method to `Runner` to check that `RunnerHandle` is ready
- Added new method to HTTP service app's `on_startup` method to check the Runner in loop until it returns true
> feat: cascade health checks to runner

- src/bentoml/_internal/server/grpc/servicer.py
- src/bentoml/_internal/server/http_app.py
This makes multi-input descriptors more generic and allows users to define their own
> fix: use `InferenceAPI.multi_input` for parsing multipart

- pyproject.toml
- requirements/dev-requirements.txt
- requirements/frameworks-requirements.txt
- requirements/tests-requirements.txt
- tests/integration/frameworks/conftest.py
Adds all frameworks to dev-dependencies as well. Skips LightGBM on arm64 because it's not supported.
Removes most of the pytest flags to make pytest output a little more sane and fix some issues caused by the `importlib` import method.
Also, warns instead of failing if a framework is not installed. Worth noting that pytest ignores the warning completely, but I couldn't find a neat way of printing the warning.
> test: minor pytest fixes

- requirements/tests-requirements.txt
Remove framework-requirements.txt from tests, which fails the CI
> revert: remove frameworks-requirements.txt from test requirements

- docs/source/concepts/bento.rst
- docs/source/reference/api_io_descriptors.rst
- pyproject.toml
- src/bentoml/bentos.py
Add ability to install optional pydantic with `bentoml[io-json]`
> chore: add options to install pydantic with `bentoml[io-json]`

- src/bentoml_cli/serve.py
- src/bentoml_cli/start.py
We should be able to run the command `bentoml serve` outside of the directory containing bentofile.yaml, for example, by running `bentoml serve ..` in a subdirectory. This does not work today. These are WIP changes made during my pairing with @sauyon today.
> fix(cli): expands working_dir with default path

- pyproject.toml
- requirements/tests-requirements.txt
This PR tries to address locking issue with mismatch opentelemtry due
to inconsistency among opentelemetry release schedule
> chore: bumping opentelemetry dependencies

- src/bentoml/_internal/bento/build_dev_bentoml_whl.py
- src/bentoml/_internal/io_descriptors/base.py
- src/bentoml/_internal/io_descriptors/file.py
- src/bentoml/_internal/io_descriptors/image.py
- src/bentoml/_internal/io_descriptors/json.py
- src/bentoml/_internal/io_descriptors/multipart.py
- src/bentoml/_internal/io_descriptors/numpy.py
- src/bentoml/_internal/io_descriptors/pandas.py
- src/bentoml/_internal/io_descriptors/text.py
- src/bentoml/client.py
- tests/unit/_internal/io/test_image.py
> fix: IO OpenAPI spec for bentoml.client

- docs/source/guides/grpc.rst
- docs/source/reference/api_io_descriptors.rst
- src/bentoml/_internal/io_descriptors/pandas.py
- tests/e2e/bento_server_grpc/service.py
- tests/e2e/bento_server_grpc/tests/test_descriptors.py
Address #2994 
This PR brings `from_proto` and `to_proto` to PandasSeries, as well as polishing some of
the validation process for series
This PR will also add a functionality `from_sample` for creation of descriptor
> feat: PandasSeries `from_proto` and `to_proto`

- src/bentoml/_internal/bento/docker/templates/base_debian.j2
- src/bentoml/_internal/bento/docker/templates/cuda_debian.j2
The new image build Kaniko Dockerfile is broken. When using the CUDA Debian-based  template.
1. software-properties-common - must be run before the add-apt-repository command is called on the next command.
2. pipefail command - Kaniko is also not perceived
Use latest bentoml 1.0.7 (26 oktober 2022) (installed from pip install git+https://github.com/bentoml/BentoML.git)
Yatai v1.0.0-d7-6c68b8e
> fix(templates): ensure dependencies are met for CUDA templates

- src/bentoml/client.py
Fixes the newly changed async/sync bento client methods, and makes from_url synchronous using the stdlib `HTTPConnection` so that it can be used in both async and non-async contexts.
> fix: async bento client methods

- src/bentoml/_internal/bento/build_config.py
A hack to conform with TYPE_CHECKING
Before
After
> style: type checking hack

- src/bentoml/_internal/io_descriptors/pandas.py
Handles null type for Pandas for OpenAPI conversion
> fix: pandas openAPI handle nulltype

- src/bentoml/_internal/bento/docker/templates/_macros.j2
This PR fixes a bug where -o pipefail is not available in sh
This PR also remove the unset variable PYTHON_VERSION for conda
> fix: ensure conda not use pipefail and unset variables

- src/bentoml/_internal/bento/build_config.py
Ensure our install.sh uses pip3 and python3
For distro such as amazonlinux, the docker container includes both python2 and python3.
python is often aliased with python2, hence this PR explicitly state the distinction.
> fix(templates): ensure to use python3 and pip3

- examples/quickstart/service.py
- examples/quickstart/train.py
Makes our quickstart example batchable by default.
> feat: make quickstart batchable

- src/bentoml/_internal/bento/build_dev_bentoml_whl.py
Fix checking grpc availability when BENTOML_LOCAL_BUNDLE_BUILD is specified
> fix: lazy check for stubs via path when install local wheels

- src/bentoml/_internal/service/openapi/__init__.py
- src/bentoml/_internal/service/openapi/specification.py
Fixes https://github.com/bentoml/BentoML/issues/3177
https://swagger.io/specification/
> fix(openapi): remove summary field under Info

- docs/source/guides/migration.rst
Thanks for good open source project!
I have been using bentoml since version 0.13.1, I checked the migration guide once I heard the news that version 1 was released this time.
While following the migration guide, I've experienced that bentofile.yaml's indent is wrong and doesn't work, so I'm trying to contribute to my favorite open source, although it's minor.
> docs: remove whitespaces in migration guides

- src/bentoml/_internal/bento/build_config.py
This PR ensures converter for our options handles NoneType when using `bentoml.bentos.build`
This PR also improve type annotations for `BentoBuildConfig.__init__`
> fix(build_config): validation when NoneType

- docs/source/guides/migration.rst
Fix indentation in migration.rst
> fix(docs): indentation in migration.rst

- src/bentoml/_internal/configuration/default_configuration.yaml
This has to do with when using API from `bentoml.serve` directly, the value for SSL
is not set, whereas on CLI, all fields are default to None.
Since the configuration value is not set under our default configuration files, using `serve_[http|grpc]_*`
directly will result in simple_di error
```prolog
File "/Users/aarnphm/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Users/aarnphm/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/Users/aarnphm/workspace/playground/scripts/run.py", line 18, in <module>
serve_http_development(
File "/Users/aarnphm/.pyenv/versions/3.10.4/lib/python3.10/site-packages/simple_di/__init__.py", …
```
> fix(ssl): provide default values in configuration

- src/bentoml/serve.py
Previously we disabled always disabled runner logging on Windows. This fixes this.
> fix: don't ignore logging conf

- src/bentoml/_internal/external_typing/tensorflow.py
- src/bentoml/_internal/frameworks/tensorflow_v2.py
- src/bentoml/_internal/utils/tensorflow.py
- tests/integration/frameworks/models/tensorflow.py
> feat: tensorflow multi outputs support

- docs/source/frameworks/pytorch.rst
> docs: cleanup whitespace and typo

- src/bentoml_cli/worker/runner.py
This mirrors the keep-alive we have set in our runner clients, which uvicorn does not appear to honor.
> fix(runner): set uvicorn keep-alive

- .github/workflows/frameworks.yml
- src/bentoml/_internal/frameworks/onnx.py
- src/bentoml/_internal/utils/onnx.py
- tests/integration/frameworks/models/onnx.py
- multiple outputs support
- more detailed input type casting
Fixes #(issue)
> perf: refine onnx implementation

- pyproject.toml
- src/bentoml/_internal/io_descriptors/base.py
- src/bentoml/_internal/io_descriptors/file.py
- src/bentoml/_internal/io_descriptors/image.py
- src/bentoml/_internal/io_descriptors/json.py
- src/bentoml/_internal/io_descriptors/multipart.py
- src/bentoml/_internal/io_descriptors/numpy.py
- src/bentoml/_internal/io_descriptors/pandas.py
- src/bentoml/_internal/io_descriptors/text.py
- src/bentoml/_internal/service/openapi/__init__.py
- src/bentoml/_internal/service/openapi/specification.py
- src/bentoml/_internal/utils/__init__.py
- src/bentoml/bentos.py
- tests/unit/_internal/io/test_base.py
- tests/unit/_internal/io/test_numpy.py
`from_sample` for all of our IO descriptor
> feat: `from_sample` for IO descriptor

- src/bentoml/_internal/io_descriptors/base.py
- src/bentoml/_internal/io_descriptors/file.py
- src/bentoml/_internal/io_descriptors/image.py
- src/bentoml/_internal/io_descriptors/numpy.py
- src/bentoml/_internal/io_descriptors/pandas.py
- tests/unit/_internal/io/test_numpy.py
> fix: from_sample override logic

- src/bentoml/_internal/tag.py
Thanks for maintaining a nice source project!
I've found the missing 'f' for `tag_max_length_error_msg`, `bentoml._internal.tag`. 
Thanks.
> fix: missing f-string in tag validation error message

- .github/dependabot.yml
With recent support for PEP621 from dependabot, we can use it to update our
pyproject.toml
> chore(build): add dependabot for pyproject.toml

- examples/custom_model_runner/README.md
Add table closing tag on instruction 4
> fix(docs): missing `table` tag

- pyproject.toml
- src/bentoml/_internal/monitoring/api.py
- src/bentoml/_internal/monitoring/opentelemetry.py
- src/bentoml/_internal/monitoring/otlp.py
Now bentoml monitoring can work with any collection libs that support otlp
> feat(sdk): implement otlp monitoring exporter

- src/bentoml/_internal/bento/build_config.py
The generated Dockerfile inside Bento will now be stripped down without BuildKit syntax.
This is for purpose of serving users who wants to build directly using this Dockerfile.
By default `bentoml containerize` is the recommended way and it uses BuildKit by default.
To opt-out specify `DOCKER_BUILDKIT=0`
Signed-off-by: Ubuntu <29749331+aarnphm@users.noreply.github.com>
> chore: generate plain dockerfile without buildkit syntax

- src/bentoml/_internal/frameworks/fastai.py
- src/bentoml/_internal/frameworks/mlflow.py
This PR cleanup type ignore to and catch module not found error for mlflow.
Some cases it hits ModuleNotFoundError instead of ImportError when mlflow is not available.
Signed-off-by: Aaron Pham (EC2) <29749331+aarnphm@users.noreply.github.com>
> style: remove `# type: ignore`

- src/bentoml/_internal/frameworks/sklearn.py
Fixes wrong instruction for install scikit-learn.
> fix: instructions for missing sklearn dependency

- src/bentoml/_internal/container/base.py
Make sure to stream logs when DOCKER_BUILDKIT=0 is set.
Before this will go to the below leaf, which uses check_output.
> fix(container): ensure to stream logs when `DOCKER_BUILDKIT=0`

- src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
- src/bentoml/_internal/container/generate.py
User know need to setup NVIDIA_VISIBLE_DEVICES now as we unset this be default when using cuda to prevent a known memory leak.
```python
docker run -e NVIDIA_VISIBLE_DEVICES=all ...
```
If user are running container then one might have to provide additional `-e` flag.
> fix: unset `NVIDIA_VISIBLE_DEVICES` when cuda image is used

- pyproject.toml
Bumping typeshed for pyright to 3.11 GA
> chore(pyproject): bumping python version typeshed to 3.11

- src/bentoml/_internal/bento/build_config.py
Parsing path for env field under ``docker``
> feat: parsing path for env

- src/bentoml/_internal/io_descriptors/pandas.py
remove assertion check for `_dtype`, as pd.read_json and read_csv does accept dtype with bool for auto infer types
> fix: remove assertion for dtype

- src/bentoml/__init__.py
Enable users to do the following:
```python
import bentoml
client = bentoml.client.Client.from_url("localhost:3000")
```
> feat: client lazy load

- src/bentoml/_internal/bento/gen.py
- src/bentoml/_internal/container/base.py
- src/bentoml/_internal/container/generate.py
- src/bentoml/_internal/utils/buildx.py
- src/bentoml_cli/utils.py
provide backward shim for bentoctl until it migrates to public API
I have tested with sagemaker. with and without conda.
> chore: provides shim for bentoctl

- src/bentoml/_internal/server/runner_app.py
> fix(runner): content-type error

- src/bentoml/_internal/server/grpc/servicer/v1/__init__.py
- src/bentoml/grpc/v1/service.proto
- src/bentoml/grpc/v1/service_pb2.py
- src/bentoml/grpc/v1/service_pb2.pyi
- src/bentoml/grpc/v1/service_pb2_grpc.py
- src/bentoml/grpc/v1/service_pb2_grpc.pyi
Add a `ServiceMetadata` rpc that passing additional service metadata.
This is helpful for writing Python Client.
> feat(grpc): adding service metadata

- docs/source/guides/index.rst
- docs/source/guides/monitoring.rst
- docs/source/integrations/index.rst
> docs: Update monitoring docs format

- src/bentoml/_internal/bento/build_config.py
- src/bentoml/_internal/container/generate.py
- src/bentoml/_internal/server/grpc/servicer/v1/__init__.py
Fixes #3325, a regression introduced by #3164
> fix: don't overwrite user base image

- pyproject.toml
- src/bentoml/_internal/bento/build_config.py
packaging 22.0 removes LegacyVersion, which pip-requirements-parser are currently using
> fix: add upper bound for packaging version

- src/bentoml/_internal/frameworks/transformers.py
Bug Fix: add task aliases of transformers pipeline supported tasks
I ran into an issue today trying to load a Huggingface pipeline after it was saved via:
```
nlp = pipeline('ner', model=model, tokenizer=tokenizer)
bentoml.transformers.save_model(name="ner", pipeline=nlp)
runner = bentoml.transformers.get("ner:latest").to_runner()  # fails here
``` 
The "ner" task is one of the `[TASK_ALIASES](https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/__init__.py#L150)` in transformers pipeline which maps to a SUPPORTED_TASK.  Funny thing is `save_model()` has TASK_ALIASES support but maybe it was forgotten in `load_model()`.
guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pu …
> fix(transformers): check for task aliases

- .github/workflows/ci.yml
- .github/workflows/frameworks.yml
- requirements/tests-requirements.txt
- bumping base python version for actions/python to 3.8
- unrestrict protobuf requirements for tests
> fix: CI breakage

- src/bentoml/_internal/container/generate.py
revert user templates handling logics to 1.0.10
See https://bentoml.slack.com/archives/CKRANBHPH/p1671009900837059
> fix: make sure to handle relative path for templates

- src/bentoml/_internal/server/static_content/swagger-initializer.js
- src/bentoml/_internal/service/openapi/__init__.py
- src/bentoml/_internal/service/openapi/specification.py
This allows for bento services to be rewritten to under a sub-page (see https://github.com/bentoml/BentoML/issues/3258).
> fix: use relative urls in swagger UI

- src/bentoml/_internal/configuration/containers.py
Found this during developing yatai-deployment
> chore(config): ignore blank lines in bentoml config options

- src/bentoml/_internal/runner/runner.py
This works around an issue where Starlette handles exceptions in startup, hiding the actual issue from the user.
In production mode, this will double print the exception, but that doesn't seem like a particularly important problem, since this is an exception and the application fails to start anyway.
We should probably do a little more digging on the implementation of the ASGI lifespan protocol, but for now this should do.
> fix: log error when runnable instantiation fails

- src/bentoml/client.py
This allows for putting bento servers behind `server.com/bento-name/`, see #3258.
> fix: allow passing server URLs with paths

- src/bentoml/_internal/server/server.py
- src/bentoml/bentos.py
- src/bentoml_cli/serve.py
> fix: serve missing logic from #3321

- src/bentoml/_internal/io_descriptors/base.py
> fix: handling KeyError when accessing IODescriptor spec

- src/bentoml/client.py
- implments `__enter__`,`__exit__`,`__aenter__`and `__aexit__`
A dummy implementation is added to support to context protocol as it is required for the 'with' statement.
The implementation of exit method is empty as client does not have any persistent connection, each api call is processed in a separate aio.http session.
Fixes #(issue)
> feat: add context manager support for `bentoml.client`

- src/bentoml/_internal/frameworks/pytorch_lightning.py
fix pytorch-lightning docs typo
> chore: migrate to newer API in docstring

- src/bentoml/_internal/io_descriptors/multipart.py
Previously the schema components from JSON inputs would not be generated by the MultiPart IO Descriptor. See issue #3436
Copied from corresponding issue:
> When creating an API endpoint with a Multipart Input, where one of the child inputs is JSON with a pydantic model with an Enum field, the resulting OpenAPI spec does not include the schema component for the Enum field.
The approach here is just to call the `openapi_components` for all children of the MultiPart input and then merge all the dictionaries together. I've looked over all of the IO descriptor classes and it appears that the JSON input is the only one that ever returns a dict here, so I believe this won't cause any issues with any of the other input types.
Fixes #3436 …
> feat: openapi_components method for Multipart

- .github/workflows/ci.yml
ci: disable 3.10 tests on x86 mac
The tests pass locally with M1 mac. I don't realy have a x86 mac to test ;(
> ci: disable 3.10 e2e for gRPC on Mac X86

- src/bentoml/_internal/exportable.py
> chore(exportable): update exception message and errors imports

- src/bentoml_cli/containerize.py
Currently, passing a boolean through `--opt` will be overridden no matter what by compatible options layer for buildx and shared options.
This PR address where the value that is already memorized will be skipped by the compatible layer.
> fix(cli): overriding memoized options via `--opt`

- src/bentoml/_internal/yatai_client/__init__.py
- src/bentoml/_internal/yatai_rest_api_client/config.py
- src/bentoml_cli/bentos.py
- src/bentoml_cli/models.py
- src/bentoml_cli/yatai.py
The `.yatai.yaml` configuration under `BENTOML_HOME` already supports contexts to communicate with multiple Yatai instances through different API tokens today. However, the same functionality was not exposed to the CLI commands and YataiClient API. This PR exposes setting and selecting contexts in the CLI.
Yatai Log-in
```
> bentoml yatai login --api-token xxx --endpoint https://yatai1 --context yatai1
Successfully logged in as user "ssheng" in organization "yatai1".
> bentoml yatai login --api-token xxx --endpoint https://yatai2 --context yatai2
Successfully logged in as user "ssheng" in organization "yatai2".
```
Bento push & pull
```
> bentoml push iris_classifier:x67srpdqs25aicvj --context yatai1
> bentoml push iris_classifier:x67srpdqs25aicvj --context yatai2
```
Model push & pull …
> feat: YataiClient context to communicate with multiple Yatai instances

- requirements/docs-requirements.txt
This should fix the API documentation.
> docs: add spark to docs requirements

- docs/source/reference/metrics.rst
To silent sphinx warning. Documentation for metrics will still work with `help()`
> docs(metrics): remove API reference

- src/bentoml/triton.py
We have already raise an exception if users pass in allow-metrics
> chore(triton): remove default set allow-metrics

- src/bentoml/_internal/server/server.py
**enter** should return self instead of yielding it
> fix(serve): return self within context manager

- tests/unit/_internal/runner/test_runner.py
The test `test_runner` misses several checks:
- This PR improves `test_runner` by adding several untested cases, both for valid and invalid runners.
- I also refactored the original test, which was too long.
In summary, the novel tests are now smaller, clearer, and more focused, which is best practice when writing tests.
> test(unit): adding test cases for runners

- tests/unit/_internal/configuration/test_helpers.py
This PR improves the tests in `test_helpers` like I did in #3514.
I added new tests and also refactored existing ones.
Again, the novel tests are smaller and more focused, with more descriptive names.
> test(unit): configuration helpers

- docs/source/guides/envmanager.rst
- docs/source/guides/index.rst
- src/bentoml/_internal/configuration/__init__.py
- src/bentoml/_internal/configuration/containers.py
- src/bentoml/_internal/env_manager/__init__.py
- src/bentoml/_internal/env_manager/envs.py
- src/bentoml/_internal/env_manager/manager.py
- src/bentoml/bentos.py
- src/bentoml_cli/env_manager.py
- src/bentoml_cli/serve.py
- tests/unit/_internal/test_env_manager.py
- tests/unit/bentoml_cli/test_env_manager.py
The env manager allows you to run `bentoml serve` in an isolated environment. This PR adds support for creating conda environment
```
> bentoml serve --env conda <bento>
```
The created environment is created under `$BENTOML_HOME/env` if `<bento>` is loaded to bentostore. For project-level invocation the created environment is ephemeral. 
To clean up the environment created, `rm -rf $BENTOML_HOME/env`
those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation) …
> feat: conda env for bentos in bentostore

- docs/source/guides/index.rst
Add the env manager docs to docs index
> docs: update env manager docs to grid index

- src/bentoml/_internal/bento/build_config.py
- src/bentoml/_internal/container/__init__.py
We will include Dockerfile.template into the bento if users specify a `dockerfile_template`
This is required for the reconstruction of the Dockerfile during containerize steps.
Address #3491 
> fix: include dockerfile_template to Bento for containerize

- src/bentoml/_internal/server/server.py
> fix(server): deprecate client and cache get_client

- src/bentoml/bentos.py
add triton_options to `bentoml.serve`
> chore(serve): update options for triton_options

- src/bentoml/_internal/models/model.py
remove ignore comments for cattrs as it is fully typed
> chore(type): remove cattr type ignore

- pyproject.toml
- requirements/tests-requirements.txt
> chore: bumping otlp deps to 1.15

- examples/README.md
Add an example index showcasing their frameworks, models, and additional functionality for easy search and discovery.
> docs: Add an example index

- pyproject.toml
- requirements/tests-requirements.txt
Reverts bentoml/BentoML#3351 
It breaks the monitoring features.
```python
Traceback (most recent call last):                                                                                                                                                                                             
File "/home/agent/BentoML/src/bentoml/_internal/server/http_app.py", line 324, in api_func                                                                                                                                      
output = await api.func(input_data)                                                                                                                                                                                         
File …
```
> revert: "chore: bumping otlp deps to 1.15"

- .github/workflows/frameworks.yml
- requirements/frameworks-requirements.txt
- src/bentoml/__init__.py
- src/bentoml/_internal/frameworks/diffusers.py
- src/bentoml/diffusers.py
- tests/integration/frameworks/models/diffusers.py
> feature(framework): diffusers

- src/bentoml/_internal/utils/formparser.py
Should fix the formparser for starlette==0.25.
@ssheng I've only done basic testing with a simple test, and there's one minor issue below, this may need polishing or we may want to just quickly replace it.
> fix: update formparser for new starlette

- src/bentoml/_internal/runner/runner_handle/remote.py
Address the following deprecation from aiohttp
```prolog
~/workspace/bentoml/src/bentoml/_internal/runner/runner_handle/remote.py:98: DeprecationWarning: verify_ssl is deprecated, use ssl=False instead
self._conn = aiohttp.TCPConnector(
```
> chore(aiohttp): remove deprecated verify_ssl to ssl

- src/bentoml/_internal/io_descriptors/file.py
- src/bentoml/_internal/io_descriptors/image.py
- src/bentoml/_internal/io_descriptors/multipart.py
- src/bentoml/_internal/io_descriptors/numpy.py
- src/bentoml/_internal/io_descriptors/pandas.py
- src/bentoml/_internal/server/grpc/servicer/v1alpha1/__init__.py
- tests/unit/_internal/io/test_base.py
- tests/unit/_internal/io/test_file.py
- tests/unit/_internal/io/test_image.py
- tests/unit/_internal/io/test_json.py
- tests/unit/_internal/io/test_multipart.py
- tests/unit/_internal/io/test_numpy.py
- tests/unit/_internal/io/test_text.py
Handle File changes from v1alpha1 to v1
refactor from #3256 
> fix(grpc): handle backward protocol version

- pyproject.toml
This shields us from incompatibility issues with starlette APIs until we find a more permanent solution.
/cc @ssheng
> chore: lock starlette version

- src/bentoml/bentos.py
- src/bentoml_cli/bentos.py
> chore(cli): figlet to show on CLI only

- src/bentoml_cli/bentos.py
- src/bentoml_cli/models.py
> chore(cli): using default background as color

- src/bentoml/_internal/marshal/dispatcher.py
- src/bentoml/_internal/server/runner_app.py
Enable cork for non-batched workloads, and immediately dispatch a batch if the queue contains enough requests.
This didn't actually help much with the case I was looking at, but we should have done this to begin with anyway.
> feat: enable cork for non-batched workloads

- src/bentoml/_internal/configuration/v1/__init__.py
- src/bentoml/_internal/configuration/v1/default_configuration.yaml
- src/bentoml/_internal/runner/runner_handle/remote.py
This is a band-aid workaround to an issue where the runner server gets overloaded by request load, especially in synthetic scenarios, which causes significant CPU usage to be dedicated purely to parsing requests.
> fix: use a semaphore to limit runner connections

- src/bentoml/_internal/io_descriptors/numpy.py
- src/bentoml/_internal/io_descriptors/pandas.py
- tests/unit/_internal/io/test_numpy.py
> fix: make sure not to override user set values for from_sample

- pyproject.toml
> revert(pyproject): add back pytest plugins

- docs/source/guides/configuration.rst
- src/bentoml/_internal/configuration/containers.py
- src/bentoml/_internal/configuration/v1/__init__.py
- src/bentoml/_internal/configuration/v1/default_configuration.yaml
- tests/e2e/bento_server_http/configs/cors_enabled.yml
- tests/e2e/bento_server_http/tests/test_meta.py
- The CORS configuration naming mistake in docs
- deprecate `access_control_ allow_origin`, use `access_control_allow_origins` instead
- `access_control_allow_origins` and `access_control_allow_headers` should be converted to list when passed to starlette's `CORSMiddleware`
- more test cases to cover origin mismatch
> fix(configuration): CORS docs, `allow_origins` and `allow_headers`

- src/bentoml/_internal/container/buildctl.py
- src/bentoml_cli/containerize.py
People who use buildctl should probably know how to use it.
Remove an auto --output from tag
> fix(containerize): remove autoconfig for buildctl

- src/bentoml/bentos.py
- src/bentoml/serve.py
- src/bentoml/start.py
- src/bentoml/triton.py
- src/bentoml_cli/serve.py
- src/bentoml_cli/start.py
Set users to pass options via runners options in service definition
> fix(triton): enable runtime options

- src/bentoml/_internal/io_descriptors/file.py
- tests/e2e/bento_server_http/tests/test_io.py
I think this makes more sense; the file IO descriptor shouldn't care what kind of data it receives unless the user specifies it.
> feat: make file io descriptor allow any mime type by default

- src/bentoml/_internal/marshal/dispatcher.py
Refactor to make this code more reasonable.
> chore(dispatcher): refactor out training code

- src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
This PR fixes a bug from #3673 where it only copies the pip layers first. This
breaks the setup_script features if setup_script requires files inside src layer
The copy layer should be moved before the setup_script is ran.
> fix: copy files before running `setup_script`

- src/bentoml/metrics.py
remove experimental warning for metrics
> chore: remove experimental warning for `bentoml.metrics`

- src/bentoml/_internal/marshal/dispatcher.py
Address issue #3710 by narrowing types passed to functions so we can access the batch size if a client pre batches their input. Also raise an error if a single batch submitted by the client exceeds the max_batch_size. This lets us accurately batch requests such that the batch is less than the configured max_batch_size in the main dispatcher loop. 
I didn't touch any of the logic that dealt with inferring the queue size. 
in Bentoml/examples/quickstart created a configuration.yaml 
```
runners:
batching:
max_batch_size: 5
```
started the server with the following command 
```
BENTOML_CONFIG=./configuration.yaml b serve --production
```
added custom logging to sklearn.py.
```
def add_runnable_method(method_name: str, options: ModelSignature):
def _run(
self: SklearnRunnable, input_data: …
```
> fix: Make it so the configured max_batch_size is respected when batching inference requests together 

- .github/workflows/frameworks.yml
- tests/integration/frameworks/models/pytorch_lightning.py
Locking keras to be <2.12 since 2.12 has breaking change on the optimizer
fixes torch.jit.script types.
Fixes #(issue)
> fix(tests): broken CI

- src/bentoml/_internal/runner/container.py
- src/bentoml/_internal/utils/pickle.py
- tests/unit/_internal/utils/test_pickle.py
This PR is an improvement of #3606 . Instead of using pickle5 to avoid memory copying of a single numpy ndarray, codes improved by this PR can avoid copying of any composite data structure (e.g. a list of ndarray) containing numpy ndarray or pandas dataframe.
Fixes #(issue)
> feat: apply pep574 out-of-band pickling to DefaultContainer

- src/bentoml/server.py
This PR addresses two issues:
1. Currently on main, `bentoml.Server` defaults to use `serve-http` as serve_cmd, which means GrpcServer won't work. This PR fixes that by passing `serve_cmd` to the server args.
2. After creating the server, there is no way to pass down subprocess args to the actual process. This PR adds `**kwargs` as passthrough to server.process 
those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting …
> fix: passing serve_cmd and passthrough kwargs

- src/bentoml/_internal/frameworks/transformers.py
- src/bentoml/_internal/frameworks/utils/transformers.py
Patching the available check for transformers 4.18
> patch: backports module availability for transformers<4.18

- src/bentoml/_internal/models/model.py
- tests/integration/frameworks/test_transformers_unit.py
A slightly nicer way for loading model instances without thinking about which module to use - which is common when building custom runners or testing saved models. Here's an example of usage without vs. with this method added:
Let's say we saved a CLIP model from the transformer:
```python
from transformers import CLIPModel, CLIPProcessor
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
bentoml.transformers.save_model('CLIP:clip-vit-base-patch32', model, custom_objects={'processor': processor})
```
Without this method, loading the model and processor looks like this:
```python
MODEL_TAG = 'clip:clip-vit-base-patch32'
model = bentoml.transformers.load_model(MODEL_TAG)
model_obj = …
```
> feat: add `model#load_model` method

- docs/source/concepts/runner.rst
- docs/source/guides/index.rst
- docs/source/guides/scheduling.rst
- pyproject.toml
- src/bentoml/_internal/configuration/containers.py
- src/bentoml/_internal/configuration/v1/__init__.py
- src/bentoml/_internal/configuration/v1/default_configuration.yaml
- src/bentoml/_internal/runner/runner.py
- src/bentoml/_internal/runner/strategy.py
- tests/integration/frameworks/test_frameworks.py
- tests/unit/_internal/configuration/test_containers.py
- tests/unit/_internal/runner/test_strategy.py
Add a new runner configuration `workers_per_resource` to spawn multiple workers on each allocated resource. The default value is 1.
The effect of this configuration varies depending on whether the CPU or GPU is used.
- CPU and multi-threading=false
* Spawns `workers_per_resources * cpu` workers
- CPU and multi-threading=true
* Spawns `workers_per_resources` workers with `cpu` threads on each worker.
- GPU
* Spawns `workers_per_resources` workers on each GPU.
those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting …
> feat: Allow spawning more than 1 worker on each resource

- src/bentoml/_internal/marshal/dispatcher.py
Fix a hidden bug in `trigger_refresh`. This bug will happen if the dispatcher just receive a few requests then the server is stopped (for example by user pressing ctrl-c, or the runner server is reloaded because file changes are detected). In this situation `np.linalg.lstsq` will report an error, which is confusing especially when we allow production mode with reload functionality enabled.
Fixes #(issue)
those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writting docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentati …
> fix(dispatcher): handling empty o_stat in `trigger_refresh`

- src/bentoml/_internal/marshal/dispatcher.py
Cleans up a minor strange code segment that used `IndexError` to exit out of a loop popping the queue, which I don't think is necessary.
@bojiang does this look fine?
> chore(dispatcher): cancel jobs with a for loop

- src/bentoml/_internal/marshal/dispatcher.py
This prevents the dispatcher from slowing down shutdown significantly.
> fix: correctly reraise `CancelledError`

- src/bentoml/_internal/exportable.py
Previously we ignored the path argument if it was not an OSFS path; we no longer do this.
See #3789
> use path as resource for non-OS paths

- src/bentoml/_internal/frameworks/tensorflow_v2.py
Fix bug on _postprocess function when the response of model is more than one element
Fixes #3806 
> feat(tensorflow): support list types inputs

- src/bentoml/_internal/bento/bento.py
- src/bentoml/_internal/bento/build_config.py
- src/bentoml/bentos.py
- src/bentoml_cli/bentos.py
- tests/e2e/bento_server_http/tests/test_client.py
Initial implementation as a part of #3580
> feat: subprocess build

- requirements/tests-requirements.txt
Remove imageio since we don't use it anymore
> chore(deps): remove imageio

- src/bentoml/_internal/configuration/containers.py
- src/bentoml/_internal/context.py
- src/bentoml/_internal/log.py
- src/bentoml/_internal/server/http_app.py
- src/bentoml/_internal/server/runner_app.py
Added support for service.name to appear in trace. 
When set with `OTEL_SERVICE_NAME`
cc @ssheng 
> feat(observability): support `service.name`

- .github/workflows/ci.yml
- pyproject.toml
Hopefully this will just work given that there seems to be some minimal testing on 3.11 already (and given that https://github.com/bentoml/BentoML/pull/3774 has merged), though 3.11 isn't consistently present in the CI files.
> chore: 3.11 support

- src/bentoml/_internal/marshal/dispatcher.py
- tests/e2e/bento_server_http/tests/test_serve.py
Fixes #3813
A bug that causes the runner to keep running after it is terminated. This is because the CancelledError is swallowed silently, making the tasks never be cancelled by the runner.
BTW, since `CancelledError` is subclassing `BaseException` it won't be caught by the `except Exception` block. We can remove it.
> fix: Eliminate the exception during shutdown

- DEVELOPMENT.md
- README.md
- docs/source/guides/migration.rst
- requirements/tests-requirements.txt
- src/bentoml/__init__.py
- src/bentoml/_internal/bento/bento.py
- src/bentoml/_internal/service/loader.py
- src/bentoml/_internal/service/service.py
- src/bentoml/server.py
- tests/e2e/bento_server_http/tests/conftest.py
- tests/e2e/bento_server_http/tests/test_serve.py
This PR made the following use case possible, this is especially helpful in a project development environment where no Bento was built yet.
```python
import bentoml
from clip_api_service.service import svc 
server = bentoml.HTTPServer(svc)
server.start(blocking=False)
client = server.get_client()
client.rank(..)
```
Similarly, users can also put a launch script within a service definition file and run it as a regular Python program:
```python
svc = bentoml.Service(...)
if __name__ == "__main__":
server = bentoml.HTTPServer(svc)
server.start(blocking=True)
```
```bash
python service.py
```
See discussion here: https://github.com/bentoml/BentoML/discussions/3560#discussioncomment-5711687
Fixes #(issue)
guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing …
> feat: allow starting server with bentoml.Service instance

- docs/source/concepts/bento.rst
- pyproject.toml
- requirements/tests-requirements.txt
- src/bentoml/_internal/container/__init__.py
> deps: move exporter-proto to optional

- src/bentoml/_internal/client/grpc.py
- src/bentoml/_internal/server/grpc_app.py
- src/bentoml/grpc/utils/__init__.py
address #3797
This is a regression when I added GrpcClient. I forgot that grpc_app eagerly
load for gRPC dependencies. This will fail when users want to use client and
don't have gRPC dependencies.
> fix(import): make sure not to import grpc when not needed

- src/bentoml/_internal/service/inference_api.py
Fixes a hidden bug where name and doc is not set in the branch for callback is
None.
InferenceAPI that created from user_defined_callback=None (mainly from client)
does assign name and doc. Currently on main, this fake_api won't have the name
This PRs address that
> fix(inference-api): assigning name in callback is None branch

- src/bentoml/_internal/utils/__init__.py
- src/bentoml_cli/bentos.py
- src/bentoml_cli/models.py
this is a chore, but adding path for models when users do `bentoml models list`
is synonymous to when `bentoml list` also shows path
> chore(cli): remove path from `bentoml list`

- src/bentoml/_internal/bento/build_config.py
- src/bentoml/bentos.py
Currently, subprocess build doesn't respect current users environment. If custom
BENTOML_HOME is set, and in the service there is a import_model logics, it will
fail to find the model from the custom BENTOML_HOME and it will try to create a
default bentoml_home instead.
> chore(type): cleanup

- docs/source/guides/logging.rst
Add the note to inform the user that initializing a custom logger in the `service.py` can not do file rotation properly, due to the logging module only support thread-safty in single process, but not for multiprocess. 
Fixes #3851 
> docs: add note to Library Logging part to inform user about file rotate issue 

- src/bentoml/server.py
BentoServer should be able to set timeout for different instance. Some types of server will just have longer timeout. Not sure if this pr is the best way to fix this. For example, another way is provide an argument for `Http/GrpcServer.get_client(timeout=10)`. This is open to discussion
> improv: BentoServer can set its own timeout

- src/bentoml_cli/bentos.py
There is a current bug (probably a regression when I wrote the subprocess build)
that CLI should return the Bento object for tracking purposes.
The events can be found under
bentoml/_internal/utils/analytics/cli_envets.py:_cli_bentoml_build_event
> fix(metrics): make sure to return bento during build for telemetry

- src/bentoml/_internal/runner/runner.py
- src/bentoml/triton.py
Fixes #3899. This is a regression from 1.0.19 when embedded is introduced.
embedded is apparently a breaking change, but since we never expose
AbstractRunner, I would assume that it won't break users custom Runner.
> fix(triton): default set embedded on Triton

- src/bentoml/_internal/frameworks/transformers.py
Fix saving tokenizer metadata where `pretrained.framework` is only a PreTrainedModel | TFPreTrainedModel | FlaxPreTrainedModel attribute, not tokenizer
> fix: make sure to only save _framework for PreTrainedModel.

- docs/source/reference/index.rst
- docs/source/reference/types.rst
- src/bentoml/types.py
At some point we should probably move these to `bentoml.models` or something, but that would be breaking.
> docs: document bentoml.types

- src/bentoml/_internal/yatai_client/__init__.py
Allows for reading uncompressed tar files, now that we upload those.
> fix: read uncompressed bentos

- .github/workflows/ci.yml
Disable windows CI until we have more bandwidth to learn how to fix it.
> chore(ci): disable windows e2e

- bentoml/types.py
`werkzeug` library expects to receive the content length header as a string and tries to parse that string with regex to get the integer. Passing an integer instead of a string directly resulted in `TypeError`. This fix converts `len(self.body)` to string
> fix: http request content length parsing

- src/bentoml/_internal/runner/container.py
- src/bentoml/_internal/utils/pickle.py
Try to fix the problem when unpickling a PyTorch tensor with its device set to "cuda" in a cpu-only environment (see this issue: https://github.com/pytorch/pytorch/issues/16797 for more information). This is crucial for BentoML's distribution runner because the distribution runner may run in a pod with GPU device while the api server run in cpu-only pods. Then when the runner pickle the tensor and send it to api server, the api server will meet unpickling errors.
The current strategy is to call normal unpickling function (`pickle.loads`) and only fallback to special torch tensor handling unpickler when a `RuntimeError` is raised. The other way is to call the special torch tensor handling unpickler everytime we need to unpickle bytes. The advantage of current strategy is it will handle …
> fix(serialization): loads gpu torch tensor on cpu-only machine and revert DefaultContainer optimization

- docs/source/concepts/service.rst
Add missing Multipart import in documentation service.rst [Composite Types](https://docs.bentoml.org/en/latest/concepts/service.html#composite-types)
> docs: fix missing Multipart import in service.rst Composite Types section

- src/bentoml/_internal/cloud/config.py
- src/bentoml_cli/bentos.py
- src/bentoml_cli/cloud.py
- src/bentoml_cli/deployment.py
- src/bentoml_cli/models.py
- src/bentoml_cli/utils.py
> feat(cli): add a global `--context`

- src/bentoml/triton.py
Fixes #4045 
An error occurs when inferring using triton runner as of bentoml 1.0.21. 
With the change to the `init_client` function in the `Runner` class in version 1.0.21, the `init_client` function in the `_TritonRunner` class was also changed.
As a result of this, the `_runner_handle` in the `_TritonRunner` class does not change a `TritonRunnerHandle` class, remains a `_DummyRunnerHandle` class.
This results in the error below.
```
root@427afba6823c:/opt/tritonserver# bentoml serve
2023-08-21T06:29:21+0000 [INFO] [cli] Prometheus metrics for HTTP BentoServer from "." can be accessed at http://localhost:3000/metrics.
...
I0821 06:29:27.504148 33884 grpc_server.cc:2450] Started GRPCInferenceService at 0.0.0.0:36469
I0821 06:29:27.504191 33884 http_server.cc:185] Started Metrics Service …
```
> fix(triton): correctly set client handle

- src/bentoml/serve.py
Fixes when the Python path has space in it. We should escape it
> fix(serve): quote python executable on POSIX

- src/bentoml/_internal/bento/build_config.py
fix: pip dependency cache miss in bento build stage
the root cause is that the requirement.text generated by pip compile contains some tmp and random annotations like 
fix this by adding `--no-annotate` to the pip compile comands
test result :
before:
after:
> fix: bento build cache miss

- pyproject.toml
Open the version constraints for Starlette, to allow the latest version (it's a consumer decision, as BentoML is used as a library is many cases).
This also allows to use the latest FastAPI (a popular combination AFAIK), as it usually requires latest version of Starlette. 
> chore(deps): open Starlette version, to allow latest

- src/bentoml/_internal/cloud/base.py
- src/bentoml/_internal/cloud/bentocloud.py
- src/bentoml/_internal/cloud/yatai.py
This fixes a few weird issues I was seeing with the httpx `content=`, as previously some functions were not behaving correctly.
> fix: use closer-integrated callbackwrapper

- src/bentoml/_internal/types.py
- fix(signature): correct annotations for ModelSignatureDict
- chore: cleanup smaller 3.8 compat
Fixes #(issue)
> chore(annotations): cleanup compat and fix ModelSignatureDict type

- src/bentoml/_internal/server/runner_app.py
> fix(exception): catch exception for users' runners code

- src/bentoml/_internal/client/http.py
This should allow for
```python
Client.from_url('http://localhost:3000/')
```
/cc @parano
> fix(httpclient): take into account trailing slash in from_url

- src/bentoml/_internal/configuration/v1/default_configuration.yaml
This allows for the amount of time it takes to cold-start a service when running with serverless.
> fix(config): set default runner timeout to 15min

- src/bentoml/_internal/ray/__init__.py
An update in Ray renamed ASGIHTTPSender to BufferedASGISender. This change has not been made in BentoML. I just renamed it.
> fix: Rename ASGIHTTPSender to BufferedASGISender for Ray compatibility.

- src/bentoml/exceptions.py
- src/bentoml/server.py
This fixes a questionable choice of mine, where getting a client when a server was not running would return `None` and warn instead of raising an exception. This is now fixed.
I also have replaced instances of deprecation warnings with `warnings.warn`, which I believe is idiomatic.
> fix(client): make get_client raise instead of logging

- src/bentoml/bentos.py
When using `bentoml.bentos.build` from the python api, my project crashes because I am using an in-project virtual env Thus the global `bentoml` command is not installed or it might be a call to another `bentoml` installation, which can cause conflicts.
This change forces subprocess to use the same python binary as the caller process, fixing the problem (tested locally)
> fix: subprocess not using same python as main process causing `bentoml.bentos.build` to crash

- src/bentoml/_internal/configuration/helpers.py
- src/bentoml/serve.py
No longer listens on ipv6 catchall by default.
> feat: support ipv6 addresses for serve

- src/bentoml/_internal/client/__init__.py
- src/bentoml/server.py
- tests/e2e/bento_server_http/tests/test_serve.py
Depends on #4181.
Review the second commit if you want to review this now.
> fix(client): type fixes

- src/bentoml/_internal/bento/bento.py
- src/bentoml/_internal/cloud/bentocloud.py
- src/bentoml/_internal/cloud/yatai.py
- src/bentoml/_internal/models/model.py
- src/bentoml/_internal/store.py
- src/bentoml_cli/bentos.py
> fix: correct the bento size to include the size of models

- src/bentoml/_internal/client/http.py
This PR fixes a bug with the `bentoml.client` API.
There were a few spots in the code where the client types weren't properly grabbing the response body, so I just fixed those.
Fixes #4244
> fix: client API

- src/bentoml/_internal/ray/__init__.py
- src/bentoml/_internal/ray/runner_handle.py
Two problems were preventing benoml.ray.deployment from working:
- Incorrect path reference to _internal.utils pkg (introduced in #4191)
Fixed to reference parent path correctly
- Missing abstract async_stream_method in the RayRunnerHandle (added to RunnerHandle in #4032)
Added a stub that throws NotImplementedError like the fix made to TitanRunnerHandle in #4251.
Fixes #(issue)
> fix: Bug 4252 Restore functioning benoml.ray.deployment

- src/bentoml/_internal/io_descriptors/text.py
- src/bentoml/_internal/utils/formparser.py
- tests/unit/_internal/io/test_multipart.py
fix issue:
Exception raised when calling bentoml.client with a Multipart format. 
```
File "<stdin>", line 1, in <module>
File "/home/paperspace/.local/lib/python3.9/site-packages/bentoml/_internal/client/__init__.py", line 133, in _sync_call
return asyncio.run(self._call(inp, _bentoml_api=_bentoml_api, **kwargs))
File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
return future.result()
File "/home/paperspace/.local/lib/python3.9/site-packages/bentoml/_internal/client/http.py", line 167, in _call
fake_resp = await api.input.to_http_response(kwargs, None)
File "/home/paperspace/.local/lib/python3.9/site-packages/bentoml/_interna …
```
> fix: StreamingResponse compatibility issue

- webui/src/components/form/InputNumber.tsx
Fix InputNumber range check fails when min or max equals 0 
> fix: webui InputNumber range check fails when min or max equals 0

- src/bentoml/serve.py
Fixes #4293 
It looks like there used to be 2 functions for grpc serving: `serve_grpc_production`(which raised on Windows) and `serve_grpc_development` (which did not raise).
In #3735 these `serve_grpc_development` was merged into `serve_grpc_production` via additional `development_mode` kwarg, but exception condition was not changed. 
I have checked that in my environment this solves issue
> fix: Disable exception in serve-grpc on Windows in development mode

- docs/source/quickstarts/deploy-a-large-language-model-with-openllm-and-bentoml.rst
> docs: update quickstart with OpenLLM

- pdm.lock
- pyproject.toml
Updates the minimum required starlette version to be at least 0.24. This fixes a bug related to image payload mime types in multipart requests. Had to refresh the `pdm.lock` file due to a unknown tritonclient version (2.38.0.69485444)
Fixes: https://github.com/bentoml/BentoML/issues/3804 
> fix: Updated starlette to >= 0.24.0

- docs/source/frameworks/transformers.rst
Fix typo in hugging face transformers framework guide
> docs: fix typo in frameworks transformers guide

- src/bentoml/_internal/configuration/v2/__init__.py
This addresses services that have custom name such as `llm-phi-runner`. By default, `unflatten_dict` will create quotation for this, which means the flattened dict of the override config would be 'services."llm-phi-runner".workers'.
For this to work correct, we need to remove all quotation from the service config name, as this is considered as valid string.
Fixes #(issue)
> fix(config): make sure to escape quotation for migration of services config

- src/bentoml/_internal/cloud/client.py
- src/bentoml/_internal/cloud/deployment.py
- src/bentoml/_internal/cloud/schemas/modelschemas.py
- src/bentoml/_internal/cloud/schemas/schemasv1.py
- src/bentoml/_internal/cloud/schemas/schemasv2.py
- src/bentoml/deployment.py
- src/bentoml_cli/deployment.py
- tests/unit/_internal/cloud/test_deployment.py
> fix: refactor deployment v2 client and cli

- src/bentoml/_internal/cloud/deployment.py
- src/bentoml/deployment.py
- src/bentoml_cli/deployment.py
> fix: fix deploy cli & sdk

- docs/source/quickstarts/snippets/openllm_api_server.py
- ci: pre-commit autoupdate [skip ci] (#4382)
- chore(deps): bump github/codeql-action from 2 to 3 (#4343)
- fix(docs): remove eager type evaluation for python 3.8
Fixes #(issue)
> fix(docs): remove eager type evaluation for python 3.8 on openllm examples

- src/_bentoml_sdk/api.py
- src/_bentoml_sdk/io_models.py
- src/bentoml/__init__.py
> fix: set content type from annotation

- src/_bentoml_sdk/service/factory.py
This is the case when running `Service.serve_http()`
Fixes #(issue)
> fix: loading service from an absolute path

- src/bentoml_cli/deployment.py
> fix: use spinner log instead of console log

- src/bentoml/_internal/cloud/deployment.py
- src/bentoml_cli/deployment.py
> fix: add config dict to cli

- src/bentoml/_internal/cloud/bentocloud.py
With the as_posix we replace the path's backslahes with slashes, making the bentoml pull command from yatai possible on windows systems.
Fixes #4440 
- [x ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
- [ x] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [x ] Did you read through [contribution …
> fix: Replace backslahes by normal slashes, making bentoml pull possible on windows

- src/bentoml/_internal/bento/build_config.py
- src/bentoml/_internal/configuration/__init__.py
> feat: lock dependencies by default considering the current bentoml version

- docs/source/guides/clients.rst
> docs: Add client code examples without context manager

- src/_bentoml_impl/client/http.py
- src/_bentoml_impl/server/app.py
- src/_bentoml_impl/worker/service.py
- src/bentoml/__init__.py
- src/bentoml/_internal/configuration/containers.py
- src/bentoml/_internal/context.py
- src/bentoml/_internal/log.py
- src/bentoml/_internal/monitoring/default.py
- src/bentoml/_internal/monitoring/otlp.py
- src/bentoml/_internal/runner/runner_handle/remote.py
- src/bentoml/_internal/server/http/instruments.py
- src/bentoml/_internal/server/runner_app.py
- src/bentoml/_internal/utils/circus/watchfilesplugin.py
- src/bentoml/grpc/interceptors/prometheus.py
- src/bentoml_cli/cli.py
- src/bentoml_cli/worker/grpc_api_server.py
- src/bentoml_cli/worker/grpc_prometheus_server.py
- src/bentoml_cli/worker/http_api_server.py
- src/bentoml_cli/worker/runner.py
- tests/unit/_internal/utils/circus/test_watchfilesplugin.py
> fix: rename server context attributes

- docs/source/guides/clients.rst
Add docs for this https://github.com/bentoml/BentoML/pull/4559
> docs: Add doc for server_ready_timeout

- examples/quickstart/service.py
- src/_bentoml_impl/server/serving.py
- src/_bentoml_sdk/service/factory.py
- src/bentoml/_internal/utils/circus/__init__.py
This should benefit workflow in REPL and Jupyter notebook. Basically, it enables the following usage:
```python
import bentoml
from service import MyService
server = MyService.serve_http(threaded=True)  # this doesn't block the following
client = bentoml.SyncHTTPClient(server.url)
try:
result = client.classify([[1,2,3,4]])
finally:
client.close()
server.stop()
```
> feat: threaded serving

- src/_bentoml_sdk/io_models.py
> fix: respect the content type config for file output

- docs/source/guides/adaptive-batching.rst
> docs: Update the adaptive batching doc

- src/_bentoml_impl/worker/service.py
- src/_bentoml_sdk/decorators.py
- src/_bentoml_sdk/service/factory.py
- tests/unit/bentoml_io/test_decorators.py
> feat: Service.to_asgi() method

- src/bentoml/_internal/bento/build_config.py
Remove this warning for now since we are still using the converter for backward compatibility
this means that even `envs` is specified, this will still be thrown
> fix(build): remove deprecated warnings

- src/bentoml/_internal/bento/build_config.py
- src/bentoml/_internal/bento/install.sh.j2
migrate install script to be in jinja for easier management
Fixes #(issue)
> feat(build): use jinja template for install script

- src/_bentoml_impl/server/app.py
> fix: add response headers for error responses

- docs/source/guides/services.rst
Add docs for https://github.com/bentoml/BentoML/issues/4613 and replace https://github.com/bentoml/BentoML/pull/4617
> docs: Add docs for bentoml.runner_service

- src/_bentoml_impl/client/base.py
- src/_bentoml_sdk/service/factory.py
Related to #4613
Fixes #(issue)
> fix: handle __call__ on clients

- src/bentoml/_internal/configuration/containers.py
- src/bentoml/_internal/configuration/v1/__init__.py
- src/bentoml/_internal/configuration/v2/__init__.py
> fix: issue overriding default service config from config file

- src/bentoml/_internal/cloud/bentocloud.py
> fix(cli): correct the comparison of upload status

- README.md
> docs: Update example project list

- docs/source/guides/build-options.rst
- docs/source/guides/model-store.rst
> docs: Add some explanations for bentoml.models.get

- docs/source/guides/build-options.rst
Convention for yaml is indentation with 2 spaces.
Also fixed some indentation for list items
Fixes #(issue)
> docs: fix indentation in build option docs

- src/bentoml/__init__.py
> fix: bug:  module 'bentoml' has no attribute 'build'

- src/_bentoml_impl/server/app.py
- src/bentoml/_internal/server/http_app.py
> fix: uncaught error missing trace headers

- docs/source/guides/deployment.rst
- docs/source/use-cases/audio/whisperx.rst
- docs/source/use-cases/audio/xtts.rst
- docs/source/use-cases/blip.rst
- docs/source/use-cases/diffusion-models/controlnet.rst
- docs/source/use-cases/diffusion-models/sdxl-lcm-lora.rst
- docs/source/use-cases/diffusion-models/sdxl-turbo.rst
- docs/source/use-cases/diffusion-models/svd.rst
- docs/source/use-cases/embeddings/clip-embeddings.rst
- docs/source/use-cases/embeddings/sentence-transformer.rst
- docs/source/use-cases/large-language-models/vllm.rst
> docs:Update credits

- src/bentoml_cli/deployment.py
> fix: fix table overflow with fold

- src/bentoml/_internal/cloud/deployment.py
- src/bentoml/_internal/cloud/schemas/modelschemas.py
> fix: add scaled to zero to ready status

- src/bentoml/_internal/bento/install.sh.j2
all pip args should be parse after `install`, such that it will work in conjunction with -r
This will fail if user pass in `pip_args` in bentofile.yaml, or via the API call.
> fix(build): make sure to parse pip_args in correct order

- docs/source/guides/build-options.rst
> docs: Add docs for installing GitHub packages for Bento

- src/bentoml/_internal/bento/build_config.py
- tests/unit/_internal/bento/test_bento.py
> feat: add a switch to opt-out packing git packages

- src/bentoml/testing/utils.py
- tests/e2e/bento_server_http/tests/test_io.py
- tests/e2e/bento_server_http/tests/test_meta.py
- tests/e2e/bento_server_http/tests/test_serve.py
Fixes https://github.com/bentoml/BentoML/issues/3411
- The async_request function in `bento.testing.utils` performs an action that duplicates the functionality of AsyncHTTPClient in `bento.client`. Since the Client is correctly implemented, I have refactored the test code to operate using it.
- Since AsyncHTTPClient use httpx, there's minor datatype change on aiohttp.FormData.
> refactor(tests): testing.util.async_request to client.AsyncHTTPClient

- docs/source/guides/build-options.rst
Add docs for https://github.com/bentoml/BentoML/pull/4729
> docs: Add git package packing doc

- src/_bentoml_impl/server/app.py
- src/bentoml/_internal/marshal/dispatcher.py
- src/bentoml/_internal/runner/container.py
- src/bentoml/_internal/runner/utils.py
- src/bentoml/_internal/server/runner_app.py
> feat(batching): break batch into smaller partitions if it's larger than max batch size

- src/_bentoml_impl/client/http.py
> fix: client response deserialization when the output is string

- src/_bentoml_impl/server/app.py
the proper order of middleware is
1. TrafficMetrics middleware 
2. OpenTelemetry middleware
3. AccessLog middleware
4. TimeoutMiddleware
5. MaxConcurrencyMiddleware
6. CORS middleware
7. ContextMiddleware
LOG
Metric
Fixes #(issue)
> fix: middleware reorder

- src/_bentoml_impl/server/app.py
- src/bentoml/_internal/context.py
- src/bentoml/_internal/server/http/traffic.py
> feat: support adding response background tasks via bentoml.Context

- src/bentoml/_internal/cloud/client.py
- src/bentoml/_internal/cloud/deployment.py
- src/bentoml/_internal/cloud/schemas/schemasv1.py
- src/bentoml/_internal/cloud/schemas/schemasv2.py
- src/bentoml/_internal/cloud/secret.py
- src/bentoml_cli/cli.py
- src/bentoml_cli/deployment.py
- src/bentoml_cli/secret.py
add secret management commands
```
1. List
(.venv) ➜  ✗ bentoml  secret list                               
Secret                                        Created_At                                                      Mount_As                          Keys                                                      Path                                                    
secret-env                                    2024-05-29 09:16:12                                             env                               IS_TEST, HF_TOKEN                                         -                                                       
secret-file7                                  2024-05-29 09:15:55                                             env                               IS_TEST …
```
> feat: add secret management commands

- src/bentoml/_internal/utils/__init__.py
Randomly encountering the error below when serving a BentoML server with `bentoml serve . -p 5000`:
The accompanying change should fix it.
The script serves multiple models in parallel and some race condition might be causing the same:
```
#!/bin/bash
source activate venv_speech
port=${PORT:-6919}
if [ -d "styletts2-cog" ]; then
cd styletts2-cog
sudo rm -r /root/bentoml/models
nohup bentoml serve . -p 5000 > styletts2-cog.log 2>&1 &
cd ..
else
echo "Directory styletts2-cog does not exist."
fi
if [ -d "ImageBind" ]; then
cd ImageBind
sudo rm -r /root/bentoml/models
nohup bentoml serve . -p 5001 > ImageBind.log 2>&1 &
cd ..
else
echo "Directory ImageBind does not exist."
fi
if [ -d "whisper" ]; then
cd whisper
sudo rm -r /root/bentoml/models
nohup bentoml serve . -p 5002 > whisper.log 2>&1 …
```
> Fixed `FileExistsError: [Errno 17] File exists: '/root/bentoml'`

- src/bentoml/_internal/io_descriptors/pandas.py
- tests/e2e/bento_server_http/tests/test_io.py
It is a shame that BentoML doesn't use the correct mime type for Parquet:
https://www.iana.org/assignments/media-types/application/vnd.apache.parquet
Here we move to using the correct mime type going forwards but accept the old mime type too.
Fixes #(issue)
> fix(pandas): use correct mime type for Parquet

- src/bentoml/_internal/utils/pkg.py
Addresses resource overhead from repeated calls to `pkg_version_info`. This function is called with only a handful of static strings, so it seems reasonable to just memoize the value indefinitely. The function is called in hot regions of the code, for example request json parsing and formatting when checking pydantic versions.
Fixes #4784
No tests written, but seems like this should be covered by existing tests.
> fix: add memoization to `pkg_version_info` to reduce cpu overhead

- src/_bentoml_sdk/validators.py
- src/bentoml/_internal/context.py
- src/bentoml/_internal/server/base_app.py
- src/bentoml/_internal/utils/temp.py
Fixes #4760
Change the request temp dir to create on demand. 
/cc @Zheaoli @gusghrlrl101
> fix: bug: memory leak when using bentoml>=1.2

- src/_bentoml_impl/server/serving.py
- src/bentoml/_internal/bento/build_config.py
- src/bentoml/serve.py
- src/bentoml/start.py
- src/bentoml_cli/serve.py
- src/bentoml_cli/start.py
Make CLI honor host and port config in service decorator, so the priorities are:
1. `--port` CLI option
2. `BENTOML_PORT` env var
3. `service(http={"port": 3456})`
The config in service decorator may take effect on Cloud if not specified explicitly by start option or env var. @bojiang please confirm this.
> fix: honor host and port config in service decorator

- src/_bentoml_sdk/validators.py
- tests/unit/bentoml_io/test_decorators.py
Output specs defined as `Annotated[pd.DataFrame, DataframeSchema(columns=["a"])]` don't work because lists are not hashable. This PR adds a converted to the `columns` field of `DataframeSchema` to convert them to a `tuple`. 
Also adds another missing test!
> fix(pandas): `Annotated[pd.DataFrame, DataframeSchema(columns=["a"])]` output spec

- src/_bentoml_impl/loader.py
- src/bentoml/_internal/bento/bento.py
- tests/unit/_internal/bento/test_bento.py
> fix: ensure relative path works within bento project

- src/_bentoml_sdk/_pydantic.py
- src/_bentoml_sdk/typing_utils.py
- tests/unit/bentoml_io/test_decorators.py
Currently, it seems to me that `numpy` annotations are broken. For example, neither of the [correct types](https://numpy.org/devdocs/reference/typing.html#typing-numpy-typing) `npt.NDArray[np.float32]` or `np.ndarray[Any, np.dtype[np.float32]],` are processed and instead result in errors.
These changes fix this and add to the unit tests to catch regressions. Additionally, I've made sure that if the type hint for a Numpy array doesn't match the `Annotated` `DType` then we throw an error.
I'm _**really**_ surprised how little unit testing there is in this area - am I missing something?
Fixes #(issue) …
> fix(numpy): `numpy` annotation processing

- src/bentoml/_internal/cloud/deployment.py
> fix(cloud-client): consider httpcore timeout when getting status

- src/_bentoml_impl/loader.py
> fix: cd into src instead of bento parent

- pdm.lock
- pyproject.toml
- src/bentoml/_internal/monitoring/otlp.py
> feat(monitoring): support GRPC LogExporter

- docs/source/guides/build-options.rst
- docs/source/guides/gpu-inference.rst
> docs: Add Docker deployment for Bentos

- src/bentoml/_internal/cloud/bentocloud.py
- src/bentoml/_internal/cloud/client.py
- src/bentoml/_internal/cloud/deployment.py
- src/bentoml/_internal/cloud/schemas/schemasv2.py
- src/bentoml_cli/deployment.py
👈 BentoML CLI 🆚 kubectl 👉
https://github.com/bentoml/BentoML/assets/1206493/e42647a0-4d08-4cb3-9f78-34eea6ff7bef
> fix: ASCII animation was not working properly in the image builder logs

- pdm.lock
- pyproject.toml
- src/_bentoml_impl/client/__init__.py
- src/_bentoml_impl/client/base.py
- src/_bentoml_impl/client/http.py
- src/_bentoml_impl/client/proxy.py
- src/_bentoml_impl/client/task.py
- src/_bentoml_impl/server/app.py
- src/_bentoml_impl/server/serving.py
- src/_bentoml_impl/tasks/__init__.py
- src/_bentoml_impl/tasks/result.py
- src/_bentoml_impl/tasks/serde.py
- src/_bentoml_impl/worker/service.py
- src/_bentoml_sdk/__init__.py
- src/_bentoml_sdk/decorators.py
- src/_bentoml_sdk/method.py
- src/_bentoml_sdk/service/factory.py
- src/_bentoml_sdk/service/openapi.py
- src/bentoml/__init__.py
- src/bentoml/_internal/bento/bento.py
- src/bentoml/_internal/configuration/containers.py
- src/bentoml/_internal/context.py
- src/bentoml/_internal/models/model.py
- src/bentoml/_internal/server/http/traffic.py
- src/bentoml/_internal/service/openapi/utils.py
- tests/unit/bentoml_io/test_decorators.py
> feat: impl client async endpoints and results

- src/bentoml/_internal/cloud/deployment.py
- src/bentoml_cli/deployment.py
1. Long url can be shown:
2. bento build progress is added:
Fixes #(issue)
> fix(deployment-client): add build process and extend url

- pdm.lock
- pyproject.toml
- src/bentoml/_internal/cloud/client.py
- src/bentoml_cli/auth_server.py
- src/bentoml_cli/cloud.py
- tests/unit/bentoml_io/test_decorators.py
support cli auto login
Fixes #(issue)
> feat: cli auto login

- src/bentoml/_internal/cloud/deployment.py
- src/bentoml_cli/bentos.py
- src/bentoml_cli/cloud.py
- src/bentoml_cli/containerize.py
- src/bentoml_cli/deployment.py
- src/bentoml_cli/env.py
- src/bentoml_cli/models.py
- src/bentoml_cli/secret.py
- src/bentoml_cli/serve.py
- src/bentoml_cli/start.py
> feat: use rich.print to replace click.echo

- noxfile.py
- pdm.lock
- src/bentoml/_internal/cloud/config.py
- src/bentoml/_internal/utils/analytics/schemas.py
- src/bentoml_cli/cloud.py
> feat: login to current context instead of default context if --context is not passed

- docs/source/index.rst
> docs: Fix broken link

- docs/source/bentocloud/byoc/azure.rst
> docs: Add azure byoc setup doc

- examples/README.md
> docs: Add 2 examples

- docs/source/guides/clients.rst
- docs/source/guides/services.rst
> docs: Add task doc

- src/bentoml/_internal/frameworks/transformers.py
> fix(framework): transformers vs 1.3.0 "TypeError: __init__() got an unexpected keyword argument 'task'"

- src/_bentoml_sdk/method.py
- src/bentoml/_internal/server/http/instruments.py
> fix: Cannot define custom duration histogram buckets via `@bentoml.service(metrics=...)`

- src/bentoml/_internal/cloud/client.py
> fix: direct return response if tracer id is null

- src/_bentoml_sdk/service/config.py
- src/bentoml/_internal/cloud/base.py
- src/bentoml/_internal/cloud/bentocloud.py
- src/bentoml/_internal/cloud/deployment.py
- src/bentoml/_internal/cloud/secret.py
- src/bentoml/_internal/configuration/containers.py
- src/bentoml/_internal/utils/analytics/usage_stats.py
- src/bentoml/deployment.py
- src/bentoml_cli/bentos.py
- src/bentoml_cli/cloud.py
- src/bentoml_cli/deployment.py
- src/bentoml_cli/env.py
- src/bentoml_cli/models.py
- src/bentoml_cli/secret.py
- src/bentoml_cli/utils.py
- tests/unit/_internal/cloud/test_deployment.py
> refactor: store the cloud context into the container instead of passing it around

- src/bentoml/_internal/frameworks/pytorch.py
Loading a torch model now takes **torch_load_args as kwargs to pass to torch.load. Warnings in newer torch version are due to e.g. weights_only using default values. Passing weights_only=False to bentoml.pytorch.load_model() will supress those warnings
Example warning:
> FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no …
> feat: Pass torch kwargs to bentoml.pytorch.load_model

- src/bentoml/_internal/cloud/base.py
- src/bentoml/_internal/cloud/bentocloud.py
- src/bentoml/_internal/cloud/client.py
> fix: uploading large files saving to disk instead of memory

- src/bentoml/_internal/bento/bento.py
This prevents the situation on linux where the default temp
directory can be on a RAM-backed FS, which meant large Bentos
could not be built.
> fix: don't use temporary directory for temp bento copying

- src/_bentoml_impl/loader.py
- src/_bentoml_impl/server/serving.py
- src/bentoml/_internal/bento/bento.py
- src/bentoml/_internal/cloud/base.py
- src/bentoml/_internal/cloud/bentocloud.py
- src/bentoml/_internal/cloud/client.py
- src/bentoml/_internal/cloud/deployment.py
- src/bentoml/_internal/cloud/schemas/modelschemas.py
- src/bentoml/_internal/cloud/schemas/schemasv2.py
- src/bentoml/_internal/service/loader.py
- src/bentoml/_internal/utils/__init__.py
- src/bentoml/bentos.py
- src/bentoml_cli/cli.py
- src/bentoml_cli/deployment.py
- src/bentoml_cli/utils.py
Try `bentoml develop` under your bento project
> feat: remote development

- pyproject.toml
- src/bentoml/_internal/bento/build_config.py
- src/bentoml/_internal/configuration/__init__.py
- src/bentoml/serving.py
- src/bentoml/testing/pytest/plugin.py
> fix: on_deployment failed to run for serve_grpc

- .github/workflows/ci.yml
- src/_bentoml_sdk/models/base.py
- src/bentoml/__init__.py
- src/bentoml/_internal/cloud/__init__.py
- src/bentoml/_internal/cloud/base.py
- src/bentoml/_internal/cloud/bento.py
- src/bentoml/_internal/cloud/client.py
- src/bentoml/_internal/cloud/deployment.py
- src/bentoml/_internal/cloud/model.py
- src/bentoml/_internal/cloud/secret.py
- src/bentoml/_internal/cloud/yatai.py
- src/bentoml/_internal/configuration/containers.py
- src/bentoml/_internal/service/service.py
- src/bentoml/bentos.py
- src/bentoml/deployment.py
- src/bentoml/models.py
- src/bentoml/testing/pytest/plugin.py
- src/bentoml_cli/bentos.py
- src/bentoml_cli/deployment.py
- src/bentoml_cli/models.py
- src/bentoml_cli/secret.py
- tests/unit/_internal/bento/test_service_serialization.py
- tests/unit/_internal/cloud/test_deployment.py
Make the cloud client APIs more structured and aligned
```python
import bentoml
import os
deployment = bentoml.deployment.get('mydeployment')
client = bentoml.BentoCloudClient("token")
deployment = client.deployment.get("mydeployment")
os.environ['BENTO_CLOUD_API_KEY'] = 'mytoken'
os.environ['BENTO_CLOUD_API_ENDPOINT'] = 'https://my.cloud.bentoml.org'
client = bentoml.BentoCloudClient()
deployment = client.deployment.get("mydeployment")
```
> refactor(1.4): Make the cloud client APIs more structured and aligned

- docs/source/guides/iotypes.rst
> doc: add instruction for `bentoml.IODescriptor`

- src/bentoml/_internal/cloud/bentocloud.py
- src/bentoml/_internal/cloud/config.py
- src/bentoml_cli/cloud.py
- src/bentoml_cli/deployment.py
- src/bentoml_cli/secret.py
> chore: update login error message

- docs/source/get-started/quickstart.rst
> doc: update quick start to use bentoml importing context manager

- src/_bentoml_sdk/models/huggingface.py
- src/_bentoml_sdk/service/dependency.py
- src/bentoml/_internal/cloud/deployment.py
- src/bentoml_cli/deployment.py
> fix: compare bento manifest and dependency client

- src/bentoml/_internal/cloud/deployment.py
> fix: tolerate build error when watching for changes

- src/_bentoml_sdk/io_models.py
- src/bentoml/_internal/cloud/deployment.py
> fix: expose errors occurring before the first yield of stream response

- docs/source/guides/build-options.rst
- docs/source/guides/gpu-inference.rst
> docs: Add CUDA version notes

- src/bentoml/_internal/cloud/deployment.py
> feat: upload setup.sh to the remote dev

- pdm.lock
- pyproject.toml
- src/_bentoml_impl/client/http.py
- src/_bentoml_impl/client/proxy.py
- src/_bentoml_impl/server/app.py
- src/_bentoml_sdk/decorators.py
- src/_bentoml_sdk/method.py
- src/_bentoml_sdk/service/factory.py
- src/bentoml/_internal/server/base_app.py
- src/bentoml/_internal/server/grpc_app.py
- src/bentoml/_internal/server/http/access.py
- src/bentoml/_internal/server/http_app.py
- src/bentoml/_internal/server/runner_app.py
- src/bentoml/_internal/service/service.py
- src/bentoml/_internal/types.py
- src/bentoml/_internal/utils/__init__.py
- src/bentoml_cli/worker/grpc_prometheus_server.py
> feat: always make an HTTP call when calling self API methods

- .gitignore
- examples/gradio/README.md
- examples/gradio/bentofile.yaml
- examples/gradio/requirements.txt
- examples/gradio/service.py
- src/_bentoml_impl/server/app.py
- src/_bentoml_sdk/_internals.py
- src/_bentoml_sdk/gradio.py
- src/_bentoml_sdk/service/factory.py
- src/bentoml/__init__.py
- src/bentoml/_internal/gradio.py
- src/bentoml/gradio.py
This PR simplifies how users can serve Gradio UI for their BentoML service. Previously user will need to manually do multiple settings and callbacks, e.g.:
```python
import bentoml
import gradio as gr
def summarize_text(text: str) -> str:
svc_instance = bentoml.get_current_service()
return svc_instance.summarize([text])[0]
io = gr.Interface(
fn=summarize_text,
inputs=[gr.Textbox(lines=5, label="Enter Text", value=EXAMPLE_INPUT)],
outputs=[gr.Textbox(label="Summary Text")],
title="Summarization",
description="Enter text to get summarized text."
)
gradio_app = gr.routes.App.create_app(io)
io.dev_mode = False
io.show_error = True
io.validate_queue_settings()
@bentoml.mount_asgi_app(gradio_app, path="/ui")
@bentoml.service(resources={"cpu": "4"})
class Summarization:
def __init__(self) -> …
```
> feat: gradio integration

- src/_bentoml_impl/loader.py
- src/_bentoml_impl/server/serving.py
- src/_bentoml_impl/worker/service.py
- src/_bentoml_sdk/service/factory.py
- src/bentoml/_internal/cloud/client.py
- src/bentoml/_internal/cloud/deployment.py
> fix: trigger reset when system package changes; find dependent

- src/_bentoml_sdk/decorators.py
Reject wrapper for `@api` and `@task` to wrap dunder methods
> fix(decorator): reject wrapper as dunder methods

- src/bentoml/_internal/cloud/bento.py
- src/bentoml/_internal/cloud/model.py
> fix: remove duplicate logs

- docs/source/bentocloud/byoc/aws.rst
- docs/source/bentocloud/byoc/gcp.rst
> docs: Add byoc request quota

- src/_bentoml_impl/docker.py
- src/_bentoml_sdk/images.py
- src/_bentoml_sdk/service/factory.py
- src/bentoml/__init__.py
- src/bentoml/_internal/bento/bento.py
- src/bentoml/_internal/bento/build_config.py
- src/bentoml/_internal/cloud/bento.py
- src/bentoml/_internal/cloud/schemas/modelschemas.py
- src/bentoml/_internal/container/__init__.py
- src/bentoml/_internal/container/frontend/dockerfile/__init__.py
- src/bentoml/_internal/container/frontend/dockerfile/entrypoint.sh
- src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2
- src/bentoml/_internal/container/generate.py
- src/bentoml/_internal/utils/__init__.py
- src/bentoml/images.py
- src/bentoml_cli/containerize.py
- tests/unit/_internal/bento/test_bento.py
> feat: Opt-in bento image support

- src/bentoml/_internal/cloud/deployment.py
- src/bentoml/_internal/cloud/schemas/schemasv2.py
- src/bentoml/deployment.py
- src/bentoml_cli/deployment.py
```python
import bentoml
bentoml.deployment.create(config_dict={..., "labels": [{"key": "hey", "value":"yo"}]})
bentoml.deployment.update(config_dict={..., "labels": [{"key": "hey", "value":"yo"}]})
bentoml.deployment.list(.., q="label:hey=yo")
bentoml.deployment.list(.., labels=[{"key": "hey", "value":"yo"}])
```
supports the following for `bentoml deploy -f deploy.yaml`
```yaml
labels:
- key: hey
value: yo
- key: xx
value: yy
```
```bash
bentoml deployment list --label key1=value1 --label key2=value2
```
Fixes #(issue)
those accordingly? Here are [documentation …
> feat: Adding SDK support for deployment labels

- src/bentoml/_internal/cloud/bento.py
- src/bentoml/_internal/cloud/schemas/schemasv1.py
> chore: upload descripiton to remote bento store

- src/_bentoml_impl/server/app.py
- src/bentoml/_internal/context.py
**feat: Add `task_id` tracking to request inference context**
This PR introduces `task_id` tracking in `Inference context request state`, making `task_id` accessible within API functions with the task decorator by accessing `ctx.request.state.task_id`. Based on the starlette documentation the request.state attribute is there to add additional information. This provides access to `task_id` across task functions, setting up support for features like state management and task control (e.g., pausing/resuming #5058).
Key changes:
- Adds `task_id` to `ctx.request.state`, available during task execution.
- Enables task functions to retrieve `task_id` directly, improving task observability.
Edit:
Initially I put the task_id in the response context, but after the comment from @frostming I modified …
> feat: Add task_id to request inference context

- src/bentoml/_internal/cloud/deployment.py
- src/bentoml_cli/cli.py
- src/bentoml_cli/utils.py
> feat: allow extending bentoml with extra commands

- src/_bentoml_impl/client/http.py
- src/_bentoml_sdk/io_models.py
- src/_bentoml_sdk/validators.py
> fix: correct file response for internal service calling

- docs/source/use-cases/index.rst
> docs: Update examples index

- docs/source/use-cases/index.rst
> docs: Update example list

- src/_bentoml_sdk/service/dependency.py
- tests/e2e/bento_new_sdk/test_asgi.py
- Adds check for close method in Dependency class
- Adds tests
Please let me know if the tests need to be adjusted.
Fixes #5082
> fix: check dependency close method (#5082)

- pdm.lock
- pyproject.toml
- src/bentoml/_internal/bento/bento.py
- tests/monitoring/task_classification/pyproject.toml
> fix: pin pydantic to < 2.10 and restore cwd when building bento

- pdm.lock
- pyproject.toml
- src/bentoml_cli/secret.py
> feat(cli): Support passing key value pairs from reading a dotenv file

- src/_bentoml_sdk/images.py
- src/bentoml/_internal/bento/bento.py
- src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2
> feat: support post commands in image spec

- src/_bentoml_sdk/models/huggingface.py
> feat: select a subset of files for huggingface models

- docs/source/examples/mlflow.rst
- docs/source/examples/xgboost.rst
> docs: Fix links

- pyproject.toml
> fix: use kantoku instead of circus

- pdm.lock
- tests/unit/_internal/utils/circus/test_watchfilesplugin.py
- tests/unit/_internal/utils/circus/utils.py
> fix: Update lock file

- src/bentoml/_internal/cloud/bento.py
- src/bentoml/_internal/cloud/deployment.py
- src/bentoml/_internal/cloud/model.py
- src/bentoml_cli/cloud.py
- src/bentoml_cli/deployment.py
> fix: use emoji code instead of emoji char

- src/bentoml/_internal/container/frontend/dockerfile/templates/cuda_debian.j2
`python3.12-distutils` seems no longer available, see issue: https://github.com/bentoml/BentoML/issues/5178
This PR removes the dependency.
Are there any automated test to validate all the python versions available?
Fixes #5178
those accordingly? Here are [documentation guidelines](https://github.com/bentoml/BentoML/tree/main/docs) and [tips on writing docs](https://github.com/bentoml/BentoML/tree/main/docs#writing-documentation).
> fix: Remove distutils dependency

- src/bentoml/_internal/cloud/deployment.py
> fix: allow usage like bentoml deploy service:MyService

- src/_bentoml_impl/worker/service.py
- src/bentoml/_internal/context.py
- src/bentoml/_internal/server/http/instruments.py
This initializes endpoints metrics with 0 request count. This way, doing `rate()` in PromQL will correctly capture the rate of change. Currently,  if it's the first time an endpoint returns error, metric is incremented to 1, but 0 value is not recorded. `rate()` will show 0 for error counts. Also imo we don't have to enumerate all http code, which spams the metrics, but we can.
> feat(metrics): init zero for request count of apis

- docs/source/build-with-bentoml/iotypes.rst
Changed the "prompt" parameter of the LanguageModel.generate method.
The previous type, int, does not match the parameter's description.
Fixes #(issue)
[5187](https://github.com/bentoml/BentoML/issues/5187)
> docs: correct types for example

- src/_bentoml_impl/server/app.py
- src/_bentoml_impl/server/mount.py
With this change, the following will be possible:
```python
import bentoml
from fastapi import FastAPI
app = FastAPI()
@app.get("/hello")
def hello():
return {"Hello": "World"}
@bentoml.service
@bentoml.asgi_app(app, path="/")
class MyService:
pass
```
Visiting `/` renders the swagger page, and visiting `/hello` gives the fastapi response. Previously, the app mounted at the root path `/` will shadow all internal endpoints
> fix: mounted apps don't eagerly match path prefix

- src/bentoml/_internal/configuration/__init__.py
> fix: get commit id from requested revision when it is missing

- src/bentoml/_internal/cloud/deployment.py
Listing deployment does not have endpoint urls, only get deployment. We might want to ignore it to to avoid confusion, e.g., `bentoml deployment list -o json` should not have `"endpoint_urls": null`. 
Another possibility is that we can also do it by deleting the key manually when `-o json` is used.
Fixes #(issue)
> fix: conditionally include endpoint_urls in deployment dictionary

- src/_bentoml_sdk/images.py
- src/bentoml/_internal/bento/bento.py
> feat: support running scripts in new image spec

- noxfile.py
- src/_bentoml_sdk/images.py
> fix: add line endings for python_packages(...)

- src/_bentoml_impl/loader.py
- src/bentoml/_internal/cloud/deployment.py
- src/bentoml/_internal/service/loader.py
- src/bentoml/bentos.py
> feat: support bentoml serve without service name

- src/_bentoml_impl/server/app.py
> fix(regression): call error when context parameter is present

- src/bentoml/_internal/utils/analytics/usage_stats.py
✅ Issue: TypeError: unhashable type: 'list'
✅ Cause: svc.models returned a list, which set() cannot handle.
✅ Fix: Convert each model to id(model), making it hashable.
✅ Branch Name: fix-runpod-unhashable-model-error
✅ Commit Message: "Fix RunPod unhashable model error by converting svc.models to hashable IDs"
> Fix RunPod unhashable model error by converting svc.models to hashable ids

- src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
- src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2
In the dockerfile templates, I've chown'd the venv directories as they are created and deleted the chown that happens after the python dependencies are installed. The post-install chown creates a docker layer that's the size of all the files in the venv, which, if it contains pytorch, could be 5 gb or more. For me, this change cuts the image size from 12gb to 6.
> build: Smaller docker images

- src/_bentoml_impl/server/serving.py
- src/bentoml_cli/serve.py
Inject env defined under `@bentoml.service` similar to behaviour as `bentoml deploy`
this PR also remove `env_manager` (given that we barely have any data pointers on people actually using this, or we might have to think of a better way to run serve in an isolated environment)
env_manager only used in conda, so idk, good to also remove this.
> feat(serve): add `--env` and inject service-defined envs to serving environment

- src/bentoml/_internal/bento/build_config.py
When setting `requirements_txt` in the bento configuration and packages (maybe from pyproject.toml) exist, this logging statement throws an exception and building the bento fails.
> fix: format substitution

- noxfile.py
- tests/e2e/bento_new_sdk/requirements.txt
- tests/e2e/fixtures/quickstart/requirements.txt
https://github.com/huggingface/transformers/issues/37326
Given that we don't need newer version of transformers for quickstart, probably ok to lock the version of transformers
> chore: locking transformers <4.51 for quickstart tests

- src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
- src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2
This PR fixes an issue where BentoML containers fail to start in Kubernetes when using an exec-style entrypoint like:
```yaml
command: ["bentoml", "serve"]
```
The failure occurs because the bentoml CLI binary is installed inside a virtual environment at /app/.venv/bin, which is not included in the default $PATH. While the binary is available interactively (e.g., via kubectl exec), it is not found during container startup using Kubernetes command: override.
This PR updates the Dockerfile generation logic to include /app/.venv/bin in the $PATH by injecting it through the bento__envs mechanism. This ensures that the Bento container works seamlessly with Kubernetes-style overrides.
Fixes #5310  
guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes …
> fix: add /app/.venv/bin to PATH to support Kubernetes exec-style entrypoints

- src/bentoml/_internal/bento/build_config.py
> fix: Merge command line args with the ones in the config file

- src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2
This PR addresses the excessive spinner progress bar when installing deps from UV.
It will still show when the dependencies are finished installing
BentoVLLM has been using this for a while now, probably good to include it in the base Dockerfile template.
> chore: disable progress bar on cloud build

- src/_bentoml_sdk/service/config.py
This PR exposes the internal literal types to be then used externally, with the likes of BentoVLLM, BentoSGLang
> chore(config): export accelerator literal type

- src/bentoml/_internal/container/frontend/dockerfile/templates/cuda_debian.j2
Historically a specially named python3.10 package was needed on Ubuntu 22.04.
This special package no longer exists so we can now install the same package
name used on other Ubuntu versions.
Fixes #5402
> build: Use python3.10 package that exists on Ubuntu22.04

- src/bentoml/_internal/cloud/deployment.py
- src/bentoml/_internal/utils/uri.py
> fix: run post setup commands for codespace

- src/bentoml_cli/deployment.py
Fixes issue where args and an argument file could not be passed to the `bentoml deployment apply` cli command
> fix: adding build args option to apply cli command

- src/_bentoml_sdk/service/factory.py
- src/bentoml/_internal/bento/bento.py
While migrating to the python sdk released in `v1.3.20` I noticed that there was a regression in the ability to set Bento Descriptions which feed directly into the OpenAPI docs. 
Previously in the `bentofile.yaml` the description could be set either via a file or a str/markdown like below:
```
service: "service:svc"
description: |
Use **any markdown syntax** here!
> BentoML is awesome!
```
```
service: "service:svc"
description: "file: ./README.md"
```
Using the pure python sdk:
- Doesn't allow you to define where the README.md file is 
- Will use the README in the same directory as the service.py file if it exists
Both are behaviour that is sub-optimal
This PR:
- Adds an optional `description` to the service class and decorator
- If the description has been populated, as part of the …
> feat: Allow bento description to be passed to service decorator

- docs/source/build-with-bentoml/services.rst
- src/_bentoml_impl/server/app.py
- src/_bentoml_impl/server/proxy.py
- src/_bentoml_impl/server/serving.py
- src/_bentoml_sdk/service/config.py
- src/bentoml/_internal/configuration/v2/__init__.py
- src/bentoml/_internal/configuration/v2/default_configuration.yaml
- src/bentoml/_internal/server/base_app.py
- src/bentoml/_internal/server/http/instruments.py
- src/bentoml/_internal/utils/circus/__init__.py
- tests/e2e/bento_new_sdk/conftest.py
- tests/e2e/bento_new_sdk/test_custom_command.py
- tests/e2e/fixtures/static_http/service.py
- tests/e2e/fixtures/static_http/test.txt
> feat: implement reverse proxy for custom command services
