bentoml/BentoML

docs/source/guides/snippets/grpc/java/WORKSPACE.snippet.bzl

Fix this issue:
ERROR: Error computing the main repository mapping: no such package '@com_github_grpc_grpc//bazel': java.io.IOException: Error extracting /private/var/tmp/_bazel_ngohieu/c1f020311892d3ad091cef9c5c5022f9/external/com_github_grpc_grpc/temp12651717362131571927/v1.48.1.tar.gz to /private/var/tmp/_bazel_ngohieu/c1f020311892d3ad091cef9c5c5022f9/external/com_github_grpc_grpc/temp12651717362131571927: Prefix "grpc-v1.48.1" was given, but not found in the archive. Here are possible prefixes for this archive: "grpc-1.48.1".
Fixes #(issue)
those accordingly? Here are [documentation …

docs: remove grpc strip_prefix in bazel WORKSPACE

---

src/bentoml/bentos.py

I found an error in the way the serve function in bentos.py constructs the HTTPServer object. By not using named arguments and by omitting the timeout parameter, all the parameters below port  are interpreted as the wrong thing. Which on my system, caused a crash when the server tried to open a subprocess with invalid arguments.
- [ x] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
- [ x] Does the code follow BentoML's code style, `pre-commit run -a` script has passed …

fix: Modified bentos.py to construct HTTPServer using named arguments

---

.pre-commit-config.yaml
examples/tutorial/init_model.py
examples/tutorial/service.py
src/bentoml/bentos.py
typings/tritonclient/grpc/model_config_pb2.pyi
typings/tritonclient/grpc/service_pb2.pyi
typings/tritonclient/grpc/service_pb2_grpc.pyi

ci: fix black file regex

---

src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/container/frontend/dockerfile/__init__.py

Fixes a regression when dropping 3.7 EOL
Fixes #(issue)

fix: support 3.7 bentos

---

src/bentoml/_internal/cloud/bentocloud.py
src/bentoml/_internal/cloud/yatai.py
src/bentoml/_internal/store.py
src/bentoml_cli/models.py

Previously, when the model version is missing, model_store.delete() will delete the **whole** `$model_name` directory. And if the version is `latest`, it will raise an error since `$model_name/latest` isn't a directory.
Fix this to resolve to the actual version to get the path correctly.

fix: correct the logic of delete model

---

src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/bento/build_dev_bentoml_whl.py
src/bentoml/bentos.py
src/bentoml/container.py
src/bentoml_cli/bentos.py
src/bentoml_cli/containerize.py

note that these two options are mutually exclusive
Fixes #(issue)

feat(build): --push and --containerize

---

.github/workflows/ci.yml
docs/source/conf.py
pyproject.toml
requirements/docs-requirements.txt
requirements/tests-requirements.txt

chore(opentelemetry): bump to 0.39b0

---

src/bentoml/_internal/service/service.py

When pickling BentoML service with "EXPORT_BENTO" strategy, use tar as export format to save pickling time

fix: bento serialization speed up

---

src/bentoml/_internal/server/http_app.py
src/bentoml/serve.py
src/bentoml/start.py
src/bentoml_cli/serve.py
src/bentoml_cli/start.py
src/bentoml_cli/worker/http_api_server.py
src/bentoml_cli/worker/runner.py

It should override `traffic.timeout` options for all api_server and runners.

feat: Support --timeout option in serve and start cmd

---

src/bentoml_cli/containerize.py

fix(containerize): regression on passing context

---

src/bentoml/__init__.py

chore: expose Strategy and Resource class

---

src/bentoml_cli/cli.py

to add `-v` to `version_option` requires specifying `version` for passing the parameters
otherwise it will show:
```prolog
bentoml, version -v
```

fix(cli): correct set `-v` for showing version

---

scripts/release_pypi.sh

chore(infra): set comments for release

---

docs/source/tutorial.rst

The doc does not have the correct rst syntax as it uses markdown format.
Preview:
Fixes #(issue)

docs: Fix link format

---

src/bentoml/_internal/utils/circus/__init__.py

fix(circus): temporary increase check_delay to omit ConflictError

---

src/bentoml_cli/deployment.py

Include `kube-namespace` and `cluster-name` as optional options for deployment update cli. 
Also refer to https://github.com/bentoml/BentoML/pull/4085
Fixes #(issue)

fix(deployment-cli): add cloud config options for deployment cli

---

src/bentoml/grpc/v1/_generated_pb4/service_pb2.pyi
src/bentoml/grpc/v1/_generated_pb4/service_pb2_grpc.pyi
src/bentoml/grpc/v1alpha1/_generated_pb4/service_pb2.pyi
src/bentoml/grpc/v1alpha1/_generated_pb4/service_pb2_grpc.pyi
tests/proto/_generated_pb4/service_test_pb2.pyi
tests/proto/_generated_pb4/service_test_pb2_grpc.pyi

chore(release): prepare for 1.1.1 [skip ci]

---

src/bentoml/_internal/models/model.py

some type checker, such as mypy strict that contains a attr plugin
will complain missing attribute when doing `ModelInfo(...)`.
Signifying `init=False` informs mypy that this class has custom
__init__, hence it will then reference the signature of the custom
`__init__`
Fixes #(issue)

chore(type): makes ModelInfo mypy-compatible

---

src/bentoml/_internal/store.py
src/bentoml/models.py

working with store
We also should flush the yaml before enter the context, for validate to work

feat(store): update annotations

---

docs/source/quickstarts/deploy-a-large-language-model-with-openllm-and-bentoml.rst
docs/source/quickstarts/deploy-a-transformer-model-with-bentoml.rst

Fix some relative links.
Fixes #(issue)

docs: Fix some relative links

---

docs/source/quickstarts/deploy-a-transformer-model-with-bentoml.rst

docs: Code format fix

---

src/bentoml/bentos.py

Fixes #4080
Passing environment into subprocess build

fix: respect environment during `bentoml.bentos.build`

---

docs/source/frameworks/pytorch.rst

Save method is deprecated. Updated it to save_model
Replaced deprecated `bentoml.pytorch.save()` method to `bentoml.pytorch.save_model()`

docs: replaced deprecated save to save_model in pytorch.rst

---

DEVELOPMENT.md
Makefile

fix: Make the install command shorter

---

docs/source/bentocloud/getting-started/build.rst

Update the BentoCloud Build doc. The example in the original doc does not work and is not appropriate for our audience. Replace it with a simple example.
Fixes #(issue)

docs: Update the BentoCloud Build doc

---

docs/source/quickstarts/deploy-a-transformer-model-with-bentoml.rst
docs/source/quickstarts/deploy-a-yolo-model-with-bentoml.rst
examples/custom_runner/torch_hub_yolov5/service.py

docs: Add quickstart repo link and move torch import in Yolo

---

src/bentoml/_internal/runner/container.py

`DataFrame.size` is equal to the number of rows times the number of columns as described in the documentation:
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.size.html
Fixes #(issue)

fix: calculate Pandas DataFrame batch size correctly

---

src/bentoml/_internal/cloud/bentocloud.py
src/bentoml_cli/bentos.py

fix(cli): fix CLI output to BentoCloud

---

docs/source/bentocloud/getting-started/build.rst
docs/source/frameworks/sklearn.rst

Fix sklearn example docs

---

docs/source/bentocloud/reference/deployment-creation-and-update-info.rst
docs/source/bentocloud/reference/index.rst
docs/source/bentocloud/references/index.rst
docs/source/index.rst

Add property explanations for the BentoCloud Deployment creation and update page.
Fixes #(issue)

docs: Add the BentoCloud Deployment creation and update page property explanations

---

.pre-commit-config.yaml
docs/source/bentocloud/getting-started/build.rst

fix: disable pyright for being too strict

---

src/bentoml/_internal/cloud/bentocloud.py
src/bentoml_cli/models.py

Just to make it consistent with the rest

fix(cli): change model to lower case

---

docs/source/overview/ecosystem.rst

Add OneDiffusion to the BentoML ecosystem doc

docs: Add OneDiffusion to the BentoML ecosystem doc

---

src/bentoml/_internal/client/http.py
src/bentoml/_internal/io_descriptors/base.py
tests/e2e/bento_server_http/service.py
tests/e2e/bento_server_http/tests/test_client.py

fix: Hotfix for StreamingResponse breaking Client

---

src/bentoml/_internal/log.py

`defaulthandler` need to be set to debug else it will get filtered out by `InfoFilter`
Fixes #(issue)

fix(cli): Fix Debug mode not working for CLI level logs

---

README.md

docs: Add text embedding example to readme

---

src/bentoml/_internal/runner/runner.py

This has to do with attr's plugin in mypy where if a class has custom init, `init=False` should be set such that the correct __init__ can be inferred.
Fixes #(issue)

fix(type): explicit init for attrs Runner

---

docs/source/quickstarts/index.rst

docs: fix typo

---

src/bentoml/bentos.py

fix: parse tag from multiline output

---

docs/source/bentocloud/getting-started/understand-bentocloud.rst

docs: Add observability to the BentoCloud overview docs

---

src/bentoml/_internal/frameworks/sklearn.py
src/bentoml/_internal/frameworks/xgboost.py

fix(framework): add args and kwargs to sklearn and xgboost methods

---

docs/source/concepts/bento.rst
docs/source/concepts/model.rst

Fixes #(issue)
**bento.rst**
- 'which will help boostrap the Bento' -> 'which will help bootstrap the Bento'
**model.rst**
- 'uese the to_runner API' -> 'use the to_runner API'
- '``runner#run`` calls made' -> '``runner.run`` calls made'

docs: fix typo in bento.rst and model.rst

---

src/bentoml/_internal/cloud/schemas.py

These fields should be deleted to sync with bentocloud schemas so that `bentoml deployment get` can work
Fixes #(issue)

fix(cloud-client): delete unused field of schema

---

docs/source/concepts/bento.rst

Add docs for https://github.com/bentoml/BentoML/pull/3696

docs: Add docs for the new bentoml.Server API

---

docs/source/quickstarts/deploy-stable-diffusion-xl-with-dynamic-lora-adapters.rst

docs: Add the OneDiffusion Google Colab task

---

docs/source/bentocloud/best-practices/cost-optimization.rst
docs/source/bentocloud/best-practices/index.rst
docs/source/index.rst

docs: Add best practices doc for cost optimization

---

docs/source/bentocloud/how-tos/manage-models-and-bentos.rst

docs: Update the Manage Models and Bentos docs

---

src/bentoml/serve.py

fix: do not use UDS on WSL

---

src/bentoml_cli/bentos.py
src/bentoml_cli/models.py

docs: fix typos in help messages

---

src/bentoml/serve.py

fix: allow WSL in the condition

---

docs/source/frameworks/easyocr.rst

`readtext` returns a list of results, hence we need to set the appropriate io descriptor.
Fixes #(issue)

fix: EasyOCR integration docs mistake

---

src/bentoml/_internal/service/openapi/__init__.py

fix: include mounted FastAPI app's OpenAPI components

---

src/bentoml/_internal/models/model.py

* src/bentoml/_internal/models/model.py -> 95 line : fixing BentoMLException's error message.

UPDATE: model.py -> fix Model class Exepction message.

---

docs/source/bentocloud/reference/deployment-creation-and-update-info.rst

docs: Remove private access mention

---

docs/source/bentocloud/best-practices/cost-optimization.rst
docs/source/bentocloud/best-practices/index.rst
docs/source/bentocloud/getting-started/index.rst
docs/source/bentocloud/how-tos/deploy-bentos.rst
docs/source/bentocloud/how-tos/index.rst
docs/source/bentocloud/how-tos/manage-access-token.rst
docs/source/bentocloud/how-tos/manage-models-and-bentos.rst
docs/source/bentocloud/how-tos/manage-users.rst
docs/source/bentocloud/how-tos/monitor-events.rst
docs/source/bentocloud/topics/index.rst
docs/source/bentocloud/topics/observability.rst

Change titles to sentence case for BentoCloud docs. Reason: https://github.com/bentoml/BentoML/pull/4203#discussion_r1331468598
Also, no need to use "ing" for title verbs. This is to make titles shorter and cleaner as they are displayed on the left menu.
I will do the same for the BentoML docs later.

docs: Change to sentence case

---

docs/source/overview/ecosystem.rst

docs: Fix dead link

---

docs/source/frameworks/detectron.rst
docs/source/frameworks/diffusers.rst
docs/source/frameworks/pytorch.rst
docs/source/frameworks/pytorch_lightning.rst
docs/source/guides/grpc.rst
docs/source/guides/migration.rst
docs/source/integrations/ray.rst

docs: Fix all dead links in BentoML docs

---

docs/source/concepts/service.rst

Add some language and format improvements for the Services doc.

docs: Update the Services doc

---

pdm.lock
pyproject.toml

- fix(exception): catch exception for users' runners code (#4150)
- docs: Add the streaming docs (#4164)
- ci: pre-commit autoupdate [skip ci] (#4167)
- fix(httpclient): take into account trailing slash in from_url (#4169)
- docs: fix typo (#4173)
- fix: apply env map for distributed runner workers (#4174)
- docs: Add the SDXL deployment quickstart (#4175)
- docs: using new API for pytorch docs (#4176)
- chore(deps): bump actions/checkout from 3 to 4 (#4177)
- fix: parse tag from multiline output (#4178)
- docs: Update the user management docs (#4186)
- fix(config): set default runner timeout to 15min (#4184)
- docs: Add observability to the BentoCloud overview docs (#4187)
- fix(framework): add args and kwargs to sklearn and xgboost methods (#4189)
- docs: fix typo (#4192)
- fix: Rename …

fix(deps): bump otel for CVE

---

docs/source/quickstarts/deploy-a-large-language-model-with-openllm-and-bentoml.rst

docs: Add the OpenLLM Llama 2 Colab link

---

docs/source/bentocloud/best-practices/bento-building-and-deployment.rst
docs/source/bentocloud/best-practices/index.rst

docs: Add best practices doc for building and deploying Bentos

---

docs/source/quickstarts/deploy-stable-diffusion-xl-with-dynamic-lora-adapters.rst

docs: Update OneDiffusion Colab link

---

src/bentoml/_internal/runner/runner_handle/remote.py

#4250 
This PR is aiming to suppress abstractmethod TypeError of TritonRunnerHandle
I checked it worked ok to define missing method with `raise NotImplementedError`
Fixes #(issue)

fix: suppress abstractmethod TypeError of TritonRunnerHandle

---

src/bentoml/_internal/server/http_app.py

fix: send request ID in response headers in all cases

---

.github/workflows/ci.yml
pyproject.toml
src/bentoml/_internal/client/http.py
tests/e2e/bento_server_http/tests/test_client.py
tests/e2e/bento_server_http/tests/test_serve.py
tests/unit/_internal/utils/test_analytics.py

- fix metrics test mocking
- fix tests related to async client changes
- disable grpc tests
- only run unit tests in tests-unit

fix(ci): fix tests

---

docs/source/guides/configuration.rst
src/bentoml/_internal/configuration/containers.py
src/bentoml/_internal/configuration/helpers.py
tests/unit/_internal/configuration/test_containers.py
tests/unit/_internal/configuration/test_helpers.py

feat: support storing secrets with env vars in config

---

docs/source/concepts/deploy.rst
docs/source/concepts/index.rst
docs/source/concepts/model.rst
docs/source/concepts/runner.rst
docs/source/guides/containerization.rst
docs/source/guides/migration.rst
docs/source/guides/monitoring.rst
docs/source/guides/security.rst
docs/source/integrations/airflow.rst
docs/source/integrations/flink.rst
docs/source/overview/ecosystem.rst
docs/source/overview/what-is-bentoml.rst
docs/source/reference/container.rst
docs/source/reference/stores.rst

This pr does the following:
1. Update the Deployment doc. Currently, BentoCloud & Docker are two major ways. Custom deployment will be added once we have a more clear position of it, probably in blog posts. I reckon in docs, we might want to encourage users to select the most common deployment options.
2. Remove bentoctl references as we are deprecating it. The only mention is this doc https://docs.bentoml.com/en/latest/guides/migration.html. I am not sure if we want to keep this or remove it?
3. Replace most of the Yatai references with BentoCloud.
those accordingly? Here are [documentation …

docs: Update the deployment docs

---

docs/source/bentocloud/how-tos/deploy-bentos.rst
docs/source/bentocloud/how-tos/manage-access-token.rst

Fix --data field in curl commands in bentocloud documentation

bentocloud doc update --data field

---

docs/source/bentocloud/getting-started/quickstart.rst
docs/source/bentocloud/how-tos/deploy-bentos.rst

Add a note to enter Repository and Bento name to search for it if it is not displayed in the dropdown.

docs: Add repository and bento selection notes

---

src/bentoml/_internal/marshal/dispatcher.py

In the training logics, we might override the batch_size variable here, causing `UnboundedLocalError: local variable 'batch_size' referenced before assignment`. This PR aims to fix that
by copying the batch_size variable to a new variable.

fix(dispatcher): unbounded overload batch_size

---

docs/source/quickstarts/deploy-a-transformer-model-with-bentoml.rst

docs: update transformers example to include gpu options

---

docs/source/guides/monitoring.rst

fix monitoring docs configuration.yaml typo

---

src/bentoml/_internal/frameworks/transformers.py

Fixes #4220
Should now accept either `torch` or `pt` for the value of `_framework` so that pretrained models can be imported and used properly.

fix: runnable framework logic in transformers.py

---

docs/source/concepts/bento.rst

docs: Update docs on supported CUDA versions

---

docs/source/frameworks/diffusers.rst
docs/source/frameworks/transformers.rst
docs/source/quickstarts/deploy-a-transformer-model-with-bentoml.rst

Add docs for https://github.com/bentoml/BentoML/pull/4247.

docs: Add docs for new transformers model import API

---

pdm.lock
pyproject.toml

fix(dependencies): lock cattrs<23.2 for now

---

README.md

fix: citation link at `README.md`

---

src/bentoml/_internal/frameworks/transformers.py
tests/integration/frameworks/test_transformers_unit.py

Add unit tests to transformers import model

fix(transformers): support `trust_remote_code` and added unit tests

---

docs/source/bentocloud/how-tos/index.rst
docs/source/bentocloud/how-tos/view-deployment-details.rst
docs/source/bentocloud/reference/deployment-details.rst
docs/source/bentocloud/reference/index.rst

Add some explanations for the properties on the Deployment details page.

docs: Add Bento Deployment details docs

---

webui/src/components/InferenceForm.tsx
webui/src/components/form/FormControl.tsx
webui/src/components/form/FormField.tsx
webui/src/hooks/useQuery.ts

Add feature for form validation

feat: add feature for form validation

---

src/bentoml/_internal/frameworks/onnx.py

There is a small syntax mistake in a code sample in the docs. Quick fix. 
Fixes #(issue)

fix: syntax error on code snippet in bentoml.onnx.save_model docs

---

examples/quickstart/service.py
src/bentoml/_internal/cloud/bentocloud.py
src/bentoml/_internal/cloud/schemas.py
src/bentoml_io/config.py

fix: example and bento config

---

examples/quickstart/model_pipeline.py
src/bentoml/__init__.py
src/bentoml/_internal/configuration/__init__.py
src/bentoml/_internal/configuration/containers.py
src/bentoml/_internal/configuration/helpers.py
src/bentoml/_internal/configuration/v1/__init__.py
src/bentoml/_internal/configuration/v2/__init__.py
src/bentoml/_internal/configuration/v2/default_configuration.yaml
src/bentoml/_internal/io_descriptors/json.py
src/bentoml_cli/serve.py
src/bentoml_cli/start.py
src/bentoml_io/client/http.py
src/bentoml_io/config.py
src/bentoml_io/factory.py
src/bentoml_io/server/allocator.py
src/bentoml_io/server/app.py
src/bentoml_io/server/serving.py
src/bentoml_io/worker/service.py
tests/unit/bentoml_io/test_allocator.py

feat: config override

---

examples/fraud_detection/benchmark/README.md

Fixed type in requirements for running benchmark in examples section
I changed documentation, so there's no need in tests or code style

docs: fixed typo in file name benchmark README.md

---

src/bentoml/_internal/configuration/containers.py
src/bentoml/_internal/configuration/v1/__init__.py
src/bentoml/_internal/configuration/v2/__init__.py

fix: fix config migration

---

src/bentoml_io/client/proxy.py

Fixes: error when call async api

fix: async api call

---

src/bentoml/_internal/configuration/containers.py

fix(config): typo on override

---

webui/src/components/InferenceForm.tsx

Add loading status when form is submitting

feat: add loading status when form is submitting

---

src/_bentoml_sdk/service/config.py

Chore: add supported gpu type

---

src/bentoml/_internal/io_descriptors/utils.py

Testing:
```
pytest tests/unit/test_utils.py
```

chore(sse): refactor sse utils with efficient buffering

---

src/bentoml/_internal/runner/container.py

fix(runner): fix DataFrame container header too long

---

src/bentoml/_internal/cloud/bentocloud.py
src/bentoml/_internal/cloud/schemas.py

fix: add services in manifest

---

src/bentoml/_internal/io_descriptors/utils.py
src/bentoml/_internal/runner/runner.py
src/bentoml/_internal/runner/runner_handle/remote.py
src/bentoml/_internal/server/runner_app.py
src/bentoml/io.py
tests/unit/test_utils.py

chore: cherry-pick SSE utils into 1.2 branch

---

src/bentoml/_internal/cloud/bentocloud.py
src/bentoml/_internal/cloud/schemas.py

fix: correct 1.2 model list and tag format when pushing bento

---

src/_bentoml_impl/server/allocator.py
src/_bentoml_impl/server/app.py
src/_bentoml_sdk/service/config.py
src/_bentoml_sdk/service/factory.py
src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/configuration/v2/__init__.py
src/bentoml/_internal/utils/__init__.py
tests/unit/bentoml_io/test_allocator.py

- Update the schema of bento.yaml
- Only allow number for `workers` config and simplify allocator

feat: Update the bento yaml schema

---

src/_bentoml_impl/server/serving.py
src/bentoml/_internal/service/loader.py

feat(sdk): use attribute chain as dependency import string

---

docs/source/integrations/triton.rst

I have found some small issues in documentation on this page https://docs.bentoml.org/en/latest/integrations/triton.html.
1. There is a typo in tritonserver_type=''http' with double ' before http
2. for example "To get OUTPUT__1 as a JSON dictionary:", there is an inconsistency in the return line where it mentions OUTPUT_0, but it should be OUTPUT_1.
Fixes #(issue)

docs: fix typo in tritonserver_type parameter and code example

---

src/_bentoml_sdk/service/factory.py
src/bentoml/_internal/bento/bento.py

fix: dependency names and import string in bento.yaml

---

src/bentoml/_internal/configuration/v2/__init__.py

feat: add external queue in config

---

src/_bentoml_impl/loader.py
src/_bentoml_impl/server/serving.py
src/_bentoml_impl/worker/service.py
src/_bentoml_sdk/service/dependency.py
src/_bentoml_sdk/service/factory.py
src/bentoml/_internal/bento/bento.py
src/bentoml/server.py
src/bentoml/testing/server.py
src/bentoml_cli/start.py

For yatai:
```
> bentoml start-http-server . --service-name Preprocessing --port 3000
> bentoml start-http-server . --service-name iris_classifier --port 4000 --depends Preprocessing=http://localhost:3000
```

chore: serve specify dependency services

---

docs/source/get-started/introduction.rst
docs/source/get-started/quickstart.rst
docs/source/guides/index.rst
docs/source/guides/services.rst
docs/source/index.rst

docs: Add the 1.2 Services doc

---

src/_bentoml_impl/server/serving.py
src/bentoml/_internal/cloud/deployment.py

- Increase default deploy timeout and interval.
- Remove the Prometheus log to avoid confusion regarding which link the user should click.
Fixes #(issue)

chore: increase default deploy timeout and interval

---

src/_bentoml_impl/client/http.py
src/_bentoml_impl/serde.py
src/_bentoml_sdk/validators.py

feat: allow url as file input

---

src/_bentoml_sdk/service/factory.py
src/bentoml/_internal/tag.py

yatai is using service name as service domain name

fix(sdk): validate service name; force lowercase

---

examples/quickstart/service.py
src/_bentoml_sdk/service/factory.py
src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/cloud/bentocloud.py
src/bentoml/_internal/cloud/schemas/modelschemas.py
src/bentoml/_internal/cloud/yatai.py
src/bentoml/_internal/tag.py
tests/unit/_internal/bento/test_bento.py
tests/unit/_internal/cloud/test_deployment.py

cc @frostming 
The bento name has to be DNS name, while we wanna keep the service name as is

refactor(bento): add entry_service to bento info

---

src/bentoml/_internal/cloud/bentocloud.py
src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/deployment.py

fix: fix get bento from cloud

---

src/bentoml/_internal/cloud/schemas/modelschemas.py

fix: change entry_service to optional

---

src/_bentoml_impl/client/http.py
src/_bentoml_impl/client/proxy.py
src/bentoml/_internal/cloud/schemas/schemasv1.py

fix: make client timeout consistent with service config

---

src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas/schemasv2.py
src/bentoml/deployment.py
src/bentoml_cli/deployment.py

fix: fix env in deploy and create error msg

---

src/_bentoml_impl/server/serving.py

fix: port reservation causes bind error on Windows

---

src/bentoml/_internal/cloud/deployment.py

fix: add more status check in wait until ready

---

README.md

docs: Update readme doc

---

src/_bentoml_sdk/validators.py

fix: image encoding issue when the format is not specified

---

src/_bentoml_impl/server/app.py

feat: add adaptive batch size histogram

---

src/bentoml_cli/cloud.py
src/bentoml_cli/serve.py

feat(cli): remove or hide unneeded commands

---

noxfile.py
src/_bentoml_sdk/io_models.py
tests/e2e/bento_server_http/tests/test_serve.py

fix: only inline display images

---

docs/source/get-started/quickstart.rst
docs/source/guides/services.rst
docs/source/index.rst

docs: Update homepage

---

src/_bentoml_impl/server/app.py
src/bentoml/_internal/log.py
src/bentoml/_internal/server/http/access.py

feat: skip access log for infra endpoints

---

src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/cloud/bentocloud.py
src/bentoml/_internal/cloud/schemas/modelschemas.py
src/bentoml/_internal/cloud/yatai.py
tests/unit/_internal/bento/test_bento.py

add schema in `Bento.yaml`
and push to bentocloud for new IO
Fixes #(issue)

feat: add schema in bentoInfo

---

src/bentoml_cli/deployment.py

fix: fix deployment cli log

---

src/_bentoml_impl/server/app.py

fix: convert generator to async gen before response

---

src/bentoml/bentos.py

Fixes #4454 
- [x ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
- [ x] Does the code follow BentoML's code style, `pre-commit run -a` script has passed ([instructions](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#style-check-auto-formatting-type-checking))?
- [ x] Did you read through [contribution guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md#ways-to-contribute) and follow [development guidelines](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md#st …

fix: Remove trailing character when building bento with API on Windows

---

src/_bentoml_impl/server/allocator.py

feat: allow disabling GPU allocation via env

---

src/_bentoml_sdk/api.py

fix: correct schema for optional type

---

src/_bentoml_impl/client/http.py

fix: client sending request fail if the input is a list of files

---

docs/source/guides/deployment.rst
docs/source/guides/index.rst

docs: Add deployment doc

---

src/_bentoml_impl/server/app.py
src/_bentoml_sdk/service/config.py
src/bentoml/_internal/configuration/v2/__init__.py
src/bentoml/_internal/configuration/v2/default_configuration.yaml
src/bentoml/_internal/server/http/access.py

feat: make skip paths configurable

---

docs/source/guides/configurations.rst
docs/source/guides/index.rst

docs: Add config docs

---

src/_bentoml_impl/client/http.py

fix(client): Convert string to Path if it isn't like a URL

---

docs/source/guides/index.rst
docs/source/guides/model-store.rst

docs: Add Model Store doc

---

docs/source/get-started/introduction.rst
docs/source/get-started/quickstart.rst

docs: Update the quickstart

---

docs/source/index.rst

docs: Add more featured use cases

---

docs/source/use-cases/blip.rst
docs/source/use-cases/embeddings/clip-embeddings.rst
docs/source/use-cases/embeddings/sentence-transformer.rst

docs: Remove direct execution lines

---

docs/source/bentocloud/how-tos/create-deployments.rst
docs/source/guides/distributed-services.rst
docs/source/guides/index.rst

docs: Add distributed services doc

---

pdm.lock
pyproject.toml
src/_bentoml_impl/server/app.py
src/bentoml/_internal/cloud/deployment.py

fix(server): clean the request resources after the response is consumed

---

src/_bentoml_sdk/service/config.py
src/_bentoml_sdk/service/factory.py
src/bentoml/_internal/configuration/v2/__init__.py
typings/schema.pyi

feat: tpu_type support

---

README.md

docs: Update the readme

---

src/_bentoml_impl/loader.py

fix(sdk): current directory for built bentos

---

src/_bentoml_impl/client/http.py
src/_bentoml_impl/serde.py
src/_bentoml_sdk/io_models.py
src/_bentoml_sdk/validators.py
src/bentoml/__init__.py

fix: bug: Dataframes not serializing correctly in the new API

---

docs/source/bentocloud/get-started.rst
docs/source/bentocloud/how-tos/create-deployments.rst
docs/source/bentocloud/how-tos/manage-access-token.rst
docs/source/bentocloud/how-tos/manage-deployments.rst
docs/source/guides/distributed-services.rst

Fix some format issues and add some output examples.

docs: Update docs

---

docs/source/bentocloud/how-tos/create-deployments.rst
docs/source/bentocloud/how-tos/manage-access-token.rst

docs: Add authorization docs

---

docs/source/bentocloud/get-started.rst
docs/source/get-started/quickstart.rst

Change the sample input to one line to avoid grabbing too much attention from the code.

docs: Change sample input to one line

---

docs/source/use-cases/diffusion-models/controlnet.rst

Update the doc based on https://github.com/bentoml/BentoControlNet/pull/3.

docs: Update ControlNet use case docs

---

docs/source/bentocloud/get-started.rst
docs/source/guides/distributed-services.rst

docs: Update the distributed services and get started docs

---

src/bentoml/_internal/cloud/deployment.py

fix: fix list deployment exception

---

src/bentoml/_internal/cloud/deployment.py

feat: add get endpoint url for deployment

---

src/bentoml/_internal/cloud/deployment.py

fix: add missing to dict for deployment config

---

src/_bentoml_impl/client/__init__.py
src/_bentoml_impl/client/http.py
src/_bentoml_impl/loader.py
src/_bentoml_impl/server/app.py
src/_bentoml_impl/server/serving.py
src/_bentoml_impl/worker/service.py

feat(client): disallow media type other than json for HTTP clients

---

src/_bentoml_impl/server/app.py

fix: correctly encode ValueError in response

---

src/bentoml/_internal/cloud/config.py
src/bentoml_cli/bentos.py
src/bentoml_cli/deployment.py

fix: improve CLI message

---

src/_bentoml_impl/server/app.py
src/_bentoml_impl/server/serving.py
src/_bentoml_sdk/__init__.py
src/_bentoml_sdk/api.py
src/_bentoml_sdk/service/factory.py
src/bentoml/__init__.py

```python
import bentoml
@bentoml.service
class MyService:
def __init__(self) -> None:
...
@bentoml.on_shutdown   
def on_shutdown(self) -> None:
...
```

feat: add back service hooks

---

docs/source/guides/model-store.rst

Otherwise this will give
```
FileExistsError: [Errno 17] File exists: '/tmp/tmppdcab4wubentoml_model_my-test-model/'
```
because the context manager already created the directory.
Fixes #(issue)

doc: allow reuse of existing directory

---

src/bentoml/_internal/cloud/config.py

feat: cloud context from env vars

---

docs/source/guides/clients.rst

1. Added the error handling section.
2. Updated code examples to not use the context manager.
3. Added some Service code for better understanding of client code.

docs: Update the clients doc

---

docs/source/guides/adaptive-batching.rst

docs: Update adaptive batching docs

---

src/bentoml/__init__.py

feat: export component context at top namespace

---

src/bentoml/_internal/context.py

feat: use starlette request directly in service context

---

pdm.lock
pyproject.toml
src/_bentoml_impl/client/__init__.py
src/_bentoml_impl/server/app.py
src/_bentoml_sdk/__init__.py
src/_bentoml_sdk/_internals.py
src/_bentoml_sdk/api.py
src/_bentoml_sdk/decorators.py
src/_bentoml_sdk/service/factory.py
src/_bentoml_sdk/service/openapi.py
src/bentoml/__init__.py
tests/unit/bentoml_io/test_decorators.py

feat: mount asgi app and fastapi support

---

src/bentoml/_internal/cloud/bentocloud.py
src/bentoml/_internal/cloud/client.py

fix: crash when pulling bento from organization with proxy mode

---

docs/source/bentocloud/how-tos/configure-deployments.rst
docs/source/guides/build-options.rst

docs: Add envs field in bentofile

---

docs/source/use-cases/audio/whisperx.rst
docs/source/use-cases/audio/xtts.rst
docs/source/use-cases/blip.rst
docs/source/use-cases/diffusion-models/controlnet.rst
docs/source/use-cases/diffusion-models/sdxl-lcm-lora.rst
docs/source/use-cases/diffusion-models/sdxl-turbo.rst
docs/source/use-cases/diffusion-models/svd.rst
docs/source/use-cases/embeddings/clip-embeddings.rst
docs/source/use-cases/embeddings/sentence-transformer.rst
docs/source/use-cases/large-language-models/vllm.rst

docs: Add GitHub repo links for use case docs

---

docs/source/use-cases/large-language-models/vllm.rst

docs: Update the vllm use case doc

---

src/_bentoml_impl/client/proxy.py
src/_bentoml_impl/server/app.py
src/_bentoml_sdk/__init__.py
src/_bentoml_sdk/_internals.py
src/_bentoml_sdk/decorators.py
src/_bentoml_sdk/method.py
src/_bentoml_sdk/service/__init__.py
src/_bentoml_sdk/service/factory.py

fix: rename the _bentoml_sdk.api module

---

src/_bentoml_impl/client/__init__.py
src/_bentoml_impl/client/base.py
src/_bentoml_impl/client/http.py
src/_bentoml_impl/client/proxy.py
tests/e2e/bento_new_sdk/test_quickstart.py

fix: wait until server ready when initializing client

---

src/_bentoml_impl/server/serving.py
src/_bentoml_sdk/__init__.py
src/_bentoml_sdk/decorators.py
src/bentoml/__init__.py

feat: Add server.on_deployment hook to execute deployment-specific logic

---

docs/source/bentocloud/how-tos/create-deployments.rst
docs/source/use-cases/embeddings/sentence-transformer.rst

docs: Adjust existing Bento deployment wording

---

src/bentoml/_internal/cloud/deployment.py

fix: fix list instance type

---

src/bentoml/_internal/cloud/deployment.py

fix: delete access in admin console

---

src/_bentoml_impl/client/proxy.py
src/_bentoml_sdk/io_models.py
src/bentoml/_internal/runner/runnable.py

fix: allow legacy runnable methods when calling API

---

docs/source/guides/index.rst
docs/source/guides/testing.rst

docs: Add testing doc

---

docs/source/guides/index.rst
docs/source/guides/lifecycle-hooks.rst
docs/source/guides/services.rst

docs: Add lifecycle hooks doc

---

src/bentoml/_internal/bento/build_config.py

fix: improve the bentoml build progress

---

src/_bentoml_impl/server/app.py

fix: allow API endpoint to return response directly

---

src/_bentoml_impl/server/app.py

fix: raise the priority of the routes from mount apps

---

src/bentoml/bentos.py

fix: build config env default to None

---

src/_bentoml_impl/worker/service.py
src/bentoml/_internal/configuration/v2/__init__.py

fix: config from multiple services override with each other

---

src/_bentoml_impl/server/app.py
src/_bentoml_sdk/service/config.py
src/bentoml/_internal/configuration/v2/__init__.py

add `concurrency` to the service config.
Fixes #(issue)

feat: add concurrency config

---

docs/source/use-cases/large-language-models/vllm.rst

docs: Add OpenAI compatible endpoints client doc

---

src/bentoml/_internal/configuration/v2/__init__.py

fix schema too strict when adding new field to service decorator
Fixes #(issue)

fix: ignore_extra_keys for v2 configuration schema

---

src/bentoml/_internal/bento/bento.py

fix: emit warnings when copying large file

---

src/_bentoml_impl/client/proxy.py
src/_bentoml_sdk/service/factory.py
tests/unit/bentoml_io/test_decorators.py

feat: service.to_async property

---

src/_bentoml_impl/client/http.py
src/_bentoml_impl/serde.py
src/_bentoml_sdk/io_models.py
src/_bentoml_sdk/validators.py

feat: picklev5 serialization

---

docs/source/guides/autoscaling.rst
docs/source/guides/index.rst

docs: add autoscaling docs

---

docs/source/guides/configurations.rst

docs: Fix old configurations doc link

---

src/bentoml/_internal/utils/circus/watchfilesplugin.py

Make sure that we watch all src folders instead of just bentoml

fix(reload): make sure to watch for all src for editable

---

src/_bentoml_sdk/service/openapi.py

See https://spec.openapis.org/oas/v3.0.2#operation-object

fix(openapi): remove invalid fields for operations parameter

---

README.md

docs: Remove old example links

---

src/_bentoml_sdk/method.py
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/bento/install.sh.j2
src/bentoml/_internal/utils/__init__.py

feat: download git+ssh dependencies to wheels/ folder

---

src/bentoml/_internal/marshal/dispatcher.py

fix: non batched request executed in non FIFO manner

---

docs/source/bentocloud/how-tos/autoscaling.rst
docs/source/bentocloud/how-tos/configure-deployments.rst
docs/source/guides/concurrency.rst

docs: Refactor the autoscaling doc

---

docs/source/guides/testing.rst

docs: Add simple verification test for Services

---

docs/source/guides/configurations.rst
docs/source/guides/lifecycle-hooks.rst
docs/source/guides/services.rst
docs/source/guides/workers.rst

docs: Add worker doc links

---

docs/source/guides/services.rst

docs: Add sync to async doc

---

src/bentoml_cli/bentos.py

fix(cli): `bentoml get` output in YAML format

---

README.md
docs/source/get-started/introduction.rst
docs/source/index.rst

docs: Update high-level BentoML messaging

---

src/bentoml/_internal/cloud/deployment.py

Fixes: delete trace error for timeout when deploying

fix: delete trace error for timeout when deploying

---

docs/source/guides/clients.rst
examples/quickstart/client.py
examples/quickstart/service.py

chore: update quickstart

---

docs/source/use-cases/large-language-models/vllm.rst

docs: Add JSON output for bentovllm

---

docs/source/get-started/installation.rst

docs: Update help info

---

src/_bentoml_impl/worker/service.py

fix: remove the uvicorn server header

---

docs/source/guides/iotypes.rst

docs: Fix format

---

docs/source/guides/configurations.rst
docs/source/guides/index.rst
docs/source/guides/observability/index.rst
docs/source/guides/observability/monitoring-and-data-collection.rst

docs: Add the monitoring and data collection doc

---

src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas/modelschemas.py
tests/unit/_internal/cloud/test_deployment.py

fix: delete useless enum and fix enum value

---

README.md

docs: Add RAG tutorial

---

docs/source/bentocloud/how-tos/call-deployment-endpoints.rst
docs/source/guides/testing.rst

docs: Add e2e test doc

---

src/bentoml/_internal/cloud/bentocloud.py
src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/yatai.py

fix bentoml push failed and more

fix(cloud client): various type error

---

src/bentoml/_internal/server/http/traffic.py

fix: bypass /livez in traffic middleware

---

src/_bentoml_impl/worker/service.py

fix: server socket binding on Windows

---

src/bentoml/_internal/server/http/traffic.py

fix: correct the logic of bypassing infra endpoints in traffic middleware

---

src/bentoml/_internal/bento/bento.py

fix: include models from config for new SDK bentos

---

docs/source/guides/iotypes.rst
src/_bentoml_sdk/_pydantic.py

Fixes bug reported in [Slack](https://bentoml.slack.com/archives/CKRANBHPH/p1714672615101629).

fix: annotation preparation list iteration bug

---

src/_bentoml_impl/server/app.py
src/bentoml/_internal/service/openapi/specification.py

- Fix #4703
- Fix #4698
Fixes #(issue)

fix: tuple schema and websocket connection

---

src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/log.py

fix: show warning instead of hard failure when model is missing

---

src/bentoml/_internal/cloud/deployment.py

fix: add scaled to zero in client

---

src/_bentoml_impl/server/app.py

fix: serailization error when request with an invalid json input

---

src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/container/generate.py

fix: handle ssh git url without ref part

---

src/_bentoml_impl/worker/service.py
src/bentoml_cli/serve.py
src/bentoml_cli/start.py
src/bentoml_cli/worker/http_api_server.py

fix: correct the default value of timeout-keep-alive

---

src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/utils/__init__.py

fix: handle subdirectory in git ssh url

---

docs/source/guides/iotypes.rst

docs: Add compound data types doc

---

docs/source/bentocloud/reference/deployment-details.rst

docs: Update deployment details explanations

---

.pre-commit-config.yaml
src/_bentoml_impl/loader.py

fix: load model aliases before loading new SDK service

---

docs/source/guides/model-composition.rst

docs: Fix cpu as strings

---

src/bentoml/_internal/monitoring/default.py
src/bentoml/_internal/monitoring/otlp.py

feat: add trace id to monitoring module

---

src/_bentoml_impl/server/app.py
src/_bentoml_sdk/io_models.py

fix: missing components from output schema if it is a root model

---

docs/source/guides/model-store.rst

docs: update model store

---

docs/source/use-cases/large-language-models/vllm.rst

docs: Add env var for mistral 7b docs

---

README.md

docs: Update GitHub readme

---

src/bentoml/_internal/bento/build_config.py

chore(build): update build_config.py

---

src/_bentoml_impl/worker/service.py

fix: configure server logging before importing service

---

src/bentoml/_internal/log.py

Currently, server logging disables all non-root loggers. This shouldn't be disabled, since users can have their own loggers set up.

fix: should enable existing loggers in server logging config

---

src/_bentoml_sdk/io_models.py
src/_bentoml_sdk/service/factory.py
src/bentoml/_internal/utils/__init__.py

fix: log errors inside a streaming response and detect service name conflicts

---

src/_bentoml_sdk/validators.py

fix: don't try to validate non-bytes as Path

---

docs/source/bentocloud/how-tos/autoscaling.rst

docs: scale from zero

---

docs/source/get-started/installation.rst

docs: Update installation.rst

---

src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/bento/build_config.py

fix: bad performance when walking the file tree and check includes

---

README.md

update readme to include chattts

---

src/bentoml/_internal/cloud/deployment.py

fix: set env to null if it is empty for merge override

---

src/_bentoml_impl/client/http.py
src/bentoml/exceptions.py

fix: map error responses from HTTP client to bentoml exceptions

---

src/_bentoml_impl/loader.py
src/_bentoml_impl/worker/service.py

fix: populate bento name and version of server context

---

pdm.lock
pyproject.toml
src/bentoml/_internal/cloud/base.py
src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas/schemasv2.py
src/bentoml_cli/deployment.py

feat: show image builder logs

---

docs/source/use-cases/diffusion-models/controlnet.rst
docs/source/use-cases/diffusion-models/sdxl-lcm-lora.rst
docs/source/use-cases/diffusion-models/sdxl-turbo.rst
docs/source/use-cases/diffusion-models/svd.rst

Update based on https://github.com/bentoml/BentoDiffusion/pull/25

docs: Update diffusion model repos to the new one

---

docs/source/use-cases/audio/whisperx.rst
docs/source/use-cases/audio/xtts.rst
docs/source/use-cases/blip.rst
docs/source/use-cases/diffusion-models/controlnet.rst
docs/source/use-cases/diffusion-models/sdxl-lcm-lora.rst
docs/source/use-cases/diffusion-models/sdxl-turbo.rst
docs/source/use-cases/diffusion-models/svd.rst
docs/source/use-cases/embeddings/clip-embeddings.rst
docs/source/use-cases/embeddings/sentence-transformer.rst
docs/source/use-cases/large-language-models/vllm.rst

docs: update examples service decorators with new features

---

docs/source/guides/error-handling.rst
docs/source/guides/index.rst

doc: Custom Error Handling

---

docs/source/guides/error-handling.rst
docs/source/guides/index.rst

doc: Wording change in error handling doc

---

src/bentoml/_internal/cloud/base.py
src/bentoml/_internal/cloud/bentocloud.py
src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/yatai.py
src/bentoml_cli/deployment.py

fix: improve the code of spinner and log tailer

---

docs/source/guides/iotypes.rst

doc: Update the docs about multipart output

---

docs/source/bentocloud/how-tos/batch-inference-jobs.rst
docs/source/bentocloud/how-tos/index.rst

docs: Add batch inference jobs doc

---

docs/source/guides/gpu-inference.rst
docs/source/use-cases/large-language-models/vllm.rst

doc: Fix typo and format

---

src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/deployment.py

fix(cli): hanging issue when deployment ready

---

docs/source/use-cases/large-language-models/vllm.rst

doc: Update vllm.rst

---

docs/source/use-cases/custom-models/mlflow.rst
docs/source/use-cases/diffusion-models/index.rst
docs/source/use-cases/embeddings/clip-embeddings.rst
docs/source/use-cases/index.rst
docs/source/use-cases/multimodality/blip.rst
docs/source/use-cases/multimodality/index.rst

docs: Reorg blip doc to multimodality section

---

src/bentoml_cli/auth_server.py
src/bentoml_cli/cloud.py

chore: update print and fix cors error

---

pdm.lock
pyproject.toml
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/bento/install.sh.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_alpine.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_amazonlinux.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_debian.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_ubi8.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/cuda_debian.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/cuda_ubi8.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/python_debian.j2
src/bentoml_cli/env.py

feat: switch to uv as the resolver and installer

---

src/bentoml_cli/bentos.py
src/bentoml_cli/containerize.py
src/bentoml_cli/utils.py

feat: --label option for bentoml build

---

docs/source/guides/services.rst

In the Python classes I changed the reference to the class to `self` from `this`. `this` is not a keyword in Python

docs: Update services.rst 

---

README.md
docs/source/guides/workers.rst

docs: Update concurrency links

---

docs/source/bentocloud/get-started.rst
docs/source/bentocloud/how-tos/manage-access-token.rst
docs/source/guides/deployment.rst
docs/source/use-cases/audio/whisperx.rst
docs/source/use-cases/audio/xtts.rst
docs/source/use-cases/blip.rst
docs/source/use-cases/custom-models/mlflow.rst
docs/source/use-cases/custom-models/xgboost.rst
docs/source/use-cases/diffusion-models/controlnet.rst
docs/source/use-cases/diffusion-models/sdxl-lcm-lora.rst
docs/source/use-cases/diffusion-models/sdxl-turbo.rst
docs/source/use-cases/diffusion-models/svd.rst
docs/source/use-cases/embeddings/clip-embeddings.rst
docs/source/use-cases/embeddings/sentence-transformer.rst
docs/source/use-cases/large-language-models/vllm.rst

Cherry pick this https://github.com/bentoml/BentoML/pull/4842 to the 1.3 branch.

Docs: Add auto cli login docs

---

src/bentoml/_internal/cloud/deployment.py

fix: stop spinner before starting to stream logs

---

src/_bentoml_impl/client/base.py
src/_bentoml_impl/client/http.py
src/_bentoml_impl/client/task.py

feat: retry and cancel task

---

src/bentoml/_internal/cloud/client.py

fix: fix error message with trace id

---

src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_alpine.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_amazonlinux.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_debian.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_ubi8.j2

fix(containerize): command to create group and user in alpine base image

---

src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/bento/gen.py
src/bentoml/_internal/configuration/containers.py
src/bentoml/_internal/exportable.py
src/bentoml/_internal/models/model.py
src/bentoml/_internal/service/loader.py
src/bentoml/_internal/store.py
src/bentoml_cli/env_manager.py

fix: encode special charaters in path

---

docs/source/guides/build-options.rst

doc: locking for platform

---

src/bentoml_cli/cloud.py

fix error like this
Fixes #(issue)

fix: options are not required

---

src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/schemas/schemasv2.py

fix: don't fail when image pod is not found

---

src/_bentoml_impl/tasks/result.py
src/_bentoml_impl/tasks/serde.py

fix: async task response deserialization crash

---

src/bentoml/_internal/cloud/deployment.py

feat: change spinner text on status change and show spinner after image build done

---

src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/deployment.py

fix: do not raise deployment pods not found error

---

src/bentoml/_internal/cloud/schemas/modelschemas.py
src/bentoml/_internal/cloud/schemas/schemasv1.py
src/bentoml/_internal/cloud/schemas/schemasv2.py

fix: change forbid extra keys to false for bentocloud

---

src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas/schemasv1.py

fix: delete cluster and ns if it is first cluster

---

src/bentoml_cli/cloud.py

fix: auto login confirm ask logic

---

src/bentoml/_internal/cloud/deployment.py

fix: secret default value

---

src/bentoml/_internal/cloud/client.py

fix: fix typo in error msg

---

docs/source/conf.py
docs/source/use-cases/large-language-models/index.rst

Theme of bentoml.com:
Theme of cloud.bentoml.com:
Fixes #(issue)

docs: update theme to match branding

---

src/_bentoml_impl/worker/service.py

fix: set prometheus env before importing service

---

docs/source/bentocloud/reference/bentocloud-cli.rst
docs/source/reference/sdk.rst

docs: Add API docs

---

src/_bentoml_impl/server/serving.py
src/_bentoml_impl/worker/service.py
src/bentoml/_internal/configuration/containers.py
src/bentoml/_internal/server/metrics/prometheus.py
src/bentoml/serve.py
src/bentoml/start.py
src/bentoml_cli/worker/grpc_api_server.py
src/bentoml_cli/worker/grpc_prometheus_server.py
src/bentoml_cli/worker/http_api_server.py
src/bentoml_cli/worker/runner.py
tests/unit/grpc/interceptors/test_prometheus.py

fix: inject prometheus env from arbiter

---

src/bentoml/bentos.py
src/bentoml_cli/bentos.py

fix: Don't run bentoml.build_bentofile in subprocess

---

docs/source/bentocloud/byoc/azure.rst

docs: update azure byoc instructions

---

docs/source/bentocloud/byoc/azure.rst

docs(azure): update azure byoc instructions

---

src/bentoml/_internal/utils/__init__.py

fix: silence git output

---

src/bentoml/_internal/bento/bento.py

fix: surface config error on bento build

---

src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_alpine.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_amazonlinux.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_debian.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_ubi8.j2

fix: move user setup to base template to make custom base image work

---

src/bentoml_cli/cloud.py

fix: press text

---

src/_bentoml_sdk/service/config.py
src/bentoml/_internal/configuration/v2/__init__.py

fix: fix resource type

---

src/bentoml/_internal/configuration/containers.py

fix: metrics duration defined with min,max,factor not taking effect

---

docs/source/get-started/introduction.rst
docs/source/index.rst

docs: Update messages

---

docs/source/use-cases/index.rst

docs: Update index.rst

---

docs/source/guides/testing.rst

doc: update the HTTP behavior test instruction

---

src/bentoml_cli/start.py

feat(cli): reload option for start-http-server

---

src/bentoml/_internal/bento/build_config.py

fix(build): preserve the index url options in requirements.txt file

---

.github/workflows/ci.yml
tests/e2e/bento_server_http/tests/test_serve.py

fix: try to fix the timeout test cases

---

README.md
docs/source/index.rst

doc: update CI status badge

---

noxfile.py
src/bentoml/_internal/frameworks/keras.py

Compatibility was lost with Keras 3. This restore the functionality when using Keras 3.4.0 or newer.
Fixes #4921 

fix:  restore keras.save_model compatibility with Keras 3

---

src/_bentoml_impl/client/proxy.py

feat: expose client url and sync client

---

src/_bentoml_sdk/io_models.py

fix: always preserve str and bytes when serializing

---

src/bentoml/_internal/cloud/bentocloud.py

Error should be raised when upload encounters a failed put request to the pre-signed url
Fixes #(issue)

fix(cloud-client): raise error if multipart push fails

---

examples/README.md

docs: Add function calling example link

---

src/_bentoml_sdk/_pydantic.py
src/bentoml/_internal/context.py

fix: pydantic/numpy patching causes `Cannot interpret 'numpy.float16 | numpy.float32' as a data type`

---

src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/utils/circus/watchfilesplugin.py

refactor: path spec ignore pattern checks children files only

---

src/bentoml/_internal/resource.py

Just a tiny fix to take care of this:
https://github.com/bentoml/BentoML/issues/4940
https://github.com/bentoml/BentoML/issues/4678

fix: improve exception handling for pynvml

---

docs/source/bentocloud/how-tos/configure-deployments.rst

doc: update cloud deploy with yaml guide

---

docs/source/guides/testing.rst

doc: fix instructions of http testing

---

docs/source/conf.py

docs: Add banner for 1.1 doc

---

src/_bentoml_impl/server/serving.py
src/_bentoml_sdk/service/factory.py
src/bentoml/__init__.py
src/bentoml/_internal/utils/circus/__init__.py
src/bentoml/bentos.py
src/bentoml/serve.py
src/bentoml/server.py
src/bentoml/serving.py
src/bentoml/start.py
src/bentoml_cli/serve.py
tests/e2e/bento_new_sdk/test_quickstart.py
tests/e2e/bento_server_http/service.py
tests/e2e/bento_server_http/tests/test_serve.py

fix: bentoml.serve to support serving new SDK services from a bento

---

README.md

docs: Update readme example links

---

src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/bento/build_config.py
src/bentoml/bentos.py
src/bentoml_cli/bentos.py

feat: lock packages for linux by default

---

src/bentoml/_internal/cloud/base.py
src/bentoml/_internal/cloud/bentocloud.py

fix: retry for model and bento upload failure

---

.github/workflows/ci.yml
src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/utils/circus/watchfilesplugin.py
src/bentoml/serving.py
tests/unit/_internal/utils/circus/test_watchfilesplugin.py
tests/unit/conftest.py

fix: reload plugin missing file changes

---

.github/workflows/ci.yml
pdm.lock
pyproject.toml
src/bentoml_cli/cloud.py
src/bentoml_cli/deployment.py

feat(cli): support passing env without value

---

docs/source/bentocloud/how-tos/autoscaling.rst
docs/source/bentocloud/how-tos/manage-secrets.rst
docs/source/guides/distributed-services.rst
docs/source/guides/observability/logging.rst
docs/source/guides/testing.rst
docs/source/use-cases/diffusion-models/sdxl-lcm-lora.rst
src/bentoml_cli/containerize.py

doc: include cli commands in secret doc

---

pyproject.toml
src/bentoml/_internal/bento/bentoml_builder.py
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/configuration/__init__.py
src/bentoml/_internal/utils/circus/watchfilesplugin.py
tests/unit/_internal/utils/circus/test_watchfilesplugin.py

fix: switch back to post-release version scheme

---

docs/source/guides/build-options.rst

doc: Add documentation about platform option of bentoml build

---

src/bentoml/_internal/bento/build_config.py

fix: only add bentoml requirement if absent

---

src/_bentoml_impl/client/http.py
src/_bentoml_impl/serde.py

fix: null filename causes parsing failure for image input

---

src/_bentoml_impl/loader.py
src/_bentoml_impl/worker/service.py
src/bentoml/__init__.py
src/bentoml/_internal/service/loader.py

feat: lazy import context manager

---

src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas/utils.py

feat: sync editable bentoml to remote

---

src/_bentoml_impl/client/proxy.py
src/_bentoml_sdk/service/dependency.py
src/_bentoml_sdk/service/factory.py
src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/configuration/containers.py
src/bentoml/_internal/models/model.py
src/bentoml/_internal/utils/analytics/usage_stats.py
src/bentoml_cli/deployment.py
src/bentoml_cli/utils.py

feat: remote dependency

---

src/_bentoml_impl/client/http.py

fix: persist trace across internal requests

---

src/bentoml/_internal/context.py

feat: expose request id and trace id in request scope

---

src/bentoml_cli/deployment.py

fix: add secrets in update/apply commands

---

src/bentoml/_internal/cloud/deployment.py

fix: make spinner optional for backward compatibility

---

src/_bentoml_sdk/models/base.py

fix: don't initialize cloud client until needed

---

docs/source/guides/model-composition.rst

doc: fix typo in model composition

---

src/bentoml/_internal/cloud/bento.py
src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/model.py
src/bentoml/_internal/cloud/schemas/modelschemas.py
src/bentoml/_internal/cloud/schemas/schemasv1.py
src/bentoml/_internal/cloud/yatai.py
tests/unit/_internal/cloud/test_deployment.py

refactor: unify same schema

---

src/bentoml/_internal/cloud/deployment.py

fix: structure bento manifest

---

src/_bentoml_sdk/models/huggingface.py
src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/cloud/__init__.py
src/bentoml/_internal/cloud/config.py
src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas/modelschemas.py
src/bentoml_cli/cloud.py

fix: allow setting timeout for cloud client; hf api; manifest eq

---

src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/cloud/deployment.py

fix: with_defaults for docker option and show diff report for bento manifest comparison

---

src/bentoml_cli/bentos.py

fix: do not initialize cloud client when building bento

---

docs/source/use-cases/large-language-models/shieldgemma.rst

doc: Update shieldgemma doc name

---

docs/source/guides/build-options.rst

doc: correct the requirements

---

examples/README.md

docs: Add new project examples

---

docs/source/guides/adaptive-batching.rst

docs: Update adaptive batching doc

---

examples/model-loading-saving/README.md

Fix a typo

---

README.md
docs/source/use-cases/large-language-models/function-calling.rst
docs/source/use-cases/large-language-models/shieldgemma.rst

docs: Add quotation marks to python versions

---

src/_bentoml_impl/frameworks/catboost.py
src/_bentoml_impl/frameworks/importer.py
src/_bentoml_impl/frameworks/lightgbm.py
src/_bentoml_impl/frameworks/mlflow.py
src/_bentoml_impl/frameworks/sklearn.py
src/_bentoml_impl/frameworks/xgboost.py
src/_bentoml_sdk/service/factory.py
src/bentoml/__init__.py
src/bentoml/_internal/runner/runner.py
src/bentoml/_internal/runner/strategy.py
src/bentoml/_internal/service/service.py
src/bentoml/_internal/utils/__init__.py
src/bentoml/_internal/utils/lazy_loader.py
src/bentoml/io.py

fix: emit deprecation warings for legacy APIs

---

src/_bentoml_impl/worker/service.py

fix: skip safetensor patching if not installed

---

docs/source/bentocloud/byoc/aws.rst

doc: update aws byoc

---

src/bentoml/_internal/cloud/deployment.py

actually it is ready
Fixes #(issue)

fix: [bug bash] prefetch url

---

src/bentoml/_internal/cloud/deployment.py

fix: upload a flag file after project ready

---

src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas/schemasv2.py
src/bentoml_cli/deployment.py

fix: update spinner with the service readyz status

---

docs/source/guides/iotypes.rst

docs: Add IO tables

---

docs/source/use-cases/large-language-models/shieldgemma.rst
docs/source/use-cases/large-language-models/vllm.rst

docs: Create secrets for deployment

---

docs/source/reference/stores.rst

doc: api docs for build and build_bentofile

---

src/bentoml/_internal/cloud/client.py
src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/secret.py
src/bentoml/deployment.py
src/bentoml_cli/deployment.py

feat: validate required envs when creating deployment

---

docs/source/guides/clients.rst

docs: fix links

---

src/bentoml/_internal/cloud/deployment.py

fix: reconstruct build config for getting requirement

---

src/bentoml/_internal/batch/spark.py

fix: spark usage following API change

---

docs/source/guides/build-options.rst

docs: Update build-options.rst

---

src/_bentoml_sdk/models/huggingface.py
tests/integration/frameworks/models/tensorflow.py

fix: use the model revision in bento info for huggingface models

---

src/_bentoml_sdk/models/huggingface.py

fix: postpone the model id normalization for huggingface models

---

src/bentoml/_internal/bento/bento.py

chore: copy existing README.md instead of creating a new one

---

pdm.lock
pyproject.toml
src/bentoml/_internal/container/frontend/dockerfile/templates/base_alpine.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_amazonlinux.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_debian.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_ubi8.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2

fix: remove the version limit of pynvml

---

docs/source/guides/model-loading-and-management.rst

docs: Add explanations for model loading acceleration

---

docs/source/bentocloud/how-tos/codespaces.rst

docs: Update codespaces desc

---

docs/source/guides/observability/tracing.rst

docs: Remove dead link

---

docs/source/conf.py

docs: Add doc canonical link

---

docs/source/use-cases/diffusion-models/index.rst

doc: update diffusion models to include comfyui

---

noxfile.py
src/bentoml/_internal/utils/__init__.py
tests/monitoring/task_classification/.bentoignore
tests/monitoring/task_classification/.gitignore
tests/monitoring/task_classification/README.md
tests/monitoring/task_classification/deployment.yaml
tests/monitoring/task_classification/locustfile.py
tests/monitoring/task_classification/pyproject.toml
tests/monitoring/task_classification/service.py
tests/monitoring/task_classification/tests/conftest.py
tests/monitoring/task_classification/tests/test_log_collection.py
tests/monitoring/task_classification/train.py

fix: move monitoring project to tests folder

---

src/bentoml/_internal/bento/bento.py

Fix exception for build/push bento in codespace
stack trace
```
File "/Users/xian/Downloads/workspace/bentoml/src/awesome-ai-apps-internal/.venv/bin/bentoml", line 8, in <module>
sys.exit(cli())
^^^^^
File "/Users/xian/Downloads/workspace/bentoml/src/awesome-ai-apps-internal/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/xian/Downloads/workspace/bentoml/src/awesome-ai-apps-internal/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/Users/xian/Downloads/workspace/bentoml/src/awesome-ai-apps-internal/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
return …
```

fix: empty doc for bare built bento

---

pdm.lock
pyproject.toml
src/bentoml/_internal/bento/bentoml_builder.py
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/utils/__init__.py

fix: build git repo with uv

---

src/_bentoml_sdk/service/factory.py

fix: use the model_id in bento

---

src/bentoml/_internal/bento/bentoml_builder.py

fix: create dir before move

---

DEVELOPMENT.md

Commit 35cd25c043ae5c85c622f99654df6a67dadf6cbb moved the `buf.yaml` into `src` directory. This PR adjusts sources to changes.

docs: update `buf.yaml` reference

---

src/bentoml/_internal/cloud/bento.py
src/bentoml/_internal/cloud/model.py

fix: read stream before accessing response.text

---

src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/cloud/bento.py

fix: set manifest.dev for bare bento upload

---

docs/source/examples/function-calling.rst
docs/source/examples/langgraph.rst
docs/source/examples/shieldgemma.rst

Relative URLs seem failed. Use absolute URLs for now.

docs: Fix invalid icon images

---

README.md
docs/source/build-with-bentoml/distributed-services.rst
docs/source/build-with-bentoml/services.rst
docs/source/examples/function-calling.rst
docs/source/examples/shieldgemma.rst
docs/source/get-started/adaptive-batching.rst
docs/source/get-started/model-composition.rst
docs/source/index.rst
docs/source/scale-with-bentocloud/deployment/configure-deployments.rst

docs: Update readme examples and add distributed service doc

---

src/bentoml/_internal/cloud/model.py

fix: protect model repository creation with a lock to avoid a race condition

---

docs/source/build-with-bentoml/observability/index.rst

modify metric's link to resolve the issue of going to tracing document when clicking on the [ Observability - Metrics ] menu in the deployed documentation

docs: Modify 'metric' menu link on 'observability index' page

---

src/_bentoml_sdk/_pydantic.py
src/_bentoml_sdk/io_models.py
src/bentoml/_internal/server/runner_app.py

fix: fix bug of serialization error and runner can't be shutdown

---

docs/source/get-started/adaptive-batching.rst
docs/source/reference/bentoml/sdk.rst

1. Make the doc simpler by removing unnecessary explanations.
2. Use the summarization example for simplicity.

docs: Simplify Adaptive batching docs

---

src/_bentoml_sdk/__init__.py
src/_bentoml_sdk/decorators.py
src/_bentoml_sdk/gradio.py
src/bentoml/__init__.py
src/bentoml/_internal/server/http/access.py
src/bentoml/_internal/server/http/instruments.py
tests/unit/bentoml_io/test_decorators.py

fix: add basic metrics and access logs for websocket

---

src/_bentoml_impl/server/serving.py
src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/cloud/bento.py
src/bentoml/_internal/container/__init__.py
src/bentoml/_internal/container/frontend/dockerfile/entrypoint.sh

fix: ensure all models to exists on deployment

---

src/bentoml/_internal/bento/bento.py

fix: enable image spec when image is explictly given

---

src/_bentoml_sdk/service/factory.py

fix: drop the redundant parameter for runner_service

---

src/bentoml/bentos.py

fix: calculate bentofile path against cwd if given explicitly

---

src/bentoml/_internal/cloud/client.py

fix: image builder log stream doesn't work

---

docs/source/get-started/cloud-deployment.rst

docs: Add GPU access messaging

---

src/bentoml/_internal/cloud/deployment.py

fix: disable markup and highlight for image log stream

---

src/bentoml_cli/secret.py

fix: don't override built-in function

---

src/_bentoml_sdk/images.py
src/bentoml/_internal/container/frontend/dockerfile/__init__.py
src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2

fix: add default install command for image spec

---

docs/source/examples/overview.rst

docs: Update examples

---

noxfile.py
pdm.lock
pyproject.toml
src/_bentoml_impl/server/app.py
src/bentoml/_internal/server/http_app.py
src/bentoml/_internal/server/runner_app.py

fix: loosen the constraints of opentelemetry dependencies

---

src/_bentoml_impl/server/app.py
src/_bentoml_sdk/io_models.py
src/_bentoml_sdk/method.py

fix: only honor ctx or context parameter with correct annotation

---

src/_bentoml_sdk/models/huggingface.py
src/bentoml/_internal/cloud/bento.py
src/bentoml/_internal/cloud/model.py

fix: temp file is deleted unexpected on Windows

---

src/bentoml/_internal/bento/install.sh.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_alpine.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_amazonlinux.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_debian.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_ubi8.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2

feat: install packages into venv and chown

---

docs/source/get-started/cloud-deployment.rst
docs/source/get-started/hello-world.rst

docs: Update onboarding docs

---

src/_bentoml_impl/server/serving.py
src/_bentoml_sdk/images.py
src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2
src/bentoml/_internal/utils/analytics/usage_stats.py
src/bentoml/_internal/utils/pkg.py

fix: raise error when certfile is not given but ssl enabled and fix local dep

---

src/bentoml/_internal/cloud/bento.py
src/bentoml/_internal/cloud/model.py

fix: bad file descirptor issue when deploying bento

---

docs/source/examples/overview.rst

docs: Update example overview

---

src/_bentoml_sdk/models/huggingface.py

fix: use content hash as the default model version

---

src/_bentoml_sdk/images.py
src/bentoml/_internal/configuration/__init__.py
src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2

fix: Permission issue of uv python installation directory

---

src/_bentoml_impl/worker/patch.py
src/_bentoml_impl/worker/service.py

fix: lazy safetensor patch

---

src/_bentoml_sdk/service/factory.py

fix: set model revision correctly

---

src/bentoml/deployment.py

fix: add missing secrets params in bentoml sdk

---

src/bentoml/_internal/cloud/bento.py
src/bentoml/_internal/cloud/model.py

fix: expose cloud api to get a single model

---

src/bentoml/_internal/cloud/__init__.py
src/bentoml/_internal/cloud/base.py

fix: use the same spinner for bento and model apis

---

src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/cloud/bento.py
src/bentoml/_internal/cloud/model.py

fix: closed file descriptior issue

---

src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/log.py
src/bentoml/_internal/utils/__init__.py

fix: turn off build log stream in jupyter notebook

---

docs/source/build-with-bentoml/model-loading-and-management.rst

docs: Add notes for loading HF private models

---

src/_bentoml_sdk/_pydantic.py
src/_bentoml_sdk/io_models.py

fix: patch annotations inside a container type

---

src/bentoml/_internal/utils/circus/__init__.py

fix: set the arbiter thread to be daemon thread

---

docs/source/build-with-bentoml/streaming.rst
docs/source/build-with-bentoml/websocket.rst
docs/source/index.rst

docs: Add streaming and websocket docs

---

docs/source/build-with-bentoml/asgi.rst
docs/source/examples/function-calling.rst
docs/source/reference/bentoml/sdk.rst

docs: Update ASGI decorator

---

docs/source/build-with-bentoml/gradio.rst

docs: Update Gradio example link

---

src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/cloud/schemas/modelschemas.py

chore: add spec into bento manifest schema

---

src/_bentoml_sdk/images.py
src/bentoml/_internal/bento/build_config.py

fix: correct the log for locking platform

---

src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_alpine.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_amazonlinux.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_debian.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_ubi8.j2

fix: uv installation in container

---

src/bentoml/bentos.py

sort of a hack to make it work with `--label`. Given that buildconfig is attrs.frozen
Fixes #(issue)

fix(build): setattr frozen sets

---

src/_bentoml_impl/loader.py
src/_bentoml_sdk/images.py
src/bentoml/__init__.py

fix:correct context path when serving from bento

---

src/_bentoml_impl/loader.py

fix: restore path after import

---

src/_bentoml_sdk/images.py
src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2

fix: compile bytecode when installing python packages

---

src/_bentoml_sdk/_pydantic.py
src/_bentoml_sdk/io_models.py

fix: IO descriptor honor validators

---

src/_bentoml_impl/client/http.py
src/_bentoml_impl/serde.py
src/_bentoml_impl/server/app.py
src/_bentoml_sdk/io_models.py
src/bentoml/_internal/service/openapi/specification.py
src/bentoml/_internal/utils/uri.py
tests/e2e/bento_new_sdk/test_asgi.py
tests/unit/bentoml_io/test_decorators.py

feat: support root input spec using positonal-only argument

---

src/_bentoml_sdk/gradio.py

fix: gradio error when uploading file

---

src/_bentoml_sdk/io_models.py
tests/e2e/bento_new_sdk/test_asgi.py

fix: input data validation for root input

---

src/_bentoml_impl/loader.py

fix: don't restore model store after importing service

---

src/_bentoml_sdk/images.py

fix: always add bentoml req unless it is specified as a url dependency

---

docs/source/examples/overview.rst

docs: update links to examples

---

src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2

fix: add files under env/docker

---

README.md

show diff changes in "Deploying your first Bento" section
Fixes #(issue)

docs: use diff for runtime image

---

docs/source/build-with-bentoml/runtime-environment.rst

docs: Update runtime explanations

---

src/_bentoml_impl/serde.py
src/_bentoml_sdk/method.py

fix(io): OpenAPI schema for multipart form request body

---

src/_bentoml_impl/loader.py
src/_bentoml_impl/server/serving.py
src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/service/loader.py
src/bentoml/_internal/service/service.py
src/bentoml/start.py
src/bentoml_cli/worker/grpc_api_server.py
src/bentoml_cli/worker/http_api_server.py
src/bentoml_cli/worker/runner.py
tests/monitoring/task_classification/pyproject.toml

This will supersede #5230
Fixes #(issue)

refactor: unify logic of loading service

---

src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas/modelschemas.py
src/bentoml/_internal/service/loader.py

fix: collect requirements from image spec for codespaces

---

README.md

docs: update deprecated links

---

docs/source/build-with-bentoml/clients.rst
docs/source/build-with-bentoml/iotypes.rst
docs/source/build-with-bentoml/services.rst

docs: Add root input usage

---

src/_bentoml_impl/server/app.py

fix: reformat the code

---

docs/source/get-started/cloud-deployment.rst

docs: Add update command to cloud deployment doc

---

src/_bentoml_sdk/images.py

fix: fallback to v1 if pack git packages is set

---

src/_bentoml_impl/client/base.py
src/_bentoml_impl/client/http.py
src/_bentoml_impl/client/task.py
src/_bentoml_impl/server/app.py
src/_bentoml_sdk/service/factory.py
src/bentoml/_internal/log.py
src/bentoml/serving.py

feat(client): add task apis to client methods

---

src/bentoml/_internal/cloud/deployment.py
tests/unit/_internal/cloud/test_deployment.py

feat: default min replicas is None

---

src/_bentoml_impl/server/app.py
tests/e2e/bento_new_sdk/test_quickstart.py

tests: banning pickle requests

---

pdm.lock
pyproject.toml
src/bentoml/_internal/container/frontend/dockerfile/templates/base.j2
src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2
src/bentoml/serving.py

feat: Fail fast when running inside container

---

docs/source/scale-with-bentocloud/administering/bring-your-own-cloud/aws.rst

docs(byoc): update aws byoc role template link

---

docs/source/examples/langgraph.rst

docs: Update langgraph example

---

pdm.lock
pyproject.toml
src/bentoml/_internal/utils/circus/__init__.py

fixes the arbiter accordingly by raising the exception from future

fix(supervisor): quit the arbiter correctly

---

src/_bentoml_sdk/images.py
src/bentoml/_internal/bento/bento.py

fix: preserve global options in requirements.txt

---

src/_bentoml_impl/server/serving.py
src/_bentoml_impl/worker/service.py
src/_bentoml_sdk/images.py
src/bentoml/_internal/service/loader.py

fix: loading service issue in worker

---

docs/source/scale-with-bentocloud/manage-api-tokens.rst

docs: Add org token doc

---

docs/source/examples/overview.rst

OpenLLM does not help users understand how to build with BentoML. While it makes sense for OpenLLM to direct users to BentoML but not the other way around.
Fixes #(issue)

docs: remove openllm from examples overview

---

src/_bentoml_impl/client/http.py

I'm trying to apply the async task queues
https://docs.bentoml.com/en/latest/get-started/async-task-queues.html
I tried to create a task and track its progress, working fine till the task is success and I cannot get the task result using task.get()
Getting result by requesting to f"http://localhost:3000/long_running_task/get?task_id={task.id}" is working normally.
Turns out it's missing .route, I have made the change in my PR.
Please take a look!
Fixes #(issue)
- [x ] Does the Pull Request follow [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary) naming? Here are [GitHub's
guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on how to create a …

fix: add missing .route of __endpoint

---

src/bentoml/_internal/utils/pkg.py

fix: non-standard ssh git url

---

docs/source/examples/overview.rst

docs: Add BentoOCR to example list

---

docs/source/build-with-bentoml/runtime-environment.rst
docs/source/reference/bentoml/bento-build-options.rst

docs: Update private repo notes

---

src/_bentoml_impl/client/http.py
src/bentoml/_internal/io_descriptors/file.py
src/bentoml/_internal/io_descriptors/image.py
src/bentoml/_internal/io_descriptors/multipart.py
src/bentoml/_internal/utils/formparser.py

replace `multipart` imports with `python_multipart`
Apparently, there is another python library called `multipart`, which is different from `python_multipart`
- https://github.com/Kludex/python-multipart
- https://github.com/defnull/multipart
By default, `python_multipart` is also available as `multipart`. However, issues arise when `multipart` is also installed. This can be easily fixed by referencing `python_multipart` instead, which is also recommended based on the documentation.
I have searched the repo and replaced 2 instance of `multipart` I found.
Below is run in `python:slim` container image.
```python
root@d7f23af8a56e:/# pip install bentoml multipart
root@d7f23af8a56e:/# python
Python 3.13.2 (main, Mar 18 2025, 01:50:09) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" …
```

fix: replace namespace import to `python_multipart`

---

src/_bentoml_sdk/service/factory.py

fix: on load bento for dependent services

---

src/bentoml/_internal/service/loader.py
src/bentoml/_internal/store.py

fix: wrong error context

---

docs/source/scale-with-bentocloud/administering/bring-your-own-cloud/saml.rst

docs(saml): add sso saml doc

---

src/_bentoml_sdk/images.py
src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2

feat: support pack_git_packages and fix add group for alpine

---

docs/source/build-with-bentoml/clients.rst
src/_bentoml_impl/client/base.py
src/_bentoml_impl/client/http.py
src/_bentoml_impl/client/proxy.py

fix: initialize async http client with async method

---

src/bentoml/_internal/bento/build_config.py
src/bentoml/bentos.py
src/bentoml_cli/bentos.py
src/bentoml_cli/cli.py
src/bentoml_cli/deployment.py

feat: support --name option for bentoml build and bentoml code

---

docs/source/reference/bentoml/bento-build-options.rst
src/_bentoml_sdk/images.py
src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/bento/build_config.py
src/bentoml/_internal/service/loader.py
src/bentoml/images.py

feat: make it possible to override values of Image from bentofile.yaml

---

SECURITY.md

docs(security): update security advisory email

---

SECURITY.md

chore: update security notes

---

docs/source/scale-with-bentocloud/administering/bring-your-own-cloud/saml.rst

doc: Update saml.rst

---

docs/source/build-with-bentoml/template-arguments.rst
docs/source/index.rst
docs/source/reference/bentoml/bento-build-options.rst

Add doc for https://github.com/bentoml/BentoML/pull/5299

docs: Add template arg doc

---

README.md
docs/source/build-with-bentoml/gpu-inference.rst
docs/source/build-with-bentoml/observability/monitoring-and-data-collection.rst
docs/source/build-with-bentoml/runtime-environment.rst
docs/source/examples/controlnet.rst
docs/source/examples/function-calling.rst
docs/source/examples/langgraph.rst
docs/source/examples/mlflow.rst
docs/source/examples/sdxl-turbo.rst
docs/source/examples/shieldgemma.rst
docs/source/examples/vllm.rst
docs/source/examples/xgboost.rst
docs/source/get-started/packaging-for-deployment.rst
docs/source/reference/bentoml/configurations.rst

doc: rename PythonImage to Image

---

docs/source/scale-with-bentocloud/manage-api-tokens.rst

docs: add monitoring API tokens section to manage-api-tokens.rst

---

src/_bentoml_sdk/method.py
src/_bentoml_sdk/service/factory.py
src/_bentoml_sdk/service/openapi.py
src/bentoml/_internal/utils/__init__.py

feat: show fastapi routes in playground ui

---

docs/source/build-with-bentoml/template-arguments.rst

doc: add examples of bentoml deploy for bento args

---

src/_bentoml_sdk/method.py
src/_bentoml_sdk/service/factory.py
src/_bentoml_sdk/service/openapi.py
src/bentoml/_internal/utils/__init__.py

revert: "feat: show fastapi routes in playground ui"

---

src/bentoml_cli/bentos.py

fix: only regard the positional arg as build ctx if it is a local dir

---

docs/source/reference/bentoml/bento-build-options.rst

docs: Remove version table

---

docs/source/build-with-bentoml/runtime-environment.rst

docs: Add bentoignore in runtime doc

---

docs/source/build-with-bentoml/model-loading-and-management.rst

docs: Change Model Store and BentoCloud to default tab

---

src/_bentoml_sdk/service/config.py

chore: add 80Gb mapping for H100

---

docs/source/reference/bentoml/configurations.rst

docs: Use command to list GPU types

---

src/bentoml_cli/secret.py

fix: handling equal sign in value of secret

---

src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2

fix: make sure to inherit from base image ENV

---

src/_bentoml_sdk/images.py

fix: don't add duplicate global options to requirements.txt

---

docs/source/build-with-bentoml/lifecycle-hooks.rst
src/_bentoml_impl/server/app.py

feat: custom readiness hook method

---

docs/source/scale-with-bentocloud/manage-api-tokens.rst

docs: Fix BentoCloud CLI link

---

src/_bentoml_impl/client/http.py

fix: subclass checking for client classes

---

src/_bentoml_sdk/images.py
src/bentoml/_internal/bento/build_config.py

fix: insert install command even if the base image is specified

---

src/_bentoml_sdk/images.py
src/bentoml/_internal/container/frontend/dockerfile/templates/base_v2.j2

fix: do not allow separate python requirements calls

---

src/_bentoml_sdk/images.py
src/bentoml/_internal/bento/bento.py

fix: support pre-built wheels in bento spec v2

---

src/_bentoml_sdk/service/factory.py
src/bentoml/_internal/bento/bento.py

feat: add paths to schemas to support openai chat endpoints

---

docs/source/build-with-bentoml/runtime-environment.rst

docs: Add docs for wheels and run_script()

---

src/_bentoml_impl/docker.py
src/bentoml/_internal/store.py

chore: minor fix, wrong message

---

docs/source/get-started/adaptive-batching.rst

docs: correct description of max_latency_ms

---

src/bentoml_cli/deployment.py

feat: support --arg for bentoml deployment create and update

---

docs/README.md
docs/source/_templates/base.html
docs/source/build-with-bentoml/gradio.rst
docs/source/build-with-bentoml/iotypes.rst
docs/source/build-with-bentoml/lifecycle-hooks.rst
docs/source/build-with-bentoml/model-loading-and-management.rst
docs/source/build-with-bentoml/observability/metrics.rst
docs/source/build-with-bentoml/observability/monitoring-and-data-collection.rst
docs/source/build-with-bentoml/observability/tracing.rst
docs/source/build-with-bentoml/services.rst
docs/source/build-with-bentoml/snippets/grpc/additional_setup.rst
docs/source/build-with-bentoml/snippets/grpc/grpc_tools.rst
docs/source/examples/controlnet.rst
docs/source/examples/langgraph.rst
docs/source/examples/mlflow.rst
docs/source/reference/bentoml/bento-build-options.rst
docs/source/reference/bentoml/frameworks/picklable_model.rst
docs/source/scale-with-bentocloud/administering/bring-your-own-cloud.rst
docs/source/scale-with-bentocloud/deployment/configure-deployments.rst
docs/source/scale-with-bentocloud/deployment/index.rst
docs/source/scale-with-bentocloud/deployment/manage-deployments.rst
docs/source/scale-with-bentocloud/manage-api-tokens.rst
docs/source/scale-with-bentocloud/scaling/autoscaling.rst

Fix some wordings in the docs and a dead redirect to the examples.

docs: reword some docs and a handful of typos

---

src/_bentoml_impl/server/app.py
src/_bentoml_impl/tasks/result.py

fix: align the task status with bentocloud

---

src/_bentoml_sdk/io_models.py

fix: compatible implementation for eval_type_lenient

---

docs/source/examples/overview.rst

docs: Add triton example

---

docs/source/scale-with-bentocloud/scaling/autoscaling.rst

docs: stabilization window

---

src/bentoml/_internal/cloud/schemas/modelschemas.py

fix: apply stabilization window config

---

src/_bentoml_sdk/decorators.py
src/_bentoml_sdk/method.py

fix: allow route name without leading slash

---

src/bentoml_cli/deployment.py

It's duplicated, an identical argument appears right above. That one has the correct default `type=click.File()`

fix(deployment): remove duplicated `--config-file`

---

docs/source/build-with-bentoml/template-arguments.rst
docs/source/scale-with-bentocloud/deployment/ci-cd-pipelines.rst
docs/source/scale-with-bentocloud/deployment/index.rst

docs: Add CI/CD pipeline doc

---

noxfile.py
src/_bentoml_impl/server/allocator.py

fix: disable GPU allocation if CUDA_VISIBLE_DEVICES is set

---

src/_bentoml_impl/server/app.py
src/_bentoml_impl/server/serving.py
src/_bentoml_impl/tasks/result.py
src/_bentoml_sdk/service/factory.py

fix: race condition issue initializing result db

---

docs/source/scale-with-bentocloud/codespaces.rst

docs: Add codespaces video

---

src/_bentoml_sdk/images.py

feat: read dependencies from uv lock

---

src/_bentoml_sdk/__init__.py
src/bentoml/__init__.py
src/bentoml/deployment.py

fix: accept bento type as the bento argument for deployment APIs

---

src/_bentoml_sdk/images.py

This PR aims to return the instance early from self.python_packages

chore: return early python_packages

---

docs/source/get-started/adaptive-batching.rst

docs: Update adaptive batching example

---

src/bentoml/_internal/cloud/deployment.py
src/bentoml/_internal/cloud/schemas/schemasv2.py

bentoml deployment apply -f deployment-jtest.yaml 
```
bento: jtest:ums23fazbcsawiru
name: jtest-lp3b
access_authorization: false
secrets: []
envs: []
services:
Jtest:
instance_type: cpu.small
envs: []
scaling:
min_replicas: 0
max_replicas: 1
policy:
scale_up_stabilization_window: 0
scale_down_stabilization_window: 600
config_overrides:
traffic:
timeout: 60
external_queue: false
deployment_strategy: RollingUpdate
A:
instance_type: cpu.small
envs: []
scaling:
min_replicas: 0
max_replicas: 1
policy:
scale_up_stabilization_window: 0
scale_down_stabilization_window: 600
config_overrides:
traffic:
timeout: 60
external_queue: false
deployment_strategy: RollingUpdate
cluster: default
canary:
route_type: header
route_by: X-Header
versions:
A:
bento: jtest:fglup3qfm6hseiru
weight: 50
services: …
```

feat: support canary for bentoml deployment apply commands

---

docs/source/build-with-bentoml/sandboxes.rst

docs: Update contact us link

---

docs/source/build-with-bentoml/sandboxes.rst

Doc sandboxes

---

docs/source/scale-with-bentocloud/deployment/index.rst
docs/source/scale-with-bentocloud/deployment/sandboxes.rst

docs: Move sandboxes doc to BentoCloud

---

src/_bentoml_sdk/images.py
src/bentoml/_internal/cloud/deployment.py

fix: Ignore python.packages when requirements_txt is provided

---

docs/source/build-with-bentoml/runtime-environment.rst
src/bentoml/_internal/configuration/__init__.py

fix: Add env var to disable local bentoml URL in requirements

---

src/bentoml/_internal/utils/args.py

fix: Correct argument merging logic in set_arguments function

---

src/_bentoml_sdk/service/config.py

feat: Add new GPU type 'amd-mi300x' to GpuLiteralType

---

docs/source/build-with-bentoml/services.rst
src/_bentoml_impl/server/serving.py
src/_bentoml_sdk/service/factory.py

feat: allow to get command later for service

---

src/_bentoml_sdk/service/config.py
src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/cloud/schemas/modelschemas.py
src/bentoml/_internal/configuration/v2/__init__.py
src/bentoml/_internal/configuration/v2/default_configuration.yaml

feat: add support for extra_ports in service configuration

---

docs/source/build-with-bentoml/iotypes.rst

pd.Dataframe -> pd.DataFrame
Fixes #(issue)

docs: Fix typo in DataFrame annotation for classify method

---

docs/source/examples/overview.rst

docs: Add Prophet example

---

src/bentoml/_internal/bento/bento.py

feat: add endpoints field to Bento class and update related methods

---

src/_bentoml_impl/server/allocator.py
src/_bentoml_impl/server/serving.py
src/_bentoml_sdk/service/factory.py
tests/unit/bentoml_io/test_allocator.py

Also change the return value of allocator.get_worker_env so it also works for custom command workers

feat: get_hosts via runner-lb API

---

src/_bentoml_sdk/service/factory.py

fix: revert get_hosts to only returning hostnames

---

src/bentoml/_internal/bento/bento.py
src/bentoml/_internal/cloud/schemas/modelschemas.py

refactor: remove extra_ports and endpoints from Bento class and related schemas

---

docs/source/scale-with-bentocloud/administering/bring-your-own-cloud/aws.rst

doc: update gpu options for on-demand p instances

---

docs/source/reference/bentoml/configurations.rst

docs: Add labels

---

src/bentoml/_internal/utils/filesystem.py

fix: use abspath instead of realpath in safe_extract_tarfile function

---

pdm.lock
pyproject.toml
src/bentoml_cli/cloud.py
src/bentoml_cli/deployment.py

fix: replace questionary with rich-toolkit

---

src/_bentoml_sdk/service/dependency.py
src/bentoml_cli/utils.py

feat: enforce requirement for at least one dependency attribute in Dependency class

---

src/bentoml/deployment.py

Currently there is a mismatch between the create function using the config_dict and the arguments in the function. If you specify `secrets` in the config dict it will check for those secrets in the deployment context and attach them to the deployment when creating. However you cannot pass the `secrets` argument to the create method normally
Also, there was an additional `context` argument as part of the `update` typing that was not part of the `update` function signature. I've opted to remove it since it was a typing error and is not actually used by the `update` function
those accordingly? Here are …

fix: Adding secret as an argument to create deployment

---

src/bentoml/deployment.py
src/bentoml_cli/deployment.py

`bentoml deployment start <deployment_name>` to mirror the `Start` button in BentoCloud.
Syntatic sugar for `bentoml deployment update <deployment_name>` with no argument
Fixes #(issue)

feat: add bentoml deployment start command

---

src/_bentoml_impl/server/serving.py
src/bentoml_cli/containerize.py
src/bentoml_cli/utils.py

fix: handle compatibility with click 8.3+

---

src/_bentoml_impl/server/proxy.py

fix: error handling in proxy request processing
